### ISSUE TITLE
Black Menu Bars

### ISSUE THREAD

**Issue by cldx** [numixproject/numix-gtk-theme#1]
Do we really use black menu bars? 
Cause it looks very much out of place for me, or what am i missing?

**Comment by cldx** [comment]
![black_menus](https://f.cloud.github.com/assets/470526/205827/2508c8d0-81ba-11e2-8fb6-fa5b91fd3f57.png)

**Comment by satya164** [comment]
Don't you have the dark titlebars?

**Comment by me4oslav** [comment]
Yeah we do. Bu really - the version of the theme comes with dark titlebars too, I have no clue why yours are light.

**Comment by cldx** [comment]
Well would be a good idea to figure out why it does that for me.

Also i don't really get how the App Windows are supposed to look, Black TItle Bar, Black Menu, Light Action Menu?

**Comment by me4oslav** [comment]
Basically like this:
http://i.imgur.com/NE4zv8K.png

**Comment by cldx** [comment]
![Bildschirmfoto vom 2013-03-02 12:53:07](https://f.cloud.github.com/assets/470526/212774/d67b7cae-832f-11e2-8845-a669881ba694.png)

This is what it looks like to me on a fresh install just after applying all the themes in GTT.

Maybe it would be a good idea to tweak the Icons to use the background color of the theme? It won't take long since i wrote a batch script to do just that.

Also i made a Color Scheme for Inkscape and Gimp, fancy that?

**Comment by me4oslav** [comment]
This is how mine looks:
http://i.imgur.com/V2uNgsx.png
And yeah, i think we want colour schemes for GIMP and Inkscape

**Comment by cldx** [comment]
It seems like Themes don't like to be ran from .themes cause moving it to /usr/share/themes fixed the Black Title Bars for me.

Oddly enough, now the Menus are not black anymore. Gotta look into that.

the Color Scheme is found right here https://github.com/cldx/numix-resources/blob/master/numix-colors.gpl

**Comment by satya164** [comment]
Just create a link ~/.local/share/themes which should point to ~/.themes

It should fix all your problems.

**Comment by cldx** [comment]
.local/share/themes ?

Now we have /usr/share/themes for system themes.
.local/share/themes for user applied themes that are shared
and .themes for users-specific themes?

Who came up with this? xD
Also, why does it mess up anyways?

**Comment by cldx** [comment]
Now i moved the theme out of /usr/share/themes to .themes

I did : ln -s ~/.themes ~/.local/share/themes

for the sake of freshness i rebooted.

Everything seems to be good, xcept GTK2 doesn't have black menus, thats still in the making right?

**Comment by me4oslav** [comment]
Yeah.

**Comment by satya164** [comment]
Gnome now recognizes window themes from .local/share/themes instead of
.themes and GTK themes from .themes

Yeah.

—
Reply to this email directly or view it on
GitHubhttps://github.com/cldx/numix-gtk-theme/issues/1#issuecomment-14366181
.
