### ISSUE TITLE
Selected items color customization

### ISSUE THREAD

**Issue by daGrevis** [numixproject/numix-gtk-theme#102]
I changed “selected items“ from red-ish to blue-ish color using `lxappearance`. It works in preview, but actually it doesn't work and everything selectable is still red-ish.

Is this a bug or am I missing something?

![2014-02-22_23 12 44__1920x1080](https://f.cloud.github.com/assets/509529/2238885/a52b3432-9c06-11e3-8146-d3da36082373.jpg)

**Comment by satya164** [comment]
Bug in lxappearance?

**Comment by daGrevis** [comment]
I don't think so. I installed other version for lxappearance (https://aur.archlinux.org/packages/lxappearance2-git/), but it did not help.

**Comment by daGrevis** [comment]
Maybe there's a way I can set theme with hand, w/o GUI?

**Comment by satya164** [comment]
You can edit the files gtk-2.0/gtkrc and gtk-3.0/gtk.css

On 23 February 2014 16:39, Raitis Stengrevics notifications@github.comwrote:

> Maybe there's a way I can set theme with hand, w/o GUI?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/shimmerproject/Numix/issues/102#issuecomment-35829172
> .

## 

Satyajit Sahoo
Profile - Facebook http://facebook.com/satya164,
Google+http://plus.google.com/u/0/114564489020097923600
Artwork - DeviantArt http://satya164.deviantart.com

**Comment by daGrevis** [comment]
Yes, that's an option. Is it possible to overwrite colors like lxappearance does with GUI w/o touching theme?

**Comment by satya164** [comment]
I've done one GUI named GTK theme config. But I think it only works for
Gnome and Xfce.

On 23 February 2014 17:00, Raitis Stengrevics notifications@github.comwrote:

> Yes, that's an option. Is it possible to overwrite colors like
> lxappearance does with GUI w/o touching theme?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/shimmerproject/Numix/issues/102#issuecomment-35829498
> .

## 

Satyajit Sahoo
Profile - Facebook http://facebook.com/satya164,
Google+http://plus.google.com/u/0/114564489020097923600
Artwork - DeviantArt http://satya164.deviantart.com

**Comment by rickpalmeira** [comment]
@satya164 It works on unity too ;)

**Comment by satya164** [comment]
Yeah. But due to recent changes in Unity decorations in trusty, it will no
longer work for trusty window buttons.
