### ISSUE TITLE
Suggestion...

### ISSUE THREAD

**Issue by Abraka** [numixproject/numix-gtk-theme#103]
First, thx for your hard work. I already tested some icons pack ant numix theme and it looks good, but what I really miss is complete-exhaustive set for specific desktop managers. Lets say I run Xfce and I want use your theme and icons. After I install latest versions I can see that icons dont cover some base programs, icons in systray dont look nice etc. What would be a wonderfull if you create complete packs for actual Xfce, cinamon, unity. In that packs should be a perfect matching numix themes, icons, systary icons, file managers feel&look icons a you make sure, that everything is smooth a user will have full expirience. And I thing that if you put this packs on your  http://numixproject.org/ page and ask for donating you can go with 10-15 bucks for such a pack. I know that there is many distros...but just stick with ubuntu and its derivates, or maybe arch, fedora. 
Right now, there is few great icons packs and themes, but non of them can give users full clear expirience without missing something. I thing if you consider scenario I just suggested, you can go far beyond others, or just ignor me and stay in shadows :)

**Comment by satya164** [comment]
Hi. There is no need for separate packs since one pack could cover all icons. We are just short of time.

If you want an icon get covered, please report bugs https://github.com/numixproject/numix-icon-theme-circle and here https://github.com/numixproject/numix-icon-theme

**Comment by Abraka** [comment]
Looks like you dont get my message... Complete packs of theme,icons,wallpaper,systray,filemanagers for specific! desktop environment like xfce or unity. My english must be a really bad or something.

**Comment by me4oslav** [comment]
Much easier said than done. We are short of time (and money, for more money equals more time working on the project) to have pixel perfect support for all popular desktop environments just yet.

**Comment by Abraka** [comment]
"Much easier said than done"..thats for sure. Lets start with small one like Xfce. You already have 85-90% of work done. Just finish it...integrate it for full user expirience. I not asking for making icons for every possible program user can install. But at least you get my point.

**Comment by me4oslav** [comment]
When we get the time, we will cover this. Keep in mind, at its current state Numix is a pet project, which we do for fun mostly, so stuff takes time to be done.

**Comment by satya164** [comment]
@Abraka So, we need your help to complete the xfce experience first. Report bugs for icons?

**Comment by Abraka** [comment]
Linux Mint 16 Xfce edition = missing icons:
-hardware manager
-recordmydesktop
-midnight commander
-miro
-scribus
-smplayer
-update manager, software manager
-thunar file manager and in thunar are not proper icon theme, just default
-printers
-zim wiki desktop
-vuze
-wireshark
-lottaNZB
Will be nice to have same systray panel icons like ubuntu unity has.

**Comment by satya164** [comment]
@Abraka please report here https://github.com/numixproject/numix-icon-theme-circle

**Comment by me4oslav** [comment]
Also, you have report them the proper way - https://github.com/Foggalong/numix-icon-theme-circle#icon-requests
