### ISSUE TITLE
Trash/Rubbish bin doesn't have an applicable icon

### ISSUE THREAD

**Issue by marcoms** [numixproject/numix-gtk-theme#104]
![screenshot from 2014-02-24 19 32 03](https://f.cloud.github.com/assets/4211302/2249945/91f51e34-9d8a-11e3-9623-8599831208ac.png)

The icon for "Trash" as a recycling bin isn't in my opinion a good metaphor for it as a) it isn't recognisable, especially in small sizes, and b) It doesn't apply because the Trash's contents aren't recycled at all, rather, they are completely destroyed :)

**Comment by satya164** [comment]
No matter what it is called. The content in "Trash" can always be reused/recycled in Gnome.

BTW it's not the correct place for this bug. Hence closing this.

Please go here https://github.com/numixproject/numix-icon-theme
