### ISSUE TITLE
button cut-off again

### ISSUE THREAD

**Issue by rhoconlinux** [numixproject/numix-gtk-theme#105]
Hello. I already commented this on g+, but just to be sure you read this. 
Since a couple of months the cut-off of the buttons was solved, at least on Ubuntu 13.10 with gnome-shell 3.10. Now the problem is back, with a little BIG difference though: NOW ADWAITA WORKS PROPERLY and Numix don't (while time ago also adwaita had this cut-off of buttons too). 

I tried to touch here and there without luck. Probably is an easy thing to solve, if you know how to track the latest changes to adwaita theme. 
Cheers! 
http://i.imgur.com/PVsoTwv.png

**Comment by 89iuv** [comment]
Hi,

I also have this problem and it is kind of annoying.
How can I help to get this fixed?

I have this issue on ubuntu 13.10 and ubuntu 14.04.

Thank you,
Valentin
![screenshot from 2014-03-19 08 57 59](https://f.cloud.github.com/assets/3298487/2457324/03c0b932-af34-11e3-8a6b-fcd73b206770.png)

**Comment by satya164** [comment]
@89iuv Which problem are you referring to? The cut off button bug should be fixed in c736089e4116f4e022ee271f364925cb045229fc

**Comment by 89iuv** [comment]
I am referring to the fact that the highlighted tab is grayed out and it looks like it has been cut from the top.

![capture](https://f.cloud.github.com/assets/3298487/2457517/9a7b5ae0-af38-11e3-8715-0f624ff26778.PNG)

**Comment by satya164** [comment]
Hmm... It's the new design, though some apps don't fit yet. But with the
upgrade to GTK3.12, everything will look fine.

On 19 March 2014 13:03, Valentin Uveges notifications@github.com wrote:

> I am referring to the fact that the highlighted tab is grayed out and it
> looks like it has been cut from the top.
> 
> [image: capture]https://f.cloud.github.com/assets/3298487/2457517/9a7b5ae0-af38-11e3-8715-0f624ff26778.PNG
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/shimmerproject/Numix/issues/105#issuecomment-38024280
> .

## 

Satyajit Sahoo
Profile - Facebook http://facebook.com/satya164,
Google+http://plus.google.com/u/0/114564489020097923600
Artwork - DeviantArt http://satya164.deviantart.com

**Comment by 89iuv** [comment]
I thought it was a bug :)).
Thank you for the info.

**Comment by 89iuv** [comment]
Hi,

I have a suggestion

Make the  current tab text color darker. It wold make it stand out a bit more and it will look much better. 
Also i think it wold look better if the tab would be a little wider.

Like here: http://worldofgnome.org/uploads/2013/12/tabs-many.png

Thank you
Valentin.

**Comment by satya164** [comment]
@89iuv Hi. Changing the active and inactive tab text color is only supported in GTK3.12. It's not supported in previous versions. I can only have one color for the tab text in previous versions. Soon the theme will be GTK3.12 and development for previous versions will be paused. Then I'll rework the tabs.

**Comment by 89iuv** [comment]
Hope we will have the GTK 3.12 numix theme soon because it look very good. :D

**Comment by satya164** [comment]
@89iuv Do you have GTK3.12 already?
