### ISSUE TITLE
Black background around mail preview and opened mail in Evolution on Gnome 3.10

### ISSUE THREAD

**Issue by cdysthe** [numixproject/numix-gtk-theme#106]
Hi,

With Numix GTK theme I'm seeing a black background around e-mail preview and opened e-mails while "view source" is almost impossible since it's dark gray letters on black background. I'm running Ubuntu GNOME 13.10 x64 with Gnome 3.10 (PPA). See this screenshot:
![screenshot from 2014-03-05 22 14 53](https://f.cloud.github.com/assets/1281031/2346242/1d321896-a540-11e3-9448-b59b4c9a2301.png)

**Comment by satya164** [comment]
I cannot reproduce the issue in my Fedora! What's your evolution version?

**Comment by cdysthe** [comment]
Evolution 3.10.3 on Ubuntu GNOME 13.10 x64 using the Gnome 3 PPA. You are right, the problem is not present in Fedora 20 with Adwaita. Does that make it a Ubuntu GNOME 13.10 with Gnome 3 PPA problem?

**Comment by cdysthe** [comment]
I upgraded to Ubuntu GNOME 14.04 Beta 1 and the problem is gone.
