### ISSUE TITLE
window buttons missing

### ISSUE THREAD

**Issue by andia89** [numixproject/numix-gtk-theme#109]
I don't know if this is designed behaviour, but there are a lot of close/minimize buttons missing. I've attached a screenshot showing as an example the "jobs window" in calibre for Numix and Ambiance. 

The same thing can be seen for the network-manager window in ubuntu

![numix](https://f.cloud.github.com/assets/6475757/2423066/21cc440c-ab95-11e3-8018-4d8132eed7fc.png)
![ambiance](https://f.cloud.github.com/assets/6475757/2423067/21ccad20-ab95-11e3-9b94-400d57a2aa9c.png)

if this is designed behaviour, would you consider changing it?

**Comment by satya164** [comment]
Numix uses metacity-2 (for unity) and metacity-3 (for gnome), whereas Ambiance uses metacity-1. This is probably the reason this is happening. The results should be same when using Adwaita, since it also uses metacity-2 and metacity-3.
