### ISSUE TITLE
Awkward bug with "selected" URLs

### ISSUE THREAD

**Issue by me4oslav** [numixproject/numix-gtk-theme#11]
See the attached image. There is a link after the @ symbol. Which doesn't go from red to f9f9f9 on "selecting". this is GTK 2 bug.
![Screenshot from 2013-03-08 01:34:34](https://f.cloud.github.com/assets/1658870/234767/bf4ccc50-877f-11e2-9eed-4e854d937994.png)

**Comment by satya164** [comment]
So, do we change the link color? Something lighter? May be mix base color and link color?

**Comment by me4oslav** [comment]
The link colour is OK. It should just go f9f9f9 when "selected" like this.

**Comment by satya164** [comment]
What's that app?

**Comment by me4oslav** [comment]
Polly, it's a GTK 2 app. It works fine under Adwaita and Ambiance.

**Comment by satya164** [comment]
Please test if the issue is still there.

**Comment by me4oslav** [comment]
Sadly, it does :(

**Comment by ochosi** [comment]
It's not a good idea to use the same color for selected_bg and links (although there might not be many conflicts like this one). I'm really not sure that this is fixable at all, unless you want to fix it solely for Polly. It might pop up in other contexts though too, so my advice is to change the link color to something slightly darker or brighter altogether.

**Comment by me4oslav** [comment]
I totally derped on this one, it does happen in Ambiance too. We should change the link text colour

**Comment by satya164** [comment]
Should we make it a darker red?

**Comment by me4oslav** [comment]
Change it to whatever you want :)

**Comment by satya164** [comment]
Changed the link color to blue in 909e533ba1db299182fee09ddf8cd55a9c1837dc

**Comment by me4oslav** [comment]
Blue? Ugh! There are two rules in that theme:
- Flatness
- No blue
  Please, please, please, nuke the blue. :)

**Comment by satya164** [comment]
Even Ambiance uses Blue for the link colour! And again, blue is the standard color for links.

**Comment by me4oslav** [comment]
Ambiance uses orange for link colour, no? The last time I checked (2 or 3 days ago) it did.

**Comment by satya164** [comment]
Yep, I see. Then probably they forget to change it in gtk.css

Well, we can keep the color as it is then I think.

**Comment by satya164** [comment]
I have deleted the commit.

**Comment by me4oslav** [comment]
No, just change it do different shade of red :)

**Comment by satya164** [comment]
Fixed in 2eb5d31
