### ISSUE TITLE
Light text on white background

### ISSUE THREAD

**Issue by aftersox** [numixproject/numix-gtk-theme#110]
I am using Ubuntu 13.04. I have provided an example from GIMP, but the same holds for Nautilus, Chrome, and others. This is the top menu, but the same problem also exists for tool-tip menus.

![numix-white-text](https://f.cloud.github.com/assets/3331259/2505903/e3670532-b39e-11e3-932a-97f3c62f6182.png)

**Comment by satya164** [comment]
Are you using the Numix Light theme? If yes, is this the latest version?

**Comment by aftersox** [comment]
I installed from the Ubuntu Software Center: numix-gtk3-light-theme 1.31-0ubuntu1

I just tried it on another Ubuntu 13.04 machine I have. Same result.

**Comment by satya164** [comment]
@aftersox Seems our packager didn't submit the new version. Let me talk to him. Meanwhile, you can send me a mail and I'll send you the latest version.
