### ISSUE TITLE
Black Tab Bar under Ubuntu 14.04

### ISSUE THREAD

**Issue by plumlis** [numixproject/numix-gtk-theme#111]
Just installed Ubuntu 14.04 Final Beta and Numix gtk theme,
There are many black tab bar with Empathy and Gedit,I searched the web and got know that disable overlay scrollbar would slove this.
But I'm love'in overlay scrollbar……so are there any tips to slove this problem?
or some patch?
![_588](https://cloud.githubusercontent.com/assets/6737429/2558360/e544badc-b742-11e3-8bc4-c8224153dde0.png)

**Comment by me4oslav** [comment]
As far as I know - nope.
There is some patch to have no black bars and have overlay scrollbars, but apparently it breaks other stuff.
So, no, not fixable.
Either learn to live with the bug or disable the overlay scrollbars.
P.S. I could be wrong, but I am fairly certain this is the case.

**Comment by plumlis** [comment]
So……I got fixed.
downloaded shimmer-theme 1.6 from saucy and overwrite 1.7 version.
Seems okay,lol

**Comment by me4oslav** [comment]
It has prolly broken some other things, but as long as it works for you ...

**Comment by satya164** [comment]
@plumlis shimmer-themes has a patch. It's almost fine in Ubuntu, but cannot be merged to master.
