### ISSUE TITLE
GNOME Music 3.10 Artist view left-hand toolbar styling

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#112]
![screenshot from 2014-03-29 22 22 31](https://cloud.githubusercontent.com/assets/6999838/2560217/3b2f074e-b7b2-11e3-89dc-928c4f49eed2.png)

The styling appears to be a bit strange in GNOME Music 3.10's left-hand toolbar; I can't exactly identify the issue, as it fails to launch with gtk-parasite, though. :(

**Comment by satya164** [comment]
Hmm... Some styling clash may be. I'll have a look.

**Comment by megax** [comment]
@ghost Still having trouble?

**Comment by megax** [comment]
@khurshid-alam Still having trouble?

**Comment by khurshid-alam** [comment]
Fixed in 3.20
