### ISSUE TITLE
Epiphany 3.12 Private Browsing theming missing

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#113]
![screenshot from 2014-03-30 11 23 35](https://cloud.githubusercontent.com/assets/6999838/2561596/608c704a-b81f-11e3-9758-60845e9e545c.png)

In 3.12, Epiphany (GNOME Web)'s Private Browsing feature uses a completely different theme; I'm not even sure if it's themable. Could this be looked into, please? Thanks in advance.

**Comment by satya164** [comment]
I'll have alook.

**Comment by aperezdc** [comment]
Unfortunately, Epiphany unconditionally loads a stylesheet for incognito mode that always overrides the theme. While this works for Adwaita, it tends to be a mess for other themes which do not play well with the colors of Epiphany's custom stylesheet.

There is a [similar bug report in the Vertex theme](https://github.com/horst3180/Vertex-theme/issues/59), and a related [bug in GNOME's Bugzilla](https://bugzilla.gnome.org/show_bug.cgi?id=742088).

**Comment by megax** [comment]
@khurshid-alam Still having trouble?

**Comment by khurshid-alam** [comment]
Already fixed.
