### ISSUE TITLE
Numix Dark in chromium and firefox 

### ISSUE THREAD

**Issue by mindfulmonk** [numixproject/numix-gtk-theme#114]
As you can see from the screenshots below the icons blend into the background, which looks kinda ugly. Is there a way to fix it? Or can I at least revert to using regular Numix for chromium/firefox and Numix Dark for everything else?

Numix Dark Chromium
![chromium_dark](https://cloud.githubusercontent.com/assets/602167/2566513/4abb827c-b8c6-11e3-844d-7506abcaf3cc.png)

Numix Chromium
![chromium_light](https://cloud.githubusercontent.com/assets/602167/2566514/4af52b62-b8c6-11e3-99ee-612e0201022c.png)

Numix Dark Firefox
![firefox_dark](https://cloud.githubusercontent.com/assets/602167/2566515/4b026156-b8c6-11e3-8ae5-47356b6d95f7.png)

Numix Firefox
![firefox_light](https://cloud.githubusercontent.com/assets/602167/2566516/4b0af848-b8c6-11e3-8893-d42f6b7396a0.png)

**Comment by satya164** [comment]
Hi. Dark themes really don't work well for Chromium and Firefox. You can install a custom theme for Chromium and Firefox which should fix this issue.
