### ISSUE TITLE
Window Decoration Icon too big

### ISSUE THREAD

**Issue by neonmagnets** [numixproject/numix-gtk-theme#115]
Hi, 
After installing Xubuntu 14.04 and changing to the Numix theme the icons in the top left corner are too big (they extend from edge to edge in the top bar) at least with a 1440x900 resolution screen.

It doesn't look very good.

**Comment by satya164** [comment]
Screenshot?

**Comment by neonmagnets** [comment]
![screenshot - 2014-03-31 - 17 57 47](https://cloud.githubusercontent.com/assets/2556900/2570620/e59227ee-b8fb-11e3-817a-7d3e458c43ae.png)

**Comment by satya164** [comment]
Hmm...

@ochosi is there any option to decrease this size?

Anyways, why don't you disable the icons in settings?

**Comment by neonmagnets** [comment]
I like it, I just wish it was a little bit smaller

**Comment by ochosi** [comment]
There definitely isn't any option to control this directly, I'll see whether the size of the icon can be influenced by other variables.

**Comment by ochosi** [comment]
From what I can tell now, the icon-size is calculated relative to the height of the titlebar, which is 24px in Numix hence it uses 22px icons. So the only way I see right now to decrease the icon-size is to decrease the height of the titlebar.

**Comment by ochosi** [comment]
Ok, so after some digging I found a way to make it use 16px icons (which is nice, because they're rendered sharply).
