### ISSUE TITLE
Loss of all window decoration

### ISSUE THREAD

**Issue by jrwiegand** [numixproject/numix-gtk-theme#116]
I have installed this theme twice on Ubuntu 14.04 and I understand that it is still in beta but both times I installed this theme and used it Unity completely crashed. The window decorations disappeared. The icons and the theming done inside the window is fine. The problem becomes the missing borders and title bar on any windows. As well as Unity is completely absent. I am not sure if this is a personal problem or maybe because of Ubuntu beta. Also, if I log into a guest session everything seems to work fine. Finally, the solution to the problem is to change the theme back to Ambience and also remove the configuration files in the home directory.

**Comment by satya164** [comment]
Hmm... I guess it's a Unity bug. @me4oslav can you reproduce the bug?

**Comment by me4oslav** [comment]
I've used Numix in Unity in 14.04 for a while and no, I can not confirm this bug.

**Comment by jrwiegand** [comment]
Maybe it has something to do with Nvidia drivers. I had those installed as well. I would like to try again but as I mentioned I happened multiple times the same way and I would really like not to mess up my system again. I am not sure what to do here. Thanks for any help though.
