### ISSUE TITLE
Glitch on window border

### ISSUE THREAD

**Issue by thiagoc** [numixproject/numix-gtk-theme#117]
Sometimes some windows stay like this on XFCE:

![numix](https://cloud.githubusercontent.com/assets/50272/2579077/8fd557bc-b99c-11e3-88f3-8c9c25838d9d.png)

I'm using Numix Light on Archlinux with latest packages.

**Comment by thiagoc** [comment]
Another image, a little different this time:

![numix2](https://cloud.githubusercontent.com/assets/50272/2591454/994ec0ce-ba6b-11e3-8c8b-b172d8c808e0.png)

**Comment by satya164** [comment]
Probably video driver bug. @ochosi ?

**Comment by ochosi** [comment]
Yes this is a known issue in Xorg, was also discussed for Greybird: https://github.com/shimmerproject/Greybird/issues/50
