### ISSUE TITLE
LibreOffice Radio Buttons/Check Boxes Problem

### ISSUE THREAD

**Issue by Rayonant** [numixproject/numix-gtk-theme#118]
There is a problem in LibreOffice with radio buttons/check boxes which do not appear until you hover the cursor over them, (I will post the link to the images for better understanding) also mention that this also happens with Bluebird, Greybird, Orion but not with Adwaita. Hope you can check it out. I am using Xfce on Mageia, the LO version is 4.1.5.3.

http://s4.postimg.org/p7qn3uxot/Numix_1_Screenshot_060414_15_14_48.png
http://s4.postimg.org/51n54z219/Numix_2_Screenshot_060414_15_15_27.png
http://s4.postimg.org/5foh4km4t/Numix_3_Screenshot_180414_13_53_37.png

**Comment by fitojb** [comment]
Please file this bug to [LibreOffice’s bug tracker](https://www.libreoffice.org/get-help/bug/). As you mentioned already, it happens with other themes sharing GTK+ 2 theming engine. So, it’s _not_ a Numix bug and there’s no point reporting it here.

**Comment by satya164** [comment]
@Rayonant Ok, so it seems to be with murrine engine. Please file a bug against LibreOffice.

**Comment by Rayonant** [comment]
@Fitoschido I'll do that, I just reported the bug here because @satya164 tell me to do it and due to the fact that it involves themes from the Shimmer Project.
