### ISSUE TITLE
Terminal colors?

### ISSUE THREAD

**Issue by addisonamiri** [numixproject/numix-gtk-theme#119]
I saw on [this](http://satya164.deviantart.com/art/Numix-GTK3-theme-360223962) deviant art page that the terminal was open and I can't seem to find that color scheme. Is it a common scheme that was used? If possible a gnome-terminal color scheme would be awesome along with the actual color values as I would like to write a vim colorscheme too.

**Comment by satya164** [comment]
@addisonamiri It's the default color scheme of Gnome Terminal and the theme is the deafult Numix theme. Nothing special here.
