### ISSUE TITLE
close/maximize minimize buttons for dash

### ISSUE THREAD

**Issue by andia89** [numixproject/numix-gtk-theme#122]
According to

https://wiki.ubuntu.com/Unity/Theming

it should be possible to theme, the close/maximize/mnimize buttons in the dash (on the lefthand side top), which are currently, looking like the buttons from the Ambiance-theme. 
Although a minor bug, some softlinks should resolve this problem, shouldn't it?

**Comment by andia89** [comment]
The buttons for unresponsive windows should be replaced as well (according to the same site). 

My workaround so far:

ln -sf /usr/share/themes/Numix/unity/close.svg /usr/share/themes/Numix/unity/close_dash.svg
ln -sf /usr/share/themes/Numix/unity/close_unfocused.svg /usr/share/themes/Numix/unity/close_dash_disabled.svg
ln -sf /usr/share/themes/Numix/unity/close_focused_pressed.svg /usr/share/themes/Numix/unity/close_dash_pressed.svg
ln -sf /usr/share/themes/Numix/unity/close_focused_prelight.svg /usr/share/themes/Numix/unity/close_dash_prelight.svg

ln -sf /usr/share/themes/Numix/unity/maximize.svg /usr/share/themes/Numix/unity/maximize_dash.svg
ln -sf /usr/share/themes/Numix/unity/maximize_unfocused.svg /usr/share/themes/Numix/unity/maximize_dash_disabled.svg
ln -sf /usr/share/themes/Numix/unity/maximize.svg /usr/share/themes/Numix/unity/maximize_dash_pressed.svg
ln -sf /usr/share/themes/Numix/unity/maximize.svg /usr/share/themes/Numix/unity/maximize_dash_prelight.svg

ln -sf /usr/share/themes/Numix/unity/minimize.svg /usr/share/themes/Numix/unity/minimize_dash.svg
ln -sf /usr/share/themes/Numix/unity/minimize_unfocused.svg /usr/share/themes/Numix/unity/minimize_dash_disabled.svg
ln -sf /usr/share/themes/Numix/unity/minimize_focused_pressed.svg /usr/share/themes/Numix/unity/minimize_dash_pressed.svg
ln -sf /usr/share/themes/Numix/unity/minimize_focused_prelight.svg /usr/share/themes/Numix/unity/minimize_dash_prelight.svg

ln -sf /usr/share/themes/Numix/unity/unmaximize.svg /usr/share/themes/Numix/unity/unmaximize_dash.svg
ln -sf /usr/share/themes/Numix/unity/unmaximize_unfocused.svg /usr/share/themes/Numix/unity/unmaximize_dash_disabled.svg
ln -sf /usr/share/themes/Numix/unity/unmaximize.svg /usr/share/themes/Numix/unity/unmaximize_dash_pressed.svg
ln -sf /usr/share/themes/Numix/unity/unmaximize.svg /usr/share/themes/Numix/unity/unmaximize_dash_prelight.svg

ln -sf /usr/share/themes/Numix/unity/close.svg /usr/share/themes/Numix/unity/sheet_style_close_focused.svg
ln -sf /usr/share/themes/Numix/unity/close_focused_pressed.svg /usr/share/themes/Numix/unity/sheet_style_close_focused_pressed.svg
ln -sf /usr/share/themes/Numix/unity/close_focused_prelight.svg /usr/share/themes/Numix/unity/sheet_style_close_focused_prelight.svg

**Comment by mzur** [comment]
@wa4557 Why don't you create a pull request for this? ;-) Symlinks seem like a good solution to me. The paths need to be relative though.
