### ISSUE TITLE
Selected tab highlight missing

### ISSUE THREAD

**Issue by bitrevo** [numixproject/numix-gtk-theme#123]
I'm using the latest Numix theme with Ubuntu 14.04 and the selected tab highlight for GTK apps are missing. For example, check below screenshot when I add 3 tabs in gedit and it doesn't show you which tab is selected.

![screenshot from 2014-05-03 11 10 57](https://cloud.githubusercontent.com/assets/1067833/2869437/933e65f0-d270-11e3-9c31-c2f9a3cf2fcf.png)

**Comment by satya164** [comment]
From which PPA are you using it?

**Comment by bitrevo** [comment]
I'm using the source from git clone and copy to ~/.themes.

**Comment by satya164** [comment]
The master branch no longer supports GTK 3.8 or GTK 3.10. Please use the latest release https://github.com/shimmerproject/Numix/releases
