### ISSUE TITLE
vmware issue

### ISSUE THREAD

**Issue by dschaefer79** [numixproject/numix-gtk-theme#124]
Hi,

When I launch Vmware a white line appear in the toolbar with numix theme,
the bar Vmware version 10.0.2

Is there a way to fix this ?

Thanks

![vmware](https://cloud.githubusercontent.com/assets/7472357/2870203/2a7316fe-d2b3-11e3-980d-593a5a64651f.jpg)

**Comment by megax** [comment]
@khurshid-alam, @dschaefer79 Still having trouble?
