### ISSUE TITLE
Window control colors don't follow custom color

### ISSUE THREAD

**Issue by vitalykorolev** [numixproject/numix-gtk-theme#125]
Custom highlight colors set by GTK Theme Configuration app do not apply to windows controls any more. Other controls seem to be ok.
![image](https://cloud.githubusercontent.com/assets/1957746/2874722/ee7e6aa8-d3f8-11e3-8ce3-3057052f112e.png)

**Comment by satya164** [comment]
@vitalykorolev DO you have latest version?

**Comment by vitalykorolev** [comment]
I have the latest from Numix PPA. And I'm on Ubuntu 14.04.

**Comment by satya164** [comment]
Unity? On unity it won't work as Unity uses pixmaps. It works with
metacity, mutter and xfwm.

**Comment by vitalykorolev** [comment]
Oh no.. but it worked in 13.10 at some point. If you're sure it won't work with Unity in 14, I shall resurrect my blue remix. :)  I like switching to blue once in a while.

**Comment by mzur** [comment]
Technically it should be possible to style the new SVG icons (#127) with arbitrary colors. But I don't know if Unity supports this.

**Comment by satya164** [comment]
@vitalykorolev Earlier Unity was using metacity theme. So it was possible. From 14.04, Unity has its own Unity Decorator. Hence it will no longer work.

@mzur gtk-theme-config doesn't modify any files. It just overrides the colors defined in the theme. I don't think it will be possible for SVGs.
