### ISSUE TITLE
USB/ HDD switched?

### ISSUE THREAD

**Issue by jrwiegand** [numixproject/numix-gtk-theme#126]
So I have noticed in the Ubuntu 14.04 LTS Unity launcher bar when a USB flash drive is plugged in the HDD icon shows up in the launcher. The opposite happens for external HDDs that are plugged-in. I don't know if this is Ubuntu or Numix issue as I don't remember what happened before I installed the Numix theme. I have included a picture below to show the exact 'issue' (if you can really call it that).

![issue](https://cloud.githubusercontent.com/assets/1606617/2875030/c253cdba-d407-11e3-86ea-50db0e3462aa.png)

**Comment by satya164** [comment]
This bug is knows and belongs to numix-icon-theme.
