### ISSUE TITLE
Not all colors are used

### ISSUE THREAD

**Issue by LouisMT** [numixproject/numix-gtk-theme#128]
I don't like the orange colors in Ubuntu, so I tried changing them to blue.

After changing the orange to blue, some menus use blue while others still use orange. I've searched all CSS files for the Hex Color Code (#d64937) but it's not found anywhere. Other themes don't have this problem, so I assume there are some rules missing in this theme's CSS.

Could you please add these rules?

I'll attach screenshots of the problem.

![Wrong Menu](http://i.imgur.com/o41SvR4.png)
![Good Menu](http://i.imgur.com/lAi0xzq.png)

**Comment by satya164** [comment]
Please use gtk-theme-config which is more suited to this task.

If you want to change them manually, you have to at least change in gtk.css, gtk-dark.css and gtkrc.

Also, for changing window manager buttons, you need to edit them manually.
