### ISSUE TITLE
Ubuntu 14.04 with unity: installs Gnome-tweak-tool instead of unity-tweak-tool

### ISSUE THREAD

**Issue by merlijn-sebrechts** [numixproject/numix-gtk-theme#129]
Hi

I just bought numix light theme from USC. After installation there appears an icon in the launcher. Clicking the icon opens gnome-tweak-tool. This has a gaping hole in it on unity... Is it possible to open/install unity-tweak-tool instead of gnome-tweak-tool on unity systems?

Related: https://github.com/shimmerproject/Numix/issues/95

Thanks!

**Comment by satya164** [comment]
Duplicate of #95
