### ISSUE TITLE
Terminal background theming

### ISSUE THREAD

**Issue by me4oslav** [numixproject/numix-gtk-theme#13]
Can we do anything else about the gnome-terminal background, but a plain colour?

**Comment by satya164** [comment]
Seems that we cannot set a background image. But I doubt many will like having a pattern.

**Comment by me4oslav** [comment]
But, it's sexy ;p
On a more serious note I might have seen that in some theme asked it's creator if that's possible.
![Screenshot from 2013-03-11 10:17:48](https://f.cloud.github.com/assets/1658870/242658/4527110e-8a24-11e2-984f-b1631bb935a4.png)

**Comment by satya164** [comment]
I was testing to see if it can be done, but doesn't seem so. Anyways, users can use their own patterns, so problem solved!

**Comment by me4oslav** [comment]
Closing it for the time being.
