### ISSUE TITLE
Confusing naming/descriptions in Ubuntu Software Center

### ISSUE THREAD

**Issue by merlijn-sebrechts** [numixproject/numix-gtk-theme#130]
I stumbled upon the very beautiful [Numix site](http://numixproject.org/) and loved the themes. On the site, it is very clear what options there are and how much each costs. I wanted to buy the light, so I opened the USC. Then, the mess began...

In the USC, I see 5 different versions of the numix theme:
- Numix GTK3 Flat theme
- Numix GTK3 Dark theme
- Numix GTK3 Light theme
- Numix GTK3 Flat theme Dark
- Numix GTK3 Flat theme Light

I have no idea what the difference is between the different themes except that some are light and some are dark. They all seem to be flat, but some have the description "completely flat". Are the "completely flat" ones flatter than the normal ones? What is the difference between the flat theme and the flat dark theme? This is extremely confusing. I have bought the "Numix GTK3 Light theme" but I am not sure that is the same one as on dA...

Is it possible to either remove duplicate packages or make it very clear in the name or in the descriptions what the difference is between them and which ones are the ones you are advertising on your beautiful site?

**Comment by satya164** [comment]
The completely flat ones are no longer supported. We'll remove them from USC.

Yeah, the one you bought is same as dA, but older version, as canonical has yet to approve the update :(

**Comment by merlijn-sebrechts** [comment]
Thanks. When will the icon sets be available in the software center?

**Comment by satya164** [comment]
@galgalesh No one knows :(

**Comment by merlijn-sebrechts** [comment]
OK :(

2014-05-10 10:17 GMT+02:00 Satyajit Sahoo notifications@github.com:

**Comment by satya164** [comment]
The flat themes are removed from USC now. Hence closing this.
