### ISSUE TITLE
No link colors in Corebird

### ISSUE THREAD

**Issue by deadite81** [numixproject/numix-gtk-theme#131]
I am using Arch Linux with the "numix-themes" community package version 2.2.3-1, GNOME 3.12, and the "corebird-git" package from the AUR.

When I use the Numix GTK theme none of the links have color in Corebird.  Other themes, such as Adwaita and Zukitwo, display the link colors correctly, so this appears to be a problem specific to Numix.

Adwaita:
![screenshot_adwaita_with_link_color](https://cloud.githubusercontent.com/assets/231300/2923660/404f9646-d71d-11e3-9223-81d3ded159d5.png)

Numix:
![screenshot_numix_no_link_color](https://cloud.githubusercontent.com/assets/231300/2923663/42d9df20-d71d-11e3-91c7-2c1efe7c9cc2.png)

Thanks for the great theme and your continued work on it.

**Comment by satya164** [comment]
Should be fixed now. Can you try again?

**Comment by deadite81** [comment]
Yes the links appear correctly now.  Thanks!
