### ISSUE TITLE
unity-force-quit window

### ISSUE THREAD

**Issue by andia89** [numixproject/numix-gtk-theme#132]
The window that appears when dealing with unresponsive windows looks "out-of-place" in unity. I've attached two screenshot (german) comparing Numix to Ambiance

![ambiance](https://cloud.githubusercontent.com/assets/6475757/2936029/0d797150-d840-11e3-98e1-328d97924dd6.png)
![numix](https://cloud.githubusercontent.com/assets/6475757/2936030/0ff10632-d840-11e3-8ac6-b60e59701688.png)

Note that I replaced the window buttons, to follow the Numix-theme according to this site:
https://wiki.ubuntu.com/Unity/Theming

and this bug:
https://github.com/shimmerproject/Numix/issues/122

**Comment by andia89** [comment]
To trigger the window:
1. Run gedit
2. in a terminal: killall -STOP gedit
3. try to close gedit -> voilá

**Comment by mzur** [comment]
I can confirm this bug.

**Comment by satya164** [comment]
Are you using the theme from the PPA?

**Comment by satya164** [comment]
And what do you mean by replaced the window buttons? Numix already supports Unity!

**Comment by mzur** [comment]
@satya164 I think he meant, that the force quit window uses the `dash` icons as window controls (#122).

```
$THEME_PATH/unity/icons/close_dash.{svg, png}
$THEME_PATH/unity/icons/close_dash_disabled.{svg, png}
...
```

[source](https://wiki.ubuntu.com/Unity/Theming)

**Comment by Tammuz** [comment]
I can confirm the bug, using theme from PPA and downloaded from here.
