### ISSUE TITLE
Battery icon in xfce too big

### ISSUE THREAD

**Issue by Tammuz** [numixproject/numix-gtk-theme#135]
Hello,
the battery icon on xfce desktop is way bigger than other icons. See attachment
![schermata da 2014-05-15 23 28 34](https://cloud.githubusercontent.com/assets/7479982/2990332/bdebcfe6-dc6f-11e3-84c3-33d45239b28a.png)

**Comment by satya164** [comment]
Hmm.. weird. BTW this issue belongs to https://github.com/numixproject/numix-icon-theme
