### ISSUE TITLE
Unity application launching visual feedback

### ISSUE THREAD

**Issue by rui-castro** [numixproject/numix-gtk-theme#136]
Hi,

The icons in unity launcher don't give any feedback when the applications are launching.
I'm don't know if this is a principle option or just something that is missing, but I think it is important to have some sort of visual feedback when you click an icon and the correspondent application is launching.

I've already posted this request in https://github.com/numixproject/numix-icon-theme/issues/123, but @me4oslav redirected me to this project.

@me4oslav also replied that "...  the nuking of the boxes (which is a design call we made) caused the lack of visual feedback when launching an app ...", but it wouldn't need to be a box arround the icon. The indicators of open/active windows (white rectangles in my case, don't know if it's always the same) could blink to indicate that the application is starting.

Congratulations for this great icon set/theme :)

Best,
Rui

**Comment by me4oslav** [comment]
As started in my last comment here, this is not fixable - https://github.com/numixproject/numix-icon-theme/issues/123
Satya, you might as well close that bug report.
