### ISSUE TITLE
Chrome menu separators look ugly

### ISSUE THREAD

**Issue by xyl0n** [numixproject/numix-gtk-theme#139]
It appears that with the Chrome update, there are some widgets in menus that are not being themed. These include the separators, menu borders, and button borders. See the screenshot.

![screenshot from 2014-05-25 12 20 36](https://cloud.githubusercontent.com/assets/4588620/3076868/81cf2b74-e3ff-11e3-8c75-1098ee7cc26c.png)

Not sure if intentional but they do look out of place seeing as how all other gtk 2 apps have dark menu separators.

**Comment by Tammuz** [comment]
It's because of Aura, all the themes are messed up. I switched back to Firefox also for that.

**Comment by xyl0n** [comment]
@MirkCe indeed, but it only seems to affect themes with dark menus like Numix and Iris for obvious reasons

**Comment by satya164** [comment]
Yes. Let's find out what we can do about it.

**Comment by Tammuz** [comment]
Any update?

**Comment by khurshid-alam** [comment]
This is a one bug I want to fix. It is long due. Initially it was chrome/chromium issue. But with Chromium >=47, I think it can be fixed.

**Comment by andia89** [comment]
@khurshid-alam Do you know where can I find information about how to fix this bug? Do we need to make a theme only for chrome/chromium or can it be fixed within the current theme?

**Comment by khurshid-alam** [comment]
@wa4557 Here you go: https://chromium.googlesource.com/chromium/src/+/master/docs/linux_gtk_theme_integration.md

I think, It can only work for chromium only as it still uses GTK+ for theme support. Although browser frame is now rendered by aura.

**Comment by andia89** [comment]
@khurshid-alam Thanks! There seems to be no way however to change this :( At least not an obvious one. All (dark) themes I've seen so far have the same "seperator" color + there seems to be no member in ChromeGtkFrame responsible for coloring the menus...

**Comment by xyl0n** [comment]
@wa4557 I've experimented around with Chrome menus periodically for a while and it seems that while you can set the styling for the background and menu items of Chrome menus, separators are not influenced by traditional styling. It's possible that they're either hardcoded or there's some other way of theming them. Attempting to look through the Chromium/Aura source code might be helpful if a bit impossible :P

**Comment by darekdeo** [comment]
Worth to mention it's not only Chrome, but probably all Chromium based software including software based on Electron. For example those ugly separators appear also in Atom text editor. :(

**Comment by khurshid-alam** [comment]
With Chromium GTK3 (>=59), this is resolved.
