### ISSUE TITLE
Datetime indicator font color

### ISSUE THREAD

**Issue by hotice** [numixproject/numix-gtk-theme#14]
In Ubuntu 13.04, if you enable the "Show week numbers" option, the week numbers font color is the same as the actual days, which shouldn't be. The same goes for the week day names. 

Screenshot attached

![numix-datetime](https://f.cloud.github.com/assets/325449/268001/83e51d92-8ef6-11e2-9ffd-0a7e398ff2c9.png)

**Comment by me4oslav** [comment]
Also a bug, satya164, fix it? **puppy eyed face**

**Comment by satya164** [comment]
Fixed in 17a8adba81e1ed8f0f0cb32911519a978680bc73
