### ISSUE TITLE
Minor issues with background

### ISSUE THREAD

**Issue by pgera** [numixproject/numix-gtk-theme#141]
The theme looks great. I noticed that the orange highlight doesn't play too well with objects which have a similar foreground. For instance, the volume slider in Ubuntu has an orange foreground, and is completely masked by the background when it is selected. Similarly, in synaptic package manager, supported packages have ubuntu's logo, which is predominantly orange.(https://help.ubuntu.com/community/SynapticHowto#Status_Icons)

**Comment by satya164** [comment]
Really cannot do anything. The issue will happen with any color.
