### ISSUE TITLE
Panel selectors look weird under Linux Mint 17

### ISSUE THREAD

**Issue by hkenneth** [numixproject/numix-gtk-theme#142]
The panel selectors (aka: "Installed", "Get more online", "Other settings" in the screenshot below) look awkward in Linux Mint 17 (based on Ubuntu 14.04). This, however, only happens in a limited amount of applications, mainly the control panel applications. Other applications, such as Update Manager, do not have such issue.

Weird panel selectors:

![screenshot from 2014-06-04 18 19 12](https://cloud.githubusercontent.com/assets/1007754/3181455/3fd1835a-ec3f-11e3-929d-82c0b0b4b2b3.png)

Panels look fine:

![screenshot from 2014-06-04 18 29 23](https://cloud.githubusercontent.com/assets/1007754/3181529/2e2f1e36-ec40-11e3-98a3-34e2b610f85e.png)

**Comment by megax** [comment]
@hkenneth @khurshid-alam Still having trouble?

**Comment by khurshid-alam** [comment]
Already fixed
