### ISSUE TITLE
List: Selected and hover = bg and fg same color

### ISSUE THREAD

**Issue by SammysHP** [numixproject/numix-gtk-theme#143]
In Dolphin (Qt with QGtkStyle) hovering an selected item in a list results in the same foreground and background color (using Numix 2.2.3 in Arch Linux).

Upper item selected, lower item hovered:

![Imgur](http://i.imgur.com/FHOdkwK.png)

Now hovering selected item:

![Imgur](http://i.imgur.com/JNLjFkY.png)

The background color changes, but the foreground (text) color does not change. Maybe related to QGtkStyle? Haven't found hover in Gtk+ yet.

**Comment by khurshid-alam** [comment]
Does it still occur with latest version?

**Comment by megax** [comment]
@SammysHP Still having trouble? :)

**Comment by SammysHP** [comment]
Not using QGtkStyle anymore. Meanwhile I think this is a Qt/KDE issue. With qt5 they changed so much and I don't know what does what and what happens next.
