### ISSUE TITLE
Selected list item with progress bar same color

### ISSUE THREAD

**Issue by SammysHP** [numixproject/numix-gtk-theme#146]
You can see an example in the download list of Firefox while a file is downloaded. Select the file in the download list (chrome://browser/content/downloads/contentAreaDownloadsView.xul). The background of the selected item will have the same color as the progress bar.

**Comment by satya164** [comment]
Firefox is not native GTK, so I cannot do anything about that.

But the theme is going under a rewrite, and I'll try to address this for other apps.
