### ISSUE TITLE
Gtk-WARNING **: Theme parsing error in transmission-gtk

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#148]
Hi,

On Numix I downloaded around March-April 2014 I did not see this error. Today I ran git clone and downloaded the latest version, and when I ran transmission-gtk I see this error;

Gtk-WARNING **: Theme parsing error: gtk-widgets.css:135:2: Missing name of pseudo-class

I'm using gtk 3.8

thanks...

**Comment by satya164** [comment]
Seems to be a problem with GTK3.8. Current Numix version no longer supports GTK3.8.

**Comment by ghost** [comment]
ok..
