### ISSUE TITLE
Consider some nice improvements

### ISSUE THREAD

**Issue by 2buisson** [numixproject/numix-gtk-theme#149]
**Don't now why, but there are some progress bar poorly rendered**
The focus color is the same than the background one, here is Firefox:

![progressbarfocus](https://cloud.githubusercontent.com/assets/8150894/3933155/7abd001c-2479-11e4-8041-db3336784881.jpg)

**Some interfaces are weird, rendered just like Windows 98 does**
Like Filezilla, or the file prompt window, with too hard shadows, here is PlayOnLinux:

![toohardshadows](https://cloud.githubusercontent.com/assets/8150894/3933156/7b015636-2479-11e4-8386-51abfbe2430c.jpg)

Numix still the best theme suite, I use it every days, but there is some things that might be changed :)
Thanks, Numix is awesome!

**Comment by satya164** [comment]
You need to install the the murrine theme engine.

**Comment by 2buisson** [comment]
Well.. sorry, thanks!

**Comment by satya164** [comment]
@varyoo no issues :)
