### ISSUE TITLE
LibreOffice appmenu selected item color same as font color

### ISSUE THREAD

**Issue by hotice** [numixproject/numix-gtk-theme#15]
The LibreOffice appmenu selected item color is the same as the font color. See attached screenshot.

![numix-libreoffice-bug](https://f.cloud.github.com/assets/325449/268003/cdc638f6-8ef6-11e2-8bdc-b860137129fb.png)

Tested in Ubuntu 13.04

**Comment by me4oslav** [comment]
Yup, a bug. satya164 can you please have a look at this one too?

**Comment by satya164** [comment]
I have no clue. May be it Is somehow related to this - https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1153350

**Comment by fitojb** [comment]
This is certainly NOT a bug in this theme, and also I can’t see how it can be exclusive to LibreOffice. IMO, it’s in indicator-application.

You just need to re-apply the theme and the issue will go away.

**Comment by fitojb** [comment]
Disregard the last part of my previous comment: it seems that indeed only LibreOffice is presenting the problem. But it happens with Ambiance as well, so it’s not related to this theme.

**Comment by ochosi** [comment]
I was just about to look into this bug, when I noticed I can't reproduce it... Are you sure this isn't fixed already?
![libre](https://f.cloud.github.com/assets/261436/689576/2a74be5e-dab7-11e2-8b87-89980f5da8a5.png)

**Comment by ochosi** [comment]
Or wait, does it only affect the application-menu indicator?

**Comment by satya164** [comment]
It haapens with appmenu indicator

**Comment by satya164** [comment]
Closing this issue as it is a bug in indicator-appmenu itself. Link to the bug report - https://bugs.launchpad.net/ubuntu/+source/indicator-appmenu/+bug/1153350
