### ISSUE TITLE
Elements not visible  - Transmission 2.84

### ISSUE THREAD

**Issue by dzklaim** [numixproject/numix-gtk-theme#151]
System: Arch x64, GTK 3.12.2, Numix theme 2.3
App: Transmission 2.84 - compact view

The completion percentage of the torrent selected is not visible.﻿
![screenshot from 2014-09-04 23 42 19](https://cloud.githubusercontent.com/assets/1281848/4174797/a5d93676-35a9-11e4-8cf6-e733a556897e.png)

**Comment by khurshid-alam** [comment]
Already Fixed.
