### ISSUE TITLE
The menu isnt looking nice on elementary os

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-gtk-theme#152]
Hello,
i'm using elementary os 0.2.1 base on ubuntu 12.04
like you see on the picture below , the menu isnt looking nice at all..
hope it will be fixed asap
![screenshot from 2014-09-07 23 02 16](https://cloud.githubusercontent.com/assets/7660997/4179711/82c33e50-36d2-11e4-98e2-10b3981ef5f2.png)

Sorry if the picture is so big..
and thanks for the awesome theme :D

**Comment by satya164** [comment]
You need to use the GTK3.4 version.
