### ISSUE TITLE
Distorted Fonts in OpenSUSE 13.1

### ISSUE THREAD

**Issue by osjerick** [numixproject/numix-gtk-theme#154]
Sometimes the fonts appears distorted in OpenSUSE 13.1.
![numix1](https://cloud.githubusercontent.com/assets/8047984/4340133/e7fa190e-402a-11e4-87d5-8424fe91cbc4.png)
![numix2](https://cloud.githubusercontent.com/assets/8047984/4340132/e7f95776-402a-11e4-9279-bdfd44d54620.png)

**Comment by satya164** [comment]
It's a problem in font rendering and not with GTK theme.

**Comment by osjerick** [comment]
But only happens when Numix GTK theme is enabled.
