### ISSUE TITLE
System monitor background colour

### ISSUE THREAD

**Issue by aldomann** [numixproject/numix-gtk-theme#156]
As you can see in the picture below, the background of the graphs and the arrows doesn't match the GTK+ background colour.

![screenshot from 2014-09-24 23 19 55](https://cloud.githubusercontent.com/assets/729732/4416925/8e1adbc8-454b-11e4-986a-cc4242d62d1f.png)

**Comment by bilelmoussaoui** [comment]
still the same bug
![moniteur systeme_003](https://cloud.githubusercontent.com/assets/7660997/4799832/d143f69a-5e1f-11e4-8037-f09fa9d7662b.png)
