### ISSUE TITLE
 Line between the titlebar and toolbar for apps that use a dark theme

### ISSUE THREAD

**Issue by hotice** [numixproject/numix-gtk-theme#16]
On apps (like the default Ubuntu image viewer) that use a dark theme, there's a line between the titlebar and toolbar, at least in Unity (Ubuntu 13.04).  See attached screenshot.

![numix-dark-apps-bug](https://f.cloud.github.com/assets/325449/268006/2711119c-8ef7-11e2-8843-74b5da49a44a.png)

**Comment by me4oslav** [comment]
We don't need that, I think. satya164 can you look at it?

**Comment by satya164** [comment]
Are you sure about that? Coz doing that will remove the separator between the menubar and toolbar in non-unity environments.

**Comment by me4oslav** [comment]
I don't think we need that at the theme.
BTW, what's up with your toolbar being dark? The current theme only has light toolbar for the time being.

**Comment by satya164** [comment]
It is the dark theme used in some GTK3 apps.

**Comment by me4oslav** [comment]
I see.
