### ISSUE TITLE
Black color in some description (nautilus)

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-gtk-theme#160]
Hello, i ve got an other bug on the numix-gtk dark theme on ubuntu 14.10 beta 2

the numix-gtk theme version : 2.3+312~201409292317~ubuntu14.10.1
nautilus version : 1:3.10.1-0ubuntu14
some pictures : 

![capture du 2014-10-15 23 46 37](https://cloud.githubusercontent.com/assets/7660997/4655026/9a7e0f80-54bd-11e4-95d9-c13e5a8e07c9.png)
![capture du 2014-10-15 23 46 49](https://cloud.githubusercontent.com/assets/7660997/4655027/9a84fdf4-54bd-11e4-9f2e-431c6cd2b11a.png)

i hope you understand what i'm trying to say..
Thank you

**Comment by satya164** [comment]
This is caused due to overlay scrollbar.
