### ISSUE TITLE
Menu gedit all grey

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#163]
with numix and gedit Jessie, the menu is all grey.

![capture du 2014-10-23 16_43_07](https://cloud.githubusercontent.com/assets/9335916/4755140/37ffb4f6-5ac3-11e4-976c-d2b4a625c2eb.png)

it's best with this gtk-theme-config:

![capture du 2014-10-23 16 41 21](https://cloud.githubusercontent.com/assets/9335916/4755176/744c417c-5ac3-11e4-9458-fbd11880fcb0.png)

the result:

![capture du 2014-10-23 16 41 33](https://cloud.githubusercontent.com/assets/9335916/4755189/87fd675a-5ac3-11e4-8fc7-2d39219bd796.png)

thanks

**Comment by seankhl** [comment]
3.14 isn't supported see #155

**Comment by ghost** [comment]
Yes, i see #155 after write this issue.

But Satya make gtk-teme-config and if i change the custom menu colors, this theme may be use with gedit and the other appli gnome 3.14...

It's a simple way to use this good theme, with Debian Jessie.
The way with sass is more difficult!

I hope so Numix support gtk 3.14, when Jessie becomes stable for exemple...

**Comment by ghost** [comment]
Thanks,
for info numix blue-remix was good appearance since few weeks...
it was a good alternative, but now the red win!

**Comment by satya164** [comment]
@tome-z :D
