### ISSUE TITLE
Antergos Numix frost light WPS office skin needed

### ISSUE THREAD

**Issue by sergioad** [numixproject/numix-gtk-theme#168]
Hello friends, do you can make a Numix frost and Numix frost light WPS office skins with Numix icons?
If you can not include icons it is not problem

**Comment by fitojb** [comment]
I would say that’s outside the scope of this repository, which contains the GTK+ theme. But everyone is welcome to create that and share it.

**Comment by sergioad** [comment]
Ok :smile:
