### ISSUE TITLE
Menu texts disappear !

### ISSUE THREAD

**Issue by louis-etne** [numixproject/numix-gtk-theme#169]
Hello! 
I recently install Numix on my new ArchLinux. It's beautiful.

But, and I don't know why, the applications menus are white! Look : 
![capture du 2014-11-09 08 48 10](https://cloud.githubusercontent.com/assets/4344540/4966853/4381d970-67e9-11e4-9771-5377ccd20f15.png)

How can I fix it ? Thank's for your help!
(Sorry for my english, I'm french)

**Comment by seankhl** [comment]
3.14 isn't supported see #155

**Comment by louis-etne** [comment]
Oh ok.. And did you know when it will be supported ?

**Comment by satya164** [comment]
Duplicate of #155
