### ISSUE TITLE
There’s no bitmap for Metacity’s window menu

### ISSUE THREAD

**Issue by fitojb** [numixproject/numix-gtk-theme#17]
Thus making it invisible while still clickable. I’d suggest a facing-down arrow. Thanks for considering, folks! :)

**Comment by satya164** [comment]
I don't think it's necessary anymore. Most themes don't have that.

**Comment by fitojb** [comment]
You didn’t provide a valid (non-lame) rejection rationale… Would you accept it if I created the missing asset (and a patch)? ;-)

**Comment by satya164** [comment]
The reason is, I don't have time and again it doesn't have any negative
effects.

If you want, you can. But do it asap coz 21st is UI freeze and I can't get
it to the official repos after that.
