### ISSUE TITLE
Panel Icons for WICD

### ISSUE THREAD

**Issue by skmexyz** [numixproject/numix-gtk-theme#171]
The default panel icons for WICD are pretty ugly. They are .pngs. located in usr/share/pixmaps/wicd
Is it possible to have them replaced with at least the default network manager icons? 
![screenshot from 2014-11-23 12 32 55](https://cloud.githubusercontent.com/assets/2701579/5158494/e33e19fa-730c-11e4-9344-a75a5ed9a7b9.png)

**Comment by satya164** [comment]
Hi. This is not a GTK theme bug. Please report here - https://github.com/numixproject/numix-icon-theme
