### ISSUE TITLE
Gnome 3.14 shell (date widget)

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-gtk-theme#172]
Hello, 
i know you're still working on apporting Numix-gtk-theme to the last version of gtk; but i would really like to ask you to fix a bug that i've with the default theme on the date widget
![screenshot from 2014-11-23 20 29 24](https://cloud.githubusercontent.com/assets/7660997/5158904/9ea550c2-734f-11e4-988f-046184b7170b.png)

i'm using Ubuntu Gnome 14.10 with Gnome Shell 3.14 
hope you could fix this (if you are going to make a Gnome-shell theme of course!) Thanks

**Comment by satya164** [comment]
Hi. This widget is part of the Shell theme, not the GTK theme. Please use Elegance Colors with a Numix preset - http://fav.me/d525x6c
