### ISSUE TITLE
Fedora 21 repository

### ISSUE THREAD

**Issue by lasombra** [numixproject/numix-gtk-theme#177]
Hi, Fedora 21 is officially out! :) Any plans to get the build service and repository up?

**Comment by satya164** [comment]
Yup, as soon as the Fedora 21 is supported in OpenSUSE build service.

**Comment by joerx** [comment]
Is it even working on F21/GTK 3.14? Tried installing from the F20 repo and it was a mess.

**Comment by satya164** [comment]
@joerx Install the master branch. The one in the repo will only work with GTK3.8 - 3.12

**Comment by joerx** [comment]
Thanks @satya164, I will try  - btw. are there any plans for a COPR repo?

**Comment by satya164** [comment]
@joerx Not sure. I've not had any experience with COPR. Help is appreciated.
