### ISSUE TITLE
Numix Sass: New color scheme makes it brighter

### ISSUE THREAD

**Issue by khurshid-alam** [numixproject/numix-gtk-theme#178]
Numix Saas introduced new color scheme which makes it much brighter than it used to be. And the perfect balance between dark & light is lost.

**_Color Scheme (Gtk-3.12):**_

``` css

/* default color scheme */
@define-color bg_color #dedede;
@define-color fg_color #555555;
@define-color base_color #f9f9f9;
@define-color text_color #333333;
@define-color selected_bg_color #d64937;
@define-color selected_fg_color #f9f9f9;
@define-color tooltip_bg_color #2d2d2d;
@define-color tooltip_fg_color #dcdcdc;

/* dark color scheme */
@define-color dark_bg_color #2d2d2d;
@define-color dark_fg_color #dcdcdc;
```

**_Color Scheme (Sass):**_

``` scss
// default color scheme
$bg_color: #eee;
$fg_color: #444;
$base_color: #fff;
$text_color: #444;
$selected_bg_color: #f06860;
$selected_fg_color: #fff;
$tooltip_bg_color: #444;
$tooltip_fg_color: #eee;

// dark colors
$dark_bg_color: #444;
$dark_fg_color: #eee;
```

**Comment by satya164** [comment]
The color scheme is not final. Right now I first need to finish the port before I can think about colors.

**Comment by khurshid-alam** [comment]
Ok. Understood. (I tried with older scheme with sass. Everything works nice except it makes desktop icon-font color black.)

**Comment by satya164** [comment]
@khurshid-alam yeah, there are no nautilus styling yet

**Comment by nazar-pc** [comment]
Anyway +1 for returning previous colors from me

**Comment by arximboldi** [comment]
+1 old colors too

**Comment by nazar-pc** [comment]
Is reverting colors to darker ones even planned?
I'm using hacked versions right now to make it more like old one.

**Comment by khurshid-alam** [comment]
Feel free to open a PR.

**Comment by lots0logs** [comment]
AFAIK there is no plan to darken the new colors. Obviously everyone has their own preference, but I rather like the current colors and I prefer them over the old (pre-sass) colors. @satya164 , what say you?

**Comment by nazar-pc** [comment]
To be honest, there are few themes that are kind of dark, but this one was truly dark and very consistent. Now I'm kind of disappointed, since it looks much closer to "average" let's say.
You can see some comparison of current colors and colors from #363 on screenshots: https://owncloud.mokrynskyi.com/index.php/s/Z34NWp0LC4nE2G4
Current dark is not quite dark actually, very difficult to look at at night.

**Comment by khurshid-alam** [comment]
Yes. When I opened this issue, there were problems with some elements using old-colors and some were not. Gtk-css was a mess back then ( still is). But now it blends rather well and we should stay with current color scheme.

@nazar-pc Your PR changes only global color scheme.....

**Comment by nazar-pc** [comment]
What else should I add there? I'm not involved in any GTK themes development at all and have rather bad understanding how it works (but I do know SCSS and CSS well). Just hacked to make it working :smile:

**Comment by khurshid-alam** [comment]
@nazar-pc https://github.com/numixproject/numix-gtk-theme/pull/363#issuecomment-211740786

**Comment by satya164** [comment]
@lots0logs Open to tweak the other colors except the Numix red. But we're never really going to satisfy everyone. Some people will like the old colors and some will like the new colors.

**Comment by lots0logs** [comment]
@satya164 Yeah, I think that at this point, we've made a decision and should stick with it. That's my vote anyways :wink:

**Comment by satya164** [comment]
@lots0logs I guess we can darken the dark theme a bit, but keep the normal theme as it is :)

**Comment by nazar-pc** [comment]
If there is Red flavor (in this repo?) can we add "Darker" flavor just for even darker version of normal one?
I have nothing against normal theme (because I'm not interested in it :smile:)

**Comment by lots0logs** [comment]
@satya164 Hmm..are you sure? I mean, like you said, we can't please everyone. I think the that we might upset just as many people as we would please by changing the colors for the dark variant. IJS, its your call of course.

**Comment by satya164** [comment]
@lots0logs True. Let's see if there's enough demand for making the dark theme darker.

**Comment by SammysHP** [comment]
Actually I changed the _light variant_ back to the previous version from the last release.

https://github.com/SammysHP/numix-gtk-theme/commit/9411b7dc1c2974e817142b93c37c9a61708c96b1

The new version is too grayish and has too low contrast IMHO.

**Comment by nazar-pc** [comment]
I've just updated [my fork](https://github.com/nazar-pc/numix-gtk-theme/tree/darker-dark) to also patch 3.20's dark styles and it looks great! I've being using default brighter version for a while and now I don't understand how did I survive for so long...

Who, among those against darker variant, are actually using it as primary theme?

**Comment by Sispheor** [comment]
@nazar-pc Thx for your fork. I prefer the old color version.

**Comment by khurshid-alam** [comment]
Resolved in 9e4844a70bc3eaab792c4992176e063570da4f41

**Comment by nazar-pc** [comment]
@khurshid-alam, how did it resolved the issue? Colors are still as painfully bright as they were, nowhere near what I loved about dark flavor of Numix theme and why I've switched to it in the first place.

Updated [my fork](https://github.com/nazar-pc/numix-gtk-theme/tree/darker-dark) once again and very sad that I'll need to do this till the end of times now.

**Comment by Sispheor** [comment]
+1

Le 13 juin 2017 11:32 AM, "Nazar Mokrynskyi" <notifications@github.com> a
écrit :

**Comment by khurshid-alam** [comment]
@nazar-pc See @bg-color is now set `#dedede ` which is darker. This bug is not about making dark-variant darker but rather making normal version little darker. We are not going back the old dark color which was to close to `#000` and hence created extreme contrast with `#fff`
