### ISSUE TITLE
Numix Sass: Gtk button cut-off

### ISSUE THREAD

**Issue by khurshid-alam** [numixproject/numix-gtk-theme#179]
It reappeared in sass but this time cut-off occurs horizontally from the edge.

![image](http://i.imgur.com/2OsFxhb.png)

**Comment by satya164** [comment]
Are you on Ubuntu?

**Comment by khurshid-alam** [comment]
Yes. I am on Ubuntu-Gnome with Gtk-3.14

**Comment by satya164** [comment]
And that screenshot is from gedit? Which version?

**Comment by khurshid-alam** [comment]
Yes. That was from gedit (3.14) from gnome-staging ppa.
