### ISSUE TITLE
Openbox workspace switch indicator is all black

### ISSUE THREAD

**Issue by Migg** [numixproject/numix-gtk-theme#18]
Hope it's not something related to my configuration. Using numix both as a gtk and a openbox theme.
![2013-03-19--1363688987_1366x768_scrot](https://f.cloud.github.com/assets/2452237/276694/4f43cfe8-90b3-11e2-9ea6-646891eae40e.png)

**Comment by jchmura** [comment]
I have the same problem when I select numix as openbox theme.

**Comment by satya164** [comment]
Fixed in https://github.com/shimmerproject/Numix/commit/e94c6bbb592b3733539de3f0d20d20394ce3c5ea
