### ISSUE TITLE
Numix Sass: Ugly toolbar buttons

### ISSUE THREAD

**Issue by khurshid-alam** [numixproject/numix-gtk-theme#180]
As seen from the screenshot,  Toolbar buttons are not exactly flat & any pressed/selected button is not visible properly (when we compare how it appears on Adwaita).

![image](http://i.imgur.com/jrUpAaW.png)

**Comment by satya164** [comment]
Does this happen with the latest commits also?

**Comment by khurshid-alam** [comment]
@satya164 yes latest commit sloved the issue. 

But now it(& some other commits) makes everything(toolbar/dialog  button size, padding..etc) much bigger. Numix is flat compact theme & should stay like this. I hope this temporary & not intentional. 

Edit: I noticed that now it is using 6 as spacing instead of 5.

**Comment by satya164** [comment]
@khurshid-alam more adjustments will be done, and nothing is final as of now.
