### ISSUE TITLE
Gnome session fallback language indicator

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-gtk-theme#183]
Hello; 
ive got something very weird : 

![selection_001](https://cloud.githubusercontent.com/assets/7660997/5532922/a9205532-8a3e-11e4-86df-1a608ef0737f.png)

![menu_003](https://cloud.githubusercontent.com/assets/7660997/5532923/a95b6f64-8a3e-11e4-91b2-2d8482d7f3ed.png)

gtk version : 
libgtk2.0-0:
  Installed: 2.24.25-0ubuntu1
  Candidate: 2.24.25-0ubuntu1
  Version table:
 **\* 2.24.25-0ubuntu1 0
       2012 http://archive.ubuntu.com/ubuntu/ utopic/main amd64 Packages
        100 /var/lib/dpkg/status
libgtk-3-0:
  Installed: 3.12.2-0ubuntu15.2
  Candidate: 3.12.2-0ubuntu15.2
  Version table:
 **\* 3.12.2-0ubuntu15.2 0
       2012 http://archive.ubuntu.com/ubuntu/ utopic-proposed/main amd64 Packages
        100 /var/lib/dpkg/status
     3.12.2-0ubuntu15.1 0
       2012 http://archive.ubuntu.com/ubuntu/ utopic-updates/main amd64 Packages
     3.12.2-0ubuntu15 0
       2012 http://archive.ubuntu.com/ubuntu/ utopic/main amd64 Packages

Ubuntu version 14.10
Everything is up to date
Numix gtk theme version : 2.4 

Thanks!

**Comment by satya164** [comment]
This is an issue with numix-icon-theme - https://github.com/numixproject/numix-icon-theme/issues
