### ISSUE TITLE
Menu's shadows ugly behaviour

### ISSUE THREAD

**Issue by paolodragone** [numixproject/numix-gtk-theme#186]
Some menus, tooltips and other components have some problems with their shadows, which behaves strangely and quite ugly.
![screenshot from 2014-12-25 18 17 00](https://cloud.githubusercontent.com/assets/1681170/5554600/b2994c4e-8c65-11e4-938a-b5afbcdbb7a3.png)
![screenshot from 2014-12-25 18 19 56](https://cloud.githubusercontent.com/assets/1681170/5554601/b2999442-8c65-11e4-89c6-a2268bdbe2e8.png)

I use Ubuntu GNOME 14.10, with GNOME 3.14.
The screenshots are taken from Nautilus.

**Comment by satya164** [comment]
This issue also happens with other themes AFAIK. Doesn't it?

**Comment by khurshid-alam** [comment]
This is most probably the problem with xorg-intel driver. On ubuntu it can be fixed using xorg-edger ppa. https://plus.google.com/102632337306838053295/posts/YKRuoUv4bh5

**Comment by satya164** [comment]
Closing it as it's not a Numix bug.
