### ISSUE TITLE
GNOME Terminal transparency

### ISSUE THREAD

**Issue by kpocius** [numixproject/numix-gtk-theme#187]
As soon as I enable Numix theme, installed from the master branch on Fedora 21, I loose terminal transparency.

If fact, if the terminal is open at the time, it retains transparency until I exit, but when I start it again, it's no longer transparent.

Interesting thing is that if I try to take a screenshot, it comes out as checker-board, which would indicate that the terminal is in fact transparent, but it's like there's another color behind it. Odd.

**Comment by Arrogance** [comment]
Yep, I have the same problem. If you adjust the transparency slider and uncheck/check custom font, then the transparency appears again.

**Comment by khurshid-alam** [comment]
We don't support transparency in the theme. You can change with custom profile.
