### ISSUE TITLE
Thunderbird addons "gears" toolbar menu looks disabled

### ISSUE THREAD

**Issue by wavexx** [numixproject/numix-gtk-theme#189]
In Thunderbird (tested on 31) -> Menu -> Addons page, click the "gears" icon next to the search box.
The drop-down menu that appears looks completely disabled (though it's active and working fine).

The same drop-down in Firefox looks normal.

**Comment by satya164** [comment]
Screenshot?

**Comment by wavexx** [comment]
![2015-01-17-16 36 43](https://cloud.githubusercontent.com/assets/1017726/5789350/535fec92-9e67-11e4-915c-32575ee18d15.png)

**Comment by satya164** [comment]
@ochosi any idea?

**Comment by wavexx** [comment]
Do I get the idea that you don't have this issue?

**Comment by satya164** [comment]
I don't use Thunderbird

**Comment by dirtydancing** [comment]
Hi, I can NOT reproduce this issue with Ubuntu 14.10 and Thunderbird 31.4.0 (Numix GTK theme 2.4).

Screenshot:
![thunderbird](https://cloud.githubusercontent.com/assets/7164227/6285286/3abd6630-b8fa-11e4-8a96-f1b4226db461.png)

**Comment by wavexx** [comment]
I've found the issue. I've customized the gtk foreground/background colors manually, and for some reason thunderbird uses them incorrectly in this popup.
