### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by tt123** [numixproject/numix-gtk-theme#19]
Great theme! Not sure if it's by design or not, but there are dashes located on the scrollbar of Firefox (see Pic) on Xubuntu 12.10. Thanks!
![Screenshot - 03202013 - 06:55:03 AM](https://f.cloud.github.com/assets/3921268/280838/9a794b0a-9167-11e2-8730-b0ba2ff047a5.png)
.

**Comment by satya164** [comment]
I'm afraid i cannot do much about firefox since it's not native GTK.

**Comment by suhr** [comment]
I want such feature outside firefox.
