### ISSUE TITLE
Ugly bookmark hover on google-chrome 40 and some apps on fedora 21 with numix master

### ISSUE THREAD

**Issue by smonv** [numixproject/numix-gtk-theme#190]
![screenshot from 2015-01-23 01 41 55](https://cloud.githubusercontent.com/assets/8962973/5862057/3b78d4d4-a2a1-11e4-87f8-41a07fd3963d.png)

**Comment by smonv** [comment]
Deluge
![screenshot from 2015-01-23 02 22 57](https://cloud.githubusercontent.com/assets/8962973/5862759/e022f4c4-a2a6-11e4-9dcf-55f670051f04.png)

**Comment by smonv** [comment]
Clementine
![screenshot from 2015-01-23 02 46 17](https://cloud.githubusercontent.com/assets/8962973/5863179/135d340a-a2aa-11e4-83cf-32f596955869.png)

**Comment by satya164** [comment]
Install murrine engine.
