### ISSUE TITLE
Keyboard item selection 

### ISSUE THREAD

**Issue by gfavaro** [numixproject/numix-gtk-theme#191]
When using the keyboard to select files or folders in Nautilus (Ctrl + arrow keys + Space) should display a border on the item with the focus, as in the printscreen.

![captura de tela de 2015-01-26 18 36 53](https://cloud.githubusercontent.com/assets/615226/5907948/6183a460-a58a-11e4-95d5-0e1035087b96.png)

**Comment by dirtydancing** [comment]
Hi, are you saying that with Numix GTK theme, such a border is not displayed when using the keyboard as you described? In that case, I can NOT reproduce your issue in Ubuntu 14.10, Nautilus/Files 3.10.1, Numix GTK theme 2.4.

Screenshot:
![nautilus-files](https://cloud.githubusercontent.com/assets/7164227/6285992/e578d7dc-b902-11e4-8649-113183b942f1.png)

**Comment by gfavaro** [comment]
Exactly. Maybe it's a problem with the nautilus 3.14.
I'm using 21 and Nautilus 3.14.2 fedora.

Em Fri Feb 20 2015 at 10:20:57, dirtydancing notifications@github.com
escreveu:

**Comment by satya164** [comment]
I cannot reproduce the issue on fedora.

**Comment by megax** [comment]
@gfavaro Still having trouble?
