### ISSUE TITLE
Nemo PathBar breadcrumbs issue

### ISSUE THREAD

**Issue by Tux1** [numixproject/numix-gtk-theme#192]
![screenshot from 2015-02-06 19 07 07](https://cloud.githubusercontent.com/assets/6661307/6084904/83a2f45c-ae35-11e4-8b60-840b16ea4193.png)

Hello,
Firstly, thank you for Numix. You have made a really great theme. 
I use Linux Mint with Cinnamon and Nemo as File Manager. I saw you manage nemo however it looks like ugly, especially regarding the pathbar. Is it normal ? 

Thanks !!

**Comment by dirtydancing** [comment]
@Tux1 Are you referring to the navigation bar on the left hand side (or to the navigation path on the top)? Possibly this recent comment of mine also applies to your issue: https://github.com/shimmerproject/Numix/issues/159#issuecomment-75233121

**Comment by Tux1** [comment]
@dirtydancing I am referrint to the navigation bar on the top of the window
Thanks for your help

**Comment by dirtydancing** [comment]
Ah, I see, so my other comment was not addressing your issue, oh well :-)

**Comment by satya164** [comment]
Hmm.. they again changed nemo theming!

**Comment by Tux1** [comment]
Do you know how to fix it ?

**Comment by megax** [comment]
@Tux1 Still having trouble?

**Comment by Tux1** [comment]
I don't use Nemo at the moment, sorry

**Comment by megax** [comment]
@khurshid-alam Not actually. Modified nemo... :)
![image](https://cloud.githubusercontent.com/assets/461493/17863883/f6bf2376-689b-11e6-9ab1-34048252332b.png)
