### ISSUE TITLE
Big fonts in gedit. How can I change font size in gedit?

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#193]
![2015-02-11 12 34 36](https://cloud.githubusercontent.com/assets/10940138/6144622/c92f931e-b1ea-11e4-9fab-dcf23bf5204e.png)
Fedora 21 Gnome .
I used to http://rpm.pbone.net/index.php3/stat/4/idpl/28565883/dir/fedora_21/com/numix-gtk-theme-2.5-1.20150119gitc119f55.fc21.noarch.rpm.html

**Comment by satya164** [comment]
Which font are you using? What is your GTK version?

**Comment by ghost** [comment]
I'm using the Ubuntu Font.
This manifests itself with all fonts.
3.14.3

**Comment by ghost** [comment]
Well, any ideas? It Must Be So
![2015-02-14 21 28 20](https://cloud.githubusercontent.com/assets/10940138/6200627/a6d4ed1a-b491-11e4-95d8-4dd1392dbf78.png)

**Comment by satya164** [comment]
Do you have an HDPI screen?

Satyajit Sahoo
Digital artist
DeviantArt Profile http://satya164.deviantart.com

We're all stories, in the end. Just make it a good one, eh? — The Doctor,
Season 5, Episode 13.

**Comment by ghost** [comment]
the problem is not in my HDPI, problem in your GTK, checked, it manifests itself in other people.

**Comment by satya164** [comment]
Well, that doesn't answer the question if you have HDPI

**Comment by ghost** [comment]
no.

**Comment by megax** [comment]
@khurshid-alam Still having trouble?

**Comment by khurshid-alam** [comment]
Fixed.
