### ISSUE TITLE
Unreadable text in Evince's view size dropdown

### ISSUE THREAD

**Issue by ogmaresca** [numixproject/numix-gtk-theme#195]
I'm using Ubuntu 14.10, Unity, and Numix 1.8.1. The dropdown menu to change the size of a PDF in Evince uses the same color for the text as the background. Hovering over an item is themed correctly.

Here's an example: http://i.imgur.com/oPzfm5M.png

**Comment by dirtydancing** [comment]
Hi, I can NOT reproduce this issue in Ubuntu 14.10 with latest Numix GTK theme 2.4 (via PPA).

Screenshot:
![evince](https://cloud.githubusercontent.com/assets/7164227/6285091/0e18969c-b8f8-11e4-80ee-b4901f1734dc.png)

**Comment by satya164** [comment]
Please update to latest Numix and test.

**Comment by ogmaresca** [comment]
That fixed it, I was using the noobslabs PPA which is outdated.
