### ISSUE TITLE
Versioning is wrong in the PPA

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#196]
Hi!

I just realized today, when trying to fix why everything was looking so horrible in Gnome 3.14, that actually the versions are wrong in the PPA:
https://launchpad.net/~numix/+archive/ubuntu/ppa

The package versioned `2.4` is actually older than the `2.3+335~201501201616~ubuntu15.04.1` which indeed contains all the fixes for these bugs. But because _apt_ just cares about version numbers, it installs the former by default.

Cheers!

**Comment by khurshid-alam** [comment]
The latest version for Vivid in the ppa is: 2.3+335~201501201616~ubuntu15.04.1

**Comment by ghost** [comment]
I was using the PPA on Debian Sid, and I guess it just picked the latest since there is no package for Sid specifically. Thanks!

**Comment by khurshid-alam** [comment]
I just bumped ppa version to 3.4. In arch its 3.5?? It is indeed mixed up.

**Comment by megax** [comment]
@khurshid-alam Still having trouble?
