### ISSUE TITLE
Problem with the dropdown arrow in Ubuntu software updater

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-gtk-theme#197]
Hi, Ubuntu 14.10 here with latest Numix GTK Theme 2.4: There is a problem with the dropdown arrow in the graphical Ubuntu software updater. The arrow (pointing sideways) disappears (or more precisely is reduced to a dot) when the item with the arrow is marked. Once it is clicked, the arrow (now pointing downwards) re-appears, but disappears again when hovered over. In contrast, all is fine with default Ambiance GTK theme.

Comparative screenshots of Numix GTK theme and Ambiance GTK theme, problem marked in the second screenshot of Numix GTK theme:

Numix GTK theme
![numix_1](https://cloud.githubusercontent.com/assets/7164227/6284821/1eb48bd0-b8f5-11e4-827b-d201937bf4ce.png)
![numix_2](https://cloud.githubusercontent.com/assets/7164227/6284824/28b81b4c-b8f5-11e4-8e07-816e4e90e43d.png)
![numix_3](https://cloud.githubusercontent.com/assets/7164227/6284825/2bb1c69a-b8f5-11e4-9eef-5ad92b561985.png)

Ambiance GTK theme
![ambiance_1](https://cloud.githubusercontent.com/assets/7164227/6284831/31e11200-b8f5-11e4-90c9-cefdba2e6c11.png)
![ambiance_2](https://cloud.githubusercontent.com/assets/7164227/6284834/36eecaf8-b8f5-11e4-9fb4-0599b19ce067.png)
![ambiance_3](https://cloud.githubusercontent.com/assets/7164227/6284837/3a2a95a8-b8f5-11e4-808b-efe05c6e99c9.png)

**Comment by satya164** [comment]
No clue how to fix. But will try.

**Comment by dirtydancing** [comment]
This problem also exists in Xubuntu 14.10. I am adding the same sets of three screenshots, this time with Numix GTK theme and as a comparison with the Xubuntu Default Greybird GTK theme.

It appears that Numix GTK theme is displaying some kind of (inconsistent) grey frame around the arrow triangle when the line is marked, and this is why the white portion of the arrow becomes hardly visible.

Hope this helps.

Numix GTK theme
![numix-gtk_1](https://cloud.githubusercontent.com/assets/7164227/6320326/50ad1742-bada-11e4-9934-6dbf8ce4d499.png)
![numix-gtk_2](https://cloud.githubusercontent.com/assets/7164227/6320327/55876a6a-bada-11e4-8f49-95b1dccbc40a.png)
![numix-gtk_3](https://cloud.githubusercontent.com/assets/7164227/6320329/59521e2e-bada-11e4-9748-e39349671e61.png)

Greybird GTK theme
![greybird-gtk_1](https://cloud.githubusercontent.com/assets/7164227/6320333/66fce248-bada-11e4-975a-5e50616f1816.png)
![greybird-gtk_2](https://cloud.githubusercontent.com/assets/7164227/6320336/6aadf8d2-bada-11e4-9a33-6bdbbf00c0f9.png)
![greybird-gtk_3](https://cloud.githubusercontent.com/assets/7164227/6320338/6d63cf98-bada-11e4-9080-55e33c9cdc7f.png)

**Comment by bilelmoussaoui** [comment]
I can confirm this! i'm using ubuntu 14.04 (elementary OS 0.3 beta 2)

**Comment by dirtydancing** [comment]
Ah, I forgot to mention explicitly that also in Xubuntu 14.10, when hovering over the downwards pointing arrow (3rd screenshot in the series), the arrow "disappears" or gets this grey/transparent border again (not visible in the 3rd screenshot, as in the screenshot the arrow is not hovered over).

In contrast, with Greybird GTK theme, the downward pointing arrow stays the same, whether hovered over or not.

In both Numix GTK theme and Greybird GTK theme, the sideways pointing arrow (2nd screenshot in the series) stays the same, whether hovered over or not.

**Comment by dirtydancing** [comment]
Quick update: This problem also exists in Ubuntu 15.04 daily (in development) with corresponding default Ambiance GTK theme.

Maybe this is related to the gtk version, and by now (in Ubuntu 15.04) Ambiance GTK theme has caught up with current Numix GTK theme? Really just guessing here.

Screenshot for Ubuntu 15.04 daily (in development) with Ambiance GTK theme:

![ubuntu-1504-daily_software-updater](https://cloud.githubusercontent.com/assets/7164227/6426471/c169eede-bf5c-11e4-9e33-996adc9f3c50.png)

**Comment by dirtydancing** [comment]
Corresponding bug report is filed against Ubuntu light-themes package (i.a. Ambiance GTK): https://bugs.launchpad.net/ubuntu/+source/ubuntu-themes/+bug/1426712

**Comment by satya164** [comment]
I'll subscribe to that bug report to see if any solution comes up.

**Comment by dirtydancing** [comment]
By coincidence I came across this fix in evopop-gtk-theme: https://github.com/solus-project/evopop-gtk-theme/commit/7a1dd2540af9932695c999171dbafa7b15b4dc75

I checked for Numix GTK theme in Xubuntu 15.04 by adding this in `/gtk-3.0/gtk-widgets.css`:

```
GtkTreeView.view:selected {
    border: none; 
}
```

And this worked.

Current (hardly visible):
![current](https://cloud.githubusercontent.com/assets/7164227/7365851/53a251dc-ed94-11e4-8b93-401f61be6c9b.png)

Modified (well visible):
![modified](https://cloud.githubusercontent.com/assets/7164227/7365854/57a44a9c-ed94-11e4-8b50-8fb8ad705017.png)

**Comment by satya164** [comment]
Thanks. Will try this as soon as I get home.

Satyajit Sahoo
UX Designer
Behance Profile

We're all stories, in the end. Just make it a good one, eh? — The Doctor, Season 5, Episode 13.

**Comment by megax** [comment]
@khurshid-alam, @dirtydancing Still having trouble?
