### ISSUE TITLE
Some black elements on Ubunut 14.04.2

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-gtk-theme#198]
Hello, i've noticed some black elements (not themed) on my ubuntu 14.04 desktop 
Gedit 
![screenshot from 2015-03-03 23 50 50](https://cloud.githubusercontent.com/assets/7660997/6474334/2743efde-c200-11e4-9163-b33c615423c8.png)
Ubuntu Software Center 
![screenshot from 2015-03-03 23 52 35](https://cloud.githubusercontent.com/assets/7660997/6474369/657f9690-c200-11e4-96f2-e1146cb95471.png)

**Comment by bilelmoussaoui** [comment]
Same thing on Nautilus 
![screenshot from 2015-03-04 22 59 10](https://cloud.githubusercontent.com/assets/7660997/6494455/31e06d06-c2c2-11e4-9c70-0f433125be4e.png)
deja-dup 
![screenshot from 2015-03-05 09 28 02](https://cloud.githubusercontent.com/assets/7660997/6501588/7cefed5a-c31a-11e4-9891-7409047d62ac.png)

**Comment by dirtydancing** [comment]
Interesting. I can not reproduce this with Ubuntu 14.10.

Gedit (3.10.4)
![gedit](https://cloud.githubusercontent.com/assets/7164227/6540767/993d8fb2-c4af-11e4-826d-e975c7702332.png)

Software Center at the bottom looks fine to me, is the same with Ubuntu default Ambiance GTK theme.

Nautilus/Files (3.10.1)
![nautilus](https://cloud.githubusercontent.com/assets/7164227/6540768/9cd24cbc-c4af-11e4-8b54-6a582fd92bbc.png)

(have not checked deja-dup)

@bil-elmoussaoui I am wondering: is this an installation on real hardware or is this running in a virtual machine? Not that this should make a big difference, but well, possibly this is some kind of graphic driver glitch? And have you checked with Ubuntu default Ambiance GTK theme for comparison, and possibly also with HighContrast GTK theme (shipping with Ubuntu): do the same issues show up? Just checking some possible routes to get to the bottom of this.

**Comment by bilelmoussaoui** [comment]
I'im using Ubuntu 14.04.2 in a real hardware 
For gedit i'm using the same version as yours 
![screenshot from 2015-03-07 11 59 08](https://cloud.githubusercontent.com/assets/7660997/6541148/6ba822c6-c4c1-11e4-8373-60d6b213f352.png)
This screenshot is wheen i  open it with root permissions 
For Nautilus its not the same screenshot , i got this only when i open a new usb drive 
and i dont have this issue on any Ubuntu default theme ;)

**Comment by dirtydancing** [comment]
Ok, I am running Ubuntu 14.10 on real hardware as well. I am using the AMD open Gallium driver, just in case that the graphics driver might be of any relevance (initially this looked like a graphics glitch to me).

For Gedit, I also have no problem when I open it with root permissions (just as I have no problem when I open it as a regular user). Here is a screenshot of Gedit with root permissions:

![gedit_root](https://cloud.githubusercontent.com/assets/7164227/6541365/297649b4-c4cb-11e4-99df-e226ce55cace.png)

I am not sure how to replicate your Nautilus "contains music" VLC scenario, so I simply used the rubbish bin because that seemed to display a similar bar. Well, now we know that this is not the same :-)

Finally, here is a screenshot of deja-dup, also no problem there:

![deja-dup](https://cloud.githubusercontent.com/assets/7164227/6541372/9877c4e6-c4cb-11e4-9546-ace4a455efd6.png)

So far, I have not experienced any of these "black elements" at all with Numix GTK theme.

**Comment by bilelmoussaoui** [comment]
Can you please tell me which numix gtk theme version are you using? i'm using the 2.4 and its not the last one! as there is a problem with ppa versioning :disappointed:

**Comment by dirtydancing** [comment]
I am using version **2.4** via PPA. This is the one that the Numix PA currently provides for Ubuntu 14.10 Utopic.

At the same time, the Numix PPA shows that the numix-gtk-theme version for Ubuntu 15.04 Vivid is indeed newer, although the version number is **2.3**+335~201501201616~ubuntu15.04.1

![numix-gtk-theme_ppa](https://cloud.githubusercontent.com/assets/7164227/6572888/2f61fdc6-c716-11e4-96c5-3b48ba2f94c3.png)

It seems that this versioning issue has also already been reported at https://github.com/shimmerproject/Numix/issues/196

But as far as I can tell, for your Ubuntu 14.04 LTS Trusty, version 2.4 is current and should be fine (?).

**Comment by gilbertcutando** [comment]
Same issue here. 

Ubuntu 14.04
numix-gtk-theme 2.4

**Comment by dirtydancing** [comment]
@bil-elmoussaoui @gilbertcutando Have you checked if you have disabled overlay scroll bars? (disabled on my machine) Apparently this is a known cause for similar issues, so I am just checking.

**Comment by bilelmoussaoui** [comment]
I didn't, but i will reinstall ubuntu soon and check this again ;)

**Comment by mrosso84** [comment]
Hello, I am having the same problem with numix icon theme on ubuntu 14.04.2.
This also affects evolution (see screenshot).
![evolution](https://cloud.githubusercontent.com/assets/8620414/8514667/86038cf0-2349-11e5-9529-8e92033ee4c2.png)

**Comment by satya164** [comment]
@mrosso84 disable overlay scrollbars

**Comment by bilelmoussaoui** [comment]
I'm going to close this as this is fixed once i disable overlay scrollbars
