### ISSUE TITLE
Thick black separators for (default) sidebar in LibreOffice 4.4

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-gtk-theme#199]
Hi, with Numix GTK theme, in LibreOffice 4.4 the (now showing per default) sidebar has a distracting border around it. This is not the case e.g. with Ambiance GTK theme.

This might be related to the previously reported https://github.com/shimmerproject/Numix/issues/74, but I am not sure about that, so I am opening a new issue.

Comparative screenshots of Writer and Calc, Ubuntu 14.10, LibreOffice 4.4.1.2 (via LibreOffice PPA):

Writer, Numix GTK theme:
![writer_numix-gtk](https://cloud.githubusercontent.com/assets/7164227/6766058/a6cf65da-cff7-11e4-82c5-5051378a46ff.png)

Writer, Ambiance GTK theme:
![writer_ambiance-gtk](https://cloud.githubusercontent.com/assets/7164227/6766059/b729f21a-cff7-11e4-8367-0a705df55614.png)

Calc, Numix GTK theme:
![calc_numix-gtk](https://cloud.githubusercontent.com/assets/7164227/6766060/bfa42c44-cff7-11e4-934c-576747319290.png)

Calc, Ambiance GTK theme:
![calc_ambiance-gtk](https://cloud.githubusercontent.com/assets/7164227/6766063/c752cca2-cff7-11e4-8f2d-ee03af36ed6b.png)

**Comment by dirtydancing** [comment]
This is the current Numix GTK theme version 2.4. for Ubuntu 14.10 via the Numix PPA.

**Comment by dirtydancing** [comment]
This issue is also present with Numix GTK theme (and again not with Ambiance GTK theme) in current daily Ubuntu 15.04 with default LibreOffice 4.4.1.2 and with current Numix GTK theme version 2.3+335.

**Comment by dgikiller** [comment]
Same issue found even on Guake using Gentoo.

**Comment by Corsseir** [comment]
Does this project still alive? I don't see response to any issue and any updated fix for a long time...

**Comment by Corsseir** [comment]
I have found solution:
/usr/share/themes/Numix/gtk-2.0/gtkrc

This section:

style "murrine-menu" = "murrine-thin" {

```
bg[NORMAL] = @menu_bg_color
bg[PRELIGHT] = @selected_bg_color
bg[SELECTED] = @selected_bg_color
bg[ACTIVE] = @menu_bg_color
bg[INSENSITIVE] = @menu_bg_color

fg[NORMAL] = @menu_fg_color
fg[PRELIGHT] = @selected_fg_color
fg[SELECTED] = @selected_fg_color
fg[ACTIVE] = @selected_fg_color
fg[INSENSITIVE] = mix (0.5, @menu_bg_color, @menu_fg_color)

text[NORMAL] = @menu_fg_color
text[PRELIGHT] = @selected_fg_color
text[SELECTED] = @selected_fg_color
text[ACTIVE] = @selected_fg_color
text[INSENSITIVE] = mix (0.5, @menu_bg_color, @menu_fg_color)

engine "murrine" {
    roundness = 0
}
```

}

is just bad.

This all stuff:

```
bg[NORMAL] = @menu_bg_color
bg[PRELIGHT] = @selected_bg_color
bg[SELECTED] = @selected_bg_color
bg[ACTIVE] = @menu_bg_color
bg[INSENSITIVE] = @menu_bg_color

fg[NORMAL] = @menu_fg_color
fg[PRELIGHT] = @selected_fg_color
fg[SELECTED] = @selected_fg_color
fg[ACTIVE] = @selected_fg_color
fg[INSENSITIVE] = mix (0.5, @menu_bg_color, @menu_fg_color)

text[NORMAL] = @menu_fg_color
text[PRELIGHT] = @selected_fg_color
text[SELECTED] = @selected_fg_color
text[ACTIVE] = @selected_fg_color
text[INSENSITIVE] = mix (0.5, @menu_bg_color, @menu_fg_color)
```

is just useless so you could simply remove it, save and bug will disappear.

If someone want to fix it with only one command then please:
http://paste.ubuntu.com/10892489/

Very long - I admit it - just copy command with double click.

**Comment by dirtydancing** [comment]
@Corsseir Thanks for helping out with this! I commented out the lines that you posted above, and this worked. Comparative screenshots with Ubuntu 14.10, LibreOffice Writer 4.4.2.2 (via LibreOffice PPA):

current (thick bars):
![writer_current](https://cloud.githubusercontent.com/assets/7164227/7336444/10df5124-ebff-11e4-89eb-d186b5a1c37a.png)

after (all fine):
![writer_after](https://cloud.githubusercontent.com/assets/7164227/7336446/1b26f060-ebff-11e4-9a7f-f36b1b43c6a9.png)

**Comment by Corsseir** [comment]
I was wrong, that section is important as hell at least for gtk2 apps. When i considered this i have deep deeper and i have found another solution, which base on Canonical Ambiance experience.

When you remove all those lines problem disappears but it also causes next issue:
![screenshot from 2015-04-26 13 43 51](https://cloud.githubusercontent.com/assets/11137173/7337063/c58ed6a6-ec1a-11e4-9a1a-c1ed9cb63f6c.png)
and:
![screenshot from 2015-04-26 13 44 41](https://cloud.githubusercontent.com/assets/11137173/7337066/cdee8b0c-ec1a-11e4-8d93-077810ecfba8.png)

What Canonical did? They have just swap the colors of menu bg-color and text-color like so:
![screenshot from 2015-04-26 13 52 17](https://cloud.githubusercontent.com/assets/11137173/7337078/7f4cca44-ec1b-11e4-9eb0-17460a79460c.png)

After these changes menus look better in many apps, which still based on gtkrc, for example: firefox, chrome and libreoffice.

![screenshot from 2015-04-26 13 46 16](https://cloud.githubusercontent.com/assets/11137173/7337086/e99c4262-ec1b-11e4-9dee-5fac88d12b77.png)

![screenshot from 2015-04-26 13 46 38](https://cloud.githubusercontent.com/assets/11137173/7337088/efcbbd70-ec1b-11e4-8a13-36075880f465.png)

![screenshot from 2015-04-26 13 54 08](https://cloud.githubusercontent.com/assets/11137173/7337090/fb8abf26-ec1b-11e4-8e94-3ed419dc0015.png)

![screenshot from 2015-04-26 13 55 15](https://cloud.githubusercontent.com/assets/11137173/7337097/13401eb8-ec1c-11e4-93a3-b69127b5ed43.png)

**Comment by dirtydancing** [comment]
Thanks for the heads-up, why am I not surprised this is not all that simple? :) Hopefully this will get fixed.

**Comment by alex94cp** [comment]
Is this bug being watched by any of the @numixproject / @shimmerproject developers?

**Comment by satya164** [comment]
This is not a Numix bug. This is LibreOffice using menu styles for the sidebar. I'm afraid we cannot do much. I certainly don't want to change the style of the theme just because of LibreOffice.

**Comment by alex94cp** [comment]
Ok, then this is a @libreoffice bug, I'll create a bug report if it does not exist already. OTOH, why does menu style have that border?

**Comment by satya164** [comment]
@alex94puchades Menu style doesn't have a dark border. Menu is dark. Somehow, LO is inheriting the menu style for the borders.

**Comment by ghost** [comment]
For what it's worth, Numix Light does not have this problem.

**Comment by khurshid-alam** [comment]
Bug in the LO. Now fixed.
