### ISSUE TITLE
Desktop shortcut labels unreadable in Mint OS

### ISSUE THREAD

**Issue by donaldrobertson** [numixproject/numix-gtk-theme#2]
I'm using Linux Mint and the text labels under desktop shortcuts (launchers) appear too dark to read (dark grey) unless I change the theme setting for "controls" back from Numix to Mint-X, which makes the text white again.  Is their a workaround for this?

**Comment by Foggalong** [comment]
This is the repo to report to https://github.com/shimmerproject/Numix
