### ISSUE TITLE
client side window decorator wrong button color in gnome 3.16

### ISSUE THREAD

**Issue by lucazade** [numixproject/numix-gtk-theme#201]
client side window decorator for non gnome apps has wrong button color, it is orange instead of white.
![window-decorator](https://cloud.githubusercontent.com/assets/1557010/6884373/a1944006-d5ef-11e4-93ff-02bd7d301fc8.png)

**Comment by vdcow** [comment]
It is not CSD on screenshot - it is usual server side decorations. The cause of problem - gnome developers removed metacity theme support and now mutter uses decoration from gtk theme. See 

https://blogs.gnome.org/fmuellner/2015/01/30/a-small-note-on-window-decorations/

for details. So we should wait when Numix devs will add decoration theme support to gtk theme.

**Comment by megax** [comment]
@lucazade @khurshid-alam Fixed, close? :)
