### ISSUE TITLE
chomium popupmenu in gnome 3.16 wrong colors and hover selection broken

### ISSUE THREAD

**Issue by lucazade** [numixproject/numix-gtk-theme#203]
chomium popup menu in gnome 3.16 has wrong colors (white lines) and hover item selection doesn't work properly (some time doesn't highlight the current entry)
![chromium](https://cloud.githubusercontent.com/assets/1557010/6884422/d329eb6e-d5f1-11e4-8676-d325b4cb9d5f.png)

**Comment by khurshid-alam** [comment]
It has been broken since Chromium/Chrome has started (v 35) to use **Aurora** instead of GTK+ to render its window.

Now it is required to include aurora styles in the Theme.
