### ISSUE TITLE
Xubuntu 15.04 Errors

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-gtk-theme#204]
Just updated to Xubuntu 15.04, which uses GTK 3.14 and XFCE 4.12

Where the volume, wifi, and notification icons should be there's just a white block. The icons appear when hovered over but not otherwise. I tried with a a few different themes to test it out.

Had the problem:
- Bluebird
- Numix
- Numix-Daily
- Orion
- Raleigh

Didn't have the problem:
- Adwaita
- Greybird
- High Contrast
- Iris
- Vold

![screenshot_2015-04-09_14-39-26](https://cloud.githubusercontent.com/assets/5920259/7069940/8b30b64a-ded3-11e4-8429-e12ca7cfd9d0.png)

![screenshot_2015-04-09_14-39-41](https://cloud.githubusercontent.com/assets/5920259/7069943/91abac0a-ded3-11e4-8a84-4a841be0bdcf.png)

**Comment by Foggalong** [comment]
That said, the other themes like Iris and Vold have problems too just in different part of the theme. This is the the only one I've found with Numix this far.

**Comment by vista-** [comment]
Can confirm this bug is still present in version 2.4 (from PPA) with Xfce 4.12.
![](http://puu.sh/jKHBm/ba92e3f06a.png) 
(ignore the marching ants around the screenshot, it's an artifact from xfce4-screenshooter)

**Comment by ochosi** [comment]
@Foggalong Strange, I can't reproduce this at all. Are you using a different version of Numix than the one shipped with 15.04?

**Comment by vista-** [comment]
Reinstalling the theme did the trick for me.

**Comment by megax** [comment]
@Foggalong Still having trouble?

**Comment by Foggalong** [comment]
Yeah, this problem was fixed for me a while ago. Sorry for not following up on this!

**Comment by megax** [comment]
@khurshid-alam @lots0logs @Foggalong Close? :)
