### ISSUE TITLE
Popup background color not very distinguished

### ISSUE THREAD

**Issue by haarp** [numixproject/numix-gtk-theme#205]
Popups (the little boxes that sometimes appear when hovering the mouse pointer over clickable elements) tend to have a very indistinguishable background color to, which makes them hard to spot and, well, distinguish.

Example 1: http://i.imgur.com/5AWkUNw.png
Can you tell that "Clipboard manager" is a popup? Looks almost like the next menu entry

Example 2: http://i.imgur.com/WPeeZng.png
This is the window list in the Xfce panel. The popup almost looks like the next item, not like a popup.

Imo, the background color of these needs to contrast much more to other backgrounds, to make it easier to tell what they are.

**Comment by khurshid-alam** [comment]
Is it still reproducible with GTK-3.18?

**Comment by haarp** [comment]
Xfce still uses Gtk2

**Comment by megax** [comment]
@khurshid-alam Idea? We can improve?

**Comment by khurshid-alam** [comment]
@megax @haarp 
I don't really see any problem with panel. And popup is using some sort of transparency.

Xfce gtk-3 port is coming soon. At this point We are not change gtk2 theme code unless it's absolutely broken.
