### ISSUE TITLE
Highlight colour stays red when window is inactive

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-gtk-theme#207]
Hi, this might be a design decision, but to me it seems easier to figure out at a glance which window is active by seeing the highlight colour in the active window, and in the active window only. Yet, when using Numix GTK theme, the highlight colour in all windows is displayed in highlight red.

In the following example screenshots (deliberately crowded for demonstration purposes), please compare Numix GTK theme and Ambiance GTK theme on Ubuntu 14.10 (same on daily Ubuntu 15.04):

Numix GTK theme (highlight red in all windows, active and inactive):
![numix-gtk](https://cloud.githubusercontent.com/assets/7164227/7102941/e15ca90a-e092-11e4-8732-02b553c625a9.png)

Ambiance GTK theme (highlight orange only in currently active window):
![ambiance-gtk](https://cloud.githubusercontent.com/assets/7164227/7102942/e387a572-e092-11e4-97fc-908aae470897.png)

**Comment by megax** [comment]
@dirtydancing Still having trouble?

**Comment by khurshid-alam** [comment]
@megax This is still reproducible with GTK-3.18 only. Can you propose a fix? Thanks.

**Comment by dirtydancing** [comment]
Thanks for coming back to this. I have since moved on to Arch/GNOME with default Adwaita GTK theme.

**Comment by megax** [comment]
@khurshid-alam Not fix. Too much work. =/
GTK 3.20 fixed.
