### ISSUE TITLE
Panel icon colour scheme not adapted to the new Numix icon theme light grey

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-gtk-theme#208]
It looks like the colour scheme has not yet been adapted to the Numix icon theme redesign. The light grey icon colour in the panel is now `#ececec`, but apparently the GTK theme colour is still `#dcdcdc` which corresponds to the old Numix icon theme panel icon colour.

This becomes visible in cases where the GTK theme colour-themes "symbolic"-named panel icons (apart from GNOME Shell) in e.g. elementary OS Freya.

With elementary GTK theme, the battery icon (`battery-full-charged-symbolic.svg`) in this screenshot is white `#ffffff` (cf. this corresponding issue report https://bugs.launchpad.net/egtk/+bug/1425133):

![elementary-gtk](https://cloud.githubusercontent.com/assets/7164227/7124976/86131416-e22d-11e4-84c7-f8809c76c657.png)

With Numix GTK theme, the battery icon is light grey `#dcdcdc`, but not `#ececec` as all the other Numix panel icons (except for the keyboard indicator icon, which has not been redesigned yet):

![numix-gtk](https://cloud.githubusercontent.com/assets/7164227/7124990/9fe8cf7a-e22d-11e4-93e0-40975ef8eb06.png)

**Comment by megax** [comment]
@dirtydancing Still having trouble?

**Comment by dirtydancing** [comment]
Thanks for coming back to this. I have since moved on to Arch/GNOME with default Adwaita GTK theme.
