### ISSUE TITLE
Unity icons (minimize, maximize, close) do not use Numix theme

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-gtk-theme#209]
I work on Ubuntu 14.04 and I have noticed that Unity icons - minimize, maximize and close - do not use Numix theme. You could clearly see it at this screen: https://www.dropbox.com/s/p0o35yjkw5gzqop/Screenshot%20from%202015-04-24%2014%3A03%3A52.png?dl=0

**Comment by Corsseir** [comment]
I have found the solution. I don't know why you did't find it before me, 'cause it wasn't hard. Link to fix:
http://paste.ubuntu.com/10885660/

Could you please repack this theme and push update to the launchpad?

**Comment by dirtydancing** [comment]
This issue has also been discussed and addressed here: https://github.com/shimmerproject/Numix/issues/153

**Comment by megax** [comment]
@Corsseir @khurshid-alam Still having trouble?
