### ISSUE TITLE
Missing visual for checkboxes' indeterminate state

### ISSUE THREAD

**Issue by ntoniazzi** [numixproject/numix-gtk-theme#21]
Checkboxes look the same whether their state is unchecked or indeterminate.

**Comment by satya164** [comment]
What do you mean by indeterminate state? Can you provide a screenshot?

**Comment by ntoniazzi** [comment]
For example, you have a hierarchy of check boxes. If a node has all his children checked, it is checked too. If none of its children are checked, it is not. If only some of them are checked, it is in an indeterminate state and cannot be checked nor unchecked. In a web page, the checkebox has a DOM attribute called "indeterminate".

I checked other GTK themes and they represent this state (with a bad looking fallback in the case of adwaita) :
![checkboxes](https://f.cloud.github.com/assets/849271/327121/cb77329c-9b64-11e2-8f1b-9150e4936aef.png)

**Comment by satya164** [comment]
Hmm.. Can you give me an example application in which I can test it?

**Comment by ntoniazzi** [comment]
You can see it here : http://jsfiddle.net/ntoniazzi/5L8LR/
I used Firefox, as Iron browser (webkit) seems to use it's own theme for form elements.

**Comment by satya164** [comment]
Thanks. I'll try to fix it soon.

**Comment by ntoniazzi** [comment]
I quickly compared the assets in Numix and Ambiance themes. It seems that the "mixed" asset should be used for this case. And in fact, the Ambiance theme has no asset corresponding to the "indeterminate" state in my screenshot.
The problem might come from Firefox not using the right element?

**Comment by satya164** [comment]
The problem is that the assets are for GTK3 and Firefox is GTK2. I've to
think of a solution since I don't want to use the pixmap engine just for
this...

**Comment by ochosi** [comment]
This bug is in the murrine-engine. It would be a one-line-fix but as the theme-engine isn't in development anymore, I'm not sure the patch will ever get merged.

So there is nothing we can do (as long as we use that engine). Lucky for us, the mixed state isn't used/useful very often.
