### ISSUE TITLE
Awful black Libre Office separators

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-gtk-theme#210]
Separators in Libre Office look awful with Numix theme:
https://www.dropbox.com/s/m2crz0bzkyqneue/Screenshot%20from%202015-04-24%2013%3A57%3A55.png?dl=0
https://www.dropbox.com/s/gqmtt98yz1c5j6e/Screenshot%20from%202015-04-24%2014%3A11%3A44.png?dl=0

**Comment by dirtydancing** [comment]
I believe this is a duplicate of https://github.com/shimmerproject/Numix/issues/199 and thus this issue can be closed :)

**Comment by megax** [comment]
@khurshid-alam Duplicated issue.

**Comment by megax** [comment]
@khurshid-alam Closed issue... :) Does not contain additional information.
