### ISSUE TITLE
White input for password in Unity Greeter

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-gtk-theme#212]
When I set Numix as LightDM theme in Ubuntu 14.04 then I get white input for password. I have found fix for this issue - just copy unity-greeter.css from Ambience theme (~/Ambience/gtk-3.0/apps/) to your theme and import it from gtk.css.

Console command here:
http://paste.ubuntu.com/10890900/

**Comment by megax** [comment]
@khurshid-alam, @corsseir Still having trouble?

**Comment by andia89** [comment]
@megax should be fixed actually, since there's a `unity-greeter` now also in numix

**Comment by Corsseir** [comment]
Ubuntu 16.04 with the newset Numix version.

It is fixed for me.
