### ISSUE TITLE
Unreadable volume control

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-gtk-theme#213]
As in the title - totally unreadable.

Normal:
![screenshot from 2015-04-30 04 06 39](https://cloud.githubusercontent.com/assets/11137173/7405123/79b856e0-eeee-11e4-8d8d-0c4b0155152f.png)

Hovered:
![screenshot from 2015-04-30 04 06 51](https://cloud.githubusercontent.com/assets/11137173/7405126/844f276e-eeee-11e4-8cc6-4cadafcb1d9f.png)

**Comment by megax** [comment]
@khurshid-alam Old/duplicated issue. New: https://github.com/numixproject/numix-gtk-theme/issues/392
