### ISSUE TITLE
Drop shadows under windows using Numix doesn't look as good as in stock Unity.

### ISSUE THREAD

**Issue by cdysthe** [numixproject/numix-gtk-theme#214]
For some reason drop shadows under windows doesn't look as good with Numix as they do in stock Unity. With Numix they seem "shallower" for some reason. There's more depth in default Unity.

I do not know how the drop shadow values are set and design is done but again, it looks better in stock Unity and even better in Elementary OS. If it is possible to do the drop shadows like in stock Unity, or even better like in Elementary OS it would be great.

**Comment by khurshid-alam** [comment]
Unity uses Compiz for gtk-window-decorator(now for unity-window-decorator) shadow which can be changed from GUI. Gnome-Shell uses mutter where they make window appear shadow-less. If I am not wrong, only way to change it by editing theme in sass(`_window.scss`).

**Comment by megax** [comment]
@cdysthe @khurshid-alam Still having trouble?

**Comment by khurshid-alam** [comment]
For ssd we let wm to draw the shadows.
