### ISSUE TITLE
Numix Light looks bad

### ISSUE THREAD

**Issue by afternewbie** [numixproject/numix-gtk-theme#216]
i've just got numix light today. i extract the zip and see there is two zip files. i have try both of them, but the theme looks bad in  unity, and not loaded in gnome. i use ubuntu 15.04

**Comment by khurshid-alam** [comment]
Screenshot?

**Comment by satya164** [comment]
@Arietux Screenshot? Also could you email me at team@numixproject.org so that I can send you the latest zip?

**Comment by afternewbie** [comment]
@satya164 this is my [Screenshot 1](http://i.imgur.com/Ke1fZra.png?1) [screenshot 2](http://i.imgur.com/cj0vNrD.png). i've sent mail to you.

thanks

**Comment by satya164** [comment]
@Arietux It's not Numix Light, it's Adwaita. I'll sent you the file ASAP.

**Comment by megax** [comment]
@Arietux Still having trouble?
