### ISSUE TITLE
Force quit window is transparent [unreadable]

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-gtk-theme#219]
Force quit windows is unreadable cause it is transparent. You can see it on this printscreen:
![screenshot from 2015-05-18 23 15 55](https://cloud.githubusercontent.com/assets/11137173/7690497/4cfe55ee-fdb4-11e4-8ff2-8bf20701728c.png)
For tests - to stop process open gedit for example, go to system monitor, find the gedit process, click on it with right mouse button and choose 'stop process'.

[gtk-widgets.css]

This:
GtkImage,
GtkImage:insensitive,
GtkLabel,
GtkLabel:insensitive,
GtkBox,
GtkBox:insensitive,
GtkGrid,
GtkGrid:insensitive {
    background-color: transparent;
}

Should looks like this:
GtkImage,
GtkImage:insensitive,
GtkLabel,
GtkLabel:insensitive,
GtkGrid,
GtkGrid:insensitive {
    background-color: transparent;
}

GtkBox,
GtkBox:insensitive {
    background-color: inherit;
}

I wont even guess why you want to make Boxes transparent... but it obviously mistake.

**Comment by hashworks** [comment]
I have this as well with the menu of the blueman icon in the taskbar.
Also the blueman menu itself looks kinda bad: http://i.imgur.com/C3NO9uF.png

Basically it's all GTK apps: http://i.imgur.com/Ntdqd6E.png

EDIT: Nevermind, of course Debian isn't updating the GTK package. v2.2.3 works fine.

**Comment by khurshid-alam** [comment]
Not valid anymore
