### ISSUE TITLE
Variety and Clementine icons on "GTK Light"

### ISSUE THREAD

**Issue by vladpolyanskiy** [numixproject/numix-gtk-theme#223]
![screenshot_2015-05-23_10-28-44](https://cloud.githubusercontent.com/assets/12570786/7783129/8bc7926a-0136-11e5-8f7e-c1315a522b36.png)

Clementine icon is screwed.

Variety is the green circle, if I turn it to "dark" it looks fine, but doesn't fit the theme, if I go light it turns into a green circle.

**Comment by andia89** [comment]
@Tuplad Those things are arguably not gtk-theme issues but icon theme issues. You should report this here: https://github.com/numixproject/numix-icon-theme/issues (if you use Numix which I suppose is true given your screenshot)

**Comment by megax** [comment]
@khurshid-alam Close?
