### ISSUE TITLE
Title bar on Debian 7,8 with XFCE looks bad.

### ISSUE THREAD

**Issue by nikolak** [numixproject/numix-gtk-theme#226]
Not really sure how to phrase the issue I'm having with Numix theme on Debian 7 and 8 with XFCE.

Basically what happens is that after certain time, sometimes days, sometimes minutes, the title bar will suddenly look like this:

![screenshot - 06132015 - 12 27 08 pm](https://cloud.githubusercontent.com/assets/720441/8144016/56efc62c-11c9-11e5-9c4d-140f9fb009d9.png)

Expected look:

![image](https://cloud.githubusercontent.com/assets/720441/8143987/6d2fe40e-11c8-11e5-9cb1-eb721dedb4a7.png)

Going to settings>window manager>theme and changing the theme from Numix to something else and then back fixes the issue. But it will eventually appear again.

The issue happens with Debian 7 and 8, on 2 different machines, and both when using master branch and the latest release version of the theme.

No major changes to the OS have been made, I've reinstalled it and the first thing that I did was set up Numix.

I'm having a hard time finding any relevant threads on this subject, so I'm opening a new issue here.

**Comment by all4pages** [comment]
Or with a reboot? I had some problems in the taskbar. After reboot it was ok.

**Comment by nikolak** [comment]
Reboot, same as changing the theme, fixes it - but it can still happen after reboot/changing the theme. Although since I reported this bug I re-installed Debian 8 stable and the issue is less frequent - happened maybe once in past ~7 days.

**Comment by satya164** [comment]
Seems more like XFWM bug rather than a theme bug.

**Comment by megax** [comment]
@Nikola-K Still having trouble?
