### ISSUE TITLE
Numix doesn't show up in appearance under MATE

### ISSUE THREAD

**Issue by codeworkx** [numixproject/numix-gtk-theme#227]
Numix can't be selected via appearance on MATE.
Adding "CursorTheme=default" to your index.theme makes it show up.

**Comment by satya164** [comment]
Seems to be a bug with mate?

**Comment by jbicha** [comment]
I believe this is a duplicate of issue #488

**Comment by lots0logs** [comment]
I think you mean the other way around as this issue predates #488 :wink:  We'll continue this over on #488 anyway though!
