### ISSUE TITLE
Firefox/Thunderbird Colours

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-gtk-theme#229]
For the SASS branch. Because of the way the colour have been chosen some apps (so far Firefox & Thunderbird) look pretty terrible.

Pre-SASS
![screenshot_2015-06-17_22-06-39](https://cloud.githubusercontent.com/assets/5920259/8218796/4f4b903c-153d-11e5-89aa-01a63d879bcb.png)

Post-SASS
![screenshot_2015-06-17_22-06-18](https://cloud.githubusercontent.com/assets/5920259/8218797/4f4d288e-153d-11e5-8e94-6298171b6997.png)

**Comment by megax** [comment]
@Foggalong Still having trouble?

**Comment by Foggalong** [comment]
I honestly couldn't tell you right now, I switched to i3 as my Windows manager so it's a long time since I've seen a Window border. Might be worth booting up a Xubuntu VM and checking
