### ISSUE TITLE
Weird colours in PDF reader menus

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-gtk-theme#231]
SASS branch, Evince 3.14 - weird colours in the menus and the menu bar
![screenshot_2015-06-18_16-17-51](https://cloud.githubusercontent.com/assets/5920259/8234748/c5ca99cc-15d5-11e5-8590-23b93ff7ccd2.png)

**Comment by satya164** [comment]
Still reproducible?

**Comment by Manizuca** [comment]
I have this problem in many programs menus, in the image im using Nemo 2.6.7 in Debian Jessie.
Also, u can see weird colors in the text of the blue bar (in trash:///)
![captura-10-09-2015-202053](https://cloud.githubusercontent.com/assets/6548848/9803515/ad9b3c56-57f9-11e5-8d88-e6cd9b234ec5.png)

**Comment by khurshid-alam** [comment]
Already fixed.
