### ISSUE TITLE
Button Colouring

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-gtk-theme#232]
The button colouring makes this look like the "reinstall" option isn't available, even if hovered over. It actually is

![screenshot_2015-06-18_18-19-00](https://cloud.githubusercontent.com/assets/5920259/8237349/a1bd80e2-15e6-11e5-9461-d32452ba8e9f.png)

**Comment by megax** [comment]
@Foggalong @khurshid-alam Still having trouble?

**Comment by Foggalong** [comment]
Nope, this appears to be fixed for me now :+1:

**Comment by SammysHP** [comment]
This does still happen with the current master. The reason is the focus state.

![record-button](https://cloud.githubusercontent.com/assets/922874/18244604/3543d66c-7361-11e6-9733-88b102125dea.gif)
