### ISSUE TITLE
Black Lines

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-gtk-theme#233]
In some programs there are weird black lines separating the GUI elements. Example below is Rhythmbox

![screenshot_2015-06-19_11-47-27](https://cloud.githubusercontent.com/assets/5920259/8252234/ee807728-167b-11e5-94c7-623384e33d61.png)

**Comment by brrrrrrrt** [comment]
the same e.g. in Evolution 3.18.4 on Arch, black lines and also notice the drop shadow of the window looks more like a border:

![bildschirmfoto von 2016-01-31 17-59-35](https://cloud.githubusercontent.com/assets/4489013/12703483/84eaf0c4-c844-11e5-933e-c2f1b2b6bb5d.png)

**Comment by khurshid-alam** [comment]
So this drop-shadow is now appearing for ssd as well? It is appearing from the box-shadow around the widows. Setting `margin: 1px` will probably reduce that. But there are lots of similar bugs. It requires deep investigation to find the optimize settings. It could also be a bug in GTK or improper css values for evolution.

**Comment by megax** [comment]
@Foggalong @khurshid-alam Still having trouble?

**Comment by Foggalong** [comment]
I can't say since I don't use those programs anymore, sorry!

**Comment by brrrrrrrt** [comment]
same here, sorry can't tell, switched to a different theme.
