### ISSUE TITLE
Border in some buttons

### ISSUE THREAD

**Issue by osjerick** [numixproject/numix-gtk-theme#236]
Some application buttons show a gray border that doesn't appear with other themes, and didn't show up using Numix in OpenSUSE 13.1, I'm currently using OpenSUSE 13.2 with Gnome 3.14. Here an example with Shotwell: 
![screenshot from 2015-06-29 12 31 56](https://cloud.githubusercontent.com/assets/8047984/8413600/85e94bd0-1e5b-11e5-8fc0-8ef78add0ba4.png)

**Comment by khurshid-alam** [comment]
Fixed in new release. 

![image1](http://i.imgur.com/MN973FI.png)
