### ISSUE TITLE
Inactive menu text in Netbeans

### ISSUE THREAD

**Issue by abishai** [numixproject/numix-gtk-theme#239]
I have strange look in Netbeans (openjdk7, xfce) with GTK style (so, it uses Numix gtkrc) in the menus. I played with style "murrine-menu" but made it even worse. I've noticed no similar behavior in other applications. Any tips ?
http://i.imgur.com/wlC912r.png

**Comment by all4pages** [comment]
I have this Problem everywhere in the context menus (desktop, taskbar,...) but not in Browser.
Oracle Java 8, xfce, jessie
Looks like there is a white shadow under the grey text.

**Comment by all4pages** [comment]
I have a solution:
sudo apt-get install gtk2-engines-murrine

thanks goes to @matart

**Comment by abishai** [comment]
I have it.
===>>> gtk-murrine-engine-0.98.2_4
