### ISSUE TITLE
Close button miss aligned in window spread mode

### ISSUE THREAD

**Issue by angel-araya** [numixproject/numix-gtk-theme#24]
The close button appears to be miss aligned when in spread view mode.

![ rea de trabajo 1_006](https://f.cloud.github.com/assets/1882727/329958/beb2b84e-9bc1-11e2-8a08-0c72c8610612.png)

**Comment by satya164** [comment]
Are you talking about Unity? The close button is added by Unity and cannot be controlled in the theme.
