### ISSUE TITLE
XFCE Whisker Menu Support

### ISSUE THREAD

**Issue by RomanSC** [numixproject/numix-gtk-theme#240]
Hey all,

After installing Numix on XFCE I noticed the whisker-menu window was taking a few things from the Numix theme like highlighting in orange for the search bar, but it was white so I found this page from the whisker-menu creator which got me started on adding the necessary lines in my Numix GTK-2.0 theme: 

https://gottcode.wordpress.com/2013/11/27/theming-whisker-menu/

Under /usr/share/themes/Numix-master/gtk-2.0/gtkrc I added:

```
 style "whisker-menu" {
         bg[NORMAL] = @menu_bg_color
         bg[ACTIVE] = @menu_bg_color
         bg[PRELIGHT] = shade (1.1, @menu_bg_color)

         fg[NORMAL] = @menu_fg_color
         fg[PRELIGHT] = @menu_fg_color
 }

 widget "*whiskermenu-window*" style "whisker-menu"
```

With these additions though, the scroll-bar becomes the same color as the background. They're the correct scroll bars, just without correct colors. What needs to be added to get the proper colors for the scroll bar?

**Comment by satya164** [comment]
@ochosi 

Also, would be great if we could add this to the theme itself.

**Comment by ochosi** [comment]
@satya164 Not sure what needs to be done there really, whiskermenu looks totally normal here:
![screenshot_2015-08-10_00-20-18](https://cloud.githubusercontent.com/assets/261436/9157227/9bd6753e-3ef5-11e5-8353-570d1710dcbc.png)

**Comment by RomanSC** [comment]
If you were to add the lines that I added to /usr/share/themes/Numix/gtk-2.0/gtkrc it would look like this, I should've included a picture with my original post. Imagine orange instead of blue accenting here as well. That's just custom color I've added in Xubuntu's options:
![screenshot - 08092015 - 06 30 20 pm](https://cloud.githubusercontent.com/assets/11790004/9157269/6246fa26-3ec5-11e5-88b3-990a20bbc093.png)

**Comment by RomanSC** [comment]
It's a bit difficult to see, but here's the issue with my edits that I was describing in my original post. The scroll bar colors seem to simply take the color of the menus if you don't add lines to specify what color you want the scroll bars to be. They're a dark gray:
![screenshot - 08092015 - 06 37 47 pm](https://cloud.githubusercontent.com/assets/11790004/9157302/a2422f32-3ec6-11e5-8c19-793d262b98d7.png)

**Comment by satya164** [comment]
@ochosi Numix Menu is style is dark all over.
