### ISSUE TITLE
mouse disappear in gedit

### ISSUE THREAD

**Issue by eveouyang** [numixproject/numix-gtk-theme#243]
I using Numix theme in xfce4. When I open gedit and press Ctrl+F to search. The mouse the mouse just disappear, when I move it the mouse will flash,but I stop moving it will disappear again.

**Comment by satya164** [comment]
Does this happen with other themes?

**Comment by eveouyang** [comment]
No, just Numix happen.

**Comment by khurshid-alam** [comment]
Could not reproduce in Xubuntu 16.04.
