### ISSUE TITLE
Calibre

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-gtk-theme#245]
Anybody nows if exists some theme for [Calibre](http://calibre-ebook.com/)? 
It GUI looks horrible! 

![calibre](https://cloud.githubusercontent.com/assets/1277920/9233989/a1ca20bc-410c-11e5-84d4-140e32c3e341.png)

**Comment by satya164** [comment]
Callibre is a Qt app, hence Numix cannot theme it, as it's a GTK theme.
