### ISSUE TITLE
Gnome Tweak Tool cannot find Numix shell

### ISSUE THREAD

**Issue by smonv** [numixproject/numix-gtk-theme#246]
On GTT, shell theme settings only show Default, my top bar and volumn tool is default theme of Fedora 22

**Comment by smonv** [comment]
![screenshot from 2015-08-14 15-07-09](https://cloud.githubusercontent.com/assets/8962973/9269696/2ccbb7c2-4296-11e5-9aa5-9df5325a9bc4.png)

**Comment by bilelmoussaoui** [comment]
Installing Numix does not install Numix shell theme. You should use a tool like elegance colors or something like that to have the shell theme installed ;)

**Comment by satya164** [comment]
There is no Numix shell theme as of now.

**Comment by smonv** [comment]
Any update for elegance colors for gnome 3.16 ?
