### ISSUE TITLE
Yandex.Browser menu

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#247]
Grey background and black text - unreadable
https://youtu.be/EwZUaU-gaB8

**Comment by png2378** [comment]
:+1:

**Comment by wa4557** [comment]
Same happens in for example inkscape

**Comment by megax** [comment]
@netforhack Still having trouble?

**Comment by ghost** [comment]
Yes.
http://i.imgur.com/MjEgVm0.png

**Comment by khurshid-alam** [comment]
Is this a gtk browser? We do not support styling for custom browser.

**Comment by ghost** [comment]
Chomium fork 
http://i.imgur.com/UNudLSK.png

**Comment by megax** [comment]
Gtk 3.18 or gtk 3.20?

**Comment by megax** [comment]
@netforhack Still having trouble?

**Comment by ghost** [comment]
Nope, Yandex.Browser changed design and all looks good http://imgur.com/a/X6pmK
