### ISSUE TITLE
Numix layout/graphic issues with Pantheon (elementary OS)

### ISSUE THREAD

**Issue by Tomblarom** [numixproject/numix-gtk-theme#248]
http://i.stack.imgur.com/pQQxl.png That's how it looks like if I use the GTK theme Numix in eOS.

I tried to make Pantheon look like this screenshot: http://ubuntuhandbook.org/wp-content/uploads/2013/10/numix-theme-xfce.jpg

Report on eOS: https://bugs.launchpad.net/elementaryos/+bug/1490327

**Comment by mateusdemboski** [comment]
I have the same problem reported on first screenshot. =/

**Comment by khurshid-alam** [comment]
The screenshot is for xfce environment. As of now, Numix does not have full support for Pantheon Shell.

**Comment by khurshid-alam** [comment]
Please open a new issue asking for eOS support.
