### ISSUE TITLE
Evince colors

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-gtk-theme#251]
The sidebar header have wierd black background.

![screenshot from 2015-09-11 17 08 26](https://cloud.githubusercontent.com/assets/1277920/9825147/dcea3d0a-58a7-11e5-9d72-899310b09cbd.png)

**Comment by khurshid-alam** [comment]
Are you using Ubuntu's gtk overlay scrollbar? Then it is a known issue. It does not happen in GTK 3.16 Under Ubuntu 15.10 as Ubuntu decided to used Gnome's new overlay scrollbar.

**Comment by khurshid-alam** [comment]
Already fixed. Closing.
