### ISSUE TITLE
Audiomixer no color in Volumencotrol

### ISSUE THREAD

**Issue by all4pages** [numixproject/numix-gtk-theme#252]
In Audiocontrol and in all progressbar
jessie, xfce
http://i.imgur.com/wFjrspM.png

**Comment by matart** [comment]
I am also noticing this behaviour. I do not know if this is a new issue or ols because I just installed Debian today

**Comment by matart** [comment]
@all4pages This issue can actually be resolved by installing the murrine gtk engine

`sudo apt-get install gtk2-engines-murrine`

**Comment by all4pages** [comment]
@matart WOW, yes this was the trick. Thanks a lot ;-)

**Comment by all4pages** [comment]
Oh and this was the solution for my other problem with the fonts too! Cool, very nice.
 Inactive menu text in Netbeans #239
