### ISSUE TITLE
Menu colours gtk3 apps

### ISSUE THREAD

**Issue by jtojnar** [numixproject/numix-gtk-theme#253]
After I updated from 5cccc5b to d6d5854 the menus in gtk3 applications are no longer legible.

pcmanfm before update
![numix-gtk3-menu-good](https://cloud.githubusercontent.com/assets/705123/10090341/c3eb56b8-632e-11e5-9d85-e6c0a8cb34d4.png)
pcmanfm after update
![numix-gtk3-menu-bad](https://cloud.githubusercontent.com/assets/705123/10090530/b848ec24-6330-11e5-85ad-5457a1788555.png)
gnome-terminal after update
![numix-gtk3-menu-bad-dark](https://cloud.githubusercontent.com/assets/705123/10090462/fcae80fa-632f-11e5-9960-2c219b0d4b62.png)

Additionaly, the menus in gtk2 applications stand even more apart from openbox windows’ title bars.

GIMP before update
![numix-menu-convergent](https://cloud.githubusercontent.com/assets/705123/10090345/c3edddfc-632e-11e5-93e8-8bdbeafaf812.png)
GIMP after update
![numix-menu-divergent](https://cloud.githubusercontent.com/assets/705123/10090342/c3eb65ae-632e-11e5-98c1-bebe8be86e7c.png)

I use GTK 3.17.8

**Comment by khurshid-alam** [comment]
Are you using Unity? Menuitem color or menubaritem bg/fg color got reverted. But it was not related with the particular commit.

**Comment by jtojnar** [comment]
No, I use openbox. It had to happen somewhere between the two commits.

**Comment by jtojnar** [comment]
Thanks for fixing it.
