### ISSUE TITLE
Window control buttons not going red when hovered over on some applications

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#255]
In certain applications such as NetBeans IDE, and from time to time in Firefox and others, I have noticed that when going over the window control buttons (Close/Minimize/Maximize) that they do not go red as they should when hovered over, although in all other ways they seem to behave perfectly normally.

I am running Ubuntu GNOME 15.04 (GNOME 3.18), and have set Numix as my GTK+ theme. When changing my GTK+ theme to the default one (not Numix) the issue does not occur in any applications though, so it is definitely a Numix issue.

**Comment by khurshid-alam** [comment]
@SeventhSonOfASeventhSon  Still happening? Screenshot?

**Comment by ghost** [comment]
No, seemingly not, though I will reopen this issue if it ever comes back.
