### ISSUE TITLE
[gtk 3.18] no padding around icons in side panel of Files(Nautilus)

### ISSUE THREAD

**Issue by leomao** [numixproject/numix-gtk-theme#256]
Numix
![2015-10-09 22-55-54](https://cloud.githubusercontent.com/assets/1811303/10397235/22bd8cc8-6ed9-11e5-90ca-6db9a5577c75.png)

Adwaita
![2015-10-09 22-59-05](https://cloud.githubusercontent.com/assets/1811303/10397284/62a48b66-6ed9-11e5-9cd1-af13a150d557.png)

**Comment by dirtydancing** [comment]
I can confirm this issue with Arch/GNOME and Files/Nautilus 3.18.0:

Numix GTK
![numix](https://cloud.githubusercontent.com/assets/7164227/10405250/077d4670-6ed8-11e5-8ede-5a3d32ed9882.png)

Adwaita GTK (all fine)
![adwaita](https://cloud.githubusercontent.com/assets/7164227/10405255/0cd80254-6ed8-11e5-9d9e-8a030b68747f.png)
