### ISSUE TITLE
Pantheon terminal + is too far to the right

### ISSUE THREAD

**Issue by me4oslav** [numixproject/numix-gtk-theme#26]
As show in the screenie ... look at the + for new tab.
http://i.imgur.com/wnP4xvS.jpg

**Comment by satya164** [comment]
I don't think it can be controlled by the theme.

**Comment by me4oslav** [comment]
O.o DanRabbit said it's a theme issue. I shall bug him about this.

**Comment by satya164** [comment]
Then you should ask him how to fix it.

**Comment by me4oslav** [comment]
Yup, did that already. Now just waiting for him to respond.

**Comment by me4oslav** [comment]
21:59 <tom95> me4oslav: should be -GtkNotebook-intial-gap, which is set to 10px in egtk

**Comment by satya164** [comment]
You mean this gap, right?

![Untitled](https://f.cloud.github.com/assets/1174278/350603/9251838a-a025-11e2-9f02-2b128a9f5d86.jpg)

If yes, -GtkNotebook-intial-gap won't change that.

**Comment by me4oslav** [comment]
Yeah, that gap, tom95 said that this -GTKNotebook-initial-gap thing-y changes it. This is getting really odd, I shall do a bit more research on it on #elementary-dev Freenode IRC.

**Comment by satya164** [comment]
Increasing -GtkNotebook-intial-gap changes the gap between the "+" and the first tab, "user@elementaryo...".

You can try yourself by editing gtk-3.0/apps/granite-widgets.css

**Comment by me4oslav** [comment]
21:32 <DanRabbit> me4oslav: try     -GtkNotebook-initial-gap: 10px;
So, basically the left space can't be removed, but adding a <x>PX for -GTKNotebook-initial-gap could make both spaces the same size =)

**Comment by satya164** [comment]
So should I change it to 10px? Or leave it at 5px?

**Comment by me4oslav** [comment]
Increase it with such value that the "whitespace" after the "+" will be the same as the one before it.

**Comment by satya164** [comment]
Check now.

**Comment by me4oslav** [comment]
Much better =)
On the not so bright side, it's too much to the bottom (this is unrelated to the fix you just made) and I'm not sure if that can be controlled by the theme, shall investigate.

**Comment by satya164** [comment]
The padding can be adjusted, but it results in undesirable side effects.
