### ISSUE TITLE
Missing progressbar in firefox?

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#262]
It seems like the progressbar is missing in firefox. It seems to be specific for numix.

![skaermbillede fra 2015-10-20 18-13-11](https://cloud.githubusercontent.com/assets/12720027/10613639/50467102-7756-11e5-8dbd-ff9f637f144d.png)

**Comment by SemaiCZE** [comment]
Same problem here. I'm on Gnome 3.18 and other progressbars in system are just fine.

**Comment by megax** [comment]
@paltas @SemaiCZE Still having trouble?

**Comment by SemaiCZE** [comment]
@megax Sorry, using arc-theme now, so no idea if it's working or not :/

**Comment by khurshid-alam** [comment]
It was fixed.
