### ISSUE TITLE
small popup menu linespace in GTK 3 (gedit) running on arch

### ISSUE THREAD

**Issue by uakimix** [numixproject/numix-gtk-theme#263]
There is a really small space between menu items in pop-up menu in some gtk 3 applications like gedit. Other gtk themes work well. When changing the theme back and forth with gedit opened, the issue is solved and the popup menu appears correct. 
I'm running an updated Arch with Xfce.
Thanks
![screenshot_2015-10-21_19-58-09](https://cloud.githubusercontent.com/assets/13281423/10652660/26e1dd24-7837-11e5-8961-fcb7f8f67a96.png)

**Comment by marmis85** [comment]
hey if you have installed numix-themes from community you should probably replace it with numix-themes-git from aur as a lot changed in the last 2 releases of gnome and I highly doubt they are going to fix the non-sass version of the theme

**Comment by megax** [comment]
@lots0logs @khurshid-alam Problem has been fixed.
