### ISSUE TITLE
Black background Geary settings on Ubuntu 15.10

### ISSUE THREAD

**Issue by varlesh** [numixproject/numix-gtk-theme#265]
Numix 2.0.2
Geary 0.10 with Settings window:
![2015-10-29 19-53-16](https://cloud.githubusercontent.com/assets/8083855/10825678/2c02692c-7e77-11e5-9efe-cc9c5f4a3e7f.png)

**Comment by varlesh** [comment]
Also on gtk3-widget-factory:
![2015-10-29 20-09-21](https://cloud.githubusercontent.com/assets/8083855/10826065/0141d824-7e79-11e5-8422-7ccc9189494d.png)

**Comment by ocm128** [comment]
Hi Varlesh

Please, what dock are you using?
http://kde-look.org/content/show.php/Papirus+%28Plasma+5+Theme%29?content=169977

btw, I couldn't install the gtk-theme
$ sudo apt-get install papirus-gtk-theme
..
Could not locate the package...

Thanks in advance

**Comment by khurshid-alam** [comment]
@varlesh 

Please search before posting a new issue. This is a duplicate of issue: #206

**Comment by varlesh** [comment]
previously I used plank, but on Plasma 5.4 not good working.
See readme:
https://github.com/varlesh/papirus-pack-kde/blob/master/gtk-themes/README.md

**Comment by varlesh** [comment]
@khurshid-alam Thx.
Why this fix not available on Ubuntu 15.10?

**Comment by varlesh** [comment]
@kalasni also you must install plank theme manual:
https://github.com/varlesh/papirus-pack-kde/tree/master/gtk-themes/papirus/plank
rename folder "plank" to "papirus" and copy to /usr/share/plank/themes

**Comment by khurshid-alam** [comment]
@varlesh 

Because nobody proposed a proper solution or made a pull-request so far. They only provided a workaround which might have other issues.

**Comment by varlesh** [comment]
Thx for answer. I close.
