### ISSUE TITLE
Hard to read some text on firefox

### ISSUE THREAD

**Issue by grenzor** [numixproject/numix-gtk-theme#271]
Currently FF has the dark navy blue default color for url history and other forms and notifications and it's harder to read text. Is it possible to make it so it is the default white/grey?

**Comment by sojusnik** [comment]
Yes, this is especially annoying in the pop-up bookmarks menu: the first level is grey, the following are dark, see [here](http://i.imgur.com/tY9uQ7t.png).

**Comment by megax** [comment]
@khurshid-alam @grenzor Still having trouble?

**Comment by khurshid-alam** [comment]
Fixed.

**Comment by megax** [comment]
Fixed? Example? :)
