### ISSUE TITLE
Fedora, copr, missing terminal tabs accent line

### ISSUE THREAD

**Issue by mvoropaiev** [numixproject/numix-gtk-theme#277]
Using an old `satya164/numix` copr repo:
![screenshot from 2015-12-13 18-05-37](https://cloud.githubusercontent.com/assets/6753164/11767874/e81dab9c-a1c4-11e5-98c9-99db085dc182.png)
Using a new `numix/numix` copr repo:
![screenshot from 2015-12-13 18-02-05](https://cloud.githubusercontent.com/assets/6753164/11767872/dfa0021c-a1c4-11e5-83bb-0cb5cad43a50.png)
Installing theme from source results in the same issue.

**Comment by khurshid-alam** [comment]
This is by design. They redesigned the tab. But I agree with with, older tab design was better.

**Comment by mvoropaiev** [comment]
I was afraid of that. I find it hard to determinate which tab is currently active now.
One more thing I have noticed is the higher title bar, but I guess it is by design too.

**Comment by megax** [comment]
@mvoropaiev Code redesign: https://github.com/numixproject/numix-gtk-theme/commit/d15039c50e14b15c0245e43f72eb8de2bfe65cd1

Example:
![image](https://cloud.githubusercontent.com/assets/461493/14767790/9c28c53c-0a2e-11e6-9501-a3bf346f515a.png)

**Comment by mvoropaiev** [comment]
@megax thank you!
but after trying to install theme manually from master branch I am still getting the tabs like on my second screenshot, did I do something wrong? Or maybe I don't fully understand it?

Thanks.

**Comment by khurshid-alam** [comment]
Bottom highlight returned in f696652305bfb. Only thing left is to restore old terminal notebook tab

**Comment by mvoropaiev** [comment]
@khurshid-alam awesome!
I can confirm that is working when installed from the master branch.
Now I can finally switch back to Numix I guess:)

**Comment by megax** [comment]
@khurshid-alam @lots0logs Fixed, Issue close? :)
