### ISSUE TITLE
Bad rendering on borders

### ISSUE THREAD

**Issue by fabienduhamel** [numixproject/numix-gtk-theme#279]
Hi.
Applying the theme makes some borders ugly. Any idea ?

I just cloned the project into `~/.themes`, ran `make` (which worked), and applied the theme (into **Contrôles** widget).
I'm on a cinnamon desktop.

![capture du 2015-12-23 21 27 26](https://cloud.githubusercontent.com/assets/10584029/11984495/00113ed6-a9bc-11e5-8bdd-ad4f65e7abe6.png)

**Comment by khurshid-alam** [comment]
Are you using theme from git master? Which distro?

**Comment by fabienduhamel** [comment]
Yes I am on master and I am on Mint 17.3. I've re-tested it just now and I got the same behaviour.

```
~  lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 17.3 Rosa
Release:    17.3
Codename:   rosa
```

**Comment by lots0logs** [comment]
@fabienduhamel Which version of Gtk do you have?

**Comment by fabienduhamel** [comment]
```
~  dpkg -s libgtk2.0-0|grep '^Version'
Version: 2.24.23-0ubuntu1.3
~  dpkg -s libgtk-3-0|grep '^Version'
Version: 3.10.8~8+qiana
```

Both 2.0 & 3.0 are installed.

**Comment by andia89** [comment]
Do you have gtk-engine-murrine installed?

**Comment by lots0logs** [comment]
Wow..I am surprised at how far behind Mint's Gtk version is! The theme was rewritten around the time Gtk 3.16 was released. Unfortunately, there was no way to retain backwards compatibility. I recommend installing copy of the theme prior to the rewrite. You can find it [here](https://github.com/shimmerproject/Numix/tree/e833d2465622ae8b0d00fa07e1b254067416d65d). Cheers!

**Comment by fabienduhamel** [comment]
I got murrine but I agree with you and I didn't know Mint was so far behind. The workaround did well since I could not compile the theme, I just wanted to customize colours properly ;) but I do it with `sed` commands now.

Thanks.
