### ISSUE TITLE
Selections on GTK from 3.8 are broken

### ISSUE THREAD

**Issue by Vistaus** [numixproject/numix-gtk-theme#28]
When trying to select something from a list or menu there's no visible text; just grey. But when you hover over it's right though.

http://i.imgur.com/DmmLedJ.png

Hopefully this can be fixed as this is the only issue I encountered on 3.8

**Comment by satya164** [comment]
It's not yet compatible with 3.8. Will try to port it soon.

**Comment by Vistaus** [comment]
Thanks for looking into it! :)

**Comment by kellerman** [comment]
Most GTK3 themes are broken. The only proper working seems to Adwaita lol.

**Comment by Vistaus** [comment]
@kellerman Nope. A few others are also made compatible with 3.8 like DarkAir (see gnome-look.org) and Ambiance and Radiance from Ubuntu (on 13.04 at least).

**Comment by satya164** [comment]
It has been fixed in d188951d0901d89e79c68294a702dda8603ad211
