### ISSUE TITLE
White margin for apps with client-side decoration in Ubuntu

### ISSUE THREAD

**Issue by andia89** [numixproject/numix-gtk-theme#281]
When using Ubuntu, GNOME apps with client side decorations have a white margin (see screenshot) compared to the dark margin apps usually have. I guess it is somehow related to #206?

I'm using the git version btw. 

![bildschirmfoto 2016-01-03 10 16 46](https://cloud.githubusercontent.com/assets/6475757/12078074/88ce7780-b203-11e5-9daa-19187729ba9d.png)

**Comment by andia89** [comment]
Why is there a margin in the first place? All the other apps don't have margins at all

**Comment by andia89** [comment]
It is this margin here: A specific reason why it is set to `1px` instead of `0px` https://github.com/shimmerproject/Numix/blob/master/gtk-3.0/scss/widgets/_window.scss#L29

**Comment by khurshid-alam** [comment]
@wa4557 

Yes.
I think the reason is to provide a  drag-area (although 1px is not enough) for re-sizing windows with mouse. On, Unity it works fine because Unity uses its own window decorator. But for other desktop session (like gnome-flashback which uses `metacity`) csd windows are not re-sizable with the mouse. Also if two windows overlaps with 0px border it is difficult to distinguish the edge between them. However I agree that it does look bad.

**Comment by khurshid-alam** [comment]
@satya164  Your thoughts on this?

**Comment by andia89** [comment]
Could the margin then made transparent?

**Comment by khurshid-alam** [comment]
@wa4557 

No. The window margin takes inherit color. So if you set **background-color** to `transparent` it will just end up having inherit window color which is black. 

So either you decorate csd or do not decorate at all. Previous design doesn't have these margin and border decoration. It was introduced during redesign phase.

**Comment by satya164** [comment]
Hey @khurshid-alam . Can you ping me on Telegram @satya164 ?

**Comment by andia89** [comment]
@khurshid-alam On Ubuntu GNOME it seems to be unnecessary to have the margin. (distinction between two overlaying windows is there because of the shadow, and gripping area is also ok).. Is this different for other GNOME distros?
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/12491956/1c5e7f6c-c07e-11e5-87f5-4994eb266723.png)

**Comment by khurshid-alam** [comment]
Window Margin is required for window mangers without composting to provide a drag area. This is done in the theme by using:

``` css
    .window-frame {
        margin: $spacing * 3;
```

Here csd margins are provided on top of that.
However this produces a black border for those old window managers (metacity) (https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1518661) for >=GTK-3.16.x.

Fortunately both for mutter(Gnome-Shell) and unity decorator, margin is not required. So We can simply set `&.solid-csd { margin: 0px;}` and be done with it. 

Old metacity users then, have to use a workaround (disabling box shadow settings in the theme). But I believe that's up to window mangers to implement a drag-area in their code (and Numix doesn't support metacity anyway).

**Comment by andia89** [comment]
Great does that mean that the margin could be removed?

**Comment by andia89** [comment]
Great does that mean that the margin could be removed?

**Comment by khurshid-alam** [comment]
Yes. But removing the code from source could be dangerous, it doesn't really affect Gnome-shell. For Ubuntu a patch can be made to set the margin as `0px`.

**Comment by khurshid-alam** [comment]
For Ubuntu I think something like this should work for now:

``` css
.window-frame {
  border: 0;
  border-radius: 2px 2px 0 0;
  background-color: mix(#303030,#eee,0.21);
  /* this is used for the resize cursor area */
  margin: 15px; }
  .window-frame.tiled {
    border-radius: 0; }
  .window-frame.solid-csd {
    border-radius: 2px 2px 0 0;
    margin: 1px;
    background-color: mix(#303030,#eee,0.21);
    box-shadow: none; }
}
```

**Comment by Corsseir** [comment]
When are you going to add this patch to launchpad package? I have same issue with Corebird app.

**Comment by khurshid-alam** [comment]
@Corsseir I do not like to commit temporary patch which will need to be modified again for GTK>= 3.19. Compiz should implement proper support for _GTK_FRAME_EXTENT which is required for GTK>=3.16. Otherwise it will always remain as patch-up job.

**Comment by Corsseir** [comment]
Ok, so how I can add this piece of code by myself? I am on Ubuntu 15.10 now.
