### ISSUE TITLE
Gnome Shell theme

### ISSUE THREAD

**Issue by sojusnik** [numixproject/numix-gtk-theme#283]
Since the theming abilities of Gnome changed drastically with the 3.16 release ([elegance colors](http://satya164.deviantart.com/art/Gnome-Shell-Elegance-Colors-305966388) isn't working anymore), I'm wondering if there is still a user friendly way to change the default Gnome Shell theme to a Numix Gnome Shell theme?

**Comment by khurshid-alam** [comment]
The issue with elegance colors is being tracked here: https://github.com/satya164/elegance-colors/issues/54

As the GTK theme is going through redesign (big changes await for 3.20), it will probably get fixed after that. 

Mean while you can use this : http://gnome-look.org/content/show.php/Numix-like+GNOME+Shell+3.16+theme?content=174129

![image1](http://gnome-look.org/CONTENT/content-pre1/174129-1.png)

**Comment by sojusnik** [comment]
Thanks!

**Comment by sojusnik** [comment]
BTW, this theme seems to be more up to date: http://gnome-look.org/content/show.php/Numix+Style+Shell+%E2%80%93+GNOME+3.16?content=174477
