### ISSUE TITLE
Background is Greyed out

### ISSUE THREAD

**Issue by WestonReed** [numixproject/numix-gtk-theme#285]
The background is greyed out, and attempting to set it does not fix it.

![numixbackgroundbug](https://cloud.githubusercontent.com/assets/11198372/12397204/6be7cd40-bdd1-11e5-8819-ff74dfa2ce6d.gif)

**Comment by khurshid-alam** [comment]
Which distro? Gnome version? Try running `nautilus -q`. Could be same issue as #272

**Comment by WestonReed** [comment]
@kurdish-alam Debian Testing and Gnome 3.18. Nautilus -q works, but comes back when I reopen nautilus.

**Comment by lots0logs** [comment]
This is a duplicate of #272 which appears to be a bug in nautilus (not the theme). Cheers!
