### ISSUE TITLE
Transparent tooltips on Firefox

### ISSUE THREAD

**Issue by astatine** [numixproject/numix-gtk-theme#288]
I am using the official Numix PPA on Ubuntu 15.10. This issue seems to have been fixed according to previous bug reports (#225, #235), but it still persists for me.

Screenshot:
![Issue #228 Transparent Tooltips on Firefox](http://i.imgur.com/8dvctF5.png)

Please let me know if you need any more information.

**Comment by mallardduck** [comment]
I'm also still seeing this issue.

**Comment by megax** [comment]
@khurshid-alam Fixed 3.20
