### ISSUE TITLE
Window title is 1px wider than window itself on right and left

### ISSUE THREAD

**Issue by nazar-pc** [numixproject/numix-gtk-theme#290]
Ubuntu 16.04, version from repository, apps like Nemo, Firefox, Thunderbird, System settings, Synaptic.
However goes not affect Gedit, Gnome tweak tool since they have different kind of window title.
![nemo](https://cloud.githubusercontent.com/assets/928965/12787046/0131df20-ca94-11e5-93ff-47499856dad8.png)

**Comment by khurshid-alam** [comment]
Can anyone confirm this on Arc? I think Ubuntu's window decorator is using 1px border on titlebar. To match it we have to use 1px border on window-frame as well.

**Comment by nazar-pc** [comment]
Another thing is that for instance 2 windows placed side by side and occupying exactly half of the screen in fact have overlapping. My guess is that actually window itself might be correct and only title should be modified.

**Comment by nazar-pc** [comment]
Thanks, visually it is fine now.

**Comment by nazar-pc** [comment]
@khurshid-alam, there is the same issue on non-focused windows, can you fix it as well?

**Comment by khurshid-alam** [comment]
@nazar-pc screenshot?

**Comment by nazar-pc** [comment]
Looks like it was something temporary, everything looks fine after reboot, sorry for bothering.
