### ISSUE TITLE
Xenial builds for Numix GTK theme

### ISSUE THREAD

**Issue by nazar-pc** [numixproject/numix-gtk-theme#291]
Last 3 builds failed and currently Xenial ppa doesn't have any theme package at all.
https://launchpad.net/~numix/+archive/ubuntu/ppa/+packages?field.name_filter=gtk-theme&field.status_filter=&field.series_filter=xenial

**Comment by nazar-pc** [comment]
BTW, the same story with builds for other Ubuntu versions.

**Comment by khurshid-alam** [comment]
Will be fixed soon. Meanwhile you can use Shimmer-Themes daily PPA https://code.launchpad.net/~shimmerproject/+archive/ubuntu/daily/+packages for Ubuntu 15.10 and lower.

**Comment by khurshid-alam** [comment]
Fixed.
