### ISSUE TITLE
Menu button sizes are incorrect for xfwm4

### ISSUE THREAD

**Issue by veganism** [numixproject/numix-gtk-theme#292]
The issue is that the height of title-*.xpm (26px) does not match the height of the buttons (24px), so they sit centered vertically with a 1px gap along the top edge of the window. This means that somebody trying to close a maximized window by putting their mouse in the very top right corner cannot activate the close button. To remove that gap we must change the buttons to be 26px, and to keep the positioning we have to make one line above and one line below the icon itself.

Since the buttons being 26px tall then overlaps the window borders, we have to replace the top line in each button with the appropriate border color. We also must adjust the canvas size of the png files to 26px and center the existing icons.

In practice, we do not visually change the xfwm4 theme at all, but we allow the top pixels to function as window buttons.

Here is an example to illustrate the differences:
![screenshot_2016-02-04_14-09-44](https://cloud.githubusercontent.com/assets/16749758/12828422/5745be34-cb4a-11e5-8424-e578599fe966.png)

And attached is a fixed version of the theme that is in the Ubuntu repos (trivial to find and replace the colors by treating *.xpm as text files to match the latest version):
[Numix-fix_ubuntu-repo-ver_2-4-2016.zip](https://github.com/shimmerproject/Numix/files/118184/Numix-fix_ubuntu-repo-ver_2-4-2016.zip)

**Comment by khurshid-alam** [comment]
Feel free to open a pull request.
