### ISSUE TITLE
Scrollbar Not at Screen Edge in Firefox

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#296]
I just got a huge update (in terms of change to the design) today for the Numix GTK theme.
One of the issues I have with it though is that the new scrollbar isn't at the edge of the screen for me in Firefox on Kubuntu 15.10.

(A further note, it would be nice to have the option of both the old and the new Numix theme but that's a separate un-related topic )

**Comment by khurshid-alam** [comment]
Screenshot?

**Comment by ghost** [comment]
![screenshot 2016-02-09 08 00 39](https://cloud.githubusercontent.com/assets/7698035/12910509/3e3605e0-cf03-11e5-9be7-a17a263c3ce4.png)

**Comment by ghost** [comment]
It does look nice not being at the edge of the screen it's just annoying not being able to click and drag it from the edge of the screen.

**Comment by khurshid-alam** [comment]
Clicking and dragging works for me on Xenial (16.04).

Ubuntu dropped their own overlay scroll-bar in 15.10. Now they use Gnome's overlay scroll bar. May be a bug should be filed against Firefox to incorporate Gnome's new scroll-bar properly as it doesn't work for non gtk apps.

Anyway, I will check if anything needs to be modified.

**Comment by ghost** [comment]
I'm just an average user I'm not too sure about any of that but I appreciate you looking into it.

**Comment by fitojb** [comment]
The Firefox scrollbar bug is already filed at https://bugzilla.mozilla.org/show_bug.cgi?id=1147847

**Comment by megax** [comment]
@khurshid-alam Still having trouble?
