### ISSUE TITLE
New Numix Theme Colour Oddities

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#297]
I've noticed some colour issues with the new look, here are the screenshots:

1) In Firefox when you search in the address bar the colours clash heavily making URLs hard to read.
![screenshot 2016-02-09 08 19 53](https://cloud.githubusercontent.com/assets/7698035/12910865/1a7563dc-cf06-11e5-82fb-99ef641bc03b.png)

2) In some applications (this example is Kazam) the light grey colour for activated boxes is too light and looks out of place.
![snapshot2](https://cloud.githubusercontent.com/assets/7698035/12910905/5c9a3d78-cf06-11e5-870a-949ea30dce33.png)

**Comment by bnonn** [comment]
I'm going to add to this thread rather than creating a new one. I've found another color problem; this one is with the progress bars in Transmission. They are completely invisible. This doesn't happen with progress bars in Nautilus, but I haven't tested any other apps (not sure what to test...I don't use that many).

![screenshot from 2016-02-10 10-37-10](https://cloud.githubusercontent.com/assets/465135/12931430/adadb1b8-cfe2-11e5-98f2-85f5350a6420.png)
![screenshot from 2016-02-10 10-36-49](https://cloud.githubusercontent.com/assets/465135/12931431/adaf994c-cfe2-11e5-948e-6bb82f17563f.png)

**Comment by ghost** [comment]
It's worth noting that today I re-installed Kubuntu and the Numix theme and now the above Firefox URL colour is different (looks good and is readable). This leads me to believe that there may have been an issue with the update itself rather than the theme but I'm not very technical so I'm not sure.

The second image I shared (showcasing the odd active box colour in Kazam) still applies and also applies to certain active buttons. To keep it consistent I'll show you what I mean in Kazam again:
![snapshot1](https://cloud.githubusercontent.com/assets/7698035/12932243/bf74422c-cf79-11e5-8bcc-6d15874e49d6.png)
Whilst there's nothing technically wrong with it as it is usable, it looks quite ugly.

**Comment by dakira** [comment]
I would also like to note that the new white background in terminal windows is very disturbing. Maybe create a new Numix style instead of changing everything?

**Comment by ghost** [comment]
Newmix

**Comment by tarhan** [comment]
> I would also like to note that the new white background in terminal windows is very disturbing. Maybe create a new Numix style instead of changing everything?

**+1**  
![terminal_with_system_palette](https://cloud.githubusercontent.com/assets/5427484/12969958/0bdb36dc-d099-11e5-997e-bb0a42ac68e5.png)

Yeah, white background in dark theme is really disturbing. I have to disable system palette usage inside gnome-terminal for now. It looks different from numix but still more comfortable for dark theme.

![terminal_without_system_palette](https://cloud.githubusercontent.com/assets/5427484/12969970/3cc58694-d099-11e5-8208-d80424afddd8.png)

**Comment by ghost** [comment]
+1 for reverting to dark-colored terminal.

**Comment by khurshid-alam** [comment]
During to new design gnome-terminal decoration was removed. It will land soon.

**Comment by dakira** [comment]
Thank god. ;-)

**Comment by tborychowski** [comment]
:+1: (to terminal)

**Comment by khurshid-alam** [comment]
Terminal issue got fixed in c637d4d

**Comment by dakira** [comment]
@khurshid-alam Is this commit going to land in the PPA any time soon?

**Comment by khurshid-alam** [comment]
@dakira Done! :)

**Comment by tborychowski** [comment]
Thanks!

**Comment by dakira** [comment]
Great, thanks!

**Comment by pavethem** [comment]
the terminal issue got fixed for me with the latest update, but the issue with transmission as mentioned by @bnonn still persists.

**Comment by khurshid-alam** [comment]
Transmission and some other issues are yet to be fixed. That is why I didn't close this issue.

**Comment by ghost** [comment]
As of Firefox 46 it now supports and uses the GTK 3 styling. This makes text in the searches in the awesome bar look ugly (see the first screenshot posted in this) and also makes the scrollbar super thin and black (although that looks fine, I just feel it's worth mentioning in case it's not meant to be that way).

**Comment by megax** [comment]
@bnonn transmission fixed: https://github.com/shimmerproject/Numix/commit/dae4da6b7cf6d13ecced503db61531abb5509861

**Comment by timtjtim** [comment]
@khurshid-alam Bumping this thread due to report on Ask Ubuntu - https://askubuntu.com/q/761473/

**Comment by megax** [comment]
@khurshid-alam Still having trouble?
