### ISSUE TITLE
Black borders in Libreoffice 5.1

### ISSUE THREAD

**Issue by sojusnik** [numixproject/numix-gtk-theme#298]
Hey,

after a recent update of LibreOffice the menu bar got a black border, as seen [here](http://i.imgur.com/8ayyuy8.png). On other themes, like Adwaita, a similar border isn't present.

Using Ubuntu 15.10 64-bit with LibreOffice 1:5.1.0~rc3-0ubuntu1~wily0 installed from their [ppa](https://launchpad.net/~libreoffice/+archive/ubuntu/ppa).

**Comment by khurshid-alam** [comment]
It could be a bug in LibreOffice. It is also present with Adwaita, but border is white. I will teak it a bit.

**Comment by khurshid-alam** [comment]
Ok. As per https://github.com/horst3180/arc-theme/issues/136 its a LibreOffice bug.

Here menu background color is used for the white borders. I.e. setting

``` css
.menu, .popup {
  background-color: green;
}
```

makes those borders green. It happens with LibreOffice GTK-3 which is still WIP
