### ISSUE TITLE
Cant change colour in gtk 3 apps

### ISSUE THREAD

**Issue by ipeacocks** [numixproject/numix-gtk-theme#299]
After last update, colour changes cant be applied to gtk3 apps through "Theme Configuration":

![alt tag](http://i.imgur.com/rj8q6m4.png)

But fine for other toolkits: qt, gtk2.

![alt tag](http://i.imgur.com/6mZ9sf7.png)

And this is typical gtk3 view:

![alt tag](http://i.imgur.com/hsdKvrk.png)

So red colour cant be overrode.

**Comment by khurshid-alam** [comment]
Which distro? version before upgrade? What is the content of `~/.config/gtk-3.0/gtk.css`?

**Comment by ipeacocks** [comment]
Xubuntu 15.10. 

It is my ~/.config/gtk-3.0/gtk.css
https://gist.github.com/ipeacocks/653b80f29c29e2932065

> version before upgrade?

Actually I don't remember but update came few weeks ago.

**Comment by khurshid-alam** [comment]
Well, from the code`menu` decoration is switched off for some reason and it I could not find `menubar_bg_color` in it which is responsible for  changing gtk3 menus. It should be something like this

``` css
@define-color menubar_bg_color @theme_selected_bg_color;
@define-color menubar_fg_color @theme_selected_fg_color;
```

You may want to file a bug against gtk-theme-config at https://github.com/satya164/gtk-theme-config/issues
