### ISSUE TITLE
Tabs need separator between them

### ISSUE THREAD

**Issue by me4oslav** [numixproject/numix-gtk-theme#3]
It look wkward (and not like the GTK 3) when the tabs have no separators between them.

**Comment by satya164** [comment]
Can you be more clear? And anyways, I have just started the GTK2 theme. Will notify you when it is done. Now you'll find thousands of things if you search.

**Comment by cldx** [comment]
I don't really get it either, post a screenie.

**Comment by me4oslav** [comment]
GTk 2 tabs:
http://i.imgur.com/32AZAfe.png
GTK 3 tabs:
http://i.imgur.com/6NnFaIa.png
There are separators between the GTK 2 tabs too, but the GTK 3 ones look MUCH better :)
