### ISSUE TITLE
Padding and tab identity issues on 2.4

### ISSUE THREAD

**Issue by arximboldi** [numixproject/numix-gtk-theme#300]
Hi!

Here is a comparison of Numix 2.3 and 2.4 on my machine (window manager is Xmonad customized to match Numix 2.3).

![screenshot from 2016-03-02 10-21-37](https://cloud.githubusercontent.com/assets/4521138/13456152/f4eb1748-e061-11e5-8cd5-736c08a7aba9.png)

![screenshot from 2016-03-02 10-18-24](https://cloud.githubusercontent.com/assets/4521138/13456155/f78c5a66-e061-11e5-9378-76c44e074ae4.png)

While the new version introduces numerous improves (great work Numix team!) I believe that there are some glitches and usability problems:
1. Paddings and margins are increased too big. This produces poor screen space usage, that can be notices in few places, as in:
   - Main toolbar. The old one was slick with big flat buttons that reach to the margin. Now almost half the vertical space is margin.
   - Tab headers. They are huge, with text looking almost tiny inside, a lot of waste.
   - Nautilus sidebar: you can see how in the old design all my sidebar items fit in the screen, while now that is not the case. On the other hand, the old version has numerous problems in this section, both in padding and in the new end-of-list marks showing as opaque rectangles.
2. Nautilus tabs text is disaligned.
3. In the new design, it is very hard to see what tab is selected. It would be very nice to have something like in the old version of the theme -- an orange bar at the bottom.

I understand that the padding issues might be a matter of taste or debatable. In case you consider this a non-bug, could you point me to the kind of rules that I should add to my custom `gtk.css` to change this?

Thanks a lot team for this work, keep it up!

**Comment by arximboldi** [comment]
Oh, one last point, I agree with #178 that 2.4 brighter colors are not so nice. I understand though that this is a matter of taste and depends on the display contrast.

**Comment by khurshid-alam** [comment]
@satya164 What do you think? Should we change back the tab design to old one?

**Comment by khurshid-alam** [comment]
@arximboldi if you want less padding, you can reduce global `$spacing` value to `3px` from `5px` under _global.scss (https://github.com/shimmerproject/Numix/blob/master/gtk-3.0/scss/_global.scss#L77). Then you need to recompile theme.

**Comment by arximboldi** [comment]
@khurshid-alam thanks for the tip. Chaning that spacing to `3px` makes the problem a bit less prominent, but the spacing loses balance in other places (e.g. drop down menu items) and tabs are still not great. On the other hand, the new SCSS based code is much nicer to edit (changing the colors is also quite nice now). Looking forward to the evolution of this theme, thanks!

**Comment by satya164** [comment]
@khursid-alam the tabs clearly look like a bug. Does this happen for every DE?

**Comment by schiegl** [comment]
I would prefer slimmer window bars by default too. There are many people with mobile devices. It's especially bad on programs that don't use the bar for controls.

Otherwise it's really nice!

**Comment by khurshid-alam** [comment]
@satya164 So far I have tested under Antergos and Ubuntu-Gnome...and I don't find anything different. And naturally, it is broken for GTK>= 3.19.3 for every DE.

**Comment by SammysHP** [comment]
The reason for the extra padding is https://github.com/shimmerproject/Numix/blob/master/gtk-3.20/scss/widgets/_toolbar.scss#L65, which includes the toolbar mixin which has a large padding in https://github.com/shimmerproject/Numix/blob/master/gtk-3.20/scss/widgets/_toolbar.scss#L12.

**Comment by satya164** [comment]
Since GTK now can have versioned themes, we could decrease the padding for 3.19 and beyond

**Comment by khurshid-alam** [comment]
Decreasing padding only from toolbar may leave other widgets/elements inconsistent and ugly. If we want  to decrease it we need to decrease it throughout the code. This requires trial-and-errors, Anyone is welcome to submit a pull request.

**Comment by khurshid-alam** [comment]
As for tabs here is the comparison: 
![notebook-tab](http://i.imgur.com/RaF83Xm.png)

If uses want it a bottom-highlight can easily be added.

**Comment by SammysHP** [comment]
I removed the `* 2` [_toolbar.scss#L12](https://github.com/shimmerproject/Numix/blob/master/gtk-3.20/scss/widgets/_toolbar.scss#L12) and it looks good at least for the headerbar. Haven't tested other elements, gtk and numix are both a little bit confusing for me.

(PS: I still prefer the colors and buttons from the last release in early 2015.)

**Comment by megax** [comment]
@khurshid-alam Still having trouble?

**Comment by khurshid-alam** [comment]
Already fixed.

**Comment by khurshid-alam** [comment]
We will look into this after we fix #486
