### ISSUE TITLE
GNOME documents, books, Videos (totem), Photos etc selection checkbox does not appear

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-gtk-theme#304]
The check symbol on selection mode with all those similar "collection" applications doesn't appear at all.

In the following screenshot I selected all the Landau and Lifshiftz physics books on Documents (the program's top bar tells of 6 selected items), but I cannot see a symbol on the checkbox while using Numix GTK3 theme

![screenshot from 2016-04-02 16-45-28](https://cloud.githubusercontent.com/assets/7532854/14228681/ca12d908-f8f2-11e5-8a8d-9640231f08fe.png)

**Comment by khurshid-alam** [comment]
Gnome version? Which Distro?

**Comment by sljunkie** [comment]
GNOME 3.18, Arch Linux

**Comment by khurshid-alam** [comment]
It is possible that assets are not getting compiled properly with gresource. I have experienced similar issue during debian packaging as well. Lets c.

**Comment by khurshid-alam** [comment]
@sljunkie Is this still reproducible with 3.20?

**Comment by sljunkie** [comment]
Yes, it's still reproducible with 3.20. I use Arch Linux, the gtk theme is included in the package numix-themes, whose version in the repos is 2.5.1.r154.9c9bf64-2

**Comment by megax** [comment]
@khurshid-alam @sljunkie
**Adwaita code:**
gtk 3.18: https://github.com/GNOME/gtk/blob/gtk-3-18/gtk/theme/Adwaita/_common.scss#L2165
gtk 3.20: https://github.com/GNOME/gtk/blob/gtk-3-20/gtk/theme/Adwaita/_common.scss#L2530

Please test numix:
**gtk 3.18:** https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.0/scss/widgets/_toggle.scss#L59
old format: `GtkIconView.content-view.cell.check`
new format: `.view.content-view.check`

**gtk 3.20:** https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.20/scss/widgets/_toggle.scss#L69
old format: `iconview.content-view.cell.check`
new format: `.view.content-view.check`

And test:
`:checked, :checked:hover, :checked:active`

Test code:

```
   .view.content-view.check {
        -gtk-icon-source: url("assets/grid-selection-unchecked#{$suffix}.png");

        &:active, &:checked:active { -gtk-icon-source: url("assets/grid-selection-checked#{$suffix}.png"); }
    }
```

**Comment by khurshid-alam** [comment]
Only old format works for 3.18.
