### ISSUE TITLE
Gnome 3.8 (as in Ubuntu Raring, Gnome3 PPA) doesn't render desktop/wallpaper properly

### ISSUE THREAD

**Issue by vegavahini** [numixproject/numix-gtk-theme#31]
Folks,

Awesome work, I have decided to use the GIT version on my 13.04, using gnome 3.8 using the Gnome3 ppa. Everything is fine, except that the wallpaper doesn't showup. I have to set, "Have Filemanager handle the Desktop" in gnome-tweak-tool to OFF to get the wallpaper.
I have the same problem if I were to use Ambiance GTK theme, I can safely use Adwaita and Updated Zukitwo for now. 
Its not a blocker for me, but i thought I would report.

Vissu

**Comment by satya164** [comment]
Fixed in d8a7994
