### ISSUE TITLE
Numix Dark and GTK 3.20

### ISSUE THREAD

**Issue by cobrafast** [numixproject/numix-gtk-theme#310]
Will Numix Dark be updated for the new GTK versions as well?

If so, will the update be released to DeviantArt or will I have to purchase again via the new store?

**Comment by khurshid-alam** [comment]
Numix Dark is not maintained any more. You do not have to purchase again. When/if there are new updates, send a email to team@numixproject.org and we will send you an updated zip.

**Comment by raku-cat** [comment]
So no more numix dark? The store download page says it was updated like a week ago, was gtk 3.20 really the breaking point?
