### ISSUE TITLE
Several GTK-3.20 issues.

### ISSUE THREAD

**Issue by sammko** [numixproject/numix-gtk-theme#312]
Using Numix a7fcd6b7b54fb20ed325fa4e3f359f1c47c01e36, GTK-3.20, Xfce 4.12 on Arch Linux.
I experience multiple issues using Xfce. Some of them also apply to Gnome Shell.
I use xfwm4 with it's internal compositor.
- CSD applications have no shadow, and can only be resized by a 1px wide border around the left and top of the header. In Gnome Shell, the border is also on the left side of the body. (`gedit` can _only_ be resized by a 1px wide border on the left side of the body.)
- The header on `gedit` is narrower than the body of the window:
  ![gedit xfce](https://cloud.githubusercontent.com/assets/703905/14409945/c6311f40-ff21-11e5-89f7-4f3e5246dac1.png)
- The border on the left side of gedit also extends to the header:
  ![screenshot_2016-04-10_13-58-06](https://cloud.githubusercontent.com/assets/703905/14410034/6a21b07c-ff24-11e5-8b95-34d20a75f701.png)

I also think the CSD header is too large, but this is a matter of opinion.

**Comment by leomao** [comment]
I can confirm these issues.

Also I found that the arrow in the dropdown menu disappears.
![2016-04-10 19-52-42](https://cloud.githubusercontent.com/assets/1811303/14410019/443da546-ff56-11e5-8283-b10c2fa83898.png)

**Comment by megax** [comment]
Gedit window bug fixed: https://github.com/shimmerproject/Numix/commit/06ae107d920c2094e6b6c69da0da163cc6f92cc7

**Comment by leomao** [comment]
It seems that the issue "CSD applications have no shadow, and can only be resized by a 1px wide border around the left and top of the header." is not fixed.
Should this be opened as a separate issue?

**Comment by khurshid-alam** [comment]
@leomao No. It has already been reported.

**Comment by megax** [comment]
@leomao Decoration fix: https://github.com/shimmerproject/Numix/pull/321
