### ISSUE TITLE
Gray menus on openbox

### ISSUE THREAD

**Issue by matiaslina** [numixproject/numix-gtk-theme#32]
Hi.. I'm having a problem with some apps in archbang (i.e. network manager, gedit) in the menus. Here are two screenshots from two apps:
![Network manager](https://f.cloud.github.com/assets/1857516/456682/890114a6-b373-11e2-9f33-0f49f2099bd0.png)
![Character map](https://f.cloud.github.com/assets/1857516/456689/bb3f9b0e-b373-11e2-9193-62d8fd2d8b84.png)

And with some others applications I have no problem, like thunar or firefox. 

![Thunar](https://f.cloud.github.com/assets/1857516/456697/06295768-b374-11e2-988a-265b80740a2a.png)

As far I can see, this is the only problem that I have with this great theme. Any idea about what could be?? 

Thanks!

**Comment by satya164** [comment]
Fixed in d8a7994
