### ISSUE TITLE
GTK warnings when using Meld

### ISSUE THREAD

**Issue by ariaviran** [numixproject/numix-gtk-theme#326]
Hi,
After upgrading to GTK 3.20 and the new Numix version that supports it I get GTK warnings every time I use meld.

The warnings are the following:
(meld:4845): Gtk-WARNING **: Theme parsing error: gtk.css:1581:39: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(meld:4845): Gtk-WARNING **: Theme parsing error: gtk.css:1581:77: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(meld:4845): Gtk-WARNING **: Theme parsing error: gtk.css:1972:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

(meld:4845): Gtk-WARNING **: Theme parsing error: gtk.css:3712:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

GTK 3.20
Meld 3.15.2
Numix built from commit #9c9bf64

**Comment by Vrchz** [comment]
Similar problems. In xfce4(archlinux) running gtk 3.20 apps, get "Theme parsing error".
for example
$gtk3-demo
(gtk3-demo:6281): Gtk-WARNING **: Theme parsing error: gtk.css:158:192: '_text_shadow_color' is not a valid color name

(gtk3-demo:6281): Gtk-WARNING **: Theme parsing error: gtk.css:1609:39: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(gtk3-demo:6281): Gtk-WARNING **: Theme parsing error: gtk.css:1609:77: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(gtk3-demo:6281): Gtk-WARNING **: Theme parsing error: gtk.css:3232:39: 'linear-gradient' is not a valid color name

(gtk3-demo:6281): Gtk-WARNING **: Theme parsing error: gtk.css:3237:41: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(gtk3-demo:6281): Gtk-WARNING **: Theme parsing error: gtk.css:3237:53: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(gtk3-demo:6281): Gtk-WARNING **: Theme parsing error: gtk.css:3244:35: 'border_disabled' is not a valid color name

or

$emacs -q

(emacs:6243): Gtk-WARNING **: Theme parsing error: gtk.css:158:192: '_text_shadow_color' is not a valid color name

(emacs:6243): Gtk-WARNING **: Theme parsing error: gtk.css:1609:39: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(emacs:6243): Gtk-WARNING **: Theme parsing error: gtk.css:1609:77: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(emacs:6243): Gtk-WARNING **: Theme parsing error: gtk.css:3232:39: 'linear-gradient' is not a valid color name

(emacs:6243): Gtk-WARNING **: Theme parsing error: gtk.css:3237:41: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(emacs:6243): Gtk-WARNING **: Theme parsing error: gtk.css:3237:53: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(emacs:6243): Gtk-WARNING **: Theme parsing error: gtk.css:3244:35: 'border_disabled' is not a valid color name

(emacs:6243): Gtk-WARNING **: Theme parsing error: gtk-keys.css:108:18: The 'gtk-key-bindings' property has been renamed to '-gtk-key-bindings'

(emacs:6243): Gtk-WARNING **: Theme parsing error: gtk-keys.css:112:18: The 'gtk-key-bindings' property has been renamed to '-gtk-key-bindings'

(emacs:6243): Gtk-WARNING **: Theme parsing error: gtk-keys.css:116:18: The 'gtk-key-bindings' property has been renamed to '-gtk-key-bindings'

(emacs:6243): Gtk-WARNING **: Theme parsing error: gtk-keys.css:120:18: The 'gtk-key-bindings' property has been renamed to '-gtk-key-bindings'

**Comment by megax** [comment]
Duplicated: https://github.com/numixproject/numix-gtk-theme/issues/351

**Comment by megax** [comment]
@lots0logs @khurshid-alam Fixed issue: https://github.com/numixproject/numix-gtk-theme/commit/1616dac147a75bc7c05f256d1408df29ba3ccf96 Close? :)
