### ISSUE TITLE
The Gnome Image Viewer (eog) Save As... dialog doesn't display correctly

### ISSUE THREAD

**Issue by gjm** [numixproject/numix-gtk-theme#33]
Here's a screenshot that shows the problem:

![eog](https://f.cloud.github.com/assets/77360/500329/544ee86c-bc71-11e2-8904-095564a45968.png)

**Comment by satya164** [comment]
Please try clearing your cache (hint: delete the ~/.cache directory) or install Numix in /usr/share/themes. Coz it should not happen!

**Comment by gjm** [comment]
I have Numix installed in /usr/share/themes (from PPA). What cache should i
delete? I'm sorry but i don't think deleting my entire ~/.cache dir would
solve that... I'm running eog 3.6.2 (gtk 3.6.4) on ubuntu 13.04.

Thanks again.

Atentamente,

Gonçalo Marrafa

**Comment by gjm** [comment]
Can you please tell me what cache i should delete? The issue is still there and it's very anoying. 

Thanks!

**Comment by satya164** [comment]
Closing the bug as it cannot be reproduced by me.
