### ISSUE TITLE
Certain GTK applications have no border or shadow

### ISSUE THREAD

**Issue by DenWav** [numixproject/numix-gtk-theme#333]
I'm not sure what term I should use to describe them, but certain GTK applications which use the bigger title bar style don't have borders or shadows. This also makes it difficult to resize these windows.
![noborder](https://cloud.githubusercontent.com/assets/1332104/14481822/45cef05c-00fc-11e6-89e5-192382a0bf0a.png)

**Comment by megax** [comment]
gtk3.20 patch: https://github.com/shimmerproject/Numix/pull/321

**Comment by megax** [comment]
Fixed https://github.com/numixproject/numix-gtk-theme/commit/0671f999457e094bcd8258d12ac1e2298c8943b2. @DemonWav @lots0logs Issue close?
