### ISSUE TITLE
Invert checkbox/radiobutton

### ISSUE THREAD

**Issue by SammysHP** [numixproject/numix-gtk-theme#335]
The old version of Numix (and the GTK 2 style) uses red checkmarks/bullets for checkboxes/radiobuttons. The current version fills the element and draws a white icon. IMHO this is too dominant (see attached picture).

![20160413_170552](https://cloud.githubusercontent.com/assets/922874/14498258/03dc6ff0-019a-11e6-882f-3f17e417b2c2.png)

**Comment by megax** [comment]
@SammysHP Fixed menuitem and popover check/radio icon. Patch: https://github.com/shimmerproject/Numix/pull/337

**Comment by SammysHP** [comment]
This was fixed in menus (thanks!), but I prefer the inverted version also for other checkboxes/radiobuttons.

IMHO this is too much red / too dominant (the buttons really stand out against the rest). Another issue: The margin to the text is missing.

![20160414_095945](https://cloud.githubusercontent.com/assets/922874/14521104/0e6d8448-0228-11e6-9fa4-c705078693a5.png)

**Comment by SammysHP** [comment]
Comparison with gtk 2 style:

![20160414_121645](https://cloud.githubusercontent.com/assets/922874/14524856/d16e5f8c-023a-11e6-8439-6cad1a58ebe9.png)

**Comment by SammysHP** [comment]
As you can see in https://github.com/shimmerproject/Numix/issues/335#issuecomment-209816936, the tabs are hard to recognize.

**Comment by SammysHP** [comment]
Introduced in https://github.com/shimmerproject/Numix/commit/bf32925cb7efe1f17887ada902ae5919d52440ce.

**Comment by SammysHP** [comment]
Can you please reopen this issue? The original issue is not fixed and I like to discuss which assets should be used. Personally I prefer the old assets (red checkmark/bullet on gray/white background) as explained above.

**Comment by khurshid-alam** [comment]
@SammysHP Old assets are not hi-dpi capable. Although we could use old assets only for checkbox and radio.

**Comment by satya164** [comment]
I prefer a filled checkbox.

**Comment by SammysHP** [comment]
@khurshid-alam That's not a problem because one can create new assets with the old design.

@satya164 Don't you think that this mass of red/orange is a bit too much?

**Comment by satya164** [comment]
@SammysHP I prefer controls to be a bit prominent. Since these kinds of controls appear only in things like configuration screens, this is not a problem, and actually improve the UX by increasing the visibility of controls. This is similar to how we style switches too.

**Comment by khurshid-alam** [comment]
@SammysHP Its not just hidpi issue, old assets doesn't blend at all with dark-variant.

**Comment by SammysHP** [comment]
Sorry, but I cannot accept that answer. The current assets are 16x16 px PNGs. Don't tell me that these are "hi-dpi capable". The SVGs in the assets directory are different images. In fact, they seem to be the old version.

**Comment by SammysHP** [comment]
Here is a quick draft:

Current version:

![assets-old](https://cloud.githubusercontent.com/assets/922874/15388518/93dde92e-1db2-11e6-9f7e-08e24ca72d9f.png)

Proposed version:

![assets-new](https://cloud.githubusercontent.com/assets/922874/15388517/93bbbdfe-1db2-11e6-82e7-5f8e4b18c3fd.png)
