### ISSUE TITLE
Bundle multiple GTK versions in same package

### ISSUE THREAD

**Issue by RohanVilloth** [numixproject/numix-gtk-theme#343]
Since GTK 3.16, there can be multiple versioned theme folders. That is, there can be multiple directories named like `gtk-3.20`, `gtk-3.18`, `gtk-3.16`, etc instead of a single `gtk-3.0` directory. For example, GTK 3.20 will search for `gtk.css` in the directories `gtk-3.20`, ...,`gtk-3.14` and `gtk-3.0`. See: https://git.gnome.org/browse/gtk+/tree/gtk/gtkcssprovider.c#n2014

This is very useful for updating theme packages and adding support for new GTK versions without breaking previous ones. For eg: Ubuntu 16.04LTS provides GTK3.18 'out of box'. But some users upgrade to GTK3.20 from GNOME Staging PPA. With multiple versioned themes, there won't be a breakage anymore. :relaxed: 

However, there's a minor hurdle in the way: GNOME Tweak Tool 3.18 can't recognize versioned themes. :flushed: See these issues: https://github.com/tista500/Adapta/issues/40 , https://github.com/tista500/Adapta/issues/27 and https://github.com/solus-project/budgie-desktop/issues/405 . But I think it can be workarounded by providing `gtk-3.0` as a symlink to current GTK theme version. :relieved: Haven't tested it though. But the good news is: GNOME Tweak Tool 3.20 fixed this issue. So maybe 3.18'll get it backported in a maintainance release. :relaxed:

**Comment by RohanVilloth** [comment]
I just checked the package from Numix PPA: https://launchpad.net/~numix/+archive/ubuntu/ppa and saw that it already uses multiple versioned themes. I should've checked before complaining. I feel so stupid now! :sweat_smile:

Though this bug report was a complete fail, I learned that providing `gtk-3.0` folder will workaround GNOME Tweak Tool 3.18's bug. :grin:

**Comment by khurshid-alam** [comment]
@HEXcube Exactly!
