### ISSUE TITLE
ArchBlue Theme 3.20

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [numixproject/numix-gtk-theme#349]
I am on Arch with ArchBlue theme installed in AUR, and I found there is an update today. After I upgraded to 3.20, it will make my background to white and the title bar, toolbar of apps it's more bigger than the theme before(in 3.18).

**Comment by lots0logs** [comment]
Do you see the same when you use the non modified version of Numix? Could you post a screenshot?

**Comment by SammysHP** [comment]
> it will make my background to white

Which background? Are you sure that it's the theme and not a changed wallpaper setting in Gnome 3.20?

> and the title bar, toolbar of apps it's more bigger than the theme before

That's the "new" style of Numix. The last official release was 2014, the redesigned version has lots of differences. (I prefer the old version myself, but it doesn't work anymore with gtk 3.20.)

**Comment by seihtam** [comment]
I can confirm, the same happened to me after upgrading to gtk 3.20. I'm also using the ArchBlue theme but the same thing is happening with the unmodified theme.
Is this really the new style? Everything is way too big, eclipse didn't look like this at all before i upgraded gtk.
![screenshot_20160429_102236](https://cloud.githubusercontent.com/assets/9626003/14911287/bbd26324-0df4-11e6-9758-9992da4c5611.png)

**Comment by SammysHP** [comment]
Yes, that is the new button padding which I (kind of) "fixed" in #354.

**Comment by khurshid-alam** [comment]
That because eclipse by default calls for `GTK_ICON_SIZE_SMALL_TOOLBAR` when setting icon size which is set to 16x16. As a result it looks that way. We could go back to old button padding.

**Comment by megax** [comment]
@khurshid-alam Still having trouble?
