### ISSUE TITLE
Various warnings

### ISSUE THREAD

**Issue by SammysHP** [numixproject/numix-gtk-theme#351]
Here some warnings when starting _gthumb_:

```
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk.css:158:192: '_text_shadow_color' is not a valid color name
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk.css:1609:39: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk.css:1609:77: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk.css:3232:39: 'linear-gradient' is not a valid color name
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk.css:3237:41: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk.css:3237:53: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk.css:3244:35: 'border_disabled' is not a valid color name
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:158:193: '_text_shadow_color' is not a valid color name
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1609:39: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1609:77: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1999:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3229:39: 'linear-gradient' is not a valid color name
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3233:41: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3233:53: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3240:35: 'border_disabled' is not a valid color name
(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3888:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version
```

**Comment by megax** [comment]
Done:
`(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk.css:158:192: '_text_shadow_color' is not a valid color name`
bug source: https://github.com/numixproject/numix-gtk-theme/blob/a0736e4c8bde17bee2eff1e394e1587fe7fbccb1/gtk-3.20/scss/widgets/_button.scss#L21
`(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk.css:1609:39: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.` (old format code)
bug source: https://github.com/numixproject/numix-gtk-theme/blob/150fda02b51fdb856efc17d6abbf8ef7b7a33b0c/gtk-3.20/scss/widgets/_menu.scss#L117
`(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1999:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version` (old format code)
bug source: https://github.com/numixproject/numix-gtk-theme/blob/a0736e4c8bde17bee2eff1e394e1587fe7fbccb1/gtk-3.20/scss/widgets/_misc.scss#L147
`(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3240:35: 'border_disabled' is not a valid color name`
bug source: https://github.com/numixproject/numix-gtk-theme/blob/a0736e4c8bde17bee2eff1e394e1587fe7fbccb1/gtk-3.20/scss/widgets/_view.scss#L210
`(gthumb:6740): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3229:39: 'linear-gradient' is not a valid color name`
bug source: https://github.com/numixproject/numix-gtk-theme/blob/a0736e4c8bde17bee2eff1e394e1587fe7fbccb1/gtk-3.20/scss/widgets/_view.scss#L185

**Comment by megax** [comment]
All warning fix: https://github.com/numixproject/numix-gtk-theme/pull/367
