### ISSUE TITLE
Resize grip in Firefox

### ISSUE THREAD

**Issue by SammysHP** [numixproject/numix-gtk-theme#352]
The resize icon is only a horizontal line.

Example: http://www.w3schools.com/cssref/tryit.asp?filename=trycss3_resize

**Comment by lots0logs** [comment]
I don't think that icon is handled by themes. Could you check to see if the result is different when using the default Adwaita theme?

**Comment by SammysHP** [comment]
Adwaita has nothing at all. Example:

---

![20160416_233729](https://cloud.githubusercontent.com/assets/922874/14583774/ad22f0cc-042c-11e6-9bef-d14f767994d8.png)

---

I think it is a combination of two issues:
- Numix has an extra border-top somewhere
- Firefox uses some strange (custom) widget

With Adwaita there is nothing, but there should be something.

```
<div style="width: 346px; height: 94px;">
    Let the user resize both the height and the width of this div element.
    <scrollbar increment="45" pageincrement="309" maxpos="0" disabled="true" curpos="0" clickthrough="always" orient="horizontal">…</scrollbar>
    <scrollbar increment="51" pageincrement="107" maxpos="0" disabled="true" curpos="0" clickthrough="always" orient="vertical">…</scrollbar>
    <scrollcorner></scrollcorner>
    <resizer clickthrough="always" element="_parent" dir="bottomend"></resizer>
</div>
```

```
resizer {
    -moz-appearance: resizer;
    background: url("chrome://global/skin/icons/resizer.png") no-repeat;
    background-size: 100% 100%;
    cursor: se-resize;
    width: 15px;
    height: 15px;
}

resizer {
    -moz-binding: url("chrome://global/content/bindings/resizer.xml#resizer");
    position: relative;
    z-index: 2147483647;
}
```

**Comment by lots0logs** [comment]
I get the same result as Adwaita with Numix and gtk 3.20 (which is nothing). Obviously that's a bug, but I'm not sure its a theme bug. Did you notice any reports of the issue upstream (gtk and/or firefox)?

**Comment by SammysHP** [comment]
This is how it looks with Numix:

---

## ![20160417_113940](https://cloud.githubusercontent.com/assets/922874/14586207/2a4e5000-0491-11e6-8db7-f6f7da451bf3.png)

Nevertheless I'll close it for the time being. There are also other issues in Firefox with gtk-3.20 (e.g. scrollbars) and it works on GitHub. Example:

---

## ![20160417_114328](https://cloud.githubusercontent.com/assets/922874/14586221/9fce0046-0491-11e6-89f8-2e818a10b4e4.png)

**Comment by satya164** [comment]
This is called resize grip, and we should be able to remove it or show it. Not sure/don't remember if we can change it though.
