### ISSUE TITLE
Calendar Categories in Thunderbird via Lightning Extension are blackened out

### ISSUE THREAD

**Issue by MPE2016** [numixproject/numix-gtk-theme#355]
Dear people at Numix,

Unlikely as it may seem, I think I have actually found a bug in your GTK theme:)

The categories in de Lightning Calendar in Thunderbird are blackened out. See the attachment for further detail. 

I am otherwise a very happy user of both your icons and GTK theme!

Kindest regards,

MPE

![selectie_002](https://cloud.githubusercontent.com/assets/15818884/14585987/2df74a52-0489-11e6-96f6-297783fba939.png)

**Comment by SammysHP** [comment]
This should be fixed already in master.

**Comment by MPE2016** [comment]
What is master?

Op 18-04-16 om 07:54 schreef SammysHP:

**Comment by SammysHP** [comment]
The development branch. You must update the package. And please tell us the name of you distribution and the version of Thunderbird and Numix.

**Comment by MPE2016** [comment]
Ubuntu 14.04
Thunderbird 38.6.0
I have no idea where I can check the Numix version.

If I update, nothing changes.

Op 18-04-16 om 09:54 schreef SammysHP:

**Comment by SammysHP** [comment]
How did you install Numix? But 14.04 should not have gtk 3.20.

**Comment by MPE2016** [comment]
Via the ppa:
ppa.launchpad.net/numix/ppa/ubuntu

Op 18-04-16 om 14:50 schreef SammysHP:

**Comment by SammysHP** [comment]
Just tested, I can reproduce it.

**Comment by MPE2016** [comment]
Glad to hear it:)

Op 19-04-16 om 20:27 schreef SammysHP:

**Comment by khurshid-alam** [comment]
Is this still happening with Thunderbird 45 which was ported to gtk3?

**Comment by MPE2016** [comment]
I can't tell for Thunderbird 45, as I am using Thunderbird 38.7.2, under 
which the problem still persists however.

Op 11-05-16 om 12:40 schreef Khurshid Alam:

**Comment by megax** [comment]
@MPE2016 Still having trouble?

**Comment by MPE2016** [comment]
None at all, I forgot closing it. It is now closed

Op 26-09-16 om 13:46 schreef Csaba Jakosa:

**Comment by megax** [comment]
Thanks you :)

**Comment by MPE2016** [comment]
thanks for reminding me:)

Op 26-09-16 om 13:53 schreef Csaba Jakosa:
