### ISSUE TITLE
GTK 3.20

### ISSUE THREAD

**Issue by wavexx** [numixproject/numix-gtk-theme#356]
In Debian Unstable we just got an updated GTK (3.20), and it seems that the GTK folks decided to break themes (again... sigh).

Starting LibreOffice (or any GTK3 program) with GTK 3.20 results in numerous warnings (see #351). But LibreOffice in particular results completely broken (menus and toolbars are blank, missing icons, etc) due to the parsing errors.

**Comment by khurshid-alam** [comment]
@wavexx There is no need to create a separate issue for the same problem. Please leave comments on #351
