### ISSUE TITLE
Scrollbar margin inconsistency

### ISSUE THREAD

**Issue by SammysHP** [numixproject/numix-gtk-theme#357]
The scrollbar has a different margin in the hovering state which results in different dimensions and jumping containers. Also the roundness is lost and the border is too thick IMHO during hovering.

Example from gtk3-widget-factory:

![scrollbar](https://cloud.githubusercontent.com/assets/922874/14586421/04e361b4-0498-11e6-981c-8373c983eeac.gif)

**Comment by satya164** [comment]
Can you send a PR to fix this? :D

**Comment by SammysHP** [comment]
I already started to debug this and ended in deleting the whole file. :D Doing it from scratch might be easier. Negative margins can create quite a mess usually.

@megax was the last editor and introduced the negative margins. Maybe he has an idea.

**Comment by megax** [comment]
@SammysHP Fixed code, please test.

Minimal style change to old numix style.

**Comment by SammysHP** [comment]
Currently I'm working on a different proposal.

Can someone explain why there is a negative margin? For my proposal I started from scratch and I didn't need it yet. I'll still need some minutes (maybe up to an hour) to finish my draft.

---

Quick update: Scrollbars are working fine, but I still have problems with the buttons. They are disabled by default, but I want to integrate them in case someone overrides the default and enables them.

**Comment by SammysHP** [comment]
Update: Everything works, tested the modifications of #361 a few hours and it looks good in all programs that I used. Even the steppers are usable in case someone enables them via a custom gtk.css.
