### ISSUE TITLE
[gtk 3.20] gnome terminal scrollbar has light colors

### ISSUE THREAD

**Issue by arximboldi** [numixproject/numix-gtk-theme#359]
Hi!

Normally the Gnome Terminal would have dark colors. Sadly, this is not the case in gtk 3.20. Here is an example screenshot highlighting the problem.

![screenshot](https://cloud.githubusercontent.com/assets/1887387/14465063/cc45de64-00d1-11e6-9f8b-a1d9fefdaee5.png)

Thanks!

JP

**Comment by arximboldi** [comment]
Failed workaround: set `gtk-application-prefer-dark-theme = false` in the gnome-terminal `settings.ini`, or use the environment variable `GTK_THEME`. It seems gnome terminal, at least in Debian, does not give a fuck about the selected theme variant :(

This is sad, because actually this app would benefit a lot from a dark theme...

**Comment by khurshid-alam** [comment]
@arximboldi Terminal or vte background (if that's what you meant) should always remain dark  (by default) irrespective of theme-variant, just like eog,videos. This is intentional and desired feature. However, some other elements/widgets (popover, switches, notebook tabs, borders...etc) should change with  dark/light theme variant. Its just that all these changes hasn't been landed yet.

Meanwhile, you can change dark background from terminal preferences with custom profile.

**Comment by arximboldi** [comment]
@khurshid-alam sorry if my further comments confused the bug report, but the **scrollbar** should be always dark AFAIK (it is in every Numix version before Gtk 3.20). As the screenshot shows, the scrollbar is not dark in the current master for Gtk 3.20, so probably the issue should be reopened.

Thanks!

JP

**Comment by khurshid-alam** [comment]
Scrollbar issue is a bug which is tracked here #357

**Comment by arximboldi** [comment]
#357 is about scrollbar _margins_. #359 is about the gnome terminal specific scrollbar _colors_, as specified in `gtk-3.20/scss/apps/_gnome-terminal.scss`. The colors specified in that file (which I guess were simply copied from `gtk-3.0`) are having no effect. I still believe it is a different issue.

**Comment by arximboldi** [comment]
@khurshid-alam sorry I just realizad that the text I wrote for the bug report was wrong: I wrote that Gnome Terminal normally would have light colors, but actually I meant the opposite! Just edited the text, I hope you are happy now to reopen the bug. Thanks!

**Comment by khurshid-alam** [comment]
Ok. Reopened!

**Comment by arximboldi** [comment]
Just found a workaround, yeah!

The problem why I could not set a dark theme for gnome terminal is that the actual window is created by the `gnome-terminal-server`, which runs in the background all the time.

A solution was to add to my `Xsession` script:

> ```
> GTK_THEME=Numix:dark /usr/lib/gnome-terminal/gnome-terminal-server
> ```

In order to explicitly launch the server in the background on start.

**Comment by arximboldi** [comment]
Ofc, this workaround does not fix the original bug though, but it is ok for those that would like to have a darker `gnome-terminal` overall...

**Comment by SammysHP** [comment]
I just installed gnome-terminal and it had a white background. I went to _Edit → Preferences_ and _Variant_ was set to _Default_ (which was _light_ obviously). I selected _light_, no change. I selected _dark_ and I got dark background **and** dark scrollbar. So everything is fine IMHO.

![20160423_201510](https://cloud.githubusercontent.com/assets/922874/14763247/40f5bc90-0990-11e6-875b-b57995c69038.png)

![20160423_201528](https://cloud.githubusercontent.com/assets/922874/14763248/40f9b37c-0990-11e6-9028-2caf9a4f5b89.png)

edit: This was tested with #357 merged.

**Comment by arximboldi** [comment]
@SammysHP what distro are you using? I thought that the dark variant in the menus is a patch that is maintained indepently in some distros but not in the main gnome terminal (not in the one in Debian, for example, but the trick I showed is a workaround)

**Comment by SammysHP** [comment]
@arximboldi Arch Linux with Numix from this repo. No Gnome session running.

**Comment by khurshid-alam** [comment]
@SammysHP This issue is about terminal scroll-bar color and not about background which in a way gets fixed with #361. 

About background, well, its a separate issue. Terminal style needs to be ported for 3.20. And we may use dark background for light variant and even darker background for dark variant.

**Comment by SammysHP** [comment]
@khurshid-alam But the scrollbar color is consistent with the background color in my screenshots.

**Comment by megax** [comment]
@khurshid-alam https://github.com/horst3180/vertex-theme/issues/173

**Comment by khurshid-alam** [comment]
@SammysHP Yes. For now it works. I will merge #361 tomorrow. Thanks.

@megax Ohk. I think it is broken due to changes in libvte...anyway I will take a look later.

**Comment by megax** [comment]
@khurshid-alam gnome-terminal master: https://github.com/GNOME/gnome-terminal/commit/13a7c920b2250e9295fa10cee88bacc39d9f2612#diff-428488447e0566e404dff2af333e083dR2836
https://bugzilla.gnome.org/show_bug.cgi?id=765590

**Comment by khurshid-alam** [comment]
@megax I see they fixed it now. Feel free to open a PR.

**Comment by megax** [comment]
@khurshid-alam https://github.com/numixproject/numix-gtk-theme/pull/429

Notebook tab color change osd background? :)

**Comment by khurshid-alam** [comment]
@megax Yes. Terminal notebook tab needs rewrite. This is how it used to look:

![old-terminal](http://i.imgur.com/KxU6OSB.png)

**Comment by lots0logs** [comment]
@khurshid-alam Don't you find that is too much black for the non-dark version of the theme? :grimacing:

**Comment by khurshid-alam** [comment]
@lots0logs Probably yes (the screenshot is old and using old darker scheme). But we use dark terminal even for light version. Gnome does the same for their photos & videos (totem) app. We once tried to make terminal light for light variant but nobody preferred that.  So we changed it back to dark.

The thing is, we don't really have proper support for dark variant so that apps like videos, photos and terminal can look and blend well for both variant.

So you want to keep it as it is.....default light notebook tab for dark terminal?

**Comment by megax** [comment]
@khurshid-alam, @lots0logs
**Test code:**

```
        notebook {
            > header {
                border-color: border_normal($osd_base);
                background-color: $osd_base;

                button { @include button($osd_bg, $osd_fg); }

                tab {
                    &:hover {
                        background-color: shade($osd_base, .8);

                        &:checked { background-color: mix($osd_bg, $osd_base, .4); }
                    }

                    &:checked:hover { background-color: mix($osd_bg, $osd_base, .4); }

                    label { color: $osd_fg; }
                }

                &.top tab {
                    border-color: border_normal($osd_base);

                    &:hover {
                        border-bottom-color: shade($osd_base, .4);

                        > box, > label { border-bottom-color: shade($osd_base, .4); }
                    }

                    &:checked {
                        border-bottom-color: $selected_bg_color;

                        > box, > label { border-bottom-color: $selected_bg_color; }

                        label { color: $selected_bg_color; }

                        &:hover { background-color: mix($osd_bg, $osd_base, .3); }
                    }
                }
            }
        }
```

![anim](https://cloud.githubusercontent.com/assets/461493/15184599/1e044742-1796-11e6-9fe0-6e84efbad42d.gif)

_Edit_

**Test code 2:**

```
        notebook {
            > header {
                border-color: border_normal(shade($osd_base, .8));
                background-color: shade($osd_base, .8);

                button { @include button($osd_bg, $osd_fg); }

                tab {
                    &:hover {
                        background-color: shade($osd_base, .8);

                        &:checked { background-color: mix($osd_bg, $osd_base, .4); }
                    }

                    &:checked:hover { background-color: mix($osd_bg, $osd_base, .4); }

                    label { color: $osd_fg; }
                }

                &.top tab {
                    border-color: border_normal($osd_base);

                    &:hover {
                        border-bottom-color: shade($osd_bg, 1.2);

                        > box, > label { border-bottom-color: shade($osd_bg, 1.2); }
                    }

                    &:checked {
                        background-color: $osd_base;
                        border-bottom-color: $selected_bg_color;

                        > box, > label { border-bottom-color: $selected_bg_color; }

                        label { color: $selected_bg_color; }

                        &:hover { background-color: $osd_base; }
                    }
                }
            }
        }
```

![anim](https://cloud.githubusercontent.com/assets/461493/15194353/ca25d21c-17c2-11e6-8d52-3ff815a2fed9.gif)

**Comment by SammysHP** [comment]
@khurshid-alam 

> The thing is, we don't really have proper support for dark variant so that apps like videos, photos and terminal can look and blend well for both variant.

Numix (at least in 3.20) has support for light and dark theme. Your screenshot obviously shows the dark variant.

This is an example of the current version of Numix:

**light:**

![20160511_171207](https://cloud.githubusercontent.com/assets/922874/15185999/964bbeec-179b-11e6-9b57-ffb6c28cf97d.png)

**dark:**

![20160511_171212](https://cloud.githubusercontent.com/assets/922874/15186000/965703ba-179b-11e6-9c4f-5835f7ef1ee8.png)

You can select the style in _Edit → Preferences → Variant_.

**Comment by megax** [comment]
@khurshid-alam I create PR?
- Test code
- Test code 2
  ?

**Comment by khurshid-alam** [comment]
I am yet to test your code. Beside I am thinking of disabling custom terminal style as we don't need that anymore as pointed out by @SammysHP.

**Comment by megax** [comment]
Okay :)
