### ISSUE TITLE
Theme parsing error

### ISSUE THREAD

**Issue by gjm** [numixproject/numix-gtk-theme#36]
Hi. I get this error in my logs:

Theme parsing error: gtk-widgets.css:1566:20: Missing name of pseudo-class

I'm using Ubuntu 13.04.

**Comment by yusiwen** [comment]
I got the same warning in my 13.04 too.

check the css file, and found this in line 1566:
.spinbutton .button:dir(rtl) {

is there some problems?

**Comment by satya164** [comment]
It's due to a new pseudo class added in GTK 3.8. Everything should work fine in GTK 3.6. Just ignore the warning.
