### ISSUE TITLE
Active tab in Nautilus is not visible clearly

### ISSUE THREAD

**Issue by uloco** [numixproject/numix-gtk-theme#364]
When I open multiple tabs in nautilus, it is really hard to distinguish, which tab is active.
There was a thin orange line in the past on the bottom border, how about introducing it again?

I installed this on 16.04 through the ppa.

**Comment by SammysHP** [comment]
I can still see the orange line.

**Comment by uloco** [comment]
![numix-screen](https://cloud.githubusercontent.com/assets/8818340/14655931/091e88d2-0685-11e6-9be1-e09781507962.png)

**Comment by SammysHP** [comment]
Which version of Numix do you use? It was fixed some days ago.

**Comment by uloco** [comment]
I installed it via ppa on 16.04. So please update the ppa

**Comment by acutbal** [comment]
I use this version 2.4ubuntu1+422~201604182216~ubuntu15.10.1 and I don't see the line to distinguish the active tab.

Regards!! :smile:

**Comment by uloco** [comment]
```
Package: numix-gtk-theme
Priority: optional
Section: gnome
Installed-Size: 500 kB
Maintainer: Satyajit Sahoo <satyajit.happy@gmail.com>
Version: 2.3+298~201405050951~ubuntu14.04.1
Depends: gtk2-engines-murrine (>= 0.90.3+git20100810)
Download-Size: 44,6 kB
APT-Sources: http://ppa.launchpad.net/noobslab/themes/ubuntu/ trusty/main i386 Packages
Description: Numix GTK Theme
 Numix is a modern flat theme with a combination of light and dark elements.
```

**Comment by SammysHP** [comment]
![20160420_115024](https://cloud.githubusercontent.com/assets/922874/14670632/399feb4a-06ee-11e6-8f79-d630b500b5e0.png)

@acutbal Looking at the date that package should include the fix. But I'm not responsible for the PPA and don't know what it includes exactly.

@uloco That looks really old, in fact that shouldn't work with gtk 3.20 at all.

**Comment by acutbal** [comment]
@SammysHP Ok, thank you very much for the info!! :smile:  Tomorrow Canonical releases Ubuntu 16.04, I'll see if the fix is included. 

Best regards!!

**Comment by SammysHP** [comment]
I think you'll need at least the PPA.

**Comment by uloco** [comment]
Sorry, this is the wrong package, I'm on my old laptop. Will update information later

**Comment by acutbal** [comment]
For Ubuntu 16.04 LTS is ready:

![captura de pantalla de 2016-04-20 12-22-47](https://cloud.githubusercontent.com/assets/2278584/14671563/c0b4bd28-06f2-11e6-9bce-e339e76b1b90.png)

Regards!! :smile:

**Comment by acutbal** [comment]
For Ubuntu 16.04 the PPA is ready:

![captura de pantalla de 2016-04-20 12-25-19](https://cloud.githubusercontent.com/assets/2278584/14671612/04472f44-06f3-11e6-9a6d-0950dee8db95.png)

Regards!! :smile:

**Comment by uloco** [comment]
Cool thank you ,  I will update in the evening!

**Comment by acutbal** [comment]
@uloco  Just in case... This is the official PPA for Numix:
ppa:numix/ppa 
https://launchpad.net/~numix/+archive/ubuntu/ppa

Better this one than the Noobslab PPA.

Regards!! :smile:

**Comment by khurshid-alam** [comment]
Notebook tabs are redesigned for 3.20 and not for 3.18

**Comment by uloco** [comment]
I did the update, but tabs are still buggy...

`sudo dpkg -l | grep numix`

```
ii  numix-gtk-theme                             2.4ubuntu1+422~201604182217~ubuntu16.04.1           all          Numix GTK Theme
rc  numix-icon-theme                            0.3+790~201604120032~ubuntu16.04.1                  all          Numix icon theme
rc  numix-icon-theme-circle                     1.0.2+5~201511012129~ubuntu16.04.1                  all          Numix Circle icons
```

`$  apt -a show numix-gtk-theme`

```
Package: numix-gtk-theme
Version: 2.4ubuntu1+422~201604182217~ubuntu16.04.1
Priority: optional
Section: gnome
Maintainer: Satyajit Sahoo <satyajit.happy@gmail.com>
Installed-Size: 3.131 kB
Depends: gtk2-engines-murrine (>= 0.98)
Download-Size: 131 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/numix/ppa/ubuntu xenial/main amd64 Packages
Description: Numix GTK Theme
 Numix is a modern flat theme with a combination of light and dark elements.

Package: numix-gtk-theme
Version: 2.1.2-0ubuntu1
Priority: optional
Section: universe/x11
Source: shimmer-themes
Origin: Ubuntu
Maintainer: Xubuntu Developers <xubuntu-devel@lists.ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1.711 kB
Depends: gtk2-engines-murrine (>= 0.98)
Suggests: xfwm4 | metacity, xfce4-notifyd
Breaks: shimmer-themes (<< 1.8.0)
Replaces: shimmer-themes (<< 1.8.0)
Homepage: http://shimmerproject.org/
Task: xubuntu-core, xubuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntu-gnome-desktop
Supported: 3y
Download-Size: 87,9 kB
APT-Sources: http://de.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Description: Numix GTK2 and GTK3 themes
 This package contains the Numix GTK+ theme from Shimmer Project.
 Numix is a modern flat theme with a combination of light and dark
 elements.
```

EDIT: @khurshid-alam Ah, you mean the GTK version... So what am I supposed to do, to get this working in the Unity desktop on 16.04? Is there any plans to fix this for gtk 3.18, too?

**Comment by khurshid-alam** [comment]
@uloco Perhaps you didn't read my previous comment. https://github.com/numixproject/numix-gtk-theme/issues/364#issuecomment-212452711

**Comment by uloco** [comment]
@khurshid-alam I edited my comment above....

**Comment by khurshid-alam** [comment]
@uloco It will probably be fixed in the next release (not in next update). It is being tracked in #300
