### ISSUE TITLE
Forking numix-gtk-theme in shimmerproject

### ISSUE THREAD

**Issue by sspreitzer** [numixproject/numix-gtk-theme#365]
Hi @satya164, @ochosi and @bluesabre 

Thanks for moving the Numix Gtk theme into the numixproject organization. Can you be so kind and fork it into the shimmerproject organization and disable issues and pull requests?
People then can find and see where the repo has moved and that issues and pull requests of it are handled in the new place.

Thank you
Sascha

**Comment by lots0logs** [comment]
That actually should not be necessary. When you try to access the old repo it will automatically redirect to the new one.

**Comment by sspreitzer** [comment]
Ah that is very handy! Tested it, working fine!
