### ISSUE TITLE
Numix Dark

### ISSUE THREAD

**Issue by sspreitzer** [numixproject/numix-gtk-theme#366]
Hi

Just wanted to ask if there is a need for a Numix theme that is optimized for darker desktops?
And how much effort it is to to create it (small deviations or huge ones) ?

Kind regards
Sascha

**Comment by SammysHP** [comment]
I thought that Numix already has a dark version (at least for gtk3).

**Comment by sspreitzer** [comment]
What, really? Okay then I have not found out yet how to turn it on for Xfce?

**Comment by SammysHP** [comment]
Just try it:

```
$ GTK_THEME=Numix:dark gtk3-widget-factory
```

**Comment by sspreitzer** [comment]
Wow! That is really nice! Thats working, cool. Thanks!
