### ISSUE TITLE
[Feature Request] Budgie support

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#368]
Will be great to have Numix native styling for the [Budgie](https://solus-project.com/budgie) Desktop :smile: 

You can find how to theme Budgie looking at the [Vertex](https://github.com/horst3180/vertex-theme/search?utf8=%E2%9C%93&q=budgie) code :smile:.

**Comment by Foggalong** [comment]
Just as a point of info: if we can get this done then having a Numix style switch shipped in the [Ubuntu Budgie](http://budgie-remix.org/) variant welcome app is a very real possibility

**Comment by megax** [comment]
Related issue: https://github.com/numixproject/numix-gtk-theme/issues/620

**Comment by khurshid-alam** [comment]
Basic budgie support ( raven panel) has already landed. It needs code block for sidebar and some othe components. Hopefully soon.
