### ISSUE TITLE
Openbox theme colors

### ISSUE THREAD

**Issue by maxer456** [numixproject/numix-gtk-theme#369]
Colors used in the Openbox theme seem to be out of date (darker backgrounds, lighter selected colors) compared to the Gtk2/3 themes. As a result, apps don't fit with the wm as wel as they used to. Take a look at these screenshots:
Gtk2 PCManFM
![PCManFM in Openbox](https://cloud.githubusercontent.com/assets/8107484/14675191/14107b8c-0708-11e6-95a9-0562f914ef74.png)
Gtk3 Firefox
![Mozilla Firefox in Openbox](https://cloud.githubusercontent.com/assets/8107484/14675250/5eec0e82-0708-11e6-8f3b-cb7952bb6635.png)
Openbox menu looks like this:
![Openbox menu](https://cloud.githubusercontent.com/assets/8107484/14675293/9e80585a-0708-11e6-9d8c-548271edd57c.png)

**Comment by ghost** [comment]
just open hour themerc and replace #333333 with #444444

**Comment by megax** [comment]
@lisdonk you could send PR?

**Comment by megax** [comment]
@khurshid-alam, @lots0logs Fixed: https://github.com/numixproject/numix-gtk-theme/pull/603
