### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by gjm** [numixproject/numix-gtk-theme#37]
I've found some issues in 1.5.0:

File roller open dialog:

![file-roller_open](https://f.cloud.github.com/assets/77360/577928/96d5c5d2-c844-11e2-922e-9473ea898c91.png)

Rhythmbox (black bar in browser):
![rhythmbox](https://f.cloud.github.com/assets/77360/577932/b0c07f50-c844-11e2-9beb-f9145fb1472d.png)

**Comment by satya164** [comment]
These issues are due to overlay-scrollbars. Uninstall or disable overlay-scrollbars to fix the problems.
