### ISSUE TITLE
Highlight of focused button

### ISSUE THREAD

**Issue by SammysHP** [numixproject/numix-gtk-theme#370]
It is not easily visible which button is focused.

![20160420_213352](https://cloud.githubusercontent.com/assets/922874/14687944/48ddec72-0740-11e6-9723-6d6bf60f3fda.png)

In this case it is the delete/Löschen button which has a slight shadow.

**Comment by megax** [comment]
@lots0logs you got something? :)

**Comment by khurshid-alam** [comment]
What happen when you press `tab`? A fine outer border should appear.

**Comment by SammysHP** [comment]
@khurshid-alam It switches between the two buttons. In the screenshot you can see both states.
