### ISSUE TITLE
gnome 3.20 firefox aurora checkbox borders missing, scrollbar indicator missing

### ISSUE THREAD

**Issue by wmcmillian-coalmarch** [numixproject/numix-gtk-theme#372]
![selection_028](https://cloud.githubusercontent.com/assets/10234084/14710032/bb2e0292-07a1-11e6-8ce0-cebb1f04a5b9.png)

![selection_029](https://cloud.githubusercontent.com/assets/10234084/14710048/d468899e-07a1-11e6-82e4-2ca8f52e2eeb.png)

**Comment by wmcmillian-coalmarch** [comment]
This is most likely related strictly to firefox (probably gtk2). The border indicator seems to work on other windows

**Comment by SammysHP** [comment]
The checkbox icons are not from Numix and the scrollbar looks different too. I assume that Firefox uses custom resources.

**Comment by Yepoleb** [comment]
It's related to the recent switch to gtk3. I have the same problem with other themes, so it's most likely a Firefox bug.

**Comment by neclimdul** [comment]
Agreed it seems something outside this theme as I see it in I see it with Adwaita as well. Unfortunately this is the top Google result... has any found or filed an upstream issue they could drop a link to?

I also didn't need Aurora to recreate this. Its happening in the stable version 46 which seem to be where "GTK3 Integration" was added.

**Comment by neclimdul** [comment]
I posted that after spending half an hour digging through different searches and posts and of course 20m minutes later I find a link deep in a reddit thread that is exactly that. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1262136

**Comment by Gallandaluz** [comment]
I confirm the fix in Firefox 48. Do you?

**Comment by toupeira** [comment]
@MaycneSonahoz careful, Debian (and I assume most of its derivatives) switched back to using Gtk+ 2 in their builds because of the known theming issues with Gtk+ 3.20. Are you sure you're in fact using a Gtk+ 3 build?

References:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822807
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832301

**Comment by Gallandaluz** [comment]
@toupeira I'm on Manjaro (Arch derivative), which does use the GTK3 version.
https://www.archlinux.org/packages/extra/x86_64/firefox/

**Comment by megax** [comment]
https://github.com/horst3180/arc-theme/pull/473

**Comment by megax** [comment]
@khurshid-alam Please test. Checkbox code fix:

```
⚡ git diff
diff --git a/gtk-3.20/scss/widgets/_toggle.scss b/gtk-3.20/scss/widgets/_toggle.scss
index 61e00b8..fef3caa 100644
--- a/gtk-3.20/scss/widgets/_toggle.scss
+++ b/gtk-3.20/scss/widgets/_toggle.scss
@@ -47,6 +47,7 @@ $suffix: if($variant == "dark", "-dark", "");
 }
 
 @include exports("checkradio") {
+    .radio,
     radio {
         @include toggle("radio");
         min-width: 16px;
@@ -54,6 +55,7 @@ $suffix: if($variant == "dark", "-dark", "");
         margin-right: $spacing;
     }
 
+    .check,
     check {
         @include toggle("checkbox");
         min-width: 16px;
@@ -61,6 +63,7 @@ $suffix: if($variant == "dark", "-dark", "");
         margin-right: $spacing;
     }
 
+    .radio:dir(rtl), .check:dir(rtl),
     radio:dir(rtl), check:dir(rtl) {
         margin-right: 0;
         margin-left: $spacing;

```

**Comment by khurshid-alam** [comment]
Is this still reproducible with latest firefox?

**Comment by khurshid-alam** [comment]
Firefox is gtk-3 now.
