### ISSUE TITLE
Firefox tabs border's colors white

### ISSUE THREAD

**Issue by wadie** [numixproject/numix-gtk-theme#374]
The borders are white,right by the website's favicon and the close tab button,image link below.
Only in Firefox,Chromium is all good. :yum: 

![screenshot from 2016-04-22 01 16 39](https://cloud.githubusercontent.com/assets/1206307/14727107/4ff27076-0828-11e6-9d8b-3c1f1088bdde.png)

**Comment by SammysHP** [comment]
I'm sure this is (another) bug in Firefox.

**Comment by wadie** [comment]
I believe it has already been fixed.
![screenshot from 2016-04-22 12 21 15](https://cloud.githubusercontent.com/assets/1206307/14738920/bb414760-0884-11e6-9082-3f3720a7982c.png)

**Comment by wadie** [comment]
This issue seems to be back on Ubuntu 16.04

**Comment by megax** [comment]
@khurshid-alam Test? Firefox bug? =/

**Comment by khurshid-alam** [comment]
This happens only with Gtk-3.20? With Firefox <=48? Right?. I can't reproduce it on 3.18 on Ubuntu.

**Comment by lots0logs** [comment]
If that's the case I don't think we should worry about it as the latest version of Firefox is always available in all distributions (thus its the only version we need to support)

**Comment by megax** [comment]
@khurshid-alam I can not reproduce. I think not Numix bug.
