### ISSUE TITLE
Gray text color in menus

### ISSUE THREAD

**Issue by toupeira** [numixproject/numix-gtk-theme#38]
Here's a screenshot of the problem: http://i.imgur.com/URNLBoo.png

I use Xfce and the Gorilla theme for Gtk2 apps, but if I use the Gtk2 Numix theme as well the text color is fine in Gtk3 apps (i.e. it's white). So it seems the Gorilla Gtk2 theme is somehow interfering with the colors of the Numix Gtk3 theme, but I have no idea how to fix this. I don't have any custom Gtk settings as far as I know.

Incidentally, I found some other versions of Numix called "Numix-v2" and "Numix Dark Toolbar" which don't have this particular problem, but since they haven't been updated in a while they have other issues with Gtk 3.8.

**Comment by toupeira** [comment]
Just to clarify: this is different from issue #32, and also the problem is not that Gorilla's menu text color is used (which is black), but something entirely different (#555555).

**Comment by satya164** [comment]
Hmm... do you have this problem with any other themes?

**Comment by toupeira** [comment]
Not that I know of, all the themes I've tried have either a colored background or a border around focused checkboxes & radio buttons. I can also reproduce this issue on another machine with the Numix Gtk2 theme, so I don't think it's another setting influencing it.

**Comment by toupeira** [comment]
I just had another look and noticed that there _is_ actually a border, but it's white and therefore almost invisible :) Other borders on buttons, dropdowns etc. are red though.

**Comment by satya164** [comment]
I think you mistook this as another bug report!

**Comment by toupeira** [comment]
Hmm why do you think so? Not sure what you mean :)

Anyway, I had a look at the theme and was able to fix it by changing `bg[SELECTED]` for `murrine-radiocheck` to `@selected_bg_color` instead of `@base_color`, see https://github.com/toupeira/numix-gtk-theme/commit/a38eb37afd9d8f6d490af3e24f03d6acb82b726e

**Comment by satya164** [comment]
Coz there was another bug report about focus border in check boxes and this
is about text color in menu.

**Comment by toupeira** [comment]
Ah whoops sorry about that :) I only read the email text and stupidly assumed it was about the other issue.

**Comment by toupeira** [comment]
I'll check if the gray text issue occurs with other themes, but in the meantime I just switched my Gtk2 theme to Numix as well and have already grown used to it :)

**Comment by satya164** [comment]
Closing this issue as it is caused by mixing a different theme in Numix. So not necessarily a Numix issue.
