### ISSUE TITLE
[Feature Request] Mate-Panel support

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#380]
When I use numix-gtk-theme the applet turn grey instant of the numix color. 
Information about theming the mate panel: https://github.com/mate-desktop/mate-themes
Thanks in advance
![vm](https://cloud.githubusercontent.com/assets/15233968/14755309/abf9768a-08e1-11e6-8b5b-0eb85a06068a.png)

**Comment by megax** [comment]
Basic support: https://github.com/numixproject/numix-gtk-theme/pull/473

**Comment by XRevan86** [comment]
Merge request is for MATE built with Gtk3. On screenshot it seems to be Gtk2.
Numix already had MATE/Gtk2 support for years, so it can be closed… but not because of #473 :-).
