### ISSUE TITLE
[gtk3.20] Toolbar separator margin bug

### ISSUE THREAD

**Issue by megax** [numixproject/numix-gtk-theme#385]
Not margin (button separator)

Example:
![image](https://cloud.githubusercontent.com/assets/461493/14761470/f3b84768-0962-11e6-9b02-273cc03f93c1.png)

**Comment by megax** [comment]
@lots0logs Fixed bug :)

**Comment by lots0logs** [comment]
@megax Hmm..it still could use a bit more space on each side of the separators.

**Comment by megax** [comment]
How highly you think?

**Comment by lots0logs** [comment]
Lets add 2px to each side. That should be enough. Thanks.

**Comment by megax** [comment]
Done.
