### ISSUE TITLE
libreoffice toolbar boxes

### ISSUE THREAD

**Issue by tt123** [numixproject/numix-gtk-theme#39]
the texts are cut off by the toolbar boxes in libreoffice. thanks for your hard work. 
![screenshot - 06122013 - 07 12 09 pm](https://f.cloud.github.com/assets/3921268/646466/2fce7118-d3cf-11e2-93a0-378f05afa38f.png)

**Comment by ochosi** [comment]
Just fixed that here: https://github.com/shimmerproject/Numix/commit/6fbc55e2cf6de60db55507cf152dcfeed68f0570
Hopefully that doesn't break anything else.

**Comment by satya164** [comment]
Unfortunately it does break the combobox

![screenshot from 2013-06-22 11 15 55](https://f.cloud.github.com/assets/1174278/690534/45fdbc52-db02-11e2-9c39-4aa6d54af89d.png)

Notice the combobox widget and also how the button in the comboboxentry is larger by 1px.

**Comment by tt123** [comment]
Can you change the size of the button just like the way you changed the box? Sorry, I don't know a lot about creating theme.

**Comment by fitojb** [comment]
This is NOT a issue in Numix. It was fixed in LibreOffice itself: http://cgit.freedesktop.org/libreoffice/core/commit/?id=84f4b84212c1d3d27376a430d172f3382922f3f9

(This fix is available in LibreOffice 4.2)

**Comment by satya164** [comment]
@Fitoschido thanks for the info.
