### ISSUE TITLE
Unreadable sound control

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-gtk-theme#392]
Sound control is completely unreadable on hover effect.

Normal:
![screenshot from 2016-04-24 18-19-52](https://cloud.githubusercontent.com/assets/11137173/14768697/75853184-0a49-11e6-8c06-501e5d672dad.png)

Hover:
![screenshot from 2016-04-24 18-20-04](https://cloud.githubusercontent.com/assets/11137173/14768711/a0c566a2-0a49-11e6-9019-f01b2a86377c.png)

May I suggest to change the color of slider bar?

**Comment by khurshid-alam** [comment]
Feel free to open a PR.
