### ISSUE TITLE
Numix Frost Light Chrome Tab Colour Issue

### ISSUE THREAD

**Issue by andy-crouch** [numixproject/numix-gtk-theme#393]
I am running Antergos Gnome 3.20 and with the latest update of the numix themes I am getting a black bad running behind the tabs in Chrome.

I am running bang upto date (updates wise) and Gnome 3.20 with Chrome built from AUR.

![image](https://cloud.githubusercontent.com/assets/721911/14770028/7a68e67c-0a5e-11e6-91da-d776184d71a5.png)

Is this by design or an actual issue.  I could see no mention of it anywhere.

**Comment by joelostblom** [comment]
Same for me

**Comment by khurshid-alam** [comment]
Please deselect `Use system title bar and borders` if that fixes the issue you.

![screenshot-chromium](http://i.imgur.com/Sf6B5tw.png)

**Comment by joelostblom** [comment]
Tried that, the background is still black, it used to be lighter and go well with the title bar.

With system title bars.
![image](https://cloud.githubusercontent.com/assets/4560057/16172116/056d1fa2-354f-11e6-8ec2-7fabfbf41512.png)

Without system title bars.
![image](https://cloud.githubusercontent.com/assets/4560057/16172128/43e0ed7c-354f-11e6-82b0-cd0be3ec8966.png)
