### ISSUE TITLE
Huge toggle button

### ISSUE THREAD

**Issue by joaojotta** [numixproject/numix-gtk-theme#396]
I'm terrible sorry if this has been mentioned before (couldn't find any mention) but am I the only one seeing a huge toggle button after the GTK 3.20 update and after the theme's update?
Is it a design update?

![screenshot from 2016-04-25 23-59-52](https://cloud.githubusercontent.com/assets/11931285/14801609/80e83f54-0b42-11e6-9b05-a237e5ba2793.png)

I'm using Cinnamon under Arch and everything is up to date.

**Comment by lots0logs** [comment]
Yes, its an update in the toggle button's design. It looks like your font size is set lower than the default values for Cinnamon? That would make the toggle button appear disproportional to surrounding elements.

**Comment by joaojotta** [comment]
Well, I did change the default size to 9 and a different font but I've just checked it against a new user and the padding remains.
It's something to do with Cinnamon or the theme and it only started with the GTK 3.20 update (don't know what's the deal with it's huge buttons anyway).

If anyone could tell me where to tweak to get it back I'd appreciate it.

Thanks!!

**Comment by lots0logs** [comment]
Its the same height as the buttons. You can see it by comparing to the buttons at the top left of your screenshot. I'll look into it to see if there's a method by which we can get the height to be more proportionate to the text around it.

**Comment by joaojotta** [comment]
Then my search is for button size globally.
It's a desktop, not a Raspberry Pi with a 320x240 screen.

**Comment by bilelmoussaoui** [comment]
The toggle icons are really so huge... 
![capture du 2016-04-26 19-08-13](https://cloud.githubusercontent.com/assets/7660997/14827368/48c4bca6-0be2-11e6-821e-e68e0b4e8c08.png)

**Comment by megax** [comment]
@khurshid-alam what to do?
Now: ![image](https://cloud.githubusercontent.com/assets/461493/17868938/4a472ad8-68b1-11e6-96a0-8967c0359a32.png)

**Comment by khurshid-alam** [comment]
Let's c.

**Comment by megax** [comment]
**Minimal correction:**
![image](https://cloud.githubusercontent.com/assets/461493/17929471/0f8cf228-6a01-11e6-9569-9c75403ee5c3.png)

@khurshid-alam @lots0logs opinion?

**Comment by lots0logs** [comment]
I think its fine like it is now. At least on my system it is :stuck_out_tongue_winking_eye: 

![2016-08-24_07-10-28-am](https://cloud.githubusercontent.com/assets/4675662/17930038/dceaf806-69c9-11e6-97e6-7b4c463837f6.png)

**Comment by megax** [comment]
@lots0logs I agree :) Only others can not.

**Comment by khurshid-alam** [comment]
Reopening as switches in header-bar looks completely out of place. 
![huge-switches](http://i.imgur.com/hMVqFG7.png)
