### ISSUE TITLE
 gtk 3.20: Almost invisible insert caret in Nautilus rename field

### ISSUE THREAD

**Issue by arximboldi** [numixproject/numix-gtk-theme#398]
Hi!

In Nautilus, when renaming some text, the text edit marker (vertical bar) is in a grey color that is almost indistinguishable from the background color. See this example, where the bar is between the _n_ and the _r_ in the word _Conrad_.

![screenshot from 2016-04-26 12-53-54](https://cloud.githubusercontent.com/assets/4521138/14815931/8b986d7c-0bae-11e6-9489-3bc7787c487a.png)

**Comment by marmis85** [comment]
this was fixed in https://github.com/numixproject/numix-gtk-theme/commit/ca69ff77691cb540474df240dd68d66d579b1108

**Comment by arximboldi** [comment]
Thanks a lot! @marmis85
