### ISSUE TITLE
Side-bar jumps to clicked location on bar when it should not

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#399]
Though this is slightly hard to explain, basically when I click a part of the side-bar which is the actual bar I drag down and not the space I drag it through if it is on the right and I click far on the right of the actual bar instead of just doing nothing or allowing me to drag it it behaves as though I have clicked on the area where the bar is not on that area and jumps down to that point. Perhaps a screencast would be better at showing what I mean though so I have attached one.

I am running Ubuntu GNOME 15.10 with GNOME 3.18 and `numix-gtk-theme` version `2.4ubuntu1+443~201604261632~ubuntu15.10.1`. This happens with all applications which have the Numix side bar. Obviously the bar just needs to be a little fatter and cover a little more area than it currently does.
[Numix_Side-Bar_Issue.mp4.zip](https://github.com/numixproject/numix-gtk-theme/files/238683/Numix_Side-Bar_Issue.mp4.zip)

**Comment by khurshid-alam** [comment]
@SeventhSonOfASeventhSon I can not reproduce this on Ubuntu 16.04.

**Comment by ghost** [comment]
@khurshid-alam, Well, I am now running Ubuntu GNOME 16.04 with GNOME 3.20 and can still reproduce the issue.

**Comment by ghost** [comment]
I have now also noticed that this issue is also present in the Adwaita theme so is this issue more central than just Numix or is it just change that Adwaita has the same issue?

**Comment by khurshid-alam** [comment]
Its not a theme issue then. Closing.

**Comment by ghost** [comment]
What do you think it could be an issue in then?
