### ISSUE TITLE
The graphical assets need fixing

### ISSUE THREAD

**Issue by me4oslav** [numixproject/numix-gtk-theme#4]
They are so not flat and think, but rather fat and not flat looking. This look needs to go away and be replaced by a flat one.

**Comment by cldx** [comment]
Should be totally flat and purely Color Schemed now

**Comment by me4oslav** [comment]
Checkboxes are still fat ;p (the check image itself)
And the check imagie for context menu is badly fucked up.

**Comment by satya164** [comment]
We also need assets for the dark theme.

**Comment by satya164** [comment]
We need to fix the insensitive checkbox and also assets for the dark theme asap before UI freeze in Ubuntu.

**Comment by satya164** [comment]
Bump

**Comment by me4oslav** [comment]
Joeeeeeeeern?

**Comment by satya164** [comment]
I'll release the theme tonight without assets for the dark theme as I don't have time for that yet. UI freeze is on 21st and I don't have time.

**Comment by me4oslav** [comment]
Sounds fair enough.

**Comment by satya164** [comment]
Fixed in https://github.com/shimmerproject/Numix/commit/ccd195361d06a822a8a5af54e1145eac4d5dabb7
