### ISSUE TITLE
Enable Numix Light theme on ppa (Ubuntu 16.04) 

### ISSUE THREAD

**Issue by ericoporto** [numixproject/numix-gtk-theme#400]
When typing `sudo apt install numix-gtk-theme` after adding the ppa, only the dark theme is installed. The light theme requires going into Deviantart.

**Comment by khurshid-alam** [comment]
Light theme is not free. You have to pay $3.

**Comment by ericoporto** [comment]
I did pay, but I have no idea what to do. I even left a [comment](https://numixproject.org/store/index.php?route=product/product&product_id=53) in the Numix Store telling that I didn't had any idea what to do. In the past I bought in the Ubuntu Software Center and everything magically worked. I bought again from the website, but it gives no directions on what to do to install, so I thought it was some kind of donation...

**Comment by khurshid-alam** [comment]
You didn't have to pay twice. Send an email to team@numixproject.org
