### ISSUE TITLE
Background colors inactive buttons on Synaptic

### ISSUE THREAD

**Issue by varlesh** [numixproject/numix-gtk-theme#403]
Main window have color #EEEEEE
But inactive buttons have background color #F2F2F2
Bug preview:
![2016-05-01 20-54-25](https://cloud.githubusercontent.com/assets/8083855/14944369/31df07e2-0fe0-11e6-906c-ca9fed886c83.png)
Ubuntu 16.04 Xenial
numix-gtk-theme 2.4ubuntu1+450~201604291631~ubuntu16.04.1 
synaptic 0.83
gtk-3.18.9

**Comment by megax** [comment]
@khurshid-alam Other application bug, gtk 3.20.

**Comment by megax** [comment]
@khurshid-alam Code bug: https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.0/scss/widgets/_button.scss#L175
