### ISSUE TITLE
red dot line around icons in nautilus, terminal, gedit, etc.

### ISSUE THREAD

**Issue by zrwang** [numixproject/numix-gtk-theme#406]
Bug previwe:
![selection_002](https://cloud.githubusercontent.com/assets/5280342/15020740/62839800-11f1-11e6-867a-2082ce000cbd.png)
![selection_003](https://cloud.githubusercontent.com/assets/5280342/15020758/742dfb90-11f1-11e6-82d1-547012b6ba24.png)
![selection_004](https://cloud.githubusercontent.com/assets/5280342/15020795/a44614de-11f1-11e6-8715-9e96d28b116a.png)

I am running ubuntu 14.04 with i3wm on Thinkpad T450s.

Any idea why these red dot lines appear? Thanks!

**Comment by khurshid-alam** [comment]
We dropped support for GTK-3.10. If you still want to use Numix, don't use Numix PPA. Instead use the version available from the repo. https://launchpad.net/ubuntu/+archive/primary/+files/numix-gtk-theme_1.9.4-0ubuntu2_all.deb
