### ISSUE TITLE
Double pips on launcher too close together on Unity

### ISSUE THREAD

**Issue by CaviaPorcellus** [numixproject/numix-gtk-theme#407]
Using the Numix theme in Unity (I'm using Ubuntu 16.04), if the size of the launcher icons is set to 34 or below, the pips showing that there are two windows of an application open are too small and merge together. This has the effect of making the pips smaller when two windows are open than when only one window is, which is confusing.

The single pip is fine, and when three or more windows are open the three pips also show up quite nicely; it's only when there are two windows open that they merge together.

Here are three screenshots with the icons set at 32 (note the single and triple ones work fine, but the double pips just merge into a smaller single pip):

![screenshot from 2016-05-04 16-46-57](https://cloud.githubusercontent.com/assets/5825551/15028885/171ac582-1219-11e6-97f1-705d5b2eef65.png)
![screenshot from 2016-05-04 16-47-07](https://cloud.githubusercontent.com/assets/5825551/15028887/171e7236-1219-11e6-93c7-22b9d434c8a6.png)
![screenshot from 2016-05-04 16-47-15](https://cloud.githubusercontent.com/assets/5825551/15028886/171bdf12-1219-11e6-978a-8595745f421e.png)

For comparison, here are the pips when the icons are set larger, to 48, which display correctly:

![screenshot from 2016-05-04 16-46-18](https://cloud.githubusercontent.com/assets/5825551/15028882/170c83f0-1219-11e6-89dd-07caf1ed1781.png)
![screenshot from 2016-05-04 16-46-31](https://cloud.githubusercontent.com/assets/5825551/15028883/1718d3d0-1219-11e6-961a-ad3421d6904a.png)
![screenshot from 2016-05-04 16-46-39](https://cloud.githubusercontent.com/assets/5825551/15028884/171a2bf4-1219-11e6-96ab-f70e7548aa29.png)

Maybe the pips could be moved farther apart, made slightly larger, or more padding added to their image files. Not sure.

Thanks for the great theme.

**Comment by khurshid-alam** [comment]
It is difficult to find exact arraow placement perfect as we are using only two sizes. Anyone who wants to modify the svgs is always welcome.

**Comment by megax** [comment]
Related issue: https://github.com/horst3180/arc-theme/issues/288
