### ISSUE TITLE
Transmission Progress Bar

### ISSUE THREAD

**Issue by dannymichel** [numixproject/numix-gtk-theme#408]
I have to scroll over individual items for them to display the completed solid orange bar. A screenshot displays it correctly, but looking at the actual app doesn't.

**Comment by khurshid-alam** [comment]
Distro? GTK version? Theme version?

**Comment by dannymichel** [comment]
```
danny@danny:~$ dpkg -s libgtk2.0-0|grep '^Version'
Version: 2.24.30-1ubuntu1
danny@danny:~$ dpkg -s libgtk-3-0|grep '^Version'
Version: 3.18.9-1ubuntu3
```

Latest Numix

**Comment by khurshid-alam** [comment]
Are you installing from PPA? Can you provide a screenshot? It looks ok here:
![transmission-progressbar](http://i.imgur.com/hTRXiBJ.png)

**Comment by dannymichel** [comment]
Yes, im installing from PPA. unfortunately, the weirdest thing is in screenshots it displays correctly but not to the human eye. I can take a photo soon
