### ISSUE TITLE
Wine Applications Missing Graphic

### ISSUE THREAD

**Issue by dannymichel** [numixproject/numix-gtk-theme#409]
I'm sure this isn't something you concern yourselves with, as it's to do with Wine applications and staging features(enable gtk), but I was wondering if you could maybe coach me on how to fix the right half of the circle in foobar's progress bar seen here.
![screenshot from 2016-05-06 13-03-17](https://cloud.githubusercontent.com/assets/1161544/15080194/f0acb702-138a-11e6-83e7-22ec1d667081.png)

**Comment by khurshid-alam** [comment]
Wine version? Not sure which version of gtk wine uses...

**Comment by khurshid-alam** [comment]
@dannymichel It works if I tell wine to use custom gtk theme by exporting path. It doesn't look like a theme issue and not all apps are affected.

**Comment by dannymichel** [comment]
Interesting. I will find out how to do that

**Comment by bilelmoussaoui** [comment]
@dannymichel take a look at this http://www.webupd8.org/2010/06/make-wine-applications-look-like-your.html never tried it before. 
@khurshid-alam this can be closed i guess!
