### ISSUE TITLE
GTK :: Linked vertical button border

### ISSUE THREAD

**Issue by megax** [numixproject/numix-gtk-theme#418]
![image](https://cloud.githubusercontent.com/assets/461493/15144772/d76f9410-16b1-11e6-833a-cb4e005f1d2f.png)
(application: gtk3-widget-factory)

**Comment by megax** [comment]
GTK 3.18 Test (Ubuntu 16.04): 
![image](https://cloud.githubusercontent.com/assets/461493/15146080/9d26ebc0-16b9-11e6-9f99-7db77621b059.png)

**Comment by khurshid-alam** [comment]
@megax The code for Linked vertical button hasn't been ported to sass. You can try porting from https://github.com/khurshid-alam/Numix/blob/master/gtk-3.0/gtk-widgets.css

![linked-vertical](http://i.imgur.com/iibAhSM.png)

**Comment by megax** [comment]
@khurshid-alam Implement: https://github.com/numixproject/numix-gtk-theme/pull/425
Please test (Only gtk3.20)

**Comment by khurshid-alam** [comment]
Fixed in e5116cc078f4501e7c960d9292f2e2bf23cf5349
