### ISSUE TITLE
Enormous bar

### ISSUE THREAD

**Issue by jccall80** [numixproject/numix-gtk-theme#421]
I've upgraded to the latest theme because after upgrading the system the numix theme had problems

Now I see that all GTK3 based software has this enormous bar
![big bar](https://cloud.githubusercontent.com/assets/19292702/15160104/69f18032-16f8-11e6-8f6d-50c41622c7e7.png)

Is it normal?

With the old Numix GTK theme the bar was smaller.

**Comment by lots0logs** [comment]
Sorry, could you mark what you are referring to on the screenshot? Thanks.

**Comment by joaodriessen** [comment]
He's referring to the titlebar. It's quite impractical on small screens.

**Comment by lots0logs** [comment]
Oh, that's called a header bar and its has replaced titlebars in all GNOME applications. I'm afraid there's nothing that can be done as it is by design (in GTK, not the theme).

**Comment by janhicken** [comment]
The header bar is even bigger as in the default Adwaita theme. Are you sure you cannot do anything about that?

![bildschirmfoto von 2016-05-11 11-26-07](https://cloud.githubusercontent.com/assets/2724840/15176418/469e227a-176b-11e6-94e1-b6fca43400b7.png)

![bildschirmfoto von 2016-05-11 11-26-11](https://cloud.githubusercontent.com/assets/2724840/15176405/3ab21e6c-176b-11e6-922a-dd8b3ab46f32.png)

**Comment by joaodriessen** [comment]
you could try this for GTK 3.20:
(https://ogbe.net/blog/gnome_titles.html)

Put the following in ~/.config/gtk-3.0/gtk.css

```
/* shrink header bars *
header bar {
    min-height: 0px;
    padding-left: 2px; /* same as childrens vertical margins for nicer proportions */
    padding-right: 2px;
    background-color: #2d2d2d;
}

header bar entry
header bar spinbutton
header bar button
headerbar separator {
    margin-top: 0px; /* same as headerbar side padding for nicer proportions */
    margin-bottom: 0px;
}

/* shrink ssd titlebars */
.default-decoration {
    min-height: 0; /* let the entry and button drive the titlebar size */
    padding: 0px
    background-color: #2d2d2d;
}

.default-decoration .titlebutton {
    min-height: 0px; /* tweak these two props to reduce button size */
    min-width: 0px;
}

window.ssd headerbar.titlebar {
    padding-top: 3px;
    padding-bottom: 3px;
    min-height: 0;
}

window.ssd headerbar.titlebar button.titlebutton {
    padding-top: 3px;
    padding-bottom:3px;
    min-height: 0;
}
```

**Comment by janhicken** [comment]
That works brilliantly, thanks!

PS: I fixed that missing forward slash at the end of line 1 ;-)

**Comment by megax** [comment]
Fix: https://github.com/numixproject/numix-gtk-theme/pull/441

**Comment by joaodriessen** [comment]
Glad to see the issue taken seriously!
