### ISSUE TITLE
Possibility to install Numix in .local/share/themes

### ISSUE THREAD

**Issue by lburgazzoli** [numixproject/numix-gtk-theme#426]
It would be nice to have a way to install Numix in .local/share/themes like:

``` shell
export INSTALL_PREFIX=~/.local/share/themes 
make install
```

By default INSTALL_PREFIX is /usr/share/themes

**Comment by khurshid-alam** [comment]
Why? If you install in `.local/share/themes`, it can create problems in root windows (opened either by gksudo or polkit).

**Comment by lburgazzoli** [comment]
i.e. for un-privileged users ;)

**Comment by khurshid-alam** [comment]
Use file roller to extract `Numix Daily` folder from rpm/deb. After extracting you can rename it to `Numix`
