### ISSUE TITLE
GTK 3.20 :: App Panel :: GtkButton:inner-border is deprecated

### ISSUE THREAD

**Issue by janhicken** [numixproject/numix-gtk-theme#428]
It seems that this warning used to be addressed in issue #351. 

However, the deprecated style property `GtkButton:inner-border` is still used [here](https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.20/scss/apps/_panel.scss#L53), which causes the following warning by using _eog_ for example:

`(eog:19892): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3971:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version`

**Comment by khurshid-alam** [comment]
It's only deprecated. AFAIK, xfce and other fallback are still using this.

**Comment by lots0logs** [comment]
I think Xfce/Openbox/etc pull their styles from `gtk-3.0` directory so it should be okay to fix this for 3.20.

**Comment by khurshid-alam** [comment]
Fixed in a173892
