### ISSUE TITLE
Checkboxes and radio buttons don't have focus border on Gtk2

### ISSUE THREAD

**Issue by toupeira** [numixproject/numix-gtk-theme#43]
In Gtk2 apps, if I move the focus to a checkbox or radio buttion using the Tab key I don't get any visual feedback which widget is currently focused (it's the first checkbox in this screenshot):

![screenshot-2013-06-15-11 24 00 476741961](https://f.cloud.github.com/assets/6501/657916/ba715874-d59d-11e2-8ee3-005b07b43794.png)

It would be nice to have the same dotted border as in the Gtk3 theme:

![screenshot-2013-06-15-11 25 41 522024056](https://f.cloud.github.com/assets/6501/657917/cb1ffcf2-d59d-11e2-88a8-b16632718dd8.png)

**Comment by toupeira** [comment]
I had a look at the theme and was able to improve it by changing `bg[SELECTED]` for `murrine-radiocheck` to `@selected_bg_color` instead of `@base_color`, see https://github.com/toupeira/numix-gtk-theme/commit/a38eb37afd9d8f6d490af3e24f03d6acb82b726e

Here's how it looks now with the checkbox having focus:

![screenshot-2013-06-17-10 37 13 575299966](https://f.cloud.github.com/assets/6501/661142/85688fac-d729-11e2-8b59-f1749bb0dd56.png)

**Comment by satya164** [comment]
A pull request is very welcome. But the correct place to send pull requests
will be http://github.com/shimmerproject/Numix

**Comment by toupeira** [comment]
Okay done. It would be helpful if you enabled issues on the other repo, and maybe disabled them on this one or move them over somehow.

**Comment by satya164** [comment]
I periodically merge the changes from that repo to this one.

BTW sorry to reject your pull request since it messes up the look of the radio/check button. I changed the focus style instead.
