### ISSUE TITLE
GTK 3.20 :: Icon selected background color backdrop mode

### ISSUE THREAD

**Issue by megax** [numixproject/numix-gtk-theme#430]
Not background color:
![anim](https://cloud.githubusercontent.com/assets/461493/15267280/d365065c-19bd-11e6-8f0c-303be032333f.gif)

Application: Nemo file selected, gtk3-widgets-factory

**Comment by lots0logs** [comment]
That's very typical of GTK these days :unamused: Still I think we need to test this to make sure it doesn't affect any other areas of the theme.

**Comment by megax** [comment]
What I knew, I tested those and I couldn't find any problems. I am waiting for your testing results. :)

**Comment by megax** [comment]
Even i test, i found errors... =/ (cinnamon-settings)

**Comment by khurshid-alam** [comment]
Ideally `selected_items` code should be in `_base.scss` .Not sure why it was under `_misc` in the first place.

**Comment by megax** [comment]
Not ideally... code bugged. Code stabile all invite (`@extend %selected_items`) it comes after. For example: https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.20/scss/_widgets.scss#L37

See Adwaita code: https://github.com/GNOME/gtk/blob/gtk-3-20/gtk/theme/Adwaita/_common.scss#L4193

**Comment by megax** [comment]
@khurshid-alam Bug create code: `@include exports("selected_items") {`

**Comment by megax** [comment]
@khurshid-alam Sass code bugged: `@at-root %nobg_selected_items, & {`

**Comment by megax** [comment]
@khurshid-alam Not ideally, code bugged... =/

Ideally (I test...): https://github.com/The-Megax/Numix/blob/master/gtk-3.20/scss/_widgets.scss#L45 ("code end")
Adwaita sample: https://github.com/GNOME/gtk/blob/gtk-3-20/gtk/theme/Adwaita/_common.scss#L4193

**Comment by megax** [comment]
@khurshid-alam @lots0logs Massive test... (code modified). I think it will be good :)

**Comment by megax** [comment]
@lots0logs Tested code:
```
    label:disabled selection:backdrop, label:backdrop selection:disabled, spinbutton:not(.vertical) selection:backdrop:disabled, entry selection:backdrop:disabled, #login_window entry selection:backdrop:disabled, calendar:backdrop:disabled:selected, row:backdrop:disabled:selected, flowbox flowboxchild:backdrop:disabled:selected, modelbutton:backdrop:disabled:active, modelbutton:active arrow:backdrop:disabled, modelbutton:backdrop:disabled:selected, modelbutton:selected arrow:backdrop:disabled, .view:backdrop:disabled:selected, iconview:backdrop:disabled:selected,
    .view text:backdrop:disabled:selected,
    iconview text:backdrop:disabled:selected,
    textview text:backdrop:disabled:selected, .view text selection:backdrop:disabled, iconview text selection:backdrop:disabled,
    textview text selection:backdrop:disabled, .cs-category-view:backdrop:disabled:selected, .nemo-window .sidebar .nemo-places-sidebar .view:backdrop:disabled:selected, .nemo-window .sidebar .nemo-places-sidebar **iconview:backdrop:disabled:selected** {
      color: mix(#f2f1f0,#d64937,0.3); }
```
`iconview:backdrop:disabled:selected` wtf???
