### ISSUE TITLE
Question: I have a couple of improvements for GTK+ 3.20 version of the theme

### ISSUE THREAD

**Issue by actionless** [numixproject/numix-gtk-theme#436]
Here you can observe the changes between Numix upstream and my fork (if Numix colorscheme is selected):

(you should zoom to observe fixed radio and checkboxes for hidpi screen)

![2016-05-15--1463299979_2430x1496_scrot](https://cloud.githubusercontent.com/assets/1655669/15272851/8014e4b2-1a86-11e6-9d6d-eef3b434a2be.png)
![2016-05-15--1463299985_2430x1432_scrot](https://cloud.githubusercontent.com/assets/1655669/15272852/81e9571e-1a86-11e6-9f36-d9137311123c.png)

Do you want me to prepare PRs to return any of those changes back to Numix?

**Comment by khurshid-alam** [comment]
Couple of things:
1. It seems you are using old assets (are you?) which we also use in Numix-Light. There are demands that we also use same asset for Numix. But for now we would stick to current one.
2. Block-fill code for `levelbar` is broken (both, for you and us). We want rounded border for discrete indicators & for that we need `:nth-child` working (if working at all). You can run test comment here.
3. Disabled toggle button doesn't work like that.....it will cause lot of problems in many apps. 
4. Spin button (disabled) seems broken for you.
5. Switches: No.
6. I like the color for the toolbar text button, but padding is wrong.
7. Border on combobox entry: perhaps yes......
8. **Link Button: yes.**
9. Gtk scale slider: Is it just me or are you using 1px border on gtk scale slider?

**Comment by actionless** [comment]
1) yes, but they're are edited a bit, original old assets are displayed not correctly on hidpi as well, also their borders are changed to semi-transparent

2) yup, i wasn't attempting to fix it

4) i think they should be the same as upstream, mb only with more contrast border (UPD: ah, i see entry is missing right border)

6) do you mean changed button border, highlighted selected button or both? padding is smaller because in global.css i have a smaller `$spacing` set by default

7) only on combobox? i think such border change won't work if it will be changed on comboboxes but not buttons (ie comboboxes then will look more contrast than button), and mb the same with "entry" widget -- i changed contrast for borders for them 3 "in-sync"

8) what exactly should i port? i think its code almost the same as upstream except of border change described in pt.7

9) that slider widget's round toggle changed together with buttons because it is reusing `button` mixin

**Comment by megax** [comment]
@actionless Spinbutton rewirte: https://github.com/numixproject/numix-gtk-theme/pull/437

**Comment by lots0logs** [comment]
@megax Most of #437 looks good. Though besides the bug you mentioned there appears to be an issue with borders of the inline toolbar linked buttons. The border should be less prominent than a single button by itself but it should still be easily distinguishable when buttons are in a group. I'll try to take a look at it sometime today.

**Comment by megax** [comment]
@lots0logs I've also noticed the mistake. Unfortunatelly, I have no idea, but if you could, please repair it or later we can reapair together, just take notes the this problem. :)

**Comment by khurshid-alam** [comment]
The border problem arises because it is using normal linked button code for inline-toolbar as well....at line 374.

https://github.com/numixproject/numix-gtk-theme/pull/437/files#diff-95a2b202b10a360b21b6c0c04f7b996aR374

**Comment by megax** [comment]
@khurshid-alam Fixed inline-toolbar code. :)

**Comment by megax** [comment]
@khurshid-alam levelbar nth-child fixed https://github.com/numixproject/numix-gtk-theme/pull/446 . Not fixed progressbar border radius =/
