### ISSUE TITLE
GTK 3.20 :: Submenus space

### ISSUE THREAD

**Issue by megax** [numixproject/numix-gtk-theme#439]
![anim](https://cloud.githubusercontent.com/assets/461493/15275457/b9fedade-1acc-11e6-9157-7dd2bdfede02.gif)

There are spaces in the submenus at your  attached gif. It is what you want? Because it is strange for me. 
The cause is this code: https://github.com/numixproject/numix-gtk-theme/commit/150fda02b51fdb856efc17d6abbf8ef7b7a33b0c#diff-ad5526d84da246f8629813978dadfa9eL46

@lots0logs, @khurshid-alam

**Comment by khurshid-alam** [comment]
Your earlier pull was ok. Please add back changes from  3f9df11

**Comment by megax** [comment]
I did not want the two together (popover padding optimize and submenu space).

**Comment by khurshid-alam** [comment]
Ok. I was talking about the trailing space correction. Anyway please open a separate pull for that. Thanks.
