### ISSUE TITLE
Numix icons missing on Ubuntu 16.04 with icon themes "Numix" and "Numix-light"

### ISSUE THREAD

**Issue by JanSurft** [numixproject/numix-gtk-theme#445]
I have a relatively fresh install of Ubuntu 16.04. In the Unity Tweak Tool, changing the theme to "Numix" or "Numix Daily" is working perfectly fine. Everything seems to change according to that theme.

Then I also want to change the Icon appearance to "Numix". This yields into some icons just missing. Some of them are: `System Settings->Appearance`, `System Settings->Language Support`, `System Settings->Text Entry`, `gnome-screenshot`, the default terminal icon and the default `help` icon. But there are more...

Numix-circle and Numix-circle-light are working just fine by the way, without any missing icons.

![icons-missing](https://cloud.githubusercontent.com/assets/10834314/15281386/e64032b4-1b3a-11e6-87f4-09d9d6225fb6.png)

**Comment by khurshid-alam** [comment]
@JanSurft Please report issues here: https://github.com/numixproject/numix-icon-theme/issues

**Comment by bilelmoussaoui** [comment]
- Those icons are added by Numix Circle, you should use that instead of Numix Base (Numix Circle = Numix Base + Circle application icons)
