### ISSUE TITLE
Evolution meeting invitation buttons have invisible text

### ISSUE THREAD

**Issue by ben-kuhn** [numixproject/numix-gtk-theme#450]
Hello,

I am using the Numix theme from the official PPA on Ubuntu 16.04.  Using either the "Numix" or Numix Daily" themes, my meeting invitation buttons in Evolution have invisible text.  When testing with Adwaita, the text is visible.

The meeting invites are also horribly ugly but that's an evolution bug/problem.

![image](https://cloud.githubusercontent.com/assets/16821405/15296926/40bbf51c-1b5d-11e6-9b17-a4e4aba82ac6.png)

**Comment by ben-kuhn** [comment]
Here is the same window with Adwaita:
![image](https://cloud.githubusercontent.com/assets/16821405/15296955/5f19d84e-1b5d-11e6-9ad5-99986ae1cd23.png)

**Comment by khurshid-alam** [comment]
How to reproduce above issue?

**Comment by ben-kuhn** [comment]
1.  Enable Numix or Numix Nightly as the GTK theme.
2.  Open Evolution
3.  Open an appointment request.
4.  Notice the text is missing on the buttons.
5.  Change the theme to something else.
6.  Check the appointment request again and see that the text is there as expected.

**Comment by khurshid-alam** [comment]
> Open an appointment request.

How?

**Comment by ben-kuhn** [comment]
First, someone will need to send an invitation.  It will show up as an email and when you open it you will see the screenshot I described.  Most calendaring applications sending invitations like this.  To test myself, I sent an appointment request from my personal google calendar to my work email account (exchange.)

**Comment by megax** [comment]
Please test gtk 3.20 and Ubuntu 16.10. In principle, there has been good (i not tested).

**Comment by ben-kuhn** [comment]
I don not have any 16.10 systems and don't really plan to.  I tend to stick to LTS releases for stability.  I know many others do the same.

**Comment by megax** [comment]
I'm not sure that will be ported to gtk 3.18

**Comment by bm-skutzke** [comment]
I have the same issue with Fedora 24.
numix-gtk-theme-2.6.0-1.fc24.noarch
gtk3-3.20.9-1.fc24.x86_64
evolution-3.20.5-1.fc24.x86_64

**Comment by megax** [comment]
@khurshid-alam, @ben-kuhn Please test master branch. It can improve  (https://github.com/numixproject/numix-gtk-theme/commit/7254e08542167c9e268f6e20492cd2e24ba9289c). I did not test.

**Comment by megax** [comment]
@khurshid-alam Still having trouble? :)
