### ISSUE TITLE
Unity drop-down windows missing shadow

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-gtk-theme#451]
![screenshot from 2016-05-17 00-34-39](https://cloud.githubusercontent.com/assets/11137173/15305993/2d62bafe-1bc7-11e6-8fa0-267e7bf2b901.png)

It makes drop-down windows completely unreadable.

**Comment by khurshid-alam** [comment]
> It makes drop-down windows completely unreadable.

I can read just fine. Beside we don't use shadows for panel menu.

**Comment by Corsseir** [comment]
![2d62bafe-1bc7-11e6-8fa0-267e7bf2b901](https://cloud.githubusercontent.com/assets/11137173/15390253/3c7952a0-1dbb-11e6-84d1-11f067f1c5a0.png)
Is this normal for you? These confluent windows?

**Comment by clauded** [comment]
Try this: edit ~/.config/gtk-3.0/gtk.css and add those lines

```
.csd .menu {
  border: 1px solid #3d3d3d;
  padding: 0;
}
```

Logout and login and you will have borders around drop down menus. This affects all themes however.

**Comment by megax** [comment]
Tested gtk 3.20 and Ubuntu 16.10 (no problem): 
![image](https://cloud.githubusercontent.com/assets/461493/18036380/4a70a414-6d69-11e6-8a48-22b38c398205.png)
