### ISSUE TITLE
GTK 2/3 menu bar padding

### ISSUE THREAD

**Issue by wavexx** [numixproject/numix-gtk-theme#453]
There's a huge difference in padding between the GTK2 and GTK3 versions of the theme.
In GTK3 menus have way too much padding:

![1463500050](https://cloud.githubusercontent.com/assets/1017726/15329724/0b271f3c-1c5a-11e6-8277-9204a2a5fe45.png)

(in the back, gpick with gtk2, in the front: gucharmap, aligned to the top margin).
It would be nice if we could use GTK2's sizes here to waste less space and be consistent.

**Comment by wavexx** [comment]
Forgot to mention, this is with GTK3.20, but I noticed the same issue in earlier versions too.

**Comment by lots0logs** [comment]
I'm pretty sure the padding in GTK3 is intentional and its the GTK2 theme that needs to be adjusted to match. @satya164 ?

**Comment by wavexx** [comment]
On Tue, May 17 2016, Dustin Falgout notifications@github.com wrote:

> I'm pretty sure the padding in GTK3 is intentional and its the GTK2 theme that needs to be adjusted to match. @satya164 ?

In the recent versions, the menus in GTK3 seem to have widened compared
to before.

On <120 dpi, it's ludicrous. Is spacing calculated according to DPI, or
there are raw pixel values at hand?

At >160dpi it looks more reasonable, but there's no way I can use that
spacing on my large external monitor.

**Comment by megax** [comment]
@satya164 must change menu padding?

**Comment by lots0logs** [comment]
@megax After looking at it a bit more I think we need to:
1. Increase the padding on the gtk2 theme
2. Decrease the padding on the gtk3 theme

So that in the end they are both the same. Let me know if you understand. Thanks.

**Comment by megax** [comment]
You need to create an intermediate size?

**Comment by megax** [comment]
@lots0logs https://github.com/numixproject/numix-gtk-theme/pull/536
