### ISSUE TITLE
GTK 3.20 :: fine-tune popup background missing

### ISSUE THREAD

**Issue by SammysHP** [numixproject/numix-gtk-theme#457]
Adwaita:

![20160519_102648](https://cloud.githubusercontent.com/assets/922874/15387261/7238f242-1dac-11e6-8262-da1427dce1e6.png)

Numix:

![20160519_102712](https://cloud.githubusercontent.com/assets/922874/15387262/725730a4-1dac-11e6-9e59-d734a81c72d3.png)

**Comment by megax** [comment]
@SammysHP Fixed: https://github.com/megax/Numix/commit/108f6d889eceef8991db7f4e598e01fc0d456081
