### ISSUE TITLE
Evoltion email client issues

### ISSUE THREAD

**Issue by mvoropaiev** [numixproject/numix-gtk-theme#458]
Hello,
I have just switched back to using Numix theme, building it from master branch on Fedora 23.
All is great for now, but I have encounter some issues (or maybe a wishlist) with Evolution email client, which can be seen at screenshot.

![screenshot from 2016-05-19 11-07-50](https://cloud.githubusercontent.com/assets/6753164/15387212/82deec02-1db4-11e6-9390-2f176d6fc684.png)

Legend:
1. the white border looks little out of place (compared with nautilus' list view for example).
2. the links are barely readable.
3. not really sure about this one (the whole blue area), but it's kinda looks out of place too, just too bright I guess.

Is it possible to fix it, or maybe some hints to fix it by myself would be appreciated.
Thanks!

**Comment by khurshid-alam** [comment]
@mvoropaiev 
Right
1. Evolution uses its own decoration style under column header view. So its not themed properly for dark mode.
2. Only in dark mode right? Can you post a screenshot with light mode?
3. That is message infobar color. Looks ok in light mode. 

Dark mode has better theme support in Gtk-3.20, i.e fedora 24.

**Comment by megax** [comment]
@mvoropaiev @khurshid-alam Still having trouble? (GTK 3.20 ?)

**Comment by megax** [comment]
@mvoropaiev @khurshid-alam Still having trouble? (GTK 3.20 ?)

**Comment by megax** [comment]
@mvoropaiev @khurshid-alam Still having trouble? (GTK 3.20 GTK 3.22 ?)

**Comment by khurshid-alam** [comment]
Fixed in 3.22
