### ISSUE TITLE
Update GTK2 scrollbars to match GTK3

### ISSUE THREAD

**Issue by satya164** [numixproject/numix-gtk-theme#46]
Below is a screenshot comparing the scrollbars in GTK2 and GTK3. I think the GTK2 scrollbar shouldn't have the trough border and the trough bg should be same as GTK3.

![screenshot from 2013-06-24 13 08 53](https://f.cloud.github.com/assets/1174278/693954/c169d740-dca1-11e2-8e79-de09d560200f.png)

Also, see the active state of scrollbars in GTK2 and GTK3. There is a Greyish border oround the scrollbar in GTK2. If it's not possible to get rid of the greyish color, will be better to get rid of the border entirely.

![scrollbar](https://f.cloud.github.com/assets/1174278/693997/cd96db5c-dca2-11e2-9727-02e2da5a3a86.png)

**Comment by ochosi** [comment]
Fixed in master: https://github.com/shimmerproject/Numix/commit/8000b1f78ff91e8af71dddb63909e61f0c927b59
