### ISSUE TITLE
GTK2 :: GTK2 apps :: colour of menu lighter than window border 

### ISSUE THREAD

**Issue by joaodriessen** [numixproject/numix-gtk-theme#464]
for a while now window borders and window menus in GTK2 apps are no longer the same colour.
I much prefer it when they are the same colour.
I understand that you can't use the window menu to drag the window hence I assume the difference in colour is necessary, none the less, can anyone offer a tip on how to set it to be the same colour?

![screenshot at 2016-05-23 14 36 37](https://cloud.githubusercontent.com/assets/3994246/15470959/cf0dac02-20f3-11e6-8ee5-2948b44cf72d.png)

**Comment by khurshid-alam** [comment]
In the theme file, title-bar has same background color as menubar. Somehow Unity using different background color. What is your theme version?

**Comment by joaodriessen** [comment]
running on arch linux - (aur) latest git.
the screenshot is Thunar running on Mate 1.12

**Comment by khurshid-alam** [comment]
Then, its mate window manager overriding title-bar color. We don't really have support for mate. It works on old fallback code for Gnome-Panel.

**Comment by joaodriessen** [comment]
Mate is a rather popular DE and surprised to hear that you don't wish to support it.
Would you point me in the direction of a GTK2 based DE you do support?
I'm running on Raspberry Pi so Lightweight is a priority.
Thanks for the response!

**Comment by khurshid-alam** [comment]
I didn't day `we don't want to` but rather we `do not have support`. Gtk2 has been deprecated long ago. And mate is moving to gtk3
