### ISSUE TITLE
GTK 3.20 :: Stackswitcher button size

### ISSUE THREAD

**Issue by megax** [numixproject/numix-gtk-theme#465]
Now:
![image](https://cloud.githubusercontent.com/assets/461493/15483595/bff35978-2135-11e6-9465-f9ac6c28b3be.png)

Corrected:
![image](https://cloud.githubusercontent.com/assets/461493/15483626/e6cca1f8-2135-11e6-9f19-0761e0ccd9fa.png)

Code: `stackswitcher button.text-button { min-width: 100px; } // FIXME aggregate with buttons`
Fixed bug: https://github.com/GNOME/gtk/commit/f7466b236a92dd7eb536f80a08e833971cb4566f

**Comment by megax** [comment]
@lots0logs, @khurshid-alam opinion?

**Comment by lots0logs** [comment]
@megax Hmm..this is an issue that cant really be properly solved via the theme (its really a problem with GTK stackswitcher widget. They should all be adjusted to equal width by gtk which would be the width of the widest button) But I digress (sorry). Anyway, I think applying a minimum width in the theme is needed. I just wonder if 100px is the most optimal value for the setting? @khurshid-alam thoughts?

**Comment by khurshid-alam** [comment]
> They should all be adjusted to equal width by gtk which would be the width of the widest button)

That what elementary's granite (a gtk+ extension) does. But it only works for text button. 

Well anything below 90px doesn't really have prominent effect. So can set it 90px.

![stackswitcher-90px](http://i.imgur.com/F0vXVor.png)

**Comment by megax** [comment]
@khurshid-alam Created PR.
