### ISSUE TITLE
GTK 3.20: xfce4-pulseaudio-plugin has incorrect color

### ISSUE THREAD

**Issue by kepler2** [numixproject/numix-gtk-theme#466]
Hello all. I'm using Arch (with XFCE D. E.) with the latest Numix theme installed (GIT version).

If you use the xfce4-pulseaudio-plugin, you may notice that the volume indicator icon is black, instead of white. (it was ok before the infamous GTK 3.20 update) - note that when using Arc theme - for example - the issue does not occur. 

Please see the screenshot below:

![numix_pulse_audio](https://cloud.githubusercontent.com/assets/18610924/15531670/3bb87398-2264-11e6-985c-53be25e67753.png)

White would be good :)

**Comment by megax** [comment]
Related errors: https://github.com/Antergos/Numix-Frost/issues/26

**Comment by megax** [comment]
@kepler2 Fixed bug: https://github.com/numixproject/numix-gtk-theme/pull/478

**Comment by kepler2** [comment]
Thank you!
