### ISSUE TITLE
Numix theme practically unusable on Ubuntu GNOME 16.04 with GNOME 3.20

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#469]
I have installed Ubuntu GNOME 16.04 with GNOME 3.20 (I upgraded from GNOME 3.18) but now have found that it is practically unusable, the following screenshots should clearly show why (I put a black box of my processes as that is private information):

![gnome-tweak-tool_numix](https://cloud.githubusercontent.com/assets/11575271/15629217/1dad7656-250b-11e6-889e-fac1dcd8fa80.png)

![gnome-tweak-tool_numix-pull-down-menu](https://cloud.githubusercontent.com/assets/11575271/15629219/22d5352e-250b-11e6-83ec-947947df8faa.png)

The above one is of when I clicked on a sort of pull-down menu but it was very hard to select an option because I sort of had to drag and then release over the correct option which did not give any indication of being selected.

![gnome-system-monitor_numix](https://cloud.githubusercontent.com/assets/11575271/15629221/470123fe-250b-11e6-9883-7bc9f08d34f4.png)

You will see the sections at the top of this one have not got proper styling.

![gnome-system-monitor_numix-processes](https://cloud.githubusercontent.com/assets/11575271/15629224/5835c1a2-250b-11e6-9294-cf8b3c44d866.png)

And with this one the categories are sort of on top of each other somewhat in terms of their names in a strange way. Anyway, all this has made Numix practically unusable, so it would be really nice if this was all fixed, it only seems to be this way on GNOME 3.20 and not previous versions, though I don't really want to downgrade but I am stuck with Adwaita at the moment and that has issues of its own.

**Comment by tliron** [comment]
The Numix package in Ubuntu only supports GNOME 3.18. Remove it and install directly from GitHub:

```
sudo apt remove numix-gtk-theme
sudo apt install git autoconf automake pkg-config libgtk-3-dev
sudo gem install sass
cd /tmp
git clone https://github.com/numixproject/numix-gtk-theme --depth 1
cd numix-gtk-theme
make install INSTALL_DIR=~/.themes/Numix
```

**Comment by ghost** [comment]
@tliron, Can't it be made to support GNOME 3.20 there as well?

**Comment by tliron** [comment]
I'm just a helpful user here, not involved with the project. I think you would need to open that bug on Ubuntu for the packagers there. It's probably something that should be opened in relation to the gnome3-staging PPA, though, because Ubuntu 16.04 does not claim to support GNOME 3.20.

**Comment by kuboosoft** [comment]
also in Fedora 24 is broken! I use the current git branch

**Comment by khurshid-alam** [comment]
It has gnome-3.20 support. It just that gnome-tweak tool(3.18) can not select respective folder for gtk-3.20. Try changing theme with dconf. 

@SeventhSonOfASeventhSon  Are you installing theme from ppa?

**Comment by ghost** [comment]
@khurshid-alam, No, I am not installing the theme from the PPA, in my opinion some of the security practices of those managing the main Numix PPA aren't very good so I stopped using it. Instead I am now using the package in the Ubuntu universe repository.

**Comment by khurshid-alam** [comment]
@SeventhSonOfASeventhSon 

**That's the reason.** Version in universe **hasn't been updated** for long time and abandoned. It is not really our project...it is a part of shimmer-themes project. It is not compatible with >=Gtk-3.18. Use the version from PPA.

You got a wrong idea about how packages are compiled in universe repo and ppa. It uses same machine and same script. In PPA it pulled the code directly from git.

**Comment by ghost** [comment]
The only reason I'm not using the PPA is because they don't seem to have a very good security policy for who they accept into their maintainers team... I mean if they added me, they don't have a very good security policy (or at least they are not following it properly). Not that I'm untrustworthy or anything (don't worry, this is not sarcasm, and neither is this), but I accidentally requested to join, didn't have anything really to show for myself at the time, and they actually added me so that makes me question who else they would allow to join their team... If it's anyone who requests to join then people could be uploading malware there for all I know.

**Comment by khurshid-alam** [comment]
@SeventhSonOfASeventhSon Join what? Team? Joining a team doesn't give you access to other people 's PPA. Actually all the packages in Ubuntu universe come from PPA. It seems you don't have clear idea how debian packaging works. So please keep yourself away from rumors.

**Comment by ghost** [comment]
@khurshid-alam, The Numix Maintainers team on LaunchPad that have direct control over the only official Numix PPA I ever heard of... Is this not the actual one? Also, I'm pretty sure that there are checks on the universe repository packages, there are no proper checks on PPAs.

**Comment by ghost** [comment]
Also, just wanted to let you know that I have now had this issue sorted out with the main GNOME3 PPA for Ubuntu which now ships the latest version of the Numix GTK Theme and it works with GNOME 3.20 perfectly fine.
