### ISSUE TITLE
Numix breaks XNoise sidebar font

### ISSUE THREAD

**Issue by me4oslav** [numixproject/numix-gtk-theme#47]
Look at the screenshot:
![screenshot 2013-06-24 11 00 32](https://f.cloud.github.com/assets/1658870/694031/3626ebca-dca4-11e2-8085-0af43df9c1e4.png)

**Comment by satya164** [comment]
Found out what causes it,

```
GtkTreeView {
    -GtkTreeView-vertical-separator: 0;
    -GtkWidget-focus-line-width: 0; /* This removes the dotted line from focused treeview */
    -GtkWidget-focus-padding: 1;
}
```

But removing it will have negative impact on the aesthetics. And anyways... there something seems to be wrong in Xnoise, or this shouldn't happen. This also happens with Zukitwo theme.

An alternative will be to switch to Adwaita engine, in which I can customize the style of the focus border. But it's not a feasible solution.

**Comment by me4oslav** [comment]
Reported against XNoise: https://bitbucket.org/shuerhaaken/xnoise/issue/56/sidebar-font-goes-wonky-with-some-themes
