### ISSUE TITLE
Nautilus desktop background white or gray

### ISSUE THREAD

**Issue by marcominetti** [numixproject/numix-gtk-theme#472]
The theme somehow overrides the user-picked color or wallpaper configuration for desktop and always uses white (or gray with global dark theme option) color.

**Comment by marcominetti** [comment]
Duplicated

**Comment by satya164** [comment]
What's your distro, GTK version and Numix theme version?

**Comment by khurshid-alam** [comment]
#272

**Comment by marcominetti** [comment]
GTK 3.20, Ubuntu 16.04 based with Gnome 3 PPA (3.20)... The problem seemed to be solved (with minor issues - wrong select icon label background color when desktop is not focused) but now it is back again... I've tried Arc theme and it is not affected from this bug, so IMHO is not a problem of nautilus as read somewhere in the issues...

**Comment by marcominetti** [comment]
https://github.com/numixproject/numix-gtk-theme/pull/482

**Comment by megax** [comment]
@marcominetti Still having trouble?

**Comment by megax** [comment]
@marcominetti "with minor issues - wrong select icon label background color when desktop is not focused": Global bug (not Nautilus specific): https://github.com/numixproject/numix-gtk-theme/issues/430
And fixed :) https://github.com/numixproject/numix-gtk-theme/pull/523
![image](https://cloud.githubusercontent.com/assets/461493/17968926/d318d670-6acf-11e6-9a9b-6755be3cd133.png)

**Comment by megax** [comment]
@khurshid-alam Fixed: https://github.com/numixproject/numix-gtk-theme/commit/4c2cf031e10cfcd4b4123fb86dcd976f604378e9

**Comment by megax** [comment]
@khurshid-alam Still having trouble?

**Comment by megax** [comment]
@khurshid-alam I fix and test! close :)

**Comment by geckolinux** [comment]
Hi, this still seems to be a problem with openSUSE Tumbleweed:

![alt](https://bugzilla.opensuse.org/attachment.cgi?id=690319)

Complete bug report: https://bugzilla.opensuse.org/show_bug.cgi?id=982134
