### ISSUE TITLE
GTK 3.20 :: Combo Boxes, Button Boxes, menus theme doesn't work on xfce4

### ISSUE THREAD

**Issue by eveouyang** [numixproject/numix-gtk-theme#479]
Arch Linux
xfce4
gtk3 3.20.6-1

Authenticate Windows can not be seen the text input area.
Combo Boxes, Button Boxes, menus theme style doesn't work on gtk3.20
![screenshot_2016-06-10_09-15-42](https://cloud.githubusercontent.com/assets/8010487/15952328/47821c8e-2ef2-11e6-9aeb-7a1d9ad2400e.png)
![screenshot_2016-06-10_09-53-14](https://cloud.githubusercontent.com/assets/8010487/15952330/4d2658b2-2ef2-11e6-881b-cd4dc35f7488.png)
![screenshot_2016-06-10_09-57-22](https://cloud.githubusercontent.com/assets/8010487/15952333/52760c72-2ef2-11e6-84cd-f0fb9c315bfa.png)
![screenshot_2016-06-10_09-58-19](https://cloud.githubusercontent.com/assets/8010487/15952335/57544164-2ef2-11e6-851c-4884ed76e1c4.png)

**Comment by lots0logs** [comment]
Looks like you are not using the latest version of the theme. How did you install it?

**Comment by eveouyang** [comment]
I had install the latest version.
Here's the version
numix-themes 2.5.1.r233.a6be634-1

**Comment by lots0logs** [comment]
The package in the Arch repos is out of date. Could you try installing the latest git version from the AUR and let me know the result? Thanks.

**Comment by eveouyang** [comment]
THX lots0logs.
Install latest git version from AUR, It works, Thanks a lot  lots0logs.
I make a mistake that I thought the repos will update in time, so I didn't check the git version.
