### ISSUE TITLE
GTK 3.20 :: Metacity :: Close button bug (not found)

### ISSUE THREAD

**Issue by megax** [numixproject/numix-gtk-theme#480]
**System: Arc linux + Cinnamon 3.0.7 + gtk 3.22**

**Numix:**
Sample: Nautilus settings
![image](https://cloud.githubusercontent.com/assets/461493/15955170/8f762b24-2edf-11e6-865f-de6b70c919ba.png)

**Other theme:**
![image](https://cloud.githubusercontent.com/assets/461493/15955183/a1ad96ec-2edf-11e6-927d-295cbaa7697b.png)

**Comment by FabianInostroza** [comment]
I don't know if this is as is by design but I've changed that in the metacity theme (see my fork)

**Comment by khurshid-alam** [comment]
@FabianInostroza This only for gtk-2? right? Shouldn't mate window-manager decorate window button?

**Comment by khurshid-alam** [comment]
@albertsmuktupavels Can you please look into the issue? 

@FabianInostroza suggested to change it from 
`<frame_style name="dialog_focused" geometry="nobuttons">` to
`<frame_style name="dialog_focused" geometry="max">` in metacity-theme-3.xml. Is this the proper way to do this?

These issues do not happen with Gtk-3.18.

**Comment by muktupavels** [comment]
What here is meant with Metacity - theme itself or window manager? Because Metacity theme is used also by other window managers... If Metacity 3.20 is used I would suggest to start using GTK+ theme.

Main problem here is that Nautilus used to have close button in dialog, but it has been removed. Metacity themes are in control whether to show buttons or not.  So proper solution is to update themes to stop hide buttons in dialogs, remove 'hide_buttons="true"' or change to false.

I could update Metacity to ignore hide_buttons, but I think it is not good idea - what if someone still want to hide buttons?

**Comment by khurshid-alam** [comment]
@albertsmuktupavels 

> What here is meant with Metacity - theme itself or window manager?

Window Manager. I think @megax is using flashback metacity session with Gtk-3.20 (on Arch perhaps). Not sure about the metacity version though. I will try to reproduce and comment here.

> So proper solution is to update themes to stop hide buttons in dialogs, remove 'hide_buttons="true"' or change to false

Ah. Right. We are using nobuttons for dialogs which has `hide_buttons=true`. Something like this:

``` xml
<frame_geometry name="nobuttons" hide_buttons="true" parent="normal" />
<frame_style name="dialog_focused" geometry="nobuttons">
```

We can simply change `geometry="nobuttons"` to `geometry="normal"`. It would change all the dialogs but its upstream fault/decision that they remove metacity buttons from dialog. 

> I could update Metacity to ignore hide_buttons, but I think it is not good idea - what if someone still want to hide buttons?

Right. There is no need to change anything which is opposite to the upstream workflow. Beside I think Debian/Ubuntu will patch this (or already patched). So it's not an issue on Ubuntu.

Thanks.

**Comment by megax** [comment]
@khurshid-alam Do you have any idea how to solve? Which does not cause regression.

**Comment by khurshid-alam** [comment]
I will look into it.

**Comment by nazar-pc** [comment]
I confirm this issue under Compiz on Ubuntu with gtk-window-decorator (I'm using custom session without Unity). I've noticed it somewhere during 16.10 development cycle, but didn't pay enough attention. Checked with settings window of Nemo file manager and Ambiance theme.
GTK 3.22, I believe it was the same with 3.20.

**Comment by khurshid-alam** [comment]
Yes....changing frame style will solve the issue for gtk3.....but gtk2 will get broken for focus dialogs.

**Comment by ghost** [comment]
Any progress on this please? I have the same problem, or a similar one - some close icons not showing - on a different theme, and I'd be grateful for any information on solving the problem.

**Comment by khurshid-alam** [comment]
@ACinnamonUserInUK 

Use **gtk** as metacity theme type. In terminal execute

`gsettings set org.gnome.metacity.theme type gtk`

**Comment by ghost** [comment]
@khurshid-alam: thanks, but I've solved the problem already. See [here](https://www.linuxquestions.org/questions/showthread.php?s=81a0c9616970ccde59b2b8ebc5bd6cf5&p=5719432#post5719432).
