### ISSUE TITLE
Unix file modes are executable on normal files

### ISSUE THREAD

**Issue by sspreitzer** [numixproject/numix-gtk-theme#485]
Currently packaging numix-gtk-theme for Fedora Linux.
One major finding in the review process is that generic files have executable bit set but are not executables.

**Comment by sspreitzer** [comment]
This is maybe the symptom of a wider problem which is quality assurance. Pull requests should have CI runner that quality checks and comments PR about quality.

**Comment by megax** [comment]
@sspreitzer https://github.com/numixproject/numix-gtk-theme/pull/515
