### ISSUE TITLE
Titlebar height

### ISSUE THREAD

**Issue by grigorii-horos** [numixproject/numix-gtk-theme#486]
Window titlebar height in [Terminix](https://github.com/gnunn1/terminix) is biggest than in other apps when I use [Numix](https://github.com/numixproject/numix-gtk-theme) theme
![2016-06-13 16-45-18](https://cloud.githubusercontent.com/assets/4980269/16009883/456869de-3187-11e6-9532-1cd3467af362.png)

**Comment by grigorii-horos** [comment]
UPD: https://github.com/gnunn1/terminix/issues/378

**Comment by bilelmoussaoui** [comment]
It has nothing to do with terminix, theres à huge padding with almost all
apps

**Comment by khurshid-alam** [comment]
@horosgrisa Weird. Can you install from git master and check if it is still happening? 

@bil-elmoussaoui Can you clarify? Which apps are you talking about?

**Comment by grigorii-horos** [comment]
@khurshid-alam I use 

```
pacman -Q numix-themes-git
numix-themes-git 2.6.0.r5.51713dc-1
```

**Comment by bilelmoussaoui** [comment]
@khurshid-alam Gnome Tweak Tools, Nautilus, Terminix...

**Comment by megax** [comment]
@khurshid-alam Archlinux -> cinnamon desktop: Not reproduced bug
![image](https://cloud.githubusercontent.com/assets/461493/16018498/f6ded032-31a4-11e6-8d65-0a1146611e61.png)

**Comment by lots0logs** [comment]
I cannot reproduce this either (also using Cinnamon on Arch)

**Comment by bilelmoussaoui** [comment]
Can you guys try it on Gnome?

**Comment by gnunn1** [comment]
I updated the bug report in Terminix (and closed it), as far as I can tell it's a bug with Numix as gedit as a larger headerbar as well. You can see a screenshot illustrating this in the terminix bug report.

**Comment by khurshid-alam** [comment]
@horosgrisa Please reinstall and try again.

**Comment by megax** [comment]
Tested virtual pc (virtual Nautilus and Native (cinnamon desktop) Nautilus):
![image](https://cloud.githubusercontent.com/assets/461493/16079383/8fe4dfc4-3303-11e6-90a2-13cb6f741396.png)

**Comment by grigorii-horos** [comment]
@bil-elmoussaoui Sorry, I forgot to mention, I use font scale 1.5.

**Comment by khurshid-alam** [comment]
@megax So the issue exists? Gtk and nautilus version? It could be the issue with icon sizes (which means a gtk bug?)

**Comment by megax** [comment]
@khurshid-alam Yes, the issue exists. Archlinux: gtk 3.20.6-1, Nautilus: 3.20.2

Edit: Not reproduced bug Adwaita.

**Comment by khurshid-alam** [comment]
@megax What happens when you compile manually on virtual machine?

**Comment by megax** [comment]
@khurshid-alam Cloned compile system (my desktop) theme (latest numix theme (git)).

**Comment by lots0logs** [comment]
@horosgrisa Could you post a screenshot of the issue with the Adwaita theme active so we can compare it to the other screenshot you already posted? (be sure that your font-scale settings are the same as before---1.5)

**Comment by grigorii-horos** [comment]
@lots0logs 
![2016-06-18 22-10-41](https://cloud.githubusercontent.com/assets/4980269/16173176/12dce21e-35a2-11e6-8350-8f2a79d06fde.png)
![2016-06-18 22-11-35](https://cloud.githubusercontent.com/assets/4980269/16173177/12ed4d2a-35a2-11e6-9c23-97fd79eebea3.png)
![2016-06-18 22-11-45](https://cloud.githubusercontent.com/assets/4980269/16173178/12fb47a4-35a2-11e6-82c1-8d51fffbb135.png)
![2016-06-18 22-12-31](https://cloud.githubusercontent.com/assets/4980269/16173179/130f032a-35a2-11e6-8cb2-7c19a7c71ab1.png)
![2016-06-18 22-12-52](https://cloud.githubusercontent.com/assets/4980269/16173180/1322b118-35a2-11e6-9a27-4d46014e0711.png)
![2016-06-18 22-13-13](https://cloud.githubusercontent.com/assets/4980269/16173181/13339654-35a2-11e6-8570-2f2d214a5a7b.png)

**Comment by grigorii-horos** [comment]
Bug only with font-scale 1.5:
![2016-06-18 22-19-00](https://cloud.githubusercontent.com/assets/4980269/16173209/bbbef084-35a2-11e6-8f67-1593d0015ec1.png)

**Comment by lots0logs** [comment]
@horosgrisa Is the font scale set to 1.5 in this one? https://cloud.githubusercontent.com/assets/4980269/16173177/12ed4d2a-35a2-11e6-9c23-97fd79eebea3.png

**Comment by grigorii-horos** [comment]
@lots0logs Yes, font-scale 1 only in last screenshot with numix 
https://cloud.githubusercontent.com/assets/4980269/16173209/bbbef084-35a2-11e6-8f67-1593d0015ec1.png

**Comment by mrlotfi** [comment]
i think the gtk3.20 version's titlebars are still too much thick. Will this get fixed?
![screenshot from 2016-07-06 21-17-51](https://cloud.githubusercontent.com/assets/9977153/16626643/1cba3b12-43bf-11e6-98ba-aa6e0daf83aa.png)

**Comment by marmis85** [comment]
I'm not really sure if it's related, but I have noticed that if I switch to the Adapta theme and then back to Numix, the headerbars get messed up like the screenshot in the OP.
Then if I switch to Adwaita and back to Numix the problem is resolved.

Using Numix from git master and GTK 3.20 on Arch Linux, no font scale

**Comment by khurshid-alam** [comment]
Any specific way to reproduce the issue?

**Comment by marmis85** [comment]
In my case it happens if you have a Nautilus window open and you switch back and forth between Numix and Adapta themes, Nautilus' headerbar get "stretched" vertically, but I think it's a problem with Adapta because it also breaks Adwaita (I was wrong before)...

**Comment by khurshid-alam** [comment]
@marmis85 Please answer following;
1. Font scale settings
2. What happen when you run `nautilus -q` or `sudo killall nautilus` and then open nautilus through GUI? Does headerbar still remain stretched?
3. Is it reproducible with any other application beside nautilus and terminix?

**Comment by marmis85** [comment]
@khurshid-alam 
1. Font scaling is 1
2. If I kill or quit and then reopen Nautilus the problem is fixed
3. As far as I can tell in my case it happens only with Nautilus

**Comment by megax** [comment]
I rewrite management, headerbar and titlebar.

**Now:**
- Fixed https://github.com/numixproject/numix-gtk-theme/issues/486#issuecomment-230834032
- Fixed titlebar/headerbar height

**Adwaita:**
 **\- Scale 1,0:**
![image](https://cloud.githubusercontent.com/assets/461493/17939544/5f85b182-6a2b-11e6-9bf3-2b4b01e6a483.png)

 **\- Scale 1,5:**
![image](https://cloud.githubusercontent.com/assets/461493/17939459/10a7701e-6a2b-11e6-81fc-3463c958f40f.png)

**Bugged:**
 **\-  Cinnamon:**
![image](https://cloud.githubusercontent.com/assets/461493/17939067/1c0ce65c-6a29-11e6-9939-1577e52dafb9.png)

**Fixed:**
 **\- Cinnamon:**
![image](https://cloud.githubusercontent.com/assets/461493/17939094/37ffccd0-6a29-11e6-9369-ee6e35bd7458.png)

**Sample (not final):**
 **\- Scale 1,0:**
![image](https://cloud.githubusercontent.com/assets/461493/17938698/690d18c0-6a27-11e6-932e-402a8de2b3c4.png)

 **\- Scale 1,5:**
![image](https://cloud.githubusercontent.com/assets/461493/17939518/4b4ecd20-6a2b-11e6-9097-1f77103b59e1.png)

**Comment by megax** [comment]
Final (i color theme...):
**Scale 1,0:**
![image](https://cloud.githubusercontent.com/assets/461493/17945775/993f896a-6a45-11e6-8291-977ea4a697bc.png)

**Scale 1,5:**
![image](https://cloud.githubusercontent.com/assets/461493/17945814/c46113b6-6a45-11e6-9289-47c3a44eea39.png)

@khurshid-alam @lots0logs So it will be good? PR? :) Example code: https://github.com/The-Megax/Numix/commit/472e8352434e2bcc02af1a57c32176ee0ea156bd

Edit: Created PR: https://github.com/numixproject/numix-gtk-theme/pull/521

**Comment by khurshid-alam** [comment]
I don't think we need that many changes. For me, using same left/right padding only for combobbox button fixes the issue. We need to be careful here not to break other things.

**Comment by megax** [comment]
I corrected several things:
- https://github.com/numixproject/numix-gtk-theme/issues/486#issuecomment-230834032
  Bugged:
  ![image](https://cloud.githubusercontent.com/assets/461493/17947943/1959dde0-6a4f-11e6-97f1-30c4a580f62a.png)
  Fixed:
  ![image](https://cloud.githubusercontent.com/assets/461493/17947854/c01d0a0e-6a4e-11e6-965c-0fcb731ed0c0.png)
- optimised toolbar, headerbar, titlebar button size.
- [ toolbar ] [ headerbar and titlebar ] separated

**Comment by megax** [comment]
@khurshid-alam Massive test. I could not find fault.

**Comment by khurshid-alam** [comment]
To All,

Does this still happen after 6cb9d03b04d9cf6aac92bc1d8dee6d20060e6a7e ? Can anyone test?

**Comment by megax** [comment]
Rebased code, please test.

**Comment by megax** [comment]
Tested PR:

**Scale 1,0:**
![image](https://cloud.githubusercontent.com/assets/461493/18080546/54d93da2-6e96-11e6-9a26-5e217666f336.png)

**Scale 1,5:**
![image](https://cloud.githubusercontent.com/assets/461493/18080617/9271e2b8-6e96-11e6-8130-0a3364d649cf.png)

Works well, as Adwaita, arc-theme

**Comment by marmis85** [comment]
@khurshid-alam  some applications still have a slightly different headerbar height
![screenshot from 2016-08-30 18-27-56](https://cloud.githubusercontent.com/assets/1887387/18097921/49add2b8-6ee0-11e6-94f4-993b31e15b26.png)

I like the compactness but IMHO it was prettier before when most of the buttons where squares

**Comment by megax** [comment]
I PR tested or not?

Edit: 16px button + padding, this issue will be...

**Comment by marmis85** [comment]
@megax sorry I didn't see your commit, I will try it, I was replying to @khurshid-alam 's question about 6cb9d03

**Comment by megax** [comment]
Oh... okay :) Thanks :)

Edit: Maximum like this can only be done (Adwaita 1,5 scale):
![image](https://cloud.githubusercontent.com/assets/461493/18101045/91c0c1e8-6eed-11e6-8dff-664f7ab34851.png)

**Comment by marmis85** [comment]
@megax I tried it, it looks good!

the only (very minor) problem I see is that Nautilus' and Gedit's headerbar is still 1px higher
![screenshot from 2016-08-30 20-22-25](https://cloud.githubusercontent.com/assets/1887387/18101711/19edf728-6ef0-11e6-88ff-2bb519d040b6.png)

**Comment by megax** [comment]
Please restart gedit and nautilus, and test :)

I do not have an error (tested: Ubuntu 16.10, Archlinux cinnamon and gnome shell):
![image](https://cloud.githubusercontent.com/assets/461493/18102631/7f684a10-6ef3-11e6-94da-b563c01c15da.png)

New test, no 1px bug =/
![image](https://cloud.githubusercontent.com/assets/461493/18103358/84d8d962-6ef6-11e6-8cd7-794f0c7f2ee9.png)

**Comment by marmis85** [comment]
@megax yes I tried killing all the gtk apps

what I did is updating to numix/master and merging megax/patch05 on top of it, are you sure you don't have some more commits because in your first screen the headerbars are a little darker than mine

**Comment by lots0logs** [comment]
One thing to note is that the headerbar height is not expected to be uniform across all applications that use them. For example, the icon sizes an application uses in its headerbar will affect the headerbar's  height.

**Comment by megax** [comment]
@marmis85 My color theme (https://github.com/The-Megax/Numix), color doesn't matter :)

@lots0logs I think there will be any better.

**Comment by megax** [comment]
@marmis85 Please test/change: https://github.com/megax/Numix/commit/cd4fe82b11b706ea134eade2915888c2deefc464#diff-557b2df12fb26276c4571752f146e701R106 (padding update)

default: `padding: 0 5px;` ($spacing: 5px)

example: `padding: 0 7px;`

**Comment by khurshid-alam** [comment]
Button are not perfectly square because we are not using symmetric padding. And not all gtk-images are perfectly symmetric. I was going to use `min-width=18px`, but I got ugly result for combox button and entries. As I said this is trail and error. 

And I would suggest to avoid testing with font-scale 1.5. IMHO 1.5 is bit of a extreme.

**Comment by khurshid-alam** [comment]
This needs to be rechecked after we merge #542.

**Comment by khurshid-alam** [comment]
@megax Breaks notebook (exccesive tab height) and close button ?

![notebook-tab](http://i.imgur.com/4pskalQ.png)

**Comment by megax** [comment]
@khurshid-alam Notebook fixed: https://github.com/numixproject/numix-gtk-theme/pull/542 Sample code: https://github.com/numixproject/numix-gtk-theme/pull/542/files#diff-1c8d87bb62da4569d069f15371fc41afR201

**Comment by megax** [comment]
@khurshid-alam Slowly I do not see them melt please :)

**Comment by khurshid-alam** [comment]
@marmis85 So everything is fine without the patch? Right? Ignore headerbar and square button issue for now.

**Comment by marmis85** [comment]
@khurshid-alam well the problem when switching themes that I reported here last month still happens, but I doubt it's caused by Numix as it only happens after I switch to Adapta and also breaks Adwaita

still I don't understand why I have 1px difference from @megax when I'm running GNOME/GTK 3.20 on arch as him

**Comment by khurshid-alam** [comment]
@marmis85 
Right. Then it is not a Numix issue.

Both of you same icon theme? He is using headerbar patch from #521. We may include some changes from that.

**Comment by megax** [comment]
@khurshid-alam I use default gnome and gnome-shell icon theme.

**Comment by khurshid-alam** [comment]
Now everything is perfectly symmetric. 

``` css
--- a/usr/share/themes/Numix/gtk-3.20/scss/widgets/_toolbar.scss
+++ b/usr/share/themes/Numix/gtk-3.20/scss/widgets/_toolbar.scss
@@ -9,7 +9,7 @@
     @include linear-gradient($bg);
     @include border($bg);

-    padding: $spacing;
+    padding: $spacing * 2;
     color: $fg;

     &:disabled {
@@ -33,11 +33,11 @@
     .linked > button { @include linked_button($bg); }

     combobox, button {
-        padding: $spacing - 1px;
+        padding: $spacing;

         &.text-button { padding: $spacing; }

-        &.image-button { padding: ($spacing + 1px) ($spacing - 1px) ($spacing + 1px) $spacing; }
+        &.image-button { padding: $spacing; }
     }

     // toolbar separators
```

![headerbar-bug](http://i.imgur.com/BvfoLr4.png)

**Comment by megax** [comment]
@khurshid-alam Please not `padding: $spacing * 2;` It will be too large headerbar, titlebar... =/

**Comment by megax** [comment]
Thus remains flawed:

![image](https://cloud.githubusercontent.com/assets/461493/18141995/ef4e9794-6fbb-11e6-9942-dc5427e2f064.png)
![image](https://cloud.githubusercontent.com/assets/461493/18142031/1425feae-6fbc-11e6-8dc1-6c7aa0c40073.png)

**Comment by marmis85** [comment]
@khurshid-alam @megax I am using numix-icon-theme + numix-circle-icon-theme from git, I tried with the default gnome icon theme but it's the same. Could it be the font? I'm using Noto Sans size 9 for everything

**Comment by megax** [comment]
I'm using Sans Regular.

**Comment by khurshid-alam** [comment]
@marmis85 No. See my previous comment.

@megax Lets c.

**Comment by megax** [comment]
@khurshid-alam just perfect: https://github.com/numixproject/numix-gtk-theme/pull/521 :)

Example:
![image](https://cloud.githubusercontent.com/assets/461493/18142954/2a03f448-6fc0-11e6-9a20-1e0f96d0a9c1.png)

**Comment by marmis85** [comment]
@khurshid-alam @megax it is indeed the font, if I use Sans Regular for the "Interface" font I don't have the 1px difference

**Comment by khurshid-alam** [comment]
@megax Ok. If you feel that strongly :/ . But you made toolbar code quite hazardous and difficult to read.. Can you reform it like this?

## _toolbar.scss (Restructure Sample)

``` css
@import "button";

@include exports("toolbar_extends") {
    %toolbar {
        //all **unique** toolbar related code like padding, border, margin....etc
    }

    %headerbar {         
        // all **unique** headerbar related code
    }

    %titlebar {         
        // all **unique** titlebar related code
    }
}



@mixin toolbar($bg, $fg) {
    //all **common** code for headerbar and toolbar
}

@mixin inline-toolbar($bg, $fg) {
    //code for inline-toolbar
}


@include exports("toolbar") {
    toolbar {
        @extend %toolbar;
        @include toolbar($toolbar_bg_color, $toolbar_fg_color);
        anything-extra {
            //anything else
        }
        &.inline-toolbar { @include inline-toolbar($toolbar_bg_color, $toolbar_fg_color); }
    }

    headerbar {
        @extend %headerbar;
        @include toolbar($toolbar_bg_color, $toolbar_fg_color);
    }


    .titlebar:not(headerbar) {
         window.csd > & {
             //insert your code
         }
         @extend %titlebar;
    }
}
```

Thanks.

**Comment by megax** [comment]
@khurshid-alam Of course I can rewrite in this way, but please admit to that if I rewrite, the tiltbar's and the headerbar's common parts will be still common, because this is how prevail for both. Do you agree with me? :)

**Comment by khurshid-alam** [comment]
Yes. Basically all I am asking to rewrite in that way including your modification from #521

**Comment by megax** [comment]
@marmis85 "I'm using Noto Sans size 9 for everything", Please test, minimal fix code...

@khurshid-alam Rewrite, please check :)

Edit: I test I have tomorrow.

**Comment by megax** [comment]
@khurshid-alam Perfect.
![image](https://cloud.githubusercontent.com/assets/461493/18156067/92dfb8aa-7013-11e6-9098-55507d7f29ba.png)

@marmis85 Tested Noto Sans... 1px bug... Sorry, there is no idea =/

**Comment by marmis85** [comment]
@megax must be something strange in the Noto font family, the others seem to work fine... I can live with Droid Sans, thanks anyways!

**Comment by megax** [comment]
@marmis85 Okay :)

**Comment by lots0logs** [comment]
# Current Master

![2016-09-01_01-37-56](https://cloud.githubusercontent.com/assets/4675662/18157923/afc6ecfa-6fe5-11e6-99e6-e25cf3cbbe14.png)

# #521

![2016-09-01_01-43-26](https://cloud.githubusercontent.com/assets/4675662/18157978/ebad8a62-6fe5-11e6-9ea9-61ebd232f1ff.png)

#521 does fix the titlebar height. However, the headerbar buttons are not good. They are not good on master currently and they are even worse in #521. Just for a point of reference, look at the current state of Numix Frost where its been about a month or so since I last cherry-picked new commits from this repo:

![2016-09-01_01-32-57](https://cloud.githubusercontent.com/assets/4675662/18158101/a906ffd0-6fe6-11e6-94a5-01eb2e99e100.png)

Notice how there really isnt any issue with the headerbar heights? Perhaps a pixel or two on Terminix but my point is that I think the commits made over the last month have taken us in the wrong direction.  
@khurshid-alam Thoughts?

**Comment by megax** [comment]
@lots0logs #521, font size bug... (not button padding bug), reference: https://github.com/horst3180/arc-theme/blob/master/common/gtk-3.0/3.20/sass/_common.scss#L993

https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.20/scss/widgets/_toolbar.scss#L27

working of operation? =/
Idea?

**Comment by megax** [comment]
@lots0logs The proportions of the same error as now 1 month ago. Only minor buttons. Now I tested everywhere, #521 symmetrical buttons. Old basic principle wrong. Already I looked back and forth in the code ... =/ Now #521 most optimal.

**Comment by lots0logs** [comment]
@megax Yeah I know the code really could use a complete rewrite for the buttons and toolbars but until we have time for that we will have to do what we can without breaking other areas.

**Comment by megax** [comment]
@lots0logs I understand, therefore trying not to make new mistakes.

**Comment by khurshid-alam** [comment]
@lots0logs 

We just changed button height/width to 16x16 (I wanted 16x18) which wasn't a proportional change , so I don't expect everything to fit in place  immediately. My intention is to use perfectly square button just like it used to. But that requires to fix toolbar code first which we are doing in #521. Also in your screenshot for master it looks really ugly.....Could it be the icon theme?

In 521, buttons are better but looks bad due to less toolbar/headerbar height, which we can fix later. And beside, 521 is still WIP......so we are not merging that yet.

Also there is this issue with headerbar. Well,  outside gnome-shell and excluding some gnome apps, headerbar height has never been equal for different apps in the first place. It has been like this since Gtk-3.14.

As of now I am watching over how it goes, but rest assured, we are  moving forward, only for better, I hope.

**Comment by megax** [comment]
@khurshid-alam "Also in your screenshot for master it looks really ugly.....Could it be the icon theme?"
Not icon theme, `padding: $spacing * 2` and headerbar bug. Unfortunately, the size of the problem grows.
