### ISSUE TITLE
Numix theme should show in MATE's theme picker

### ISSUE THREAD

**Issue by jbicha** [numixproject/numix-gtk-theme#488]
Numix doesn't show up in Mate's theme picker (mate-appearance-properties) after it's installed.

It looks like all that's missing is for index.theme to select a default icon theme.

I suggest we default to Numix. Unfortunately many users may not have it installed. We'll need to encourage distros to have numix-gtk-theme depend on numix-icon-theme.

Here's  a screenshot of what it looks like if users don't have numix-icon-theme installed:
![numix-missing-icon-theme](https://cloud.githubusercontent.com/assets/876259/16136806/d7dc7a82-33fb-11e6-8c91-4b3501d46cad.png)

**Comment by jbicha** [comment]
Otherwise, distros can patch the line to say IconTheme=Adwaita or whatever

**Comment by lots0logs** [comment]
Does this file follow the same spec as icon themes in regards to fallbacks? I'll need to check on it before merging. Anyway, thanks! We'll get to it asap.

**Comment by jbicha** [comment]
Maybe the Icon-Theme should be set to Numix-Circle.

It's a bit tricky though because I prefer upstream app icons like Firefox's, but Numix alone doesn't theme the GNOME Settings app enough.

As far as I know, mate-appearance-properties is the only thing that pays attention to the Icon-Theme setting in index.theme.

**Comment by khurshid-alam** [comment]
I just added `numix-icon-theme` under suggests (http://bazaar.launchpad.net/~numix/numix/deb-packaging/view/head:/debian/control) for Ubuntu. As of now, We can not add it under `depends` or `recommends` as the icon-theme is only available under PPA for Debian/Ubuntu unlike numix-gtk-theme which is also available on Ubuntu repo provided by `shimmer-themes` package. Everything will get fixed once we bring both gtk & icon theme in debian.

And if the icon-theme is not installed it will simply fallback to gnome/high-color.

**Comment by jbicha** [comment]
It would be a lot easier for me to get numix-icon-theme into Ubuntu if you guys actually [tagged a release](https://github.com/numixproject/numix-icon-theme/issues/855).

**Comment by megax** [comment]
@jbicha, @khurshid-alam Still having trouble?

**Comment by jbicha** [comment]
By the way, I did try last summer (Northern Hemisphere) to have numix-gtk-theme Recommend numix-icon-theme in Debian/Ubuntu but several developers thought Suggests was sufficient. numix-icon-theme is a pretty large package and I'm sure there are a lot of people who use the theme without the icons.
