### ISSUE TITLE
Colors not loaded right?

### ISSUE THREAD

**Issue by ozcelebi** [numixproject/numix-gtk-theme#49]
Some texts are unreadable because of their color, is the background color loaded wrong or the font color ?

I tried to fix it, but I couldn't find the appropriate color..

![screenshot](https://f.cloud.github.com/assets/3045769/710045/dfe37acc-de73-11e2-889f-69edd66a9704.png)

**Comment by satya164** [comment]
What is your Ubuntu version and GTK3 version? Numix supports GTK 3.6 and up.

**Comment by ozcelebi** [comment]
Oh I have 3.4.2, i'll try to update if possible. Thanks.

**Comment by ozcelebi** [comment]
I upgraded, looks fine now.
