### ISSUE TITLE
Copr repo update

### ISSUE THREAD

**Issue by lburgazzoli** [numixproject/numix-gtk-theme#491]
I see that the latest copr build for fedora is dated 2016-04-17, would it be possible to do a new release for Numix v2.6.0 ?

**Comment by encounter** [comment]
Numix themes are now available in the main Fedora repositories. You can switch to those versions by running 

```
dnf copr disable numix/numix
dnf distro-sync
```

It will say "downgrading" for the Numix packages, but that's only because the versioning is different.

**Comment by lburgazzoli** [comment]
thx
