### ISSUE TITLE
Xubuntu Numix theme and gtk2-engines-murrine

### ISSUE THREAD

**Issue by makitso** [numixproject/numix-gtk-theme#492]
Seems that a recent update to gtk2-engines-murrine on xubuntu 16.04 causes the desktop icon or folder text and shadows to diverge.  Problem does not affect any of the other xubumtu themes.

**Comment by makitso** [comment]
Ok, have confirmed that the standard Nimux theme has a problem with the recent upgrade to GTK2-engines-murrine on the xubuntu 16.04 system.  In gtkrc in folder usr/share/themes/Numix/gtk-2.0, if you change line 531 to read textstyle = 0 the problem goes away.

**Comment by ghost** [comment]
I can confirm this. After Fedora 24 update ,which got me new version of gtk-murrine-engine-0.98.2-9.fc24.x86_64, I had text floating left to the icon with shadow in usual place. Fix provided by @makitso works. I also found reddit thread where ubuntu user had same problem, so maybe we need a fix
