### ISSUE TITLE
Fedora packages the dependencies with a different name

### ISSUE THREAD

**Issue by ajarara** [numixproject/numix-gtk-theme#493]
on fedora 24
glib-compile-schemas
    is provided by glib2-devel
gdk-pixbuf-pixdata
    is provided by gdk-pixbuf2-devel

just updating the readme would save a lot of people time.

**Comment by sspreitzer** [comment]
Hi @alphor 

I try to understand the problem. Can you please explain a bit further what the problem situation is?
Can you even provide a pull request for to change the README so we see what you are proposing?

**Comment by lots0logs** [comment]
@alphor As of about a month ago, the theme is available in the official fedora repositories so you shouldn't need to worry about handling dependencies manually.

**Comment by ajarara** [comment]
Ooh, you're right.

I can PR the Readme and add the names of the libs anyway, but if they're in the repos, it doesn't really matter.
