### ISSUE TITLE
Color customized

### ISSUE THREAD

**Issue by ShawsZzz** [numixproject/numix-gtk-theme#494]
Hi artists: 

I need your help! I have installed the black numix on my ubuntu 16.04, but i am wondering how to exchange the "menu_bg_color" and “menu_fg_color”...

**Comment by khurshid-alam** [comment]
You mean Dark Numix? Can you post a screenshot about the issue?

**Comment by ShawsZzz** [comment]
@khurshid-alam 
Thanks for your attention! 

I install Numix by adding ppa and then typing "sudo apt install numix-gtk-theme". Now i want to make some change, for example, make the "menu_bg_color" white and the "menu_fg_color" black. Sorry for my English...

Note: There is a screenshot bug(the blurry menu) in the image, not Numix's bug. Here's the screenshot image: 
![hi](https://cloud.githubusercontent.com/assets/20335680/16767430/0366f9fe-4872-11e6-90b9-6981406121f4.png)

**Comment by khurshid-alam** [comment]
You can change color values in https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.0/scss/widgets/_menu.scss for .menu, .menubar and popover section. Then you need to recompile the theme.
