### ISSUE TITLE
Missing gtk.css file

### ISSUE THREAD

**Issue by gaea44** [numixproject/numix-gtk-theme#495]
Hi,

I'm trying your theme under my Debian 8.5 with xfce 4.10 and lightdm enabled.
All seems great, but some apps shows either glitches (Firefox 47.0.1) or are completely transparent (Gedit) :
![ff](https://cloud.githubusercontent.com/assets/8070041/16770078/88cac052-484b-11e6-9a37-5f47710d33eb.png)
![gedit](https://cloud.githubusercontent.com/assets/8070041/16770079/88cc25fa-484b-11e6-9b6a-660d4eee6d22.png)

When searching for the logs, I've found the message error :
`(firefox:6191): Gtk-WARNING **: Theme parsing error: gtk.css:1:61: Failed to import: resource in « /org/numixproject/gtk/dist/gtk.css » doesn't exists`

Is there any workaround for this?

Thanks

**Comment by khurshid-alam** [comment]
How did you install it? @gaea44 ?

**Comment by khurshid-alam** [comment]
On Debian you can directly install from this deb. https://launchpad.net/~numix/+archive/ubuntu/ppa/+files/numix-gtk-theme_2.6.0+514~201607261318~ubuntu16.04.1_all.deb
