### ISSUE TITLE
Terminal dark tabs

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-gtk-theme#497]
Hi, someone knows how to change the terminals tab-bar to dark or more like numix?
They never match the theme, look (terminator in front of gnome-terminal):

![screenshot from 2016-07-15 22-59-02](https://cloud.githubusercontent.com/assets/1277920/16892141/f2706c50-4adf-11e6-8b54-1414dfe94c2a.png)

Ps.: Gnome-terminal tab height is huuuge. I hate it. :)

**Comment by khurshid-alam** [comment]
With Gtk-3.20, you can use dark variant for gnome-terminal. Go to Edit → Preferences and set Variant to dark.

![gnome-terminal-dark](https://cloud.githubusercontent.com/assets/922874/15186000/965703ba-179b-11e6-9c4f-5835f7ef1ee8.png)

**Comment by leoheck** [comment]
But there are other terminals... I am asking about the theme customization.

**Comment by satya164** [comment]
We can by default have dark tabs in terminals.

**Comment by khurshid-alam** [comment]
@leoheck Dark mode was removed from terminal in 3.16 and returned in 3.20. Other terminals should respect global theme variant. If Terminix doesn't do that then it is a bug in terminix.

That said I am ok with dark mode as default for Terminals.

**Comment by leoheck** [comment]
@khurshid-alam my gnome-terminals `3.18.3` don't have the dark variant you described. At least under the Preferences as you said. Also I did not mention terminix, I told `terminator`, but I believe it is the same issue for each `*term*` name we find. I am looking for a numix-like customization for the white tab bars that does not fit well with the theme. I use terminas 100% of time I believe others users do the same. So, why not to improve its theme to be more numix.

**Comment by khurshid-alam** [comment]
>  my gnome-terminals 3.18.3 don't have the dark variant you described.

That's because gnome-dev remove that feature in 3.18. Anyway, dark-mode (which will be default) for 3.18 is on the way.

**Comment by khurshid-alam** [comment]
Fixed in 749cfa3. 

![dark-mode-terminal](http://i.imgur.com/qJYhNpW.png)

**Comment by leoheck** [comment]
Yeah, I installed numix on a new pc today and became surprised that gnome-terminal was like your picture. Good job @khurshid-alam!

Please, it is possible to extend this to other terminals like terminator?
