### ISSUE TITLE
GTK 3.18 :: Firefox :: Address suggestion panel has too dark color for URL

### ISSUE THREAD

**Issue by ingria** [numixproject/numix-gtk-theme#499]
Dark blue color (#3F51B5) is nearly unreadable:

![numix](https://cloud.githubusercontent.com/assets/2178368/16991270/0cc6b044-4eac-11e6-9cbe-ea6c8858b279.png)

Ambiance has an orange color for both URL and selection background (#DF7245):

![ambiance](https://cloud.githubusercontent.com/assets/2178368/16991306/25860418-4eac-11e6-9c7c-80063392eff2.png)

Suggestion: use color #F0544C for URL.

_Related issue: #458_

**Comment by khurshid-alam** [comment]
Changing url color globally could affect chromium and other browser.  If its a firefox specific issue, it should only be fixed for firefox.
