### ISSUE TITLE
Scrollbar takes Focus Color for Background

### ISSUE THREAD

**Issue by cldx** [numixproject/numix-gtk-theme#5]
dat title.....it's kinda distracting to always have it appear like it's focused. 

Also, in GTK2(3?) some Scrollbar Backgrounds are red? I assume this was a mistake.

**Comment by satya164** [comment]
Did not quite get it. Scrollbars are only red when you click on them. So...

**Comment by cldx** [comment]
![geany](https://f.cloud.github.com/assets/470526/216803/8557484c-84d5-11e2-9d53-77eef4608244.png)
This is Geany, so it's GTK2. 

...wait,let me do a pull first, maybe it just resolved itself since i had this Theme Inheritance Problem.

**Comment by cldx** [comment]
Nope, it's still there...i was wondering if you just didn't get to this by now, but i reported it anyway :)

**Comment by satya164** [comment]
It is weird. I wonder how you get such weird theme errors! Do you have a .gtkrc file in your home folder or something?

**Comment by cldx** [comment]
No .gtkrc 
It's a purely fresh install of Fedora 18.
Linked .local/share/themes to .themes, nothing in /usr/share/themes
It's happening both on my Laptop and Desktop with the exact same setup.

BTW...the Scrollbars DO become red when i drag them, not on hover.
It's awesome red on red :)

Maybe it's a Geany Thing...

**Comment by satya164** [comment]
Does this still happen?

**Comment by me4oslav** [comment]
Nope, but then again - it never happened for me.

**Comment by cldx** [comment]
This still happens to me on Fedora 19 with a pretty fresh install.
I just extracted the archive from git to /usr/share/themes and it's very much red in at least Geany, Inkscape and Firefox. Does this happen to nobody else? I mean COME ON xD

**Comment by rickpalmeira** [comment]
![screenshot from 2013-06-24 11 44 46](https://f.cloud.github.com/assets/4140033/695947/a650ac1e-dcdc-11e2-8cec-2524015e6926.png)
I have a similar one here... It's not the whole bar, only the ending and beginning of them...
- Firefox on Ubuntu 13.04 using unity

**Comment by satya164** [comment]
@Rickinbsb Your bug has been fixed recently. Try the git version. 

@cldx What's your murrine engine version?

**Comment by satya164** [comment]
The issue is caused as murrine engine is not installed. Installing murrine engine will fix it. Hence closing the issue.

**Comment by rickpalmeira** [comment]
Since the last numix update, I'm facing this issue on skype...

![screenshot from 2013-07-03 12 58 37](https://f.cloud.github.com/assets/4140033/744306/e72894ee-e3f9-11e2-8801-902d32655c90.png)

This is skype 4.2 using the gtk+ option

**Comment by satya164** [comment]
@Rickinbsb You don't seem to have murrine engine installed. Please install murrine engine.

**Comment by rickpalmeira** [comment]
Actually, I do have it... (sorry if you are talking about a different one)
![screenshot from 2013-07-05 11 35 55](https://f.cloud.github.com/assets/4140033/754173/3efc5bb0-e580-11e2-8867-71fc231f4d3f.png)

**Comment by satya164** [comment]
Hmm... I'll install skype and try. In the meantime, can you install the package "thewidgetfactory", run `twf` in a terminal and give me the outputs?

Also, try the GIT version of Numix.

**Comment by rickpalmeira** [comment]
There it is:

rick@HorusUbuntu:~$ twf

(twf:11401): Gtk-WARNING **: GtkSpinButton: setting an adjustment with non-zero page size is deprecated

(twf:11401): Gtk-WARNING **: GtkSpinButton: setting an adjustment with non-zero page size is deprecated
rick@HorusUbuntu:~$

I'll download the git version and try it asap

---

update:

I'm using the git version right now and the problem is still there
![screenshot from 2013-07-05 16 52 03](https://f.cloud.github.com/assets/4140033/755362/c2c4b646-e5ac-11e2-9507-cc17a2bcdc00.png)

maybe it is a skype-only error and we are beating a dead horse XD

**Comment by gfavaro** [comment]
You need to install murrine 32 bits.

on fedora:  "sudo dnf install gtk-murrine-engine.i686"
