### ISSUE TITLE
Plank has green icon badges on Ubuntu Mate.

### ISSUE THREAD

**Issue by acutbal** [numixproject/numix-gtk-theme#501]
Hi,

I've realized that Plank has green icon badges on Ubuntu Mate 16.04, I don't know if this is a bug or a feature. This only happens with Numix theme, others are not affected.

![pantallazo-2016-07-21 10-17-37](https://cloud.githubusercontent.com/assets/2278584/17016101/c08ef894-4f2d-11e6-8b21-0a3a6c27855e.png)

Best regards!!

**Comment by khurshid-alam** [comment]
It's a feature. `Green` signifies **unread** messages. And it's not a gtk-theme issue.

**Comment by acutbal** [comment]
@khurshid-alam My apologies, I thought it was a bug because in other themes the icon badges are red.

Best regards!! :smile:
