### ISSUE TITLE
Invisible buttons on active windows - Ubuntu 16.04, Unity 7.4, GNOME 3.20

### ISSUE THREAD

**Issue by LogicStuff** [numixproject/numix-gtk-theme#502]
Active windows don't show the control buttons:

![a](https://cloud.githubusercontent.com/assets/11589772/17022083/48b048e0-4f4c-11e6-98d5-8fa4c1a25051.png)

(I'm able to see them for a while in an animation when I close a window)

Is this intentional (for differentiation of the active window)? If yes, couldn't it be done another way?

**Comment by LogicStuff** [comment]
On the other hand, shouldn't be window title bars dark grey - `#444444`, same as the menu bar? Maybe there's a problem with my configuration.

**Comment by khurshid-alam** [comment]
How exactly are you using Unity with Gtk-3.20 in 16.04? If you are using Ubuntu-Gnome ppa, it is only meant for gnome shell. Unity with Gtk-3.20 in 16.04 will appear broken.

**Comment by LogicStuff** [comment]
I'm using it wrong, then. But it's not that broken.
