### ISSUE TITLE
GTK Error with Python Plotting

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#506]
Thanks for the fantastic theme! I've encounter a small issue when plotting figures using matplotlib in Python. Specifically I get the following error with the simplest plotting command:

`Gtk-WARNING **: Theme parsing error: gtk-dark.css:67:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version`

When I turn off the dark version I get the same error just without the '-dark' prefix. I've confirmed that this is not a problem with neither Python nor matplotlib - the error disappears when I switch to a different theme.

Happy to run any code that would help to locate the error. I'm on Arch Linux with newest Gnome desktop. The error can be replicated with:

`from matplotlib import pyplot as plt`
`plot_kd = plt.figure()`

Many thanks for looking into this.

**Comment by megax** [comment]
Fixed: https://github.com/numixproject/numix-gtk-theme/pull/525
