### ISSUE TITLE
GTK 3.18 :: Firefox 48 :: New address suggestion panel

### ISSUE THREAD

**Issue by ingria** [numixproject/numix-gtk-theme#507]
New panel in Fx 48 has:
- white background 
- favicon
- single-line design

![2016-08-06 07-14-58](https://cloud.githubusercontent.com/assets/2178368/17454625/f38bdf28-5bad-11e6-8695-57ca1f378017.png)

**Comment by khurshid-alam** [comment]
@codefuhrer Fixed with firefox 50. No?
