### ISSUE TITLE
Missing and unsynchronized SVGs

### ISSUE THREAD

**Issue by Sakrecoer** [numixproject/numix-gtk-theme#508]
Hi,

Over at Ubuntu Studio, we are looking into customizing the colors of this fantastic theme to our color-scheme, and while doing so, i noticed that the SVGs aren't synchronized with the PNGs. That is; the source SVG-files have a completly different look from the PNG-files used by https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.0/gtk.gresource.xml

Also, some PNGs are missing their SVG counter-part such as: https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.0/assets/radio-checked.png

I went through all the SVGs and synced them as good as I could to the current PNGs, also I managed to recreate the missing SVGs without major trouble, but they are not 100% similar; i lack the perfect tiny little shade of red in the bottom of the radio-buttons and the checkboxes .

Would you be so kind as to provide the source SVGs? If they have gone lost, would you be interested in a Pull Request from me with my replicas?

Regardless, i also want to thank you for your awesome work! :)

Yours,
*Sakrecoer

**Comment by khurshid-alam** [comment]
These are old svgs from old design. When we brought new assets, only png files are uploaded (introduced in bf32925).

May be @satya164 can tell where are those new asset-svgs?

**Comment by satya164** [comment]
@khurshid-alam I actually have a `.sketch` file. Right now I'm at office, but ping me later tonight and I'll export and send you the SVGs.

**Comment by khurshid-alam** [comment]
@satya164 Cool. Thanks.

**Comment by Sakrecoer** [comment]
Thank you for your quick respone @satya164 and @khurshid-alam !

Looking forward to those assets!

Thank you for your time and consideration!

Yours,
Sakrecoer

**Comment by Sakrecoer** [comment]
Hi guys! Not too sure when tonight is under your latitudes, and i don't mean to be nagging. Just thought i'd poke the issue :) Hope you don't mind...

Thankful regards,
Sakrecoer

**Comment by satya164** [comment]
Sorry. Seems @khurshid-alam forgot to ping me. Here is the zip with SVGs

[numix-assets.zip](https://github.com/numixproject/numix-gtk-theme/files/416643/numix-assets.zip)

**Comment by khurshid-alam** [comment]
Ah. Sorry. Completely forgot about that. But it seems there is some sort download problem.

**Comment by Sakrecoer** [comment]
Seems the download works fine here! Thank you guys, means a lot for us!!

**Comment by khurshid-alam** [comment]
We can not use new assets svgs yet. Because of this-> https://github.com/numixproject/numix-gtk-theme/pull/528#issuecomment-242781686

**Comment by Sakrecoer** [comment]
thank you @khurshid-alam ! I noticed it, but haven't got the time to report it yet. Sorry for that.
On a similar note, the zip filed shared in this [reply](https://github.com/numixproject/numix-gtk-theme/issues/508#issuecomment-239626573) is missing the SVG version of `pane-handle.png` as invoked by `gtk.gresource.xml` might be specific to the[ zip file](https://github.com/numixproject/numix-gtk-theme/issues/508#issuecomment-239626573), but worth being brought toy our attention. :)

Thank you for looking into this!

**Comment by satya164** [comment]
@khurshid-alam When I open the SVGs in browser they all have borders. I think there is issue with SVG format exported from Sketch.

I'm attaching the file as PDF here from which someone should be able to take the vectors out in Inkscape. I've also exported them to EPS if it makes the conversion easier.

[numix-assets.pdf](https://github.com/numixproject/numix-gtk-theme/files/441265/numix-assets.pdf)
[numix-assets.zip](https://github.com/numixproject/numix-gtk-theme/files/441383/numix-assets.zip)

**Comment by Sakrecoer** [comment]
thank you @satya164 ! Awesome! I might as well do that during this week. Will submit a pull request whenever i'm done :)

**Comment by khurshid-alam** [comment]
@satya164 I also thought they (svgs) were not properly exported. Thanks for EPS. :)

**Comment by lots0logs** [comment]
Just fyi, I saved links to the assets for future reference in [the wiki](https://github.com/numixproject/numix-gtk-theme/wiki)

**Comment by Sakrecoer** [comment]
@satya164 may i ask where the EPS are? maybe i missed something but, the zip you link i[n this reply](https://github.com/numixproject/numix-gtk-theme/issues/508#issuecomment-242989050) contains SVGs 

ps. @lots0logs i tried the wiki link and the zip listed there also contains SVGs, instead of EPS as stated on the link

**Comment by satya164** [comment]
@Sakrecoer Oops. Seems I uploaded the wrong file. Uploading the correct one now. Thanks.

**Comment by satya164** [comment]
@Sakrecoer Check now.

**Comment by Sakrecoer** [comment]
@satya164 Thank you!! \o/

**Comment by satya164** [comment]
@Sakrecoer BTW not sure if EPS can handle gradients and stuff. So probably editing the PDF is the best bet.

**Comment by satya164** [comment]
If it's not possible to extract out proper SVGs, let me know and I'll try exporting them from Affinity Designer which has better SVG support.

**Comment by Sakrecoer** [comment]
@satya164 yes, i just saw that... was wondering if it was because of inkscape's interpretation of EPS. If you have some spare time to try with Affinity Designer, please do. Otherwise, all good, it should be fine with the PDF, just more manual work :smile_cat:

**Comment by satya164** [comment]
@Sakrecoer I can do that over the weekend since it'll be manual work of exporting each item one by one.

**Comment by Sakrecoer** [comment]
@satya164 ok, if it is manual work for you too, then i propose you relax until i submit mine sometime before next Friday. Would i have made lots of mistakes or done it wrong, I'll leave it up to you, fair deal? :)

**Comment by satya164** [comment]
@Sakrecoer Sounds good :D

**Comment by satya164** [comment]
What'll be cool is, if we can keep all SVGs in one file and export them to multiple files. This is not very simple with Inkscape, but once setup, should be good to go.

**Comment by Sakrecoer** [comment]
I suppose that would require a file with defined grid. I am afraid i don't have the skills to do the scripting required afterwards. However, I noticed some of the assets are 32x32 (grid-selected-*) while the rest is 16x16. If this distinction is necessary, can we still have them in the same file?

**Comment by satya164** [comment]
@Sakrecoer Yeah, we need those at different size. Exporting shouldn't be very hard.

http://typethinker.blogspot.in/2010/07/exporting-slices-from-inkscape.html

**Comment by Sakrecoer** [comment]
looking into it now. I'm still missing an asset for `pane-handle.png` ... It is listed in `gtk.gresource.xml`, but perhaps it is not needed anymore?

**Comment by megax** [comment]
Used: https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.20/scss/apps/_mate-applications.scss#L24

**Comment by Sakrecoer** [comment]
looking at the new PNGs, `pane-handle.png` appears to be in sync with the old SVG for it 
https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.0/assets/pane-handle.svg
https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.0/assets/pane-handle.png

I'll use that one :)

**Comment by Sakrecoer** [comment]
Here you go: https://github.com/numixproject/numix-gtk-theme/pull/549

Note that i didn't touch the PNGs that were in your master. I tested the script and the result though, and it worked like a charm!
