### ISSUE TITLE
gtk3 has weird window menu items

### ISSUE THREAD

**Issue by laur89** [numixproject/numix-gtk-theme#509]
Gtk3 version has weird window menu items (if that's the name) - [see the '_MeldFileEdit..._' section](https://i.imgur.com/dqktz94.png)

Not sure if bug, but something looks a bit off.

Running Debian stretch, no desktop environment.
gtk ver **3.20.6-2**

**Comment by khurshid-alam** [comment]
Not sure what's the issue here?...Meld I think, using Gtk-2.

**Comment by laur89** [comment]
Issue is that the window menu buttons don't appear to be properly formatted. No styling, and see how they are all together without any spacing.

[meld](http://meldmerge.org/) uses gtk3+;
tested it also with [go-for-it](https://github.com/mank319/Go-For-It), which is gtk3 app as well - same result.

**Comment by khurshid-alam** [comment]
Numix theme version? Are you using it from PPA?

**Comment by laur89** [comment]
Built it according to the project readme; ver is the current state of master.

**Comment by khurshid-alam** [comment]
Can you post bigger screenshot? From the above screenshot, it looks like you are still using our old theme.

**Comment by laur89** [comment]
Once I get back from work.

**Comment by laur89** [comment]
[full screen shot of meld](https://i.imgur.com/tlOhvT1.png)

**Comment by megax** [comment]
Tested Arch linux (meld 3.16.2-1)
![image](https://cloud.githubusercontent.com/assets/461493/17838055/d2f1159a-67c3-11e6-8ec3-e7d8eba1f342.png)

**Comment by khurshid-alam** [comment]
@megax In the above image everything looks good. Or is there a issue?

**Comment by megax** [comment]
@khurshid-alam there are errors, for example: `black sperator`, `button default color` (not background color) ... but it is not meld an error

Sample bug:
https://github.com/numixproject/numix-gtk-theme/issues/403

**Comment by laur89** [comment]
Any idea why the 'MeldFileEdit...' window buttons are right next to each other, without any spacing?

**Comment by khurshid-alam** [comment]
@laur89 Meld using gtk image button with margin manually set to 0 (instead of leaving as default). You can test this with inspector `GTK_DEBUG=interactive meld`
