### ISSUE TITLE
Black tab bar [gtk 3.8]

### ISSUE THREAD

**Issue by hotice** [numixproject/numix-gtk-theme#51]
The tab bar in Gedit and probably other places too, is black when using Numix with GTK 3.8. This didn't occur with GTK 3.6.

Screenshot:
![numix-tabbar-bug](https://f.cloud.github.com/assets/325449/729351/b668957c-e230-11e2-99b0-5011454cbc03.png)

**Comment by satya164** [comment]
The bug is due to overlay-scrollbars. Disable them. I'll add a patch for Ubuntu in next release (the patch turns the desktop grey in other distros).

You can also add the following in gtk-widgets.css,

```
* {
    /* inherit colors from parent */
    color: inherit;
    background-color: inherit;
}
```

**Comment by satya164** [comment]
Fixed in PPA.
