### ISSUE TITLE
Main color switched from #333333 to #444444 ?

### ISSUE THREAD

**Issue by Sispheor** [numixproject/numix-gtk-theme#510]
After a fresh install of Ubuntu 16.04 and Numix from the ppa.
The main color is now lighter. I used a color piker to check the value of the color. It's #444444.

If I look at the [official website](http://satya164.github.io/numix/), the main color should be #333333. Doesn't it?

Here is a screenshot [![#444444.png](https://s9.postimg.org/r3qxh2yun/444444.png)](https://postimg.org/image/5u3b68ijv/)

The bottom part of the console is set to #333333 like before to see the difference.

**Comment by khurshid-alam** [comment]
Yes. It is due to new design.
