### ISSUE TITLE
GTK3-theme for xfce4-notifyd

### ISSUE THREAD

**Issue by killermoehre** [numixproject/numix-gtk-theme#511]
Hi,

with xfce4-notifyd 0.3.0 the conversation to GTK3 was done. But now a new theme is needed. See https://git.xfce.org/apps/xfce4-notifyd/tree/README?id=xfce4-notifyd-0.3.0 for hints.

**Comment by lots0logs** [comment]
@sammko Thanks, we'll take a look at your PR ASAP!
