### ISSUE TITLE
Issues with Rhythmbox 2.99.1 [GTK 3.8]

### ISSUE THREAD

**Issue by hotice** [numixproject/numix-gtk-theme#52]
Rhythmbox 2.99.1 (with GTK 3.8) looks really bad when using Numix: the sidebar doesn't have any separators, and there are black areas all around the UI. See the screenshots below:

![numix-rhythmbox_2](https://f.cloud.github.com/assets/325449/729368/63b27e14-e231-11e2-93e0-bc90f903d74b.png)
![numix-rhythmbox-1](https://f.cloud.github.com/assets/325449/729369/64c7848e-e231-11e2-9d5a-d3907bde1ffc.png)

**Comment by satya164** [comment]
This is the same issue as #51

**Comment by satya164** [comment]
Fixed in PPA.
