### ISSUE TITLE
Bug with Numix and LibreOffice Calc

### ISSUE THREAD

**Issue by marcogiannini** [numixproject/numix-gtk-theme#53]
Hi, I have a little bug with Numix and LibreOffice Calc. With this theme tabs are very small.
This is a screenshot 
![schermata del 2013-07-04 20 42 02](https://f.cloud.github.com/assets/4943897/751097/bfcf7a12-e4e8-11e2-8743-72ce8a38457b.png)

The problem is similar with elementary theme and here there is a fix http://www.elementaryupdate.com/2013/04/libreoffice-on-elementary-part-2.html

**Comment by wimstefan** [comment]
Same problem here.

I see that GtkScrollbar::slider-width is now set to 10 but the sliders are still tiny ... raising the value to 16 gives a reasonable size.

Could that be changed in the repository as well?

**Comment by satya164** [comment]
No. It cannot be changed in the theme. you can use the following workaround instead.

Create a file .gtkrc-libreoffice in your home folder with the following content,

```
style "libreoffice-scrollbar" {
GtkScrollbar::trough-border = 3
}

widget_class "*" style "libreoffice-scrollbar"
```

Then launch libreoffice with the following command,

`GTK2_RC_FILES=$HOME/.gtkrc-libreoffice libreoffice`

**Comment by wimstefan** [comment]
Thanks for your quick response satya164!
But if I try to use your workaround I get a completely un-themed libreoffice :-/
I certainly must do something wrong?

**Comment by satya164** [comment]
@wimstefan Hmm...

You can try adding the following at the start of the .gtkrc-libreoffice file,

`include  '/usr/share/themes/Numix/gtk-2.0/gtkrc'`

Change /usr/share/themes/ to wherever the theme is installed.
