### ISSUE TITLE
Places icons too close to edge in window

### ISSUE THREAD

**Issue by SiriusFuenmayor** [numixproject/numix-gtk-theme#531]
![issue_numix](https://cloud.githubusercontent.com/assets/8355915/18030022/b9219614-6c76-11e6-8876-744b7fece0ee.jpg)

**Comment by SiriusFuenmayor** [comment]
This is with the last version of the numix theme in Ubuntu 16.04

**Comment by SiriusFuenmayor** [comment]
This is in the last version of the numix theme in Ubuntu 16.04

**Comment by lots0logs** [comment]
Where did you install the theme package? Did you use [our PPA](https://launchpad.net/numix)? It doesn't look like you have the latest version.

**Comment by wadie** [comment]
I'm having this as well on Ubuntu 16.04 and I think I have the latest version of the theme.

**Comment by khurshid-alam** [comment]
@wadie Are you sure that you are using latest version from PPA? Please use the PPA as the vesion in the repo is tool old.

**Comment by wadie** [comment]
This is what I have in numix-ppa-trusty.list

> # deb-src http://ppa.launchpad.net/numix/ppa/ubuntu trusty main

Not sure if I should remove the hashtag, but still the same anyway..

**Comment by khurshid-alam** [comment]
Which Ubuntu version are you using? Trusty is not supported any more. If you are on 16.04, please remove the ppa add it with apt:

``` sh
sudo add-apt-repository ppa:numix/ppa
sudo apt-get update
sudo apt-get install numix-gtk-theme
```

**Comment by wadie** [comment]
Beautiful, thanks!
