### ISSUE TITLE
GTK 3.20 :: Nemo :: Patch-bar padding bug.

### ISSUE THREAD

**Issue by megax** [numixproject/numix-gtk-theme#548]
![image](https://cloud.githubusercontent.com/assets/461493/18106693/2c003b78-6f05-11e6-8707-502b5d2fa846.png)

**Comment by megax** [comment]
@lots0logs Idea? =/

**Comment by lots0logs** [comment]
This is a side affect of the recent changes to buttons. I dont have time to check it now but I will asap!

**Comment by megax** [comment]
Bug source: https://github.com/numixproject/numix-gtk-theme/blob/master/gtk-3.20/scss/apps/_nemo.scss#L49

```
            &.primary-toolbar button {
                min-width: 28px;
                padding: 3px;
            }
```

**Comment by megax** [comment]
@lots0logs Fixed bug: https://github.com/numixproject/numix-gtk-theme/pull/568

**Comment by lots0logs** [comment]
@megax Hmm..in your screenshot the toolbar buttons shape changed. We dont want them to look like rectangles :grimacing:

**Comment by megax** [comment]
@lots0logs Idea? :)

**Comment by lots0logs** [comment]
I'm going to try and get a patch submitted to nemo for adding a css selector for the pathbar. There really is no way to properly target the pathbar currently so I am sure the patch will be accepted. I just have to find the time to do it :grimacing:

**Comment by megax** [comment]
@lots0logs related PR: #565

**Comment by megax** [comment]
@lots0logs Minimal fixed `padding: 0 ($spacing + 4px);`: ![image](https://cloud.githubusercontent.com/assets/461493/18813817/8c37d18e-8307-11e6-9f3d-da47f204c2f5.png)

`padding: 0 ($spacing + 5px);`:
![image](https://cloud.githubusercontent.com/assets/461493/18813840/5e63d5ea-8308-11e6-9d3f-f47c939acc90.png)

Which one should be?

**Comment by lots0logs** [comment]
the second one :+1:

**Comment by megax** [comment]
Done.
