### ISSUE TITLE
Black background in Gnome-Calendar

### ISSUE THREAD

**Issue by beanaroo** [numixproject/numix-gtk-theme#55]
I know gnome-calendar isn't stable yet and probably uses a lot of custom widgeting but I thought I'd mention this as I don't experience the bug with any other GTK theme. I am not sure if this is related to Numix, could just be a missing style.
![screenshot from 2013-07-24 12 31 53](https://f.cloud.github.com/assets/1748909/845935/aef4a838-f3f8-11e2-9270-7a143151b68e.png)

**Comment by satya164** [comment]
What's your distro & GTK version?

**Comment by satya164** [comment]
Are you using Ubuntu with overlay-scrollbars?

**Comment by beanaroo** [comment]
@satya164 Sorry for the delated response, forgot I filed the bug. 

At the time of reporting I was running Arch with GNOME 3.8. I have since reformatted and now running GNOME 3.10.
Installing the extension from git shows no change in either the master branch nor the new ui-rewrite branch. (Screenshot attached)

![gnome-cal-rewrite](https://f.cloud.github.com/assets/1748909/1378158/3fa4c738-3ac0-11e3-8a8f-748f856a356c.png)

**Comment by satya164** [comment]
Hmm.. Gnome Calendar is not stable yet I think. Is it?

**Comment by beanaroo** [comment]
Nowhere near stable. It is barely functional. I just noticed it and thought you might be missing out on a new style of some sorts.

**Comment by satya164** [comment]
Hmm... I cannot fix it as long as it's not available in Fedora repos :(

**Comment by beanaroo** [comment]
I don't think anybody is using the application at the moment. And I am unaware of any other application using the GcalMonthView widget. It does seem to be pulling the colour from the GTK theme though.

**Comment by beanaroo** [comment]
Found the stylesheet for the application's UI. Still not sure where the background style originates but by overriding it, I found the class to be <code>.calendar-view</code>

https://github.com/GNOME/gnome-calendar/blob/ui-rewrite/data/theme/gtk-styles.css

I messed with the file just for fun:
![gnome-cal-modded](https://f.cloud.github.com/assets/1748909/1387504/6917d4cc-3b9a-11e3-96f5-d8ad03c7bbeb.png)

**Comment by satya164** [comment]
Hey.. Thanks a lot. I'll add it to the theme :D
