### ISSUE TITLE
GTK-3.20:: Gnome-Panel :: Port gnome panel for 3.20

### ISSUE THREAD

**Issue by khurshid-alam** [numixproject/numix-gtk-theme#550]
Gnome-Panel or gnome-flashback-panel needs to ported to 3.20.

![gnome-panel](http://i.imgur.com/1HW0LBn.png)

**Comment by megax** [comment]
Example: https://github.com/horst3180/arc-theme/blob/master/common/gtk-3.0/3.20/sass/_applications.scss#L436 (I do not know up to date)

**Comment by khurshid-alam** [comment]
I think it is interfering with mate-panel code.

**Comment by megax** [comment]
@khurshid-alam Ambiance test code: http://bazaar.launchpad.net/~ci-train-bot/ubuntu-themes/ubuntu-themes-ubuntu-yakkety-landing-1903/revision/507

http://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/view/head:/Ambiance/gtk-3.20/apps/gnome-flashback.css
http://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/view/head:/Ambiance/gtk-3.20/apps/gnome-panel.css

**Comment by megax** [comment]
Reference code: https://github.com/horst3180/arc-theme/commit/fb1a401ba9c8b32a2c1159ea26816ad21750174a
https://github.com/horst3180/arc-theme/commit/e250405fdb7509b3d3f8fb9c7ca6a78f0f59bad6
https://github.com/horst3180/arc-theme/commit/32a5aa99d306143caa03fdbab30a635be46c69fe
