### ISSUE TITLE
gtk-icon-shadow error

### ISSUE THREAD

**Issue by MichaelTiebesl** [numixproject/numix-gtk-theme#558]
Ubuntu 16.04. Theme and icons installed by PPA : 
GTK theme 2.6.0+545~201609022016~ubuntu16.04.1
Icon Theme 2.0.3+7~201608312136~ubuntu16.04.1

I have in Lollypop the following errors:

![1](https://cloud.githubusercontent.com/assets/10792019/18224781/6a04548e-7213-11e6-89eb-02c2217b9167.png)

What is wrong here? Thanks.

**Comment by megax** [comment]
Thanks, fixed: https://github.com/numixproject/numix-gtk-theme/pull/559
