### ISSUE TITLE
Background of input fields and nautilus is black

### ISSUE THREAD

**Issue by felipap** [numixproject/numix-gtk-theme#56]
Why is this happening?
(Awesome job, btw!)
![](http://i.imgur.com/46Y1smM.png)
![](http://i.imgur.com/n0zLal3.png)
My gtk version is `3.6.4-0ubuntu8`.

**Comment by satya164** [comment]
Are you using the theme from GitHub/dA? It's a Ubuntu specific bug with overlay scrollbars and has been patched in the PPA.

**Comment by felipap** [comment]
I'm using the PPA.

**Comment by felipap** [comment]
Ops, turns out all it took was resetting the apps. Thanks.
