### ISSUE TITLE
GTK 3.20 :: Scale fine tuning jumping and padding

### ISSUE THREAD

**Issue by SammysHP** [numixproject/numix-gtk-theme#560]
- Left/right padding was increased
- Scale jumping again in fine tune mode

Maybe because of ff98d448fc01c637ddff3203c02095ceaca013f7?

![slider-padding2](https://cloud.githubusercontent.com/assets/922874/18252327/6422fb98-738e-11e6-8c3a-448ef709ac61.gif)

**Comment by megax** [comment]
Adwaita: 
![anim](https://cloud.githubusercontent.com/assets/461493/18248088/bc472046-7376-11e6-93c7-5f6044077f89.gif)

Not fix padding the two slider. I think just as much trouble.

**Comment by megax** [comment]
@SammysHP Corrected fine-tune size (base arc-theme and adwaita) and fix padding. https://github.com/numixproject/numix-gtk-theme/pull/563

**Comment by khurshid-alam** [comment]
Since when are we using padding fluctuation in fine tune mode? Other themes do not do this...We don't have to be like adwaita which sometimes makes pathetic attempt to introduce effect which they thought cool.

**Comment by megax** [comment]
Okay.

**Comment by SammysHP** [comment]
But there should be some kind of indication that it is in fine tune mode.

**Comment by megax** [comment]
Color change, as scrollbar?

Edit:
![anim](https://cloud.githubusercontent.com/assets/461493/18251882/1f3f078a-738c-11e6-819f-c366825c8298.gif)

@khurshid-alam Please test unity menu (sound applet).
