### ISSUE TITLE
GTK 3.20 :: fine-tune OSD strange shadow

### ISSUE THREAD

**Issue by SammysHP** [numixproject/numix-gtk-theme#561]
![20160905_110628](https://cloud.githubusercontent.com/assets/922874/18244432/6a759740-7360-11e6-86a1-b923c108fd50.png)

**Comment by megax** [comment]
![image](https://cloud.githubusercontent.com/assets/461493/18247613/a8fccef8-7373-11e6-8c50-32f0fa1e2499.png)

I do not see =/

**Comment by SammysHP** [comment]
It happens only sometimes. Play a little bit with the fine tune mode and it might appear.

**Comment by megax** [comment]
Can you possibly send PR?

**Comment by SammysHP** [comment]
I'm now able to reproduce it, but I still don't know the reason. It seems to be related to `box-shadow`, but I cannot find the matching rule or even the element.

This fixes it, but only after the window was resized (which might clear some cache or forces a redraw).

```
colorchooser button {
    box-shadow: none;
}
```

Actually it might be a bug in GTK.

**Comment by megax** [comment]
@SammysHP Test code: https://github.com/numixproject/numix-gtk-theme/pull/629

**Comment by megax** [comment]
@SammysHP @khurshid-alam It solved the problem? I have no fault, but please let us know if you still have.
