### ISSUE TITLE
GTK 3.21.5 :: Cinnamon 3.0.7 :: Nemo 3.0.6-2 :: Big arrows 

### ISSUE THREAD

**Issue by BaraVaq** [numixproject/numix-gtk-theme#565]
![arrows](https://cloud.githubusercontent.com/assets/22131622/18531816/c5370e16-7ac7-11e6-8b3e-c325e7338203.png)

**Comment by khurshid-alam** [comment]
As of now we do not support Gtk >= 3.20.

**Comment by BaraVaq** [comment]
Probably it is an issue of Nemo, because in 3.0.6-1 it was ok. 
This is the changelog: 
nemo (3.0.6-2) unstable; urgency=medium
- Import upstream patches:
  window-remove-custom-get_preferred_width-height-impl.patch,
  pathbar-avoid-gtk-warnings.patch and
  pathbar-remove-hardcoded-width-for-sliders.patch.
  Thanks to johu for reporting (Closes: 836922)

**Comment by megax** [comment]
@BaraVaq Please test code: https://github.com/numixproject/numix-gtk-theme/pull/568 It can improve error. (supposition :) )

**Comment by BaraVaq** [comment]
@megax It fixed big arrows.

**Comment by megax** [comment]
@BaraVaq thanks you :)

**Comment by megax** [comment]
@khurshid-alam, @lots0logs Fixed issue.
