### ISSUE TITLE
White Highlight on XFCE Panel Items

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-gtk-theme#566]
With the update that came yesterday from the daily PPA the highlight on the XFCE panel is now solid white. Makes the icon look messy and is generally not in keeping with the rest of the theme.

![screenshot_2016-09-19_10-59-53](https://cloud.githubusercontent.com/assets/5920259/18628497/6476ff70-7e58-11e6-972c-151fdae554f6.png)

**Comment by megax** [comment]
@lots0logs https://github.com/numixproject/numix-gtk-theme/commit/7e617ce8f5f11b289b8f944dc4558ea98bd072f5

**Comment by tserhii-gh** [comment]
Same problem, indicator plugin background is solid white
![screenshot_2016-09-19_17-32-22](https://cloud.githubusercontent.com/assets/1315398/18635821/0bc18314-7e8f-11e6-94af-bf9af6d3de7f.png)

**Comment by megax** [comment]
Please revert @lots0logs commit and test code. A temporary solution may be.
But I agree with @lots0logs. Must rewrite/check xfce code. 

Edit: @lots0logs Xfce GTK 3.20 code: https://github.com/shimmerproject/Greybird/blob/master/gtk-3.0/_xfce.scss I guess that's pretty much good. Should be amended accordingly.

**Comment by khurshid-alam** [comment]
Only the panel button code needs rewrite. xfce code are kept at minimum level to avoid problems with different distributions.

**Comment by lots0logs** [comment]
Sorry guys, I will take care of this. :sweat_smile:

**Comment by lots0logs** [comment]
@Foggalong I cant reproduce the issue with Xfce on Arch which is weird. I'll look into it further...

**Comment by Foggalong** [comment]
This is XFCE on Ubuntu here :)

**Comment by megax** [comment]
@khurshid-alam GTK 3.20?

**Comment by khurshid-alam** [comment]
@megax 

Does reverting 7e617ce fix it for 3.20? I don't think so.

To fix it properly for 3.20 we first need to port **_panel.scss** (#550), specifically fix `%panelbutton` code inside it.

**Comment by lots0logs** [comment]
AFAIK xfce-panel is still using gtk2. I dont understand how the changes made in the gtk3 theme are having any affect on it. Also, like I said, I cannot reproduce the issue shown in the screenshots on a clean install of Xfce on Arch.

**Comment by khurshid-alam** [comment]
It depends. Libxfce4ui 4.12 (which is in Ubuntu) can compile with both gtk2 and gtk3. Dialogs are all gtk3 in 4.13. Complete port will be done in 4.14 , i guess. Also there are many third-party applets that uses gtk3.
