### ISSUE TITLE
2.6.2 broke XFCE power manager plugin icon

### ISSUE THREAD

**Issue by wooque** [numixproject/numix-gtk-theme#567]
Before (2.6.1) ![before](https://cloud.githubusercontent.com/assets/1936195/18644628/66197aa4-7eaa-11e6-8d39-1ed1c82ae237.png)
After (2.6.2) ![after](https://cloud.githubusercontent.com/assets/1936195/18644630/69b66406-7eaa-11e6-9c48-469d8e196926.png)
It started to look like that after commit "**disable some unused styles for xfce**" https://github.com/numixproject/numix-gtk-theme/commit/7e617ce8f5f11b289b8f944dc4558ea98bd072f5

**Comment by megax** [comment]
@lots0logs, @wooque related PR: https://github.com/numixproject/numix-gtk-theme/issues/566

**Comment by megax** [comment]
@wooque Still having trouble?

**Comment by wooque** [comment]
Just updated to 2.6.4, everything is fine. This issue can be closed.
