### ISSUE TITLE
White title bar Numix-gtk-theme bug in Xenial (16.04.1)

### ISSUE THREAD

**Issue by gtomas41** [numixproject/numix-gtk-theme#569]
This happens now and then. Once I fixed it, but I'm not sure how. Purging and reinstalling the theme doesn't help.

![image](https://cloud.githubusercontent.com/assets/22322105/18671469/83e4bb8a-7f44-11e6-9f3a-2aee6311126d.png)

Ubuntu Unity 16.04.1 LTS

**Comment by cdysthe** [comment]
This happens all the time on 16.10 Beta 1. I do have red window controls when hovering over the window bar area when the controls are (the left side on Unity).

**Comment by khurshid-alam** [comment]
Please use the PPA for Ubuntu 16.04/16.10. Thanks.

**Comment by cdysthe** [comment]
I am using the PPA:

http://ppa.launchpad.net/numix/ppa/ubuntu yakkety main

**Comment by khurshid-alam** [comment]
Ah..sorry...it was caused by an error on utils.sh where we are coping a gtk.css which contains nothing.

**Comment by khurshid-alam** [comment]
Please install the new version and check again. Thanks.

**Comment by gtomas41** [comment]
Why is this closed? I have opened the issue having installed the lastest issue from the official PPA for Ubuntu xenial 16.04.!

**Comment by khurshid-alam** [comment]
@gtomas41 

I just pushed a fix. It may take few hours to compile on launchpad. Please update when its available (`sudo apt-get update`) and then install and try again.

**Comment by cdysthe** [comment]
I stll haven't gotten an update in Ubuntu 16.04 Beta 1. Will I get an update through the PPA?

**Comment by khurshid-alam** [comment]
Yes. Through PPA.

**Comment by gtomas41** [comment]
Me neither. Been checkimg for two days.

**Comment by cdysthe** [comment]
So we are sure it is available for 16.10 at all? Doesn't normally take this long for an update to propagate.

**Comment by cdysthe** [comment]
So nothing yet on the PPA for Ubuntu 16.10. Should it take this long?

**Comment by khurshid-alam** [comment]
New Build was completed 12 hrs ago.

**Comment by gtomas41** [comment]
This is the PPA, right: sudo add-apt-repository ppa:numix/ppa
There's no update as of yet for xenial (16.04.1).

**Comment by khurshid-alam** [comment]
Latest version is `2.6.0+581~201609221601~ubuntu16.04.1`. You can try removing your existing theme and then reinstall.

**Comment by gtomas41** [comment]
I have tried that, doesn't help. I've also tried removing the PPA and
readding it. Maybe it installs the latest build, but it does not fix the
proble.

**Comment by khurshid-alam** [comment]
This is the deb: https://code.launchpad.net/~numix/+archive/ubuntu/ppa/+build/10943668/+files/numix-gtk-theme_2.6.0+581~201609221601~ubuntu16.04.1_all.deb

**Comment by khurshid-alam** [comment]
What is the output of `ls -l "/usr/share/themes/Numix Daily/gtk-3.0"` ? Also check theme version with `apt-cache policy numix-gtk-theme`.
`

**Comment by khurshid-alam** [comment]
You are using Unity right?  Use unity-tweak-tool change the theme to Ambiance and then back to Numix. On my pc it looks alright.

![numix-ppa](http://i.imgur.com/CjGAU0z.png)

**Comment by gtomas41** [comment]
I have the later build, 2.6.1. Still the same problem.
reseting to ambience and then Numix doesnt solve the issue.

**Comment by khurshid-alam** [comment]
Tell me the output that I have asked before.

**Comment by gtomas41** [comment]
There's no Numix Daily folder.
However, there's a NUmix folder, and the output of the command you listed
is as follows:

drwxr-xr-x 2 root root   4096 Ruj 23 07:39 assets
drwxr-xr-x 2 root root   4096 Ruj 23 07:39 dist
-rw-r--r-- 1 root root     62 Lip 18 15:39 gtk.css
-rw-r--r-- 1 root root     67 Lip 18 15:39 gtk-dark.css
-rw-r--r-- 1 root root 518592 Kol  6 18:09 gtk.gresource
-rw-r--r-- 1 root root   3052 Lip 18 15:39 gtk.gresource.xml
drwxr-xr-x 4 root root   4096 Ruj 23 07:39 scss
-rw-r--r-- 1 root root   1567 Kol  6 18:09 thumbnail.png

**Comment by khurshid-alam** [comment]
> I have the later build, 2.6.1. Still the same problem.

Ah. That's the problem. **There is no 2.6.1 on our PPA. It's a debian version only works in yakkety.** Remove whatever version you have and install the exact version from the ppa.

You can first try removing "/usr/share/themes/Numix" and "/usr/share/themes/Numix Daily" manually from nautilus (just run nautilus with sudo) and then install the deb file (or from PPA) I provided earlier.

**Comment by gtomas41** [comment]
Ok. So which version should i specify to install? I sudo apt install
numix-gtk-theme...?

**Comment by khurshid-alam** [comment]
**Are you sure that you are on Ubuntu 16.04 and not on Ubuntu 16.10?** 

I think you are not updating the repository.**Since version in the universe is greater than PPA, it won't work for Ubuntu 16.10 (Yakkety).**

 **If you are on 16.04**, Run these command 

``` sh
sudo add-apt-repository ppa:numix/ppa
sudo apt-get update
sudo apt-get install numix-gtk-theme
```

**If you are on 16.10**, Run these command

``` sh
sudo apt-get install numix-gtk-theme
```

PPA update for yakkety will be uploaded soon.

**Comment by cdysthe** [comment]
I have had the Numix PPA added for years :-) I have updated it many times over the last couple of days. I even purged it and added it back again but there's no update for the GTK theme as of now. I still have the one with white window bar. This i what I get when purge it and then install again. I now see that it will be updated for yakkety soon, so I'll wait a little more :-)

**Comment by Mentis** [comment]
The problem is that official Ubuntu repos have version 2.6.1 whether ppa has version 2.6.0-something
You need to force install specific version like this:
sudo apt install numix-gtk-theme=2.6.0+581~201609221604~ubuntu16.10.1

**Comment by cdysthe** [comment]
Thanks! Did that and was told the it was being downgraded. I don't care as long as it works. There must be a way to set up the PPA so the correct version is selected. I wouldn't know how, but maybe the Numix devs can find out? And what a relief that have my desktop back! :)

**Comment by cdysthe** [comment]
@Mentis Thank you for that solution. It's pretty difficult to be running 16.10 beta and always have one package I can't upgrade or Numix will break. Why isn't it possible to make sure the PPA contains a version newer that the one in the Ubuntu repos so we do not have to use this workaround to get it to work? Aslo the terminal is white, shouldn't it be black in Numix?

**Comment by gtomas41** [comment]
OK, so can anyone finally provide me with the complete command line sudo
for installing a Numix GTK theme that WILL work fine on ubuntu 16.04.1? The
link provided above does not work even if I change ubuntu to 16.04.1
