### ISSUE TITLE
Preferences dialog in gedit has white text on white background

### ISSUE THREAD

**Issue by anshin** [numixproject/numix-gtk-theme#57]
![2013-08-01-1375405778](https://f.cloud.github.com/assets/1342599/898418/8365fa40-fb10-11e2-82b8-6d569b6d1d8a.png)

Can this be fixed?

**Comment by me4oslav** [comment]
How can I open this Preferences window? I can't find it anywhere is gedit.

**Comment by satya164** [comment]
@anshin are you using gtk3.4? Numix supports only GTK3.6 and up.

**Comment by satya164** [comment]
@me4oslav from the GMenu

**Comment by me4oslav** [comment]
Yup, I found it.
And I can't reproduce the issue.
http://i.imgur.com/iTxAs6c.png

**Comment by anshin** [comment]
Turns out my version of GTK3 is outdated. I didn't even consider that. My fault.
Thanks for your help.

**Comment by satya164** [comment]
A GTK 3.4 version is available here https://launchpad.net/~satyajit-happy/+archive/themes/+files/numix-gtk-theme_1.9~precise.tar.gz

**Comment by anshin** [comment]
@satya164 will GTK3.4 will be supported longterm, or is this a one-off release?

**Comment by satya164** [comment]
@anshin No long term support, coz I don't have 3.4 anymore. But there will be bug fixes if needed.

**Comment by anshin** [comment]
@satya164 thanks, that's good enough for me.
