### ISSUE TITLE
Missing checkbox theming

### ISSUE THREAD

**Issue by jbicha** [numixproject/numix-gtk-theme#570]
Ubuntu GNOME 16.10 Beta with GTK 3.20.9
numix 2.6.3

I compiled numix and installed numix 2.6.3. I am missing checkboxes in GTK3 apps like in gedit's Preferences dialog or in Firefox forms (Ubuntu's Firefox is GTK3-enabled).

I looked in /usr/share/themes/Numix/gtk-3.20/gtk.gresource and it mentions "../assets/radio-unchecked.png" but there is no assets folder there.

**Comment by khurshid-alam** [comment]
@lots0logs I thought I already fixed that in earlier commit. Now it has broken again.

**Comment by lots0logs** [comment]
@khurshid-alam No you didnt fix it. The assets were not included. I fixed it and I tested it. Let me know what issue you are seeing.

**Comment by khurshid-alam** [comment]
@lots0logs No issue. Only broken in launchpad. It was not working because it wasn't creating the necessary symlinks to assets. So I changed debian rules to do that. But now that makefile doing exactly that..... there is no need for extra install file.

**Comment by khurshid-alam** [comment]
Fixed on launchpad as well. All good.

**Comment by lots0logs** [comment]
> But now that makefile doing exactly that..... there is no need for extra install file.

I'm not sure what you mean? :confused:
