### ISSUE TITLE
GTK 3.22 Issues

### ISSUE THREAD

**Issue by lots0logs** [numixproject/numix-gtk-theme#571]
According to [this page](https://developer.gnome.org/gtk3/stable/GtkCssProvider.html#GtkCssProvider.description) in GTK docs, we should not need to symlink `gtk-3.22` to `gtk-3.20` directory. It should "just work" as it is now. Just need to confirm that is actually the case.

**Comment by khurshid-alam** [comment]
I think we better create a separate gtk-3.22 folder as lots of things are different in 3.22 than in 3.20....specially with the patched version of GTK that Debian/Ubuntu ships.

**Comment by lots0logs** [comment]
@khurshid-alam You have any specific examples? AFAIK there should not be any breaking changes to the theme API. If there are new styles needed then we can add them without hurting anything on gtk 3.20.

**Comment by lots0logs** [comment]
- [ ]  Theme parsing error: gtk.css:680:14: not a number
- [ ]  Theme parsing error: gtk.css:680:14: Expected a string.
- [ ]  Theme parsing error: gtk.css:683:17: Expected a string.
- [ ]  Theme parsing error: gtk.css:838:14: not a number
- [ ]  Theme parsing error: gtk.css:838:14: Expected a string.
- [ ]   Theme parsing error: gtk.css:841:17: Expected a string.
- [ ]  Theme parsing error: gtk.css:1257:14: not a number
- [ ]  Theme parsing error: gtk.css:1257:14: Expected a string.
- [ ]  Theme parsing error: gtk.css:1261:17: Expected a string.
- [ ]  Theme parsing error: gtk.css:2792:8: not a number
- [ ]  Theme parsing error: gtk.css:2792:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
- [ ]  Theme parsing error: gtk.css:2797:8: not a number
- [ ]  Theme parsing error: gtk.css:2797:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
- [ ]  Theme parsing error: gtk.css:5694:12: not a number
- [ ]   Theme parsing error: gtk.css:5694:12: Expected a string.
- [ ]  Theme parsing error: gtk.css:5715:18: not a number
- [ ]  Theme parsing error: gtk.css:5715:18: Expected a string.
- [ ]  Theme parsing error: gtk.css:5817:12: Expected a string.
- [ ]  Theme parsing error: gtk.css:5819:16: not a number
- [ ]  Theme parsing error: gtk.css:5819:16: Expected a string.
- [ ]   Theme parsing error: gtk.css:5976:12: not a number
- [ ]  Theme parsing error: gtk.css:5976:12: Expected a string.

cc: @megax @khurshid-alam

**Comment by lots0logs** [comment]
**_Note:**_ Let's see if we can fix these issues in the 3.20 directory without breaking backwards compatibility. I would like to avoid adding a separate directory for 3.22 if possible.

**Comment by khurshid-alam** [comment]
- [x]  Theme parsing error: gtk.css:2792:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
- [x]  Theme parsing error: gtk.css:2797:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

It's a simple fix: We need to use `font-weight`, `font-size`, `font-family` instead of `font`. So it can be merged with 3.20
