### ISSUE TITLE
The same text color as the background color of a button

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-gtk-theme#572]
Details on a screenshot:
![screenshot from 2016-09-25 00-53-33](https://cloud.githubusercontent.com/assets/11137173/18811750/e4186de8-82ba-11e6-952c-b3e322a5bd52.png)

**Comment by lots0logs** [comment]
Which version of Ubuntu and the theme does this occur with? It was recently fixed so please ensure you are using the latest version of the theme.

**Comment by marmis85** [comment]
@lots0logs I have this also on Arch GNOME 3.20 Numix latest commit, I have only noticed it in those buttons in Geary

**Comment by moonmehta** [comment]
@lots0logs @marmis85 @Corsseir @satya164 Can confirm on Ubuntu 16.10 (GTK 3.20) Beta builds with Geary too. I am on the PPA (so assuming I am on the latest) and can confirm it has not been fixed.

![numix-geary-text-bug-ubuntu-16-10](https://cloud.githubusercontent.com/assets/22585732/19101589/19916ad6-8ae7-11e6-82da-da2f990e32b7.png)

**Comment by khurshid-alam** [comment]
Geary is going through lots of changes in master. Although it shouldn't affect 11.x series. But then people have reported (see mailing-list) that they are having trouble even with 11.x in yakkety.

**Comment by megax** [comment]
I tested git master repo (geary). Fixed bug (new style https://github.com/GNOME/geary/commit/898fa3303ddbcfe72519526d54be95440c1cecbf): 
![image](https://cloud.githubusercontent.com/assets/461493/19219343/b729fef8-8e10-11e6-9591-902b352b6462.png)

**Comment by khurshid-alam** [comment]
Ok. They are now using infobar. But It should work for 11.x series as well as it is working with Gtk-3.18. maybe changing the code to  `.info {.button, button` instead of `.info button` is required.
![infobar-button](http://i.imgur.com/p3G8ZpO.png)

**Comment by megax** [comment]
@khurshid-alam Test Adwaita infobar structure: https://github.com/GNOME/gtk/blob/gtk-3-20/gtk/theme/Adwaita/_common.scss#L3835

**Comment by megax** [comment]
Related: https://github.com/numixproject/numix-gtk-theme/issues/450

**Comment by megax** [comment]
@khurshid-alam Bug source: https://github.com/numixproject/numix-gtk-theme/blob/2.6.4/src/gtk-3.20/scss/widgets/_button.scss#L303 I don't know why there... =/

But there are ideas.
Related bug: https://github.com/horst3180/arc-theme/issues/27 and fixed:

```
    // Webkitgtk workaround start
    &:active { color: $fg; }
    // Webkitgtk workaround end
```
