### ISSUE TITLE
The current working version of numix-gtk-theme gets updated to a non working version from the Ubuntu repositories.

### ISSUE THREAD

**Issue by cdysthe** [numixproject/numix-gtk-theme#573]
Hi,

The working numix-gtk-theme 2.6.0+581~201609221604~ubuntu16.10.1 has to be forced installed on Ubuntu 16.10 Beta and then locked/held since the one in the Ubuntu repositories has the version number 2.6.1-1 which is higher than the one in the PPA. It would be good if the PPA could get a version number ahead of the Ubuntu repositories so it doesn't have to be locked forced and locked.

**Comment by lots0logs** [comment]
@khurshid-alam is taking care of this. We are reworking the PPA to offer a stable package and a daily build.

**Comment by khurshid-alam** [comment]
In-Progess

**Comment by khurshid-alam** [comment]
Fixed.
