### ISSUE TITLE
White background Gnome Terminal

### ISSUE THREAD

**Issue by cdysthe** [numixproject/numix-gtk-theme#574]
The Gnome Terminal has a white background in Numix on Ubuntu 16.10 Beta running Unity. I seem to remember it used to be dark, but I may be wrong. I know I can easily set the background myself, but was wondering if this was an intentional change?

**Comment by khurshid-alam** [comment]
You don't need to change background. You can use dark variant from terminal profile preference.

**light:**

![20160511_171207](https://cloud.githubusercontent.com/assets/922874/15185999/964bbeec-179b-11e6-9b57-ffb6c28cf97d.png)

**dark:**

![20160511_171212](https://cloud.githubusercontent.com/assets/922874/15186000/965703ba-179b-11e6-9c4f-5835f7ef1ee8.png)

**Comment by megax** [comment]
@khurshid-alam Now dark window and background :)
![image](https://cloud.githubusercontent.com/assets/461493/18817363/ae157c8c-835e-11e6-9090-115dd8678da0.png)

**Comment by cdysthe** [comment]
That's weird. I only have one profile 'default' and it's white on vanilla Ubuntu 16.10 Beta. I'll create my own dark profile for Numix with a color picker :)

**Comment by khurshid-alam** [comment]
It's not the profile-preference, but preference->theme variant. 
![screenshot from 2016-09-26 00-28-30](https://cloud.githubusercontent.com/assets/1333217/18817545/88bad65e-8380-11e6-9859-33074f2abf2d.png)

**Comment by megax** [comment]
![anim](https://cloud.githubusercontent.com/assets/461493/18817550/594f494e-8363-11e6-9eac-b59c00593695.gif)

**Comment by cdysthe** [comment]
Thanks, see it now! :) However, it's not Numix enough for me. I will use that as a base though.

**Comment by edwinksl** [comment]
Just to make sure I got this right: when using the Numix theme, the default background color for GNOME terminal has gone from `#444` in Ubuntu 16.04 to `#eee` in Ubuntu 16.10?
