### ISSUE TITLE
Bad look of the windows style on Ubuntu 16.04 with Gnome Classic (gnome-session-fallback)

### ISSUE THREAD

**Issue by pwittchen** [numixproject/numix-gtk-theme#577]
After upgrading the system to Ubuntu 16.04, a few windows started looking bad (like old gnome classic style) and a few windows got a huge padding. Moreover, Dropbox icon in the top panel is not consistent with the rest of the icons. I'm using Gnome Classic (gnome-session-fallback). On Ubuntu 14.04 everything was fine. See attached screenshot.

![screenshot](https://cloud.githubusercontent.com/assets/695319/18886194/34afa2f4-84ef-11e6-8312-3293342567c3.png)

I suppose it may be related to the fact that gnome-session-fallback is not frequently updated. For now, I switched to Gnome Shell, which works fine with Numix theme and newest Ubuntu, but I think I like previous DE a little bit more :).

**Comment by khurshid-alam** [comment]
It doesn't look like gnome-session-fallback. It's gnome-session-flahback with gnome3-panel.

**Comment by pwittchen** [comment]
I've installed it with the following command:

```
sudo apt-get install gnome-session-fallback
```

so I suppose it's `gnome-session-fallback`.

**Comment by muktupavels** [comment]
gnome-session-fallback is a transitional package to ease upgrades to gnome-session-flashback. In ubuntu 16.04 you need use this command to change metacity theme:
`gsettings set org.gnome.metacity theme "THEME_NAME"`

Or you can also use dconf-editor...

**Comment by megax** [comment]
@pwittchen We managed to solve?

**Comment by pwittchen** [comment]
@megax I actually switched to Gnome 3, where this problem does not occur and everything works and looks good.

It's fine for me now, so I didn't spend more time for fixing reported issue by myself.

**Comment by khurshid-alam** [comment]
Related issue #550
