### ISSUE TITLE
Add the application icon for Visual Studio

### ISSUE THREAD

**Issue by cawa-93** [numixproject/numix-gtk-theme#578]
Now the application icon for Visual Studio is no different from the usual icons editor. It is not comfortable.
![2016-09-27 21-26-02](https://cloud.githubusercontent.com/assets/1662812/18886684/924d12fc-84f9-11e6-82b2-8e3dee76db87.png)

**Comment by megax** [comment]
@khurshid-alam Numix theme issue?

**Comment by jclc** [comment]
This is an icon issue, not an issue with the GTK theme

**Comment by megax** [comment]
@cawa-93 Please write here: https://github.com/numixproject/numix-icon-theme/issues
