### ISSUE TITLE
Very small icons on Xfce panel

### ISSUE THREAD

**Issue by jpmacedosilva** [numixproject/numix-gtk-theme#58]
After the last Numix updates my the icons in my Xfce panel (i'm using Xubuntu 13.04) changed to a very small size. I'm talking about icons like volume and network icons, mail watcher, aplications laucher and the "show desktop" icons... All of them got very small?!

The size goes back to normal if I change theme (like Greybird or Bluebird), but if I change back to Numix, the icons on the panel get smaller again.

I'm attaching images that to show the before the last updates and the after.

Best regards.
Pedro
![before](https://f.cloud.github.com/assets/5247071/978642/c8006a6e-06c3-11e3-8c46-af141f71dbd9.png)
![after](https://f.cloud.github.com/assets/5247071/978643/d0e36f8c-06c3-11e3-84a1-d0f44a7dc865.png)

**Comment by satya164** [comment]
They are a side effect of increase in padding. Also, the the icons in window list buttons are much smaller.
![screenshot from 2013-08-18 07 23 41](https://f.cloud.github.com/assets/1174278/981947/4acbd7de-07ab-11e3-8318-b7d976cceb5e.png)

**Comment by jpmacedosilva** [comment]
Sorry for my english, but I didn't understand what is "increase in paddding".
But most important, is there any way to fix this?

Best regards.

**Comment by satya164** [comment]
@jpmacedosilva If you want to fix it manually, edit the file `gtk-2.0/gtkrc`, search for the following,

`style "murrine-panel" = "murrine-thin"`

Below that line, there will be `xthickness = 4`

Decrease the value to what you like.
