### ISSUE TITLE
No icons in marco window manager (MATE) in preferences/options/equalizer windows in quodlibet and audacious.

### ISSUE THREAD

**Issue by darkshram** [numixproject/numix-gtk-theme#581]
This is how quodlibet preferences window looks with Ambiance gtk+ theme in MATE Desktop (marco as window manager, no-compiz). Menu icon at the left, close icon at the right.
![1](https://cloud.githubusercontent.com/assets/10327500/19009747/7797370e-873c-11e6-8da6-e9796c18e9e7.png)

This is how quodlibet preferences window looks with Numix gtk+ theme in MATE Desktop (marco as window manager, no-compiz). No options and close icons.
![2](https://cloud.githubusercontent.com/assets/10327500/19009748/7798646c-873c-11e6-899e-b78e7a880f1c.png)

Similar thing happens with audacious preferences and equalizer windows.

Ambiance:
![audacious-1](https://cloud.githubusercontent.com/assets/10327500/19009835/89913f9e-873d-11e6-9df0-4e797b6e6bf9.png)

Numix:
![audacious-2](https://cloud.githubusercontent.com/assets/10327500/19009836/89952546-873d-11e6-88b7-59c274ef1a94.png)

**Comment by megax** [comment]
Related issue: https://github.com/numixproject/numix-gtk-theme/issues/480

**Comment by darkshram** [comment]
Understood #480 . I made a patched version for [ALDOS 1.4](http://www.alcancelibre.org/staticpages/index.php/notas-lanzamiento-aldos-1-4). Very close to set Numix as default theme for next release. Please, you may close this issue.
![pantallazo-2016-10-02 16-42-58](https://cloud.githubusercontent.com/assets/10327500/19023916/56c97508-88bf-11e6-91d8-90ca92984e92.png)
