### ISSUE TITLE
Failed to locate 'assets/checkbox-checked-dark.png' in any source directory.

### ISSUE THREAD

**Issue by zruu** [numixproject/numix-gtk-theme#582]
I'm not really sure why I get this error when running make install (the file is there):

```
sudo make install
rm -rf src/gtk-3.0/dist
rm -f src/gtk-3.0/gtk.gresource
rm -rf src/gtk-3.20/dist
rm -f src/gtk-3.20/gtk.gresource
scss --update --sourcemap=none src/gtk-3.0/scss:src/gtk-3.0/dist
  directory src/gtk-3.0/dist
      write src/gtk-3.0/dist/gtk-dark.css
      write src/gtk-3.0/dist/gtk.css
scss --update --sourcemap=none src/gtk-3.20/scss:src/gtk-3.20/dist
  directory src/gtk-3.20/dist
      write src/gtk-3.20/dist/gtk-dark.css
      write src/gtk-3.20/dist/gtk.css
glib-compile-resources --sourcedir=src/gtk-3.0 src/gtk-3.0/gtk.gresource.xml
src/gtk-3.0/gtk.gresource.xml: Failed to locate 'assets/checkbox-checked-dark.png' in any source directory.
Makefile:20: recipe for target 'gresource' failed
make: *** [gresource] Error 1
```

**Comment by megax** [comment]
@lots0logs idea?

**Comment by lots0logs** [comment]
No, I'm afraid not. I recommend cloning a fresh copy and trying it again. It should work. It works fine for me locally and it also works on our CI builds.

**Comment by khurshid-alam** [comment]
@zruu Probably a problem with symlinks. Clone the source and try again.

**Comment by lots0logs** [comment]
You know what..I bet they downloaded the archive instead of cloning with git. To address this case we'll have to check for the existence of the symlinks and create them if necessary. I will take care of it asap!

**Comment by megax** [comment]
@lots0logs This improves? :) https://github.com/numixproject/numix-gtk-theme/commit/5ccc199112740a11b7b4a8de9a0f9ca696d9a0c2
