### ISSUE TITLE
How can I buy numix dark? The web store appears to be blank.

### ISSUE THREAD

**Issue by BurningSmile** [numixproject/numix-gtk-theme#583]
I would like to buy the Numix dark gtk3 theme but the store is broken. How can I go about buying it?

**Comment by khurshid-alam** [comment]
Numix dark hasn't been maintained. Anyway send us a email at team@numixproject.org

**Comment by megax** [comment]
@BurningSmile solved? :)

**Comment by SammysHP** [comment]
The dark theme is included in this version and can be enabled via Gnome/GTK configuration.

![20161017_205807](https://cloud.githubusercontent.com/assets/922874/19451143/72467a4e-94ac-11e6-93b9-6cb18777d0f3.png)
