### ISSUE TITLE
GTK 3.22 :: dconf-editor :: hardly usable 

### ISSUE THREAD

**Issue by BaraVaq** [numixproject/numix-gtk-theme#584]
![dconf](https://cloud.githubusercontent.com/assets/22131622/19029417/9006dc22-8935-11e6-93d2-1952c48a8ec3.png)

**Comment by megax** [comment]
Strange, the other works? (popover menu)

**Comment by BaraVaq** [comment]
Looks like other things work.

**Comment by khurshid-alam** [comment]
https://mail.gnome.org/archives/commits-list/2016-July/msg06797.html

**Comment by megax** [comment]
If i change Adwaita popover code (background color), can not respond background color.
![image](https://cloud.githubusercontent.com/assets/461493/19420189/8f1a14bc-93e6-11e6-8460-b52c20475412.png)

I think not theme error.
**Edit:** https://bugzilla.gnome.org/show_bug.cgi?id=772978

**Comment by megax** [comment]
If all true, corrected: https://github.com/GNOME/dconf-editor/commit/d13aa05e00e4e2ed2cfd39f0d4b211276e322677

**Comment by megax** [comment]
@khurshid-alam, @BaraVaq Tested https://github.com/GNOME/dconf-editor/commits/gnome-3-22 code. Fixed bug.

![image](https://cloud.githubusercontent.com/assets/461493/19609458/a6dc805e-97d7-11e6-9b65-5f9e87e8c96b.png)

Close issue?
