### ISSUE TITLE
GTK 3.22 :: System Monitor :: white points on the left and right sides

### ISSUE THREAD

**Issue by BaraVaq** [numixproject/numix-gtk-theme#585]
![system monitor](https://cloud.githubusercontent.com/assets/22131622/19029741/72da7e58-8938-11e6-965f-927963a5a8db.png)

**Comment by megax** [comment]
And bug 3.20:
![image](https://cloud.githubusercontent.com/assets/461493/19044358/2c643368-8994-11e6-9324-c9ea233efd49.png)

And bug arc-theme (example):
![image](https://cloud.githubusercontent.com/assets/461493/19044402/68a31c0e-8994-11e6-89fb-c69f64ba1fce.png)
