### ISSUE TITLE
PPA for Ubuntu 16.10 no longer has dark tab colors for Terminal by default

### ISSUE THREAD

**Issue by moonmehta** [numixproject/numix-gtk-theme#586]
In 16.04, the background colors of the tabs in Nautilus used to be dark. Now they are light and don't look good. They look odd.
![numix-gtk-theme-nautilus-ppa](https://cloud.githubusercontent.com/assets/22585732/19031076/a27317d8-896f-11e6-9e26-3c89d92ec5f0.png)
![numix-gtk-theme-terminal-ppa](https://cloud.githubusercontent.com/assets/22585732/19031077/a27d8cae-896f-11e6-9bcb-4cc54b0aea50.png)

**Comment by satya164** [comment]
> tabs in Nautilus used to be dark

Are you sure about that? I don't think they were.

The Terminal tabs however used to be dark.

**Comment by megax** [comment]
Please change terminal settings: https://github.com/numixproject/numix-gtk-theme/issues/574#issuecomment-249439613 (dark theme)

**Comment by uncertainquark** [comment]
@satya164 @megax My bad, Nautilus tabs used to be white on 16.04. Maybe they would look better as dark though, since you want to create a good contrast between Dark and Light. Maybe make a mock-up and let's see if people like it?

However I must say, that personally the Light variant for the Numix terminal looks awful. Especially considering that most people prefer dark color schemes in the terminal. Any plans to default it to Dark?

**Comment by moonmehta** [comment]
@satya164 @megax My bad, Nautilus tabs used to be white on 16.04. Maybe they would look better as dark though, since you want to create a good contrast between Dark and Light. Maybe make a mock-up and let's see if people like it?

However I must say, that personally the Light variant for the Numix terminal looks awful. Especially considering that most people prefer dark color schemes in the terminal. Any plans to default it to Dark?

**Comment by moonmehta** [comment]
Here is an example of a Windows where Dark tabs be default would look better and help separate the content with the options.
![numix-software-and-updates](https://cloud.githubusercontent.com/assets/22585732/19075570/1ebd698a-8a63-11e6-856a-a3f27355b492.png)

**Comment by lots0logs** [comment]
Is that how the title bar looks by default are have you made some modifications to the theme?

**Comment by megax** [comment]
@lots0logs Unity uniqueness... :)

**Comment by khurshid-alam** [comment]
@uncertainquark Tabs are also redesigned in 16.10. So whether they are dark or light, they are not the same. Also tabs looks really bad in 16.10 due to a gtk patch.

**Comment by moonmehta** [comment]
@khurshid-alam So it can't be fixed?

**Comment by khurshid-alam** [comment]
@uncertainquark No. Tabs are light by design. We don't use dark tab in light window.
