### ISSUE TITLE
The Numix and Numix-blue packages in Ubuntu 16.10 default repos have titlebar color and buttons visiblity issues

### ISSUE THREAD

**Issue by moonmehta** [numixproject/numix-gtk-theme#587]
Here's how it looks 

![numix-ubuntu-16-10-nautilus](https://cloud.githubusercontent.com/assets/22585732/19100484/eb40db76-8adc-11e6-8d63-47ca36367e9a.png)
![numix-ubuntu-16-10-terminal](https://cloud.githubusercontent.com/assets/22585732/19100485/eb714004-8adc-11e6-9651-0a110b7cddb1.png)

The ones in the PPA look fine on the other hand:

![numix-gtk-theme-nautilus-ppa](https://cloud.githubusercontent.com/assets/22585732/19100544/64f9b88e-8add-11e6-9f8a-93901f89c078.png)
![numix-gtk-theme-terminal-ppa](https://cloud.githubusercontent.com/assets/22585732/19100559/7e7f6c86-8add-11e6-93ef-5158943534bb.png)

It'd be cool to fix it before Ubuntu 16.10 releases on Oct 13 :)

**Comment by lots0logs** [comment]
We have no control over the version that is packaged in the official Ubuntu repos. I recommend submitting a bug report on launchpad to request that the official package be updated.

**Comment by bluesabre** [comment]
We're working on getting numix-gtk-theme updated to 2.6.4 in Ubuntu 16.10.
https://bugs.launchpad.net/ubuntu/+source/numix-gtk-theme/+bug/1630401

**Comment by uncertainquark** [comment]
Good to know :)
Hopefully all will go well and done by the release time :)

**Comment by uncertainquark** [comment]
@bluesabre Is it updated to 2.6.4?
