### ISSUE TITLE
Padding in tabs in Audacious

### ISSUE THREAD

**Issue by mishurov** [numixproject/numix-gtk-theme#588]
GTK-3.20
Numix 2.6.4 (aldo branches 'latest-release' and 'master' at the time of creation this issue)
Gentoo
![tabs](https://cloud.githubusercontent.com/assets/1371641/19210971/e956738e-8d39-11e6-937e-578864af29e8.png)

**Comment by megax** [comment]
Other applications also occurs?

**Comment by mishurov** [comment]
It seems that I don't have applications with such a type of a UI element although other GTK 3.20 themes like Adapta draw these tabs well.

**Comment by megax** [comment]
And other theme good? (notebook tab)

**Comment by mishurov** [comment]
This is Flat-Plat theme, all other is the same.
![flay-plat](https://cloud.githubusercontent.com/assets/1371641/19419377/ea2a5f72-93de-11e6-8abb-bf603331dda1.png)

**Comment by megax** [comment]
@lots0logs Idea?

**Comment by megax** [comment]
@lots0logs Tested. Not inherits the style...
![image](https://cloud.githubusercontent.com/assets/461493/19519346/dbeccfc4-960b-11e6-9806-779e7a272641.png)

**Comment by megax** [comment]
@lots0logs Any idea what could cause?

**Comment by lots0logs** [comment]
@megax Which version of the app did you test? It looks fine for me:

![2016-10-23_10-18-49-am](https://cloud.githubusercontent.com/assets/4675662/19627335/31381942-990a-11e6-8aab-f87fa171dfed.png)

**Comment by megax** [comment]
@lots0logs GTK3 version bad. GTK2 version good (yours is the).

**Comment by megax** [comment]
@lots0logs GTK3 version bad. GTK2 version good (yours is the).

![image](https://cloud.githubusercontent.com/assets/461493/19627373/e9b6f58e-9945-11e6-9f05-ff533ff83f87.png)

**Comment by megax** [comment]
@lots0logs GTK3 version bad. GTK2 version good (yours is the).

![image](https://cloud.githubusercontent.com/assets/461493/19627393/3d12642a-9946-11e6-8351-c1fd53c6853a.png)

**Edit:** Arch linux package (aur): https://aur.archlinux.org/packages/audacious-gtk3 https://aur.archlinux.org/packages/audacious-plugins-gtk3/

**Comment by mishurov** [comment]
My Audacious is compiled with gtk3 USE-flag. It's a GTK 3.20 or later, older versions of GTK3 were fine.

**Comment by lots0logs** [comment]
@megax found the problem..will push fix in a few minutes

**Comment by megax** [comment]
@lots0logs okay. I am interested in the solution :)

**Comment by mishurov** [comment]
It just werks, thnx.
