### ISSUE TITLE
Color issues in Mint 15

### ISSUE THREAD

**Issue by blumf** [numixproject/numix-gtk-theme#59]
Great theme.

A couple of problems on Mint 15 Cinnamon;
- Edit box drop down lists on Firefox (e.g. the search box on the top-right, or lists of previous entries in edit boxes on pages) appear with awkward colors. You get alternating background colors - dark grey (okay) and white (not okay because of light grey text), the highlight color is a light blue, which also seems off for the style.

![ff](https://f.cloud.github.com/assets/130734/978937/426272f2-06ce-11e3-9bed-b0ece73f6393.png)
- The image viewer (Eye of GNOME) has messed up colors on it's preference and the file open dialogs (very weird as other apps don't suffer from this) This might be because it an old version (3.6.2 vs 3.9.5) but it's the one that comes with Mint.

![eog](https://f.cloud.github.com/assets/130734/978938/470d5808-06ce-11e3-8e1d-81089aee6dcf.png)
![eog2](https://f.cloud.github.com/assets/130734/978959/933db8d4-06cf-11e3-8b03-1e02c05005fc.png)

**Comment by satya164** [comment]
Do you have the theme from our PPA? Or manually installed?

**Comment by blumf** [comment]
The PPA (up to date with 1.9-0~151+201308152202~raring1)

**Comment by satya164** [comment]
Hmm... can you try completely uninstalling the theme and reinstalling? It's a duplicate of #33 .

**Comment by blumf** [comment]
Tried the following:
Unselected the Numix control and window theme

```
sudo apt-get purge numix-gtk-theme
rm -rf .cache
rm -rf .gconf/apps/eog
```

Rebooted

```
sudo apt-get install numix-gtk-theme
```

Reselected the Numix theme and... still the same, both on FF and eog :(

Just for a test, I tried building eog v3.8.2 (newest one that'd work, later need newer GTK libs) and it shows the same issue.

**Comment by satya164** [comment]
Try deleting the file /usr/share/themes/Numix/settings.ini

Logout and login back. Does that fix the issue?

**Comment by blumf** [comment]
I tried

```
cd /usr/share/themes/Numix/gtk-3.0
sudo mv settings.ini settings.ini.bak
```

Now the eog dialogs are all dark, but are usable
![eog3](https://f.cloud.github.com/assets/130734/981900/b020e19c-07a1-11e3-8fd4-c8189ba082a6.png)
(really odd as every other g\* app I try, gedit, gimp, etc. etc., is fine, it's just eog)

No change to the FF drop lists.

**Comment by satya164** [comment]
EOG uses a dark theme since it is a media app. Apps like totem etc also use a dark theme (the gtk3 theme needs to specify a dark theme for this to work).

I never had the problem mixing light and dark themes though. It seems to be a GTK bug.

About firefox, are you using a custom firefox theme? Coz I don't have the problem you've specified.

![screenshot from 2013-08-18 06 41 29](https://f.cloud.github.com/assets/1174278/981908/902af650-07a3-11e3-8053-f22e9c619317.png)

**Comment by satya164** [comment]
BTW just for clarification, do you have gnome-settings-daemon running?

**Comment by blumf** [comment]
Ah, I see totem is the same (never use it)

gnome-settings-daemon is running.

FF looks like something is messed up in the config, tried a clean profile and it's fine, but I have no idea what's causing the problem. Default theme, no extensions that look like they'd fiddle with anything, irritating but seems safe to say it's not Numix's fault.
