### ISSUE TITLE
Using Numix GTK breaks Window Snapping

### ISSUE THREAD

**Issue by cldx** [numixproject/numix-gtk-theme#6]
Recreate:

Use Adwaita, snap windows to the side/top of the screen

Use Numix, no snapping available.

**Comment by satya164** [comment]
Are you using Gnome Shell? Cause it works well for me.

**Comment by cldx** [comment]
Yep, Gnome Shell, i don't even know how this can happen. Is the GTK theme responsible for the snapping? I'm dumbfounded.

**Comment by cldx** [comment]
The Hell? I tried it like 20 times and it never worked and all of a sudden its working? -_-

Way to make me feel stupid.
