### ISSUE TITLE
GTK 3.20:: Network Manager GTK Applet :: All of the buttons are flat

### ISSUE THREAD

**Issue by jcjordyn130** [numixproject/numix-gtk-theme#604]
It looks like this: [nm-applet.png](https://voidlinuxforum.s3-eu-west-1.amazonaws.com/original/1X/fc3b092b378a6485d3e65f09bad09de68af9d6c4.png)

Sorry if i'm not providing enough information.

**Comment by khurshid-alam** [comment]
@jcjordyn130 
Which distro? GTK version? How did you install?

**Comment by jcjordyn130** [comment]
@khurshid-alam I'm using void linux, with gtk2 version 2.24.30 and gtk3 version 3.20.3, and I installed to ~/.themes with make

**Comment by khurshid-alam** [comment]
That's the problem. Please install it to /usr/share/themes. Also make sure you have all installed first.

**Comment by jcjordyn130** [comment]
That fixed it, closing... :)
