### ISSUE TITLE
change Numix Blue folder name

### ISSUE THREAD

**Issue by nathaneltitane** [numixproject/numix-gtk-theme#608]
The folder name under /usr/share/themes is listed as 'NumixBlue' - would you please correct it as to show 'Numix Blue' instead for better naming consistency.

thank you.

**Comment by megax** [comment]
Numix Blue not Numix Theme. Blue theme one fork. We cannot improve it.

@khurshid-alam

**Comment by nathaneltitane** [comment]
I'm not sure I understand what you've explained @khurshid-alam - I have not found the NUmix Blue project entry to post to it, I'm sorry.

Can it be fixed?

**Comment by khurshid-alam** [comment]
@nathaneltitane Numix Blue is not our project. Someone else created it. You can try reaching the developer who created it. https://github.com/aceat64/Numix-Blue
