### ISSUE TITLE
Stark black BG in GCC 3.9.X

### ISSUE THREAD

**Issue by me4oslav** [numixproject/numix-gtk-theme#61]
Running Gnome 3.9.x and respectfully Gnome Control Centre 3.9.X (from Gnome 3 staging PPA) and Numix from our PPA and I haz some stark black coloured BG in it.
See the attached screenie.
![screenshot 2013-09-09 21-49-36](https://f.cloud.github.com/assets/1658870/1109555/8b30375a-1982-11e3-9224-edf8fd2be910.png)

**Comment by satya164** [comment]
I cannot reproduce this with Gnome 3.10 in Fedora. It's most likely to be related with overlay scrollbar. Does this occur with Adwaita or Ambiance?
