### ISSUE TITLE
Where's Numix Light & Dark?

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#618]
Hello,

Where can I download the Light theme?

It's being talked about on deviantart;

http://satya164.deviantart.com/art/Numix-Light-GTK3-theme-391993388

thanks

**Comment by khurshid-alam** [comment]
Numix light hasn't really been ported to 3.20. I have started porting....but it could take a while. And it's not an open source theme. So you have to purchase it. Deviantart page will be updated when it's ready.

**Comment by ghost** [comment]
I'm on 3.18, is there a free version for that?

By the way, what distro are you using?

Because the last time I looked on distrowatch.com I didn't see any of the 300 distros there being charged for.

People put out entire systems and applications for free, charging for themes is a disgrace!

**Comment by khurshid-alam** [comment]
No. Unfortunately there is no free version. Only Numix and Numix-Dark are available for free.

And it It has nothing to do with distro. Numix-Light is closed source and it was for $3. Due to lack of maintenance purchase option was removed from deviant-art. However after porting we may make it free.

**Comment by ghost** [comment]
Closed source themes, never heard of that one before... :(

**Comment by craft37** [comment]
@khurshid-alam So if you plan to finish Numix Light and than make it free, why you not open sourse it already?
Now I am in situation when I bought the theme but cannot download it from Deviantart and Ubuntu Software, neither maintain it by myself. :(

**Comment by khurshid-alam** [comment]
@craft37 
There is a issue with the license. Also it depends on the original authors. But if you are interested in contributing I can give you the access to https://github.com/khurshid-alam/Numix-Light (private repo)

In that case please send me a email.

**Comment by satya164** [comment]
We had decided to publish the source when we remove the purchase option. cc @Foggalong

It's not really closed source, since the source code is almost the same as the normal theme with just a few tweaks.

**Comment by craft37** [comment]
@khurshid-alam I noticed that this original repo have two options - dark and normal version.
Normal version is light, right?
If @satya164 decided to publish the source it's better to maintain Numix Light here.

**Comment by khurshid-alam** [comment]
@craft37 No. Normal is normal (mixture of dark & light). Dark is not really a variant but rather a scheme of gtk.

**Comment by craft37** [comment]
@khurshid-alam Gotcha. So let's make a separate branch for Light in this repo, maybe?

**Comment by craft37** [comment]
@khurshid-alam Gotcha. 
So let's make a separate branch for Light in this repo, or please provide the access to you private one.

**Comment by craft37** [comment]
@satya164 Any estimates, maybe?

**Comment by satya164** [comment]
sorry I don't work on it anymore.

**Comment by craft37** [comment]
@satya164 I mean publish the source

**Comment by craft37** [comment]
@satya164 I mean for publish the source

**Comment by khurshid-alam** [comment]
@craft37 There is no timeline as of now. But hopefully it will happen at the end of the winter.

**Comment by craft37** [comment]
@khurshid-alam @satya164 Guys, open it as is maybe?

**Comment by Foggalong** [comment]
Even if they're no longer being actively worked on, I think it would be nice if both the Light and Dark themes could be open sourced so that if people want to port/update/fork they can.

**Comment by khurshid-alam** [comment]
@Foggalong @satya164 said It is up to you to make that happen. Isn't it? I can merge my work once Numix-Light get published.

**Comment by Foggalong** [comment]
@khurshid-alam I don't have access to the source code repos for either of those projects. I'm not sure where they were hosted because they aren't on the GitLab. @satya164?

**Comment by khurshid-alam** [comment]
Last time I checked it was on google drive. And no, I don't have access to that folder either. Satya sent me the tarball.

**Comment by Foggalong** [comment]
@khurshid-alam Oh right! If the one on Google Drive is the latest then I'll get it uploaded to a new GitHub repo asap :)

**Comment by khurshid-alam** [comment]
Alright. Thanks.

**Comment by khurshid-alam** [comment]
@Foggalong Can you set up the new github repo with Numix-Light?

**Comment by Foggalong** [comment]
Thanks for being patient while I got around to doing this! Here are the repos for [Numix Dark](https://github.com/numixproject/numix-gtk-theme-dark) and [Numix Light](https://github.com/numixproject/numix-gtk-theme-light). Ball's in your court now GTK team :wink:
