### ISSUE TITLE
GTK 3.20 :: Support for new Unity appearance option "Show the menus for a window: In the window's title bar"

### ISSUE THREAD

**Issue by Sadi58** [numixproject/numix-gtk-theme#632]
Behavior for hover/selection on Ubuntu's Unity top panel, which also serves as title/menu bar for maximized windows (as well as global menu bar, which now is optional) is a lighter grey bgcolor, but if the new option "Show the menus for a window: In the window's title bar" is selected, there's no difference at all for hover/selection on the title/menu bar of unmaximized app windows (GTK 2/3) .

On the other hand, when you open Synaptic Package Manager as root, the menu bar hover/selection behavior is the same as Unity top panel, i.e. lighter grey bgcolor.

Unity top panel:
![unity](https://cloud.githubusercontent.com/assets/6375934/20536498/08cc3d94-b0f2-11e6-88dc-f5e28ab13a6f.png)
Nautilus window:
![nautilus](https://cloud.githubusercontent.com/assets/6375934/20536515/139b2032-b0f2-11e6-9656-dcb3dc41ac78.png)
Nautilus maximized window - using top panel as menu bar:
![nautilusmax](https://cloud.githubusercontent.com/assets/6375934/20536730/d438400e-b0f2-11e6-8100-f6fc5f3b3169.png)
Synaptic window:
![synaptic](https://cloud.githubusercontent.com/assets/6375934/20536522/19b0d7fa-b0f2-11e6-9432-74cae0c64844.png)

**Comment by khurshid-alam** [comment]
@Sadi58 Screenshot?

**Comment by Sadi58** [comment]
@khurshid-alam Edited above now with screenshots.

**Comment by khurshid-alam** [comment]
If I am not wrong...the second screenshot of nautilus is without root and 3rd is with root? Do you have numix related themes under ~/.themes? If you do, try removing those.

And why nautilus is not showing horizontal global menu for non root window?

**Comment by Sadi58** [comment]
Only Synaptic Package Manager is with root in the screenshots above.
I'm using a tweaked version of Numix (changing only selection bgcolor and the like to blue) named Numix-Blue, but I switched to default Numix, removed my Numix-Blue, and saw no difference (naturally).
I use Unity with menus displayed in app window title bar (new option) instead of global menu bar (Unity top panel) unless they're maximized.
So I think this must be the cause of this - probably Numix GTK theme assumes the users have only a global menu. When I change my settings to use global menu bar, naturally this inconsistency disappears.

**Comment by khurshid-alam** [comment]
For me it's ok....

![screenshot](http://i.imgur.com/5T2Opgz.png)


About nautilus, Unity's global menu patch is broken for nautilus on 16.10 I guess.

**Comment by Sadi58** [comment]
It seems I couldn't make myself clear enough, sorry.
This is also what I see (1) when I have a maximised app window, and also (2) when I choose `System Settings... > Personal: Appearance >  Behaviour: Show the menus for a window: In the menu bar`.

The problem appears only when you choose to see the menus `In the window's title bar` instead of the global menu bar (i.e. Unity top panel)

I'm ignorant about theming, but it seems to me like menu bar behaviour is defined for global menu bar only, although in the past I used to see sort of Unity.Window.Decoration section, I don't know...

Or maybe this is due to a Unity bug that causes app windows (title bar) to fail in taking over the function of the global menu bar.

As a result I should better go back to the use of global menu bar again for the sake of consistency (although it's somettimes inconvenient when a large external monitor is connected) at least until this problem is resolved.

**Comment by khurshid-alam** [comment]
It seems .menu style is overwriting titlebar menu style (bg color) when using local menu-bar. Could be a unity bug. I will try and reproduce in zesty.

**Comment by Sadi58** [comment]
FYI: Some other GTK themes like **Greybird** don't have this problem. So maybe the their CSS coding for menubar covers this new Unity feature as well.

**Comment by megax** [comment]
@Sadi58, @khurshid-alam Fixed code: https://github.com/numixproject/numix-gtk-theme/pull/647 Please test.

**Comment by Sadi58** [comment]
It seems this is for GTK 3.22 only. No change in GTK 3.20 (Ubuntu 16.10) even if I copy and paste that code to the relevant block in menubar section.

**Comment by bilelmoussaoui** [comment]
@Sadi58 you must build the theme. The code in the commit is a sass code;)

**Comment by Sadi58** [comment]
@bil-elmoussaoui thanks, I know that...
@khurshid-alam thanks, it's all OK now :-)
