### ISSUE TITLE
System Settings 

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-gtk-theme#634]
Hi, can improve (change) the System Settings (white) background? 
Thanks.
![system settings_033](https://cloud.githubusercontent.com/assets/1277920/20862289/aca27976-b98d-11e6-95fa-bcabbb97b434.png)

And, where can I post the issue regarding selected icons... they have pixelated edges. This annoys me since long time ago. Look above on the "Online Accounts" icon for example

**Comment by khurshid-alam** [comment]
For icons please open a issue at numix-icon-theme-circle.

**Comment by bilelmoussaoui** [comment]
@khurshid-alam For the icons, i don't think it's an icon issue. it's more a hover effect that should be removed.

**Comment by megax** [comment]
Ubuntu coding bug... Default ubuntu theme (ambiance) buged. Not numix specific.
Cinnamon gtk 3.18 and 3.20 fix https://github.com/numixproject/numix-gtk-theme/pull/471:
https://github.com/numixproject/numix-gtk-theme/blob/master/src/gtk-3.20/scss/apps/_cinnamon-applications.scss#L6

**Comment by leoheck** [comment]
@khurshid-alam, considering the icons problem, look the palob answer:
https://github.com/numixproject/numix-icon-theme/issues/1169#issue-193370591
If you guys confirm this is a new numix-gtk-theme issue I can open a new one.

**Comment by khurshid-alam** [comment]
Yeah, I saw that. Unity uses old gnome-control-center. So we may need a separate style for like cinnamon. Icon problem is probably due to improper border radius.

**Comment by ghost** [comment]
@leoheck The pixelated edges will not appear when I use Adwaita theme(no hover effect), so it should be a numix-gtk-theme issue about icon highlight

**Comment by khurshid-alam** [comment]
@megax If it can be fixed for cinnamon, it can also be fixed for Unity-Control-Center. No? If yes, open a separate pull.

**Comment by megax** [comment]
@khurshid-alam Fixed code: https://github.com/numixproject/numix-gtk-theme/pull/646 Please test :)

**Comment by leoheck** [comment]
Someone can confirm that the bg color is right? I think it is the wrong gray.

![image](https://cloud.githubusercontent.com/assets/1277920/22606708/f9b5cd38-ea3b-11e6-8fcf-d5d984ca64c7.png)

**Comment by khurshid-alam** [comment]
Hover and focus effects are missing from Unity-Control-Center...which will be fixed soon.

**Comment by leoheck** [comment]
Ok, but what about the background color? Is this the right gray?
