### ISSUE TITLE
Slider "bubble" cut off by 1 pixel on some applications.

### ISSUE THREAD

**Issue by MasterLink86** [numixproject/numix-gtk-theme#635]
Ubuntu 16.04 LTS 64-bit, up to date via apt-get upgrade as of 2 hours ago, and is using the Numix PPA, which is also as up to date as of this writing.

Applications affected: VMPK, Gqrx, OBS

The sliders, as seen in the screenshots provided, appear to be cut off by 1 pixel on these apps.  On other apps it seems to be fine, and in Gqrx, the slider is ok in some spots, while cut off by a pixel on the top in others.  It's not consistent, but the bubble is always cut off in the same exact spot on these apps.

![screenshot from 2016-12-19 04-12-32](https://cloud.githubusercontent.com/assets/2136976/21307107/17c39436-c5a2-11e6-8208-7ffb6135e42b.png)
![screenshot from 2016-12-19 04-13-20](https://cloud.githubusercontent.com/assets/2136976/21307106/17c2d51e-c5a2-11e6-8ecb-29212e2536e0.png)
![screenshot from 2016-12-19 04-14-00](https://cloud.githubusercontent.com/assets/2136976/21307105/17c27a74-c5a2-11e6-890f-32955b29a936.png)

Hopefully these screenshots help.  Otherwise, this theme has been absolutely perfect to my liking, minus some icon issues which I'll make another bug report on.

**Comment by khurshid-alam** [comment]
Looks like a qt5 issue.

**Comment by MasterLink86** [comment]
That's what I was thinking, but I couldn't actually tell if the apps were using QT or not (other than VMPK which advertises it in the Help menu).

However, I can't install the QT (KDE) themes because there are none for Ubuntu 16.04 in the PPA I used.

**Comment by MasterLink86** [comment]
I can't tell, and perhaps my eyes are failing me as I get older, but it almost looks like it's less of the fact that the bubble is cut off, but more that the bubble is 1px too high above the slider line, as compared to native GTK applications.

**Comment by khurshid-alam** [comment]
Is this reproducible with other themes? I couldn't reproduce this on zesty which uses newer versions.

**Comment by MasterLink86** [comment]
No, other themes I tried seemed to be working just fine..  I'll keep trying a few other themes to see if I can find one.  One thing I notice though is in other themes, the slider bubble (or widget, whatever you call it), isn't as large in them as it is in Numix, so it may be a case of, it "is" actually cutting off but because it isn't as large, we wouldn't see it.

**Comment by khurshid-alam** [comment]
Closing as we are dropping support for 16.04 soon.
