### ISSUE TITLE
Small window border

### ISSUE THREAD

**Issue by sojusnik** [numixproject/numix-gtk-theme#637]
After a fresh Ubuntu Gnome 16.10 installation the window border is disproportionately small, as depicted [here](http://i.imgur.com/HMLTCaR.png).

Seems like a bug, or is this really by design?

numix-gtk-theme has the version `2.6.6+626~201611150117~ubuntu16.10.1`

**Comment by megax** [comment]
Not bug, really design :) Nautilus, gedit etc normal (old style) window titlebar decoration.
Gnome-Hilfe: Gnome 3.10 feature. Sample (Adwaita theme): 
![image](https://cloud.githubusercontent.com/assets/461493/21741587/2cdff4f2-d4db-11e6-940c-c5c5838b1ab8.png)

**Comment by sojusnik** [comment]
Apps like Gedit, Nautilus and the like have indeed a normal border height (due to Gnome's menu integrated in it), but Firefox and Transmission, as you can see in my linked screenshot in the first post, definitely have a very small one. Don't you think so?

**Comment by khurshid-alam** [comment]
@sojusnik If you don't like headerbar in Unity, you can disable it using no-csd plugin (https://github.com/PCMan/gtk3-nocsd). How it has nothing do with our gtk theme. We support both headerbar and traditional titlebar-headerbar app.
