### ISSUE TITLE
File transfer dialouge not vanishing

### ISSUE THREAD

**Issue by meetdilip** [numixproject/numix-gtk-theme#638]
File transfer indicator on File manager icon ( in launcher ) does not vanish even after file transfer finished. I am not facing this issue while use Adapta Theme. Happens also with the file transfer indicator in the file manager window. I mean, in the circle that indicates file transfer progress.

**Comment by khurshid-alam** [comment]
Distro? Is this reproducible with Adwaita? I think it's a bug with nautilus

**Comment by khurshid-alam** [comment]
This is a known bug for nautilus.
