### ISSUE TITLE
Ubuntu Software Center look is out of place

### ISSUE THREAD

**Issue by Hacker-Planet** [numixproject/numix-gtk-theme#64]
I have the Numix dark theme installed and the Ubuntu software center looks a bit out of place with the theme, some places look ok and when you go to see different sections the text is light and hard to read and the background is white.
![screenshot 2013-09-12 18 15 41](https://f.cloud.github.com/assets/500779/1135039/683ccffa-1c03-11e3-8052-1578ade6d9f2.png)

**Comment by satya164** [comment]
Yeah. USC uses custom CSS and it messes up the theme. I'll try to fix it soon. Expect the fix to arrive with next release.

**Comment by satya164** [comment]
Sorry to disappoint. But USC uses so much custom stuff that I don't seem to be able to theme it correctly. The bug cannot be fixed in Numix. It's up-to the USC devs if they want to support third party theming or not.

**Comment by Hacker-Planet** [comment]
It's cool, it is the application that doesn't fit well but I can live with it

**Comment by strycore** [comment]
One workaround is taking the stylesheet from the Plane Gtk theme here: http://gnome-look.org/content/show.php/?content=156309 and rename it to softwarecenter.numix.css then copy it to /usr/share/software-center/ui/gtk3/css

The Software Center will play along nicely with numix.
