### ISSUE TITLE
gtk3.22.5 :: Geary :: White fonts on button

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#640]
The Gnome mail application Geary will show white fonts on white buttons with numix gtk theme. It looks like this picture:
![screenshot from 2017-01-07 01-45-50](https://cloud.githubusercontent.com/assets/24662041/21727916/8d68da76-d47e-11e6-8cd6-0a7ed3019366.png)

**Comment by rewqazxv** [comment]
When click the first button shows "Show pictures" and the second also shows something. So it should be a colour issue.

**Comment by megax** [comment]
@rewqazxv Numix theme version?
https://github.com/numixproject/numix-gtk-theme/issues/572

**Comment by khurshid-alam** [comment]
Distro?
Os?

This was the problem with new webkit in 3.20. I thought fixed it in 7254e08.

**Comment by ghost** [comment]
Oh, I didn't see that closed issue...
This problem is fixed in the latest version. Thank you.
