### ISSUE TITLE
XFCE: Dragging gtk3 applications with client-side decoration issue

### ISSUE THREAD

**Issue by jackgu1988** [numixproject/numix-gtk-theme#641]
I am using XFCE on Fedora 25 and when I am moving gtk3 applications that are using client-side decoration (like evince), I get a very weird behaviour. When I start dragging the window, it starts maximizing and unmaximizing constantly. When I finally manage to drag it to the screen border, so that it takes up half the screen, it usually takes the wrong size. I reset all my XFCE configuration and the first problem was solved. However, when I drag the window to the screen border nothing happens. I do not get this issue on any other theme.

**Comment by khurshid-alam** [comment]
Numix theme version?

**Comment by jackgu1988** [comment]
Version 2.6.0 (shipped with Fedora 25). I tried compiling version 2.6.6, but it fails (I installed all the required packages and followed the instructions on the README). Unfortunately I don't have time for the next few weeks to figure out why it is not compiling.

I am guessing I have to report it on Fedora's bug tracker, as it may have been fixed here.

**Comment by khurshid-alam** [comment]
Please comment here if it gets fixed. It doesn't look like a theme issue though.

**Comment by khurshid-alam** [comment]
@jackgu1988 Still experiencing the problem?

**Comment by jackgu1988** [comment]
Yes I am, but a bit different. Sorry I tried a clean install and forgot to mention. Now it works, but gtk3 windows with client side decisions don't tile when I drag them to the border. Very rarely they do tile, but usually their size is wrong (covers more than half of the screen). All other windows work perfectly fine, as do the gtk3 applications with other themes.

**Comment by khurshid-alam** [comment]
Open a new issue for tile problem.
