### ISSUE TITLE
Inkscape 0.92 GTK3 theme (snap package)

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-gtk-theme#642]
Hi, someone already tried the new Inkscape 0.92?
Installing with the snap package it looks old. 

http://www.inkscapeforum.com/viewtopic.php?t=31548

**Comment by khurshid-alam** [comment]
.92? Gtk3? Snap doesn't have proper support for gtk3-theme yet.

**Comment by leoheck** [comment]
> Not an Inkscape problem - the current Snap package for Inkscape just does not include GTK2 theming (see also these tweets).

Look: [this](https://twitter.com/tedjgould/status/817377039464464384) and [this](https://twitter.com/tedjgould/status/817381605924831232)

Edit: Hm, ok. I misunderstood what you said @khurshid-alam

**Comment by khurshid-alam** [comment]
I will try to create a hack to make it work with snap-edge.

**Comment by leoheck** [comment]
I installed [inkscape-trunk](https://launchpad.net/~inkscape.dev/+archive/ubuntu/trunk) yesterday to give it a try, and it looked better than the snap version. Some gtk items were not so good. I don't know if this is caused by the numix-gtk-theme or by the application itself. There are also some icons that are duplicated and missing. Unfortunately I don't have a screenshot right now.

**Comment by khurshid-alam** [comment]
A screenshot will be nice. Inkscape trunk is just normal debian package (which is why it should work...and it is working for me with Ubuntu 16.04/16.10/17.04). 

For snap We need to wait for proper support for gtk-themming.

**Comment by leoheck** [comment]
Inkscape-trunk looks better now. Probably it was a build that was not so good.
![image](https://cloud.githubusercontent.com/assets/1277920/22182961/832268b2-e099-11e6-8741-5cc0858b5200.png)

**Comment by mustaphaasbbar** [comment]
how can i replace the default icons with the symbolic ones  in windows

**Comment by pedzed** [comment]
```bash
snap install inkscape
```

Inkscape 0.92.3 (d244b95, 2018-08-02)

![image](https://user-images.githubusercontent.com/8146593/45255707-f4e04f80-b38a-11e8-800d-562c0829fab0.png)

I'm not really satisfied with the snap look.

**Edit:** I just realized that this is not the Inkscape repo. I came here by a Google search.
