### ISSUE TITLE
California (Calendar) unredable text

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-gtk-theme#645]
Look the summary input and the OK button. The white text is the selected one. Look 
![california_046](https://cloud.githubusercontent.com/assets/1277920/22156670/7e16c82e-df1b-11e6-9c47-5adc6741986c.png)

**Comment by khurshid-alam** [comment]
California is not maintained. It will create trouble with anything >= Gtk-3.20. Does it work with Adwaita?

**Comment by leoheck** [comment]
I don't have Adwaita installed. How did you installed it? But it has the same issue in Ambiance.

**Comment by khurshid-alam** [comment]
Closing. California is not maintained & won't work for >= gtk-3.20
