### ISSUE TITLE
Plank strange text sizes

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-gtk-theme#648]
The text is changing its size. From issue https://github.com/numixproject/numix-gtk-theme/issues/644#issue-202169519

![image](https://cloud.githubusercontent.com/assets/1277920/22620677/1c609a04-eaf8-11e6-8f4e-39e44c62ea18.png)

![dc481826-e097-11e6-9408-ecdc39fa2af8](https://cloud.githubusercontent.com/assets/1277920/22211871/b60a2d00-e175-11e6-8546-08bfb0ad16c3.png)

Edit: 1st image was updated.

**Comment by khurshid-alam** [comment]
Already fixed in latest plank.
