### ISSUE TITLE
The circle in volume indicator look more like Bjorn than Agnetha! :>

### ISSUE THREAD

**Issue by me4oslav** [numixproject/numix-gtk-theme#65]
That circle we have in the volume indicator is simply not sexy enough. 
Change it to something mean and lean.
http://i.imgur.com/K14v3Ld.png

**Comment by satya164** [comment]
Hmm... Suggestions?

**Comment by fitojb** [comment]
The contrast is what makes it look a bit out of place in this menu. I don’t know if it’s possible in GTK, but perhaps if the circle was semitransparent, it’d look better. Just an idea.

**Comment by me4oslav** [comment]
I think it is possible and I think we even had a version with it, but it looked kinda weird.
Anyways, we can have a look again if @satya164 makes one and decide if we want it.
