### ISSUE TITLE
Unity: launcher when positioned to bottom, theme reverts to default 

### ISSUE THREAD

**Issue by makdamujji** [numixproject/numix-gtk-theme#650]
Distro: Ubuntu 16.10
Unity version: 7.5.0
GTK: 3.20.9-1ubuntu2
**Issue**
When the unity launcher is placed at bottom (available since Ubuntu 16.04) the launcher reverts back to default theme.
**Launcher in left position:**
![n2](https://cloud.githubusercontent.com/assets/25422642/22409078/4f3477f4-e6aa-11e6-9928-20030df78d45.png)
**Launcher in bottom position:**
![n1](https://cloud.githubusercontent.com/assets/25422642/22409083/5f9cafd0-e6aa-11e6-80d9-b731b6e89b5a.png)
(The "line" style for denoting active programs is replaced by default "triangles" in bottom position)

**Comment by khurshid-alam** [comment]
Not sure if it's a theme issue or not.

**Comment by makdamujji** [comment]
The reason I believe it is a theme issue is because there are no theme instances (sprites) available for launcher for bottom position.

**Comment by khurshid-alam** [comment]
This is how our dash asset is. We can't change that as the same asset are being used for several docks in various desktop sessions.
