### ISSUE TITLE
GTK 3.0 source script, toolbar color ignored

### ISSUE THREAD

**Issue by leipero** [numixproject/numix-gtk-theme#653]
When building theme (both master and latest), if toolbar color is changed in global.scss it gets ignored, even if it's defined in colors.scss also (for example, @dark_bg_color etc.) it still gets ignored.

This proably got broken when structure was changed ~6 months ago.

**Comment by khurshid-alam** [comment]
We are not using **color.scss** (unless certain widgets overwrites). `$tooolbar_bg_color` is `$bg_color` (defined in **global.scss**) which again depends on the theme variant.

**Comment by leipero** [comment]
Well, that's my point, if someone tries to redefine $tooolbar_bg_color to something else in global.scss (for example, setting it to $dark_bg_color instead of $bg_color), it doesn't work in GTK-3.0 version, it did work before restructuring (or at least 7-8 months ago).

But if that is the way it should be, it's ok, just wanted to let you guys know in case it isn't.
