### ISSUE TITLE
GTK theme parsing error with mate-menu and firewall-config

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#654]
I'm using the Numix theme with the mate-menu applet and I get these log spams everytime the menu is opened:

> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4523:12: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4523:12: not a number
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4475:16: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4475:16: not a number
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4473:12: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4417:22: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4417:22: not a number
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4402:16: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4402:16: not a number
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4393:12: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4393:12: not a number
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4331:14: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:4331:14: not a number
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:3755:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:2287:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:2287:8: not a number
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:2282:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:2282:8: not a number
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:1099:17: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:1096:14: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:1096:14: not a number
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:787:17: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:784:14: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:784:14: not a number
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:600:17: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:597:14: Expected a string.
> Feb 17 17:48:56 localhost mate-menu[1388]: Theme parsing error: gtk.css:597:14: not a number
> 

And with firewall-config:

> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4523:12: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4523:12: not a number
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4475:16: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4475:16: not a number
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4473:12: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4417:22: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4417:22: not a number
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4402:16: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4402:16: not a number
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4393:12: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4393:12: not a number
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4331:14: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:4331:14: not a number
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:3755:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:2287:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:2287:8: not a number
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:2282:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:2282:8: not a number
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:1099:17: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:1096:14: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:1096:14: not a number
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:787:17: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:784:14: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:784:14: not a number
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:600:17: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:597:14: Expected a string.
> Feb 17 17:52:29 localhost firewall-config[3513]: Theme parsing error: gtk.css:597:14: not a number
>

**Comment by khurshid-alam** [comment]
Theme version? Distro? Os?

**Comment by ghost** [comment]
> numix-gtk-theme.noarch               2.6.0-1.fc25                  @@commandline
> numix-icon-theme.noarch              0.1.0-12.git101307f.fc25      @@commandline
> numix-icon-theme-circle.noarch       0.1.0-11.gitc3aefdb.fc25      @updates 

Fedora 25

**Comment by khurshid-alam** [comment]
@USER762341 Can you try gtk-theme from git master and produce the output here?

**Comment by khurshid-alam** [comment]
I can not reproduce this with master. We moved from pango to css. Closing. Please reopen if you can reproduce.
