### ISSUE TITLE
Terminix white line on top.

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-gtk-theme#655]
Terminix just updated to the version `1.5.0`. Now it displays a white line on top. Someone knows how change it?

![terminix default_028](https://cloud.githubusercontent.com/assets/1277920/23140631/6a5dd21c-f791-11e6-88dd-a1ae8924f07e.png)

**Comment by khurshid-alam** [comment]
Does it happen with other themes?

**Comment by leoheck** [comment]
I don't have many themes here, and none of the themes I have, have this little bar dark. Probably this white line is dark in the other themes. Ah, the arc theme is okay!

**Comment by leoheck** [comment]
Today, the white line has disappeared in my notebook. Later I will check at my work to see if it goes away.

Edit: Oh, and it can be related with OS version. I have 16.10 on my notebook. At work 16.04.

**Comment by bilelmoussaoui** [comment]
The white line must be caused by the scrollbar of Gtk.scrolledwindow !  There was a fix upstream on terminix, not sure if it's on the master branch or was released with 1.5.0

**Comment by khurshid-alam** [comment]
So can anyone check Terminix from master that it still exists?

**Comment by leoheck** [comment]
I don't have this problem on my notebook with Ubuntu 16.10 and I have this issue on Ubuntu 16.04 at my work, so. I will have to test it tomorrow.

**Comment by bilelmoussaoui** [comment]
Someone reported this upstream. I will try this tomorrow and see if I can reproduce it 
https://github.com/gnunn1/terminix/issues/799

**Comment by gnunn1** [comment]
I had a look, I think it's because Numix doesn't declare the @borders color or it is set to a white/grey color. I've posted a comment on the terminix bug report with how to fix this:

https://github.com/gnunn1/terminix/issues/799#issuecomment-282563306
