### ISSUE TITLE
Terminix: CSS class(es) to terminal title 

### ISSUE THREAD

**Issue by lburgazzoli** [numixproject/numix-gtk-theme#657]
Terminix has now a CSS class to customize the terminal title [1] so it would be nice if Numix can make it working similar to the gnome-terminal (i.e. active terminal with red title).

[1] https://github.com/gnunn1/terminix/issues/688

**Comment by khurshid-alam** [comment]
Terminix is tilix now. Did they change the class names?

**Comment by bilelmoussaoui** [comment]
@khurshid-alam Yep https://github.com/gnunn1/tilix/blob/master/data/resources/css/tilix.base.css
