### ISSUE TITLE
Checkboxes and radio buttons need to be morre distinct

### ISSUE THREAD

**Issue by imranmunshi** [numixproject/numix-gtk-theme#658]
The status of checkboxes and radio buttons is not visibly distinct when they are selected/unselected. I don't know how but they should be more distinctly distinguishible when they are selected, right now they just go from shaded to orange'ish colour. Like in the following, UTF-8 radio button is selected which is quite unnoticeable from a distance of more than 2 feet
![2017-03-15-14 02 10-screen](https://cloud.githubusercontent.com/assets/5736192/23940189/006b3556-098a-11e7-8628-607b89a05bfb.png)

Arch Linux, XFCE, numix-gtk-theme-git from AUR

**Comment by khurshid-alam** [comment]
We are using our own assets for that. But I don't really see any problem with that. It's not orangeish , it's rather bright reddish.
