### ISSUE TITLE
GTK 3.20 :: white border around window

### ISSUE THREAD

**Issue by bbernardoni** [numixproject/numix-gtk-theme#659]
I have just installed the non-git version of numix-gtk-theme on arch linux and with gtk 3.20 apps there seems to be a white border around the windows. I have specifically noticed this with gnome-calculator and evince. I have confirmed that these apps are using the gtk3.20 theme and I have tried to fix it, but I am very new to this and cannot find what exactly is causing it. 

I tried to search for a solution online but everything I found was for gtk 3.0 and the changes they suggested did not work for 3.20. The closest I found was #281. It looks like the exact same problem I have but the fixes suggested did not seem to work.

![numix_white_border](https://cloud.githubusercontent.com/assets/6415389/24112854/d35a6144-0d68-11e7-80a9-a973c44f970e.png)

**Comment by khurshid-alam** [comment]
The fix won't work because it is for Gtk-3.18. Gtk-3.20 doesn't really have this problem. Can you try using from git? I couldn't reproduce the issue. 

![calc](https://i.imgur.com/D2vcIfY.png)

**Comment by sw9** [comment]
I just installed from git and I'm experiencing this issue on i3wm with csd applications. However, the white border doesn't appear under unity. I'm running compton as my compositor. Also just for comparison, I tried arc theme as well and there is no white border present.

**Comment by bbernardoni** [comment]
I just installed the git version as well and the problem persists.

**Comment by khurshid-alam** [comment]
Does your window manager support compositing? Because I can't reproduce under mutter either.

**Comment by sw9** [comment]
Compton does compositing. As a work around, I changed `background-color: $fg_color` in `.solid-csd &`, and it's a lot less ugly now.
