### ISSUE TITLE
Chrome task manager process bars appear black

### ISSUE THREAD

**Issue by facboy** [numixproject/numix-gtk-theme#660]
Chrome Version 57.0.2987.110 (64-bit) on Xubuntu 16.04

The bars (scrollbars?) on the left of the task column that indicate shared processes appear totally black.  This doesn't happen with eg Greybird.  I tried playing around with gtk-2.0/gtkrc but the only thing that had any effect was deleting line 670:

```
class "GtkWindow" style "metacity-frame"
```

It seems like it's completely ignoring the styles linked to ChromeGtkFrame.

**Comment by khurshid-alam** [comment]
Screenshot? Is this same with chromium? Also chrome is about to switch to gtk-3. So it could be a bug in chrome/chromium.

**Comment by facboy** [comment]
Oops, that would be helpful!  It does happen on chromium as well.

![image](https://cloud.githubusercontent.com/assets/222095/24455505/b8921a52-1487-11e7-879d-37227645e4bb.png)

**Comment by khurshid-alam** [comment]
Chromium stable buids switched to gtk3 which fixed this bug.
