### ISSUE TITLE
Ubuntu MATE Window List handle missing

### ISSUE THREAD

**Issue by facboy** [numixproject/numix-gtk-theme#661]
The handle on the Window List panel doesn't render under Numix on Ubuntu MATE 16.04.

![image](https://cloud.githubusercontent.com/assets/222095/24544466/4af48668-15fb-11e7-8209-e7f97af02584.png)

That blank gap is where the handle is supposed to be.

**Comment by khurshid-alam** [comment]
@facboy 
A bigger screenshot perhaps ?

**Comment by facboy** [comment]
the screenshot above shows you the handle of the Window List (or rather where the handle should be), what would you like to see in the bigger screenshot?

**Comment by khurshid-alam** [comment]
It's hard for me to see which part of window-list you are talking about. Take a full screen screenshot and point me to it (or just put a arrow with gimp)

Do you use custom background? What are the applets you are using? Mate 16.04 is gtk2 and I can not reproduce it.

**Comment by facboy** [comment]
Hmm...ok while taking the screenshots, I was trying to contrast it with XFCE4 (where I can see the handle).  It seems that it's a clash with the panel background.  If I leave Alpha at 100 (the default), then I can't see the handle (I've made a mini-panel to demonstrate):

![image](https://cloud.githubusercontent.com/assets/222095/25013591/16f040b6-206c-11e7-8cc7-74d52ca8527a.png)

If I turn the Alpha down (so that the panel background becomes lighter on this white background) then I can see the handle (the 3 bars to the left of the Chrome window button):

![image](https://cloud.githubusercontent.com/assets/222095/25013550/e80b5b00-206b-11e7-8c01-6089b401e213.png)

The XFCE panel settings:

![image](https://cloud.githubusercontent.com/assets/222095/25013610/2a9e9ffe-206c-11e7-8137-6b2e859e04d1.png)

I assume that on MATE the panel alpha is 100 by default.  Does that help?

**Comment by khurshid-alam** [comment]
Yes. It was designed to blend in with panel doesn't look ugly. In gtk3 we could use lighter color on hover for window-list handle, but not sure we could do that for gtk2.

**Comment by facboy** [comment]
It's a design decision and up to you, but my personal opinion is that having it blended in to the point that it's invisible is not very useful.  How will users know to hover over it in the first place if they can't see it?
