### ISSUE TITLE
XFCE Whisker Menu Support (Gtk 3?)

### ISSUE THREAD

**Issue by flg** [numixproject/numix-gtk-theme#666]
Hello,

After upgrade to Xubuntu 17.04, it seems that the XFCE whisker menu (xfce-panel plugin) has lost support from Numix (I mean it appears pale grey whereas the theme is dark grey; and it used to be dark grey before upgrade). I suspect it could have something to do with port to Gtk 3.

If any information is needed, just ask.
Thanks

**Comment by mirkosrc** [comment]
I have the same issue for the whisker menu.
Also the background colour from the bars of xfce4-systemload-plugin is now white instead of black. 
Same for Okular pdf viewer background.

**Comment by khurshid-alam** [comment]
Screenshot ?  Theme version? Is it using gtk-3 or gtk-2?

**Comment by flg** [comment]
This shows the problem on an up-to-date Xubuntu 17.04 with Numix daily (taken from ppa).
![problem](https://cloud.githubusercontent.com/assets/325736/25607625/ba9f90a4-2f17-11e7-85b4-8b2432051b92.png)

This shows how it is working properly on a CentOS 7 with Numix 2.6.0 (release 1.el7).
![ok](https://cloud.githubusercontent.com/assets/325736/25607612/a735fd46-2f17-11e7-9c23-4c43c226321e.png)

I don't how to tell if it is using Gtk 2 or 3. Any hint?

**Comment by khurshid-alam** [comment]
The upper one is gtk3. The lower one is gtk2. We need to change whiskermenu background color. I will create a fix.

**Comment by c5e3** [comment]
i also noticed some change in 'gqrx', that uses gtk2 i guess
before:
![before](https://cloud.githubusercontent.com/assets/11488798/25664384/bf06c33e-301a-11e7-8e40-57ed4caa25f4.jpg)

after:
![after](https://cloud.githubusercontent.com/assets/11488798/25664385/bf18cc96-301a-11e7-9139-867b7138dc9e.png)

**Comment by MasterLink86** [comment]
c5e3, I wanted to let you know that is not a problem with Numix, 17.04 broke GTK themes from working in QT applications, like gqrx (which I use every day for emergency response).

I have a fix for it.

sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get install qt4-qtconfig qt5ct
nano ~/.profile - Add this line: export QT_QPA_PLATFORMTHEME=qt5ct
Log out, log in.
Launch qtconfig-qt4 and qt5ct and set both to "gtk".

If you can't open qt5ct for whatever reason (it's a fickle beast), and it's complaining that the platformtheme variable isn't properly set, just type the line in terminal, then open qt5ct, then it'll open, so you can set the theme to gtk..  We just need to set it to gtk, as it's likely stuck on the default KDE theme (like your screenshot shows, and same as mine).

**Comment by c5e3** [comment]
nice, big thx! :D
turned out, only qt5 was configured wrong. 
i also had to change the fonts in qt5.

**Comment by MasterLink86** [comment]
Ahh so it wasn't just me that had the fonts messed up too and looking overly large.

Glad it helped.

**Comment by mirkosrc** [comment]
@flg , did the fix, provided by @lnx64 , work  for you ? The whisker menu and the background colour of the xfce4-systemload-plugin bar looking still white instead of numix dark for me.

**Comment by flg** [comment]
I think the solution provided by @lnx64 has nothing to do with the original problem but is related to fonts and integration of Gtk theming in QT applications. Meaning I did not try.

**Comment by khurshid-alam** [comment]
@Mirkosrc I haven't pushed the fix in master. It's in my local repo. Will do in next weekend.

**Comment by mirkosrc** [comment]
@khurshid-alam Great,  thank you

**Comment by Limator** [comment]
@khurshid-alam This would be very nice! I like the dark whisker a lot more :D

**Comment by MasterLink86** [comment]
@flg, correct, this fix I provided has nothing to do with the menu, it was simply for @c5e3 who thought the issue they had was related to this thread, but it was not.

**Comment by Limator** [comment]
Hi at all, could anyboy help to fix this color-issue? Thanks a lot!

**Comment by ghost** [comment]
I tried to fix the issue but couldn't find any way to change whiskermenu's coloring. Anyone got a hint where to look at?

**Comment by ghost** [comment]
Still no news on that issue?

**Comment by mirkogym** [comment]
Stupid question: This issue is appears since 17.04.  In 16.10 it works. So the GTK+ 3 changes from https://xubuntu.org/news/xubuntu-17-04-release/  broke it. Wouldn't it be better if they fix it by adding downward compatibility ?

**Comment by Limator** [comment]
HI @khurshid-alam , any new on your fix for the gtk3/gtk3.2 whisker menu-decoration?

**Comment by khurshid-alam** [comment]
It seems they have done something to checkbox between 2.1.1 & 2.1.2, also I could not override some styles from theme. It will be fixed after I fix panel-applets.

**Comment by ghost** [comment]
Any news on that issue? Do you need any help?

**Comment by khurshid-alam** [comment]
@tuxedovinz See https://bugzilla.xfce.org/show_bug.cgi?id=13646

Any help is always welcome. :)

**Comment by Limator** [comment]
Maybe this helps:
If using gtk-dark.css as replacement for gtk.css (simple renaming it) the menu is dark ^^
Some other things are also dark, but I just want to say, that something inside the gtk-dark.css has also impact on the whiskermenu!

**Comment by hexum1** [comment]
Any word on this issue?

**Comment by khurshid-alam** [comment]
@hexum1 See https://bugzilla.xfce.org/show_bug.cgi?id=13646. It's broken on upstream. Without proper class it can not be themed. 

However, You can use a custom gtk.css in ~/config/gtk-3.0.

**Comment by hexum1** [comment]
Ok. I downgraded to an older version for the time being.

**Comment by mirkosrc** [comment]
For me, the theme is black again, after adding `gtk-application-prefer-dark-theme = true` in ~/.config/gtk-3.0/settings.ini  .

But the search bar background for Chrome is black too...

**Comment by flg** [comment]
Just wanted to comment that the (original) problem is still present: whisker menu has bright decoration when all the rest is dark.

gtk-application-prefer-dark-theme = true in ~/.config/gtk-3.0/settings.ini does not work for me.

**Comment by Simon-the-Sorcerer** [comment]
@flg Just create  `~/.config/gtk-3.0/settings.ini` and add

`[Settings]`
`gtk-application-prefer-dark-theme = true`

to it. The whisker menu should be dark now.

**Comment by flg** [comment]
I was missing the header. That works thanks.

**Comment by c0d3z3r0** [comment]
gtk-application-prefer-dark-theme breaks other applications like Chrome

**Comment by c0d3z3r0** [comment]
Please test if that works for you, too.
The default is to take xfce4-panel's css style but it can be overridden by ~/.config/gtk-3.0/gtk.css.
https://github.com/gottcode/xfce4-whiskermenu-plugin/pull/113

**Comment by c0d3z3r0** [comment]
As already mentioned in my xfce-whiskermenu issue my patch is not needed.
This one works for me:

~~~
#whiskermenu-window {
  background-color: #000;
}
~~~

@khurshid-alam

**Comment by khurshid-alam** [comment]
@c0d3z3r0 

Ah. I see. Can you open a pull? I think we also need a whiskermenu border ?

**Comment by c0d3z3r0** [comment]
@khurshid-alam I am absolutely new to SCSS, so maybe you could convert this to SCSS? :-)
This is what I am currently using:

~~~
#whiskermenu-window * {
  border: 0;
  outline: none;
}

#whiskermenu-window {
  background-color: #444;
  color: #ccc;
}

#whiskermenu-window entry {
  background-color: #555;
  color: #eee;
}

#whiskermenu-window button {
  background-color: #444;
  color: #ccc;
}

#whiskermenu-window treeview {
  background-color: #3e3e3e;
  color: #ccc;
}

#whiskermenu-window button:focus,
#whiskermenu-window button:hover,
#whiskermenu-window treeview:selected,
#whiskermenu-window treeview:hover
{
  background-color: #D64937;
  color: #fff;
}
~~~

![image](https://user-images.githubusercontent.com/6205797/40970062-c9bb6b62-68b9-11e8-9041-609419e0d851.png)
![image](https://user-images.githubusercontent.com/6205797/40970103-ec2099a2-68b9-11e8-81db-9960d5fed9d3.png)
