### ISSUE TITLE
Dark version on Ubuntu

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-gtk-theme#668]
I usually set numix theme with unity-tweak-tool on Ubuntu. Today, testing gnome-shell I found a dark version of numix which is awesome. Back to unity, it looks really cool. I would like to know if there is a way to set it in unity? Will be nice to have this information on README.md

**Comment by khurshid-alam** [comment]
You can set with gnome-tweak-tool. In appearance turn on Global dark theme. And then restart the session.

Global dark theme is not complete and requires more work. So you may find some issues. I plan to resume work for it in this cycle.

**Comment by leoheck** [comment]
Yeah, I discovered it with gnome-tweak-tool. I may have some issues, but it looks so cool!
