### ISSUE TITLE
Numix-Dark issues with Nautilus bread crumbs 

### ISSUE THREAD

**Issue by Hacker-Planet** [numixproject/numix-gtk-theme#67]
The bread crumbs in nautilus only show up after selecting a different folder, they use the be there when the file manager first opened.
![screenshot from 2013-10-02 15 44 44](https://f.cloud.github.com/assets/500779/1257228/eb159bbe-2ba3-11e3-82f3-80b460a8e04c.png)

**Comment by me4oslav** [comment]
Here is my nautilus with dark under GS: http://i.imgur.com/SKGVmVo.png
And here is under Unity: http://i.imgur.com/w78ItyG.png
I can not confirm this bug.

**Comment by Hacker-Planet** [comment]
I was using the Numix-dark 3.4 I switched to just numix-dark and it is all good now
