### ISSUE TITLE
gnome-terminal (and otehr apps) title bar and control buttons inconsistent size

### ISSUE THREAD

**Issue by leipero** [numixproject/numix-gtk-theme#670]
Arch, GNOME 3.24.2, master branch. Gnome-terminal and other non-CSD applications have inconsistent titlebar size (too small) compared to CSD applications.
Applications in screen shot (terminal, nautilus and Virtualbox):
![2017-05-10 10-54-39](https://cloud.githubusercontent.com/assets/21347343/25891216/80c4815a-3570-11e7-9c04-cf83d1b68593.png)

Online soulution of adding in ~/.config/gtk-3.0/gtk.css (partially) solved the problem:
```
.default-decoration {
    min-height: 0; /* let the entry and button drive the titlebar size */
    padding: 4px; }

.default-decoration .titlebutton {
    min-height: 32px; /* tweak these two props to reduce button size */
    min-width: 26px; }
```
Other themes, Adwaita for example also have smaller, but it is more in line as screenshot below after above workaround is done for Numix theme, so it's pretty much balanced (maybe it could be a bit smaller, this is my personal preference):
![2017-05-10 10-56-40](https://cloud.githubusercontent.com/assets/21347343/25891340/04607ee2-3571-11e7-8028-b9b9c46af70e.png)

**Comment by khurshid-alam** [comment]
The size is inconsistent because terminal doesn't use toolbar, also you have terminal menu hidden. And you are not using tabs on terminal. Ssd and csd decorates window in very different. 

Beside changing default decoration like that makes button rectangular and creates problems in other desktops sessions like mate and xfce.

**Comment by leipero** [comment]
Oh, ok, then we can close this i guess? Since I'm not using other DE's, it doesn't bother me to change it globally, but before 3.20 i think it was different, and Adwaita also have different size, but it's not as noticable.
