### ISSUE TITLE
Gnome Shell Theme

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-gtk-theme#674]
Hey guys,

I would like to help you with gnome shell theme. I have ~3 years experience with css3/html5/javascript/jquery/angular/etc. Just tell me what I need to do, also I suggest to create new repository "numix-gnome-shell-theme" for example as part of this project.

**Comment by bilelmoussaoui** [comment]
Hey, 
The issue about Gnome Shell theme is here https://github.com/numixproject/numix-gtk-theme/issues/389
