### ISSUE TITLE
Using 16px as small-toolbar icons

### ISSUE THREAD

**Issue by andia89** [numixproject/numix-gtk-theme#675]
Gtk-2.0 programs like inkscape, are using the arguably wrong icon size for the `small-toolbar` icons (something smaller than 16px which is the smalles size for (all) icon themes). 

Adding 
`gtk-icon-sizes = "inkscape-decoration=16,16:gtk-small-toolbar=16,16"`

to the `gtkrc` file in `gtk-2.0` solves this issue. Is this a "good" way to fix this issue? (I have close to no experience in gtk theming)

**Comment by khurshid-alam** [comment]
Yes. But what if user has his own gtkrc file in ~/.gtkrc ?

**Comment by bilelmoussaoui** [comment]
as soon as this property is not overwritten ln the local gtkrc it should work as expected. We can try that to be sure of that

**Comment by khurshid-alam** [comment]
Can you which icons are problematic?  This is my inkscape:  https://i.imgur.com/bQW1ncJ.png and I don't find any irregularities.

**Comment by bilelmoussaoui** [comment]
you have to test with wa4557's branch on Numix icon theme which contains a lot of icons for an Inkscape theme

**Comment by andia89** [comment]
The top icons. In your screenshot you should see at for example the rotate icon, when using numix (third from left). It is blurry because a 16px icon is scaled up to a 18px icon.

You can of course overwrite this in a local gtkrc file

**Comment by khurshid-alam** [comment]
Ok. Fixed.
