### ISSUE TITLE
Resize borders are to small

### ISSUE THREAD

**Issue by Limator** [numixproject/numix-gtk-theme#676]
hi,

the area/border of each window where it could be resized is to small. At the moment I have to match the exact pixel to catch the resize-function ^^
pressing alt + rightklick + drag&drop is a good alternative, but not everybody knows this!

Could you higher the size of the resizing-area or could you tell me how to higher this size?

Thank you!

**Comment by khurshid-alam** [comment]
Window manager problem. See #100

**Comment by Limator** [comment]
Hi @khurshid-alam 
That is not correct! I've taken a look on other themes and other themes have bigger resizing areas. I've done a little google-search and found out that the size of the resizing-area depends on the theme. Someone told me to use a theme with a resizing-area that fits my needs ;) but that's not the right way I think ^^

**Comment by Limator** [comment]
@satya164 wrote: "Numix can compromise and increase the grip area"
Would this be possible for you to do this? Maybe with some funds for this?

**Comment by khurshid-alam** [comment]
Resize grip was removed from GTK. See https://mail.gnome.org/archives/commits-list/2014-July/msg00351.html

Now Window manger gives a invisible border which can be used as resize grip. We use 15px. 

> Client-side decorated windows when running under a compositor have 5
> pixels around the border that can be used as a resize area. If there
> is no compositor running, the border is automatically increased from
> 1px to, I think, 3px

If windows manger doesn't provide that invisible border we cann't control it. If we introduce our window border, it will cause other issues like black boder around the window.

**Comment by khurshid-alam** [comment]
Resize grip was removed from GTK. See https://mail.gnome.org/archives/commits-list/2014-July/msg00351.html

Now Window manger gives a invisible border which can be used as resize grip. We use 15px. 

> Client-side decorated windows when running under a compositor have 5
> pixels around the border that can be used as a resize area. If there
> is no compositor running, the border is automatically increased from
> 1px to, I think, 3px

If windows manger doesn't provide that invisible border we cann't control it. If we introduce our window border, it will cause other issues like black boder around the window.

@Limator What is your window-manager by the way?

**Comment by Limator** [comment]
Hi @khurshid-alam 
I'm using Xfce (Xubuntu 16.04)
