### ISSUE TITLE
xfce4-notifyd shows only themes that have css file 

### ISSUE THREAD

**Issue by sjb0x49** [numixproject/numix-gtk-theme#677]
Xfce4-notifyd no longer checks for gtkrc files for themes, it now accepts only gtk.css. The change was committed a while ago:
[https://git.xfce.org/apps/xfce4-notifyd/commit/?id=a75d021670d31388623c30e6e8f63da70d6c82af](url)
Not a huge deal, but it would be nice for notifications to match the theme.
Thank you all so much for your work, I love the numix themes.

**Comment by khurshid-alam** [comment]
The link is giving me "Page not found". 

And as of now, we do not have proper support Xfce4-notifyd (gtk3). But it is on my radar.

**Comment by sjb0x49** [comment]
https://git.xfce.org/apps/xfce4-notifyd/commit/?id=a75d021670d31388623c30e6e8f63da70d6c82af
Sorry about that, the editor changed the url for the link, for some reason. (you can see while hovering the first link) I probably did something wrong. Anyway this should show the commit. Thank you

**Comment by ragazenta** [comment]
After looking commit histories and old pull requests, I notice that `xfce-notify-4.0/gtk.css` had already been added (#512) but then removed (https://github.com/numixproject/numix-gtk-theme/commit/30b14f77d05389d80b395720e6603836a579edd4), it was moved into scss.

Should it be restored? But I also notice some styles are different: background-color, border-color, etc.

Xfce4-notifyd (gtk3) use `xfce-notify-4.0/gtk.css` to override styles on main `gtk.css` theme and it will appear in Configuration, CMIIW. I think the Default option in Configuration has already matched the theme.

**Comment by khurshid-alam** [comment]
Feel free to open a PR.

**Comment by fish47** [comment]
`xfce-notify-4.0/gtkrc` is still there, and not renamed to `xfce-notify-4.0/gtkrc.css`, according to the debian build.
https://packages.debian.org/sid/all/numix-gtk-theme/download
