### ISSUE TITLE
Gedit, Pluma and xed using classic and tango color schemes when 'Highlight current line' is enabled.

### ISSUE THREAD

**Issue by darkshram** [numixproject/numix-gtk-theme#678]
When Gedit, Pluma 1.18 (gtk3) and Xed use the default color scheme (tango) or classic one and the editor has enabled **Highlight current line**, foreground and background of the the current line are completely white. Also the colors from the color schemes over the Numix dark background make it to very uncomfortable to work. My environment uses Gtk 3.18. Had to downgrade Pluma to 1.16 (gtk2) because all the gtk3 editors have the same issue while using Numix.

Xed with Numix.
![xed-numix](https://user-images.githubusercontent.com/10327500/27774527-659ff0a4-5f59-11e7-9a33-34b58daf1540.png)

Does not happen with other dark themes, such as Ambiance, BlackMATE, etc. or editors using Gtk2 such as Pluma 1.16.

Pluma 1.16 (gtk2) with Numix.
![pluma-gtk2-numix](https://user-images.githubusercontent.com/10327500/27774530-65a2908e-5f59-11e7-99f0-86a2bce1465b.png)

Xed with Ambiance.
![xed-ambiance](https://user-images.githubusercontent.com/10327500/27774529-65a1b7e0-5f59-11e7-8e01-d0ca7a245b43.png)

Xed with BlackMATE.
![xed-blackmate](https://user-images.githubusercontent.com/10327500/27774528-65a028d0-5f59-11e7-8445-226c49706f1c.png)

**Comment by khurshid-alam** [comment]
That's not a Numix theme issue.You are using wrong themes (classic & tango). Those are not for dark themes. It is same for all other themes which uses dark background for textview.

The highlight-color is `current-line`  in GtkSourceView styles of the gedit themes. You can find them in `/usr/share/gtksourceview-3.0/styles`. Try modifying the highlight-color in the theme.
