### ISSUE TITLE
It is not displayed correctly in the start menu of the latest system,Linux Mint 18.2

### ISSUE THREAD

**Issue by 0x7a7a** [numixproject/numix-gtk-theme#679]
Hi,Alam
Today I upgraded my linux mint(mate) system from 18.1 to 18.2,Numix theme is not displayed correctly on the menu bar.
This is some screenshots
![](http://ww1.sinaimg.cn/large/c704dca4gy1fhdqpskpbgj201c06w3yc.jpg)
![](http://ww1.sinaimg.cn/large/c704dca4gy1fhdqpyzswdj20170ch3yg.jpg)  
A piece of white black.
This is my configuration information
![](http://ww1.sinaimg.cn/large/c704dca4gy1fhdqrpts2nj209n0dhq3k.jpg)
![](http://ww1.sinaimg.cn/large/c704dca4gy1fhdqrusa6lj209g0d8t94.jpg)
If I use the system's own theme, there will be no problem

**Comment by khurshid-alam** [comment]
Please mention theme version. And the issue is probably due to shift from gtk2-gtk3 panel. It was fixed in master.

**Comment by 0x7a7a** [comment]
I am using apt-get install installed, how should I check the version information?

**Comment by khurshid-alam** [comment]
Run

`apt-cache policy numix-gtk-theme`

And for mint, use Numix-Daily ppa to get latest. https://launchpad.net/~numix/+archive/ubuntu/numix-daily
