### ISSUE TITLE
Selected text in galculator is white on almost white

### ISSUE THREAD

**Issue by meebey** [numixproject/numix-gtk-theme#68]
Screenshot of this issue:
http://www.meebey.net/temp/numix-gcalc-selection-issue.png

Numix version:
ii  numix-gtk-theme                                             1.9-0-182+201309110137~ubuntu13.10.1    all          Numix GTK Theme

**Comment by meebey** [comment]
Upgraded to latest version, but the issue remains with version:
ii  numix-gtk-theme                        2.0-0-199+201309210909~u all                      Numix GTK Theme

**Comment by me4oslav** [comment]
It seems galculator is some random gtk 2 app and not the official gnome 3 calculator app (gnome-calculator), so this bug doesn't really ... bugs us (HA! :>). Somebody close that issue.

**Comment by meebey** [comment]
Yeah galculator is an 3rd party app (it is GTK3 though!) and not the official GNOME3 one. Haven't noticed I was using the wrong tool :-)

**Comment by satya164** [comment]
@meebey It very much seems like GTK2 to me.

**Comment by meebey** [comment]
No longer matters, I uninstalled it, so I don't start it by accident. I think it came from LXDE btw.

**Comment by satya164** [comment]
@meebey :D
