### ISSUE TITLE
Ubuntu 16.04.2 theme not working

### ISSUE THREAD

**Issue by hungpham2411** [numixproject/numix-gtk-theme#680]
Hi.
I'm using Ubuntu 16.04.2 with gtk 3.18. I downloaded the source code at:
https://github.com/numixproject/numix-gtk-theme/releases/tag/2.6.6
then add to themes folder in my Home folder (because I don't want install it to my system), but there are nothing working at all, all style lost and shows black background and white text.
Must I install by command line instead of add as user's theme?

**Comment by amrmsaraya** [comment]
i think you need to compile the src first and build it as it said in [README.md](https://github.com/numixproject/numix-gtk-theme/blob/master/README.md)

**Comment by khurshid-alam** [comment]
You don't need to compile anything. There are stable & daily build PPAs, please read the readme.
