### ISSUE TITLE
numix-blue-gtk-theme 0.54 :: Gnome Shell 3.22, Ubuntu Gnome 17.04 :: Desktop icon labels' font color dark blurry when desktop not in focus

### ISSUE THREAD

**Issue by SubhamSatyajeet** [numixproject/numix-gtk-theme#681]
numix-blue-gtk-theme:
Icons on the Gnome Desktop need to be enabled for this bug to be reproduced.
![screenshot from 2017-08-10 00-11-25](https://user-images.githubusercontent.com/7932787/29138291-e1312ef2-7d60-11e7-83b8-016ed39c5931.png)
The above image is for when a Nautlius window is opened, with the desktop being in focus.

![screenshot from 2017-08-10 00-11-05](https://user-images.githubusercontent.com/7932787/29138335-057ee114-7d61-11e7-909f-6ab0ccdbcad8.png)
This is what happens when I click on the Nautilus window to bring it into focus. The icon labels on the desktop change to an ugly dark blurry colour.

This does not occur in numix-gtk-theme. It only happens in the blue variant.

**Comment by bilelmoussaoui** [comment]
Numix blue gtk theme is not being designed by Numix team. So it's an invalid issue

**Comment by SubhamSatyajeet** [comment]
But numix-blue-gtk-theme is a part of this theme's PPA content. The numix-blue site also has a bug-report link that redirects to the this repo's page.

**Comment by bilelmoussaoui** [comment]
Which PPA?

**Comment by SubhamSatyajeet** [comment]
I'm sorry. This was my fault. Upon inspecting the package, it was added to the Ubuntu distro directly from the Numix-Blue fork. It is _not_ a part of the Numix PPA.

Closing the issue now.
