### ISSUE TITLE
ubuntu 17.04 without gnome -> theme not working

### ISSUE THREAD

**Issue by changemenemo** [numixproject/numix-gtk-theme#682]
should we do have this result? because I clearly don't have that kind of result in my xfce4 and I have installed numix nightlies with apt. 
[supposed result](https://github.com/mzgnr/solarized-dark-xfce)

**Comment by lots0logs** [comment]
Could you be more specific? Its not clear what the problem is that you are experiencing.

**Comment by changemenemo** [comment]
I am asking if what we are supposed to get is what is shown on the link "supposed result"? Because if it's that then I will show my screenshots to show you thet is totally not what I'm getting.

**Comment by changemenemo** [comment]
jsut to be more precise, besides the places of buttons of window and the button's image who has changes, for me the colors hasn't change at all anywhere.

**Comment by khurshid-alam** [comment]
Numix solarized was abandoned long ago. This repo has nothing to do with that and you can change window buttons with gnome-tweak-tool.

And what is Numix nightlies ?
