### ISSUE TITLE
GTK3: Visual glitches with Lollypop music player

### ISSUE THREAD

**Issue by k-kirill** [numixproject/numix-gtk-theme#683]
There are some visual glitches with Lollypop music player: https://github.com/gnumdk/lollypop
1) The "play" symbol icon in the header has the wrong color, though, the "pause" icon has the correct bright color. The "play" icon is painted correctly also in the fullscreen mode when not in the header.
2) The right border around clip art is missing in Radios view, though, the border is shown in All artist view.
![glitches](https://user-images.githubusercontent.com/8539168/29230504-06075eb8-7eec-11e7-8bc6-0cb65840f4f2.png)

I cannot reproduce these two issues using Adwaita gtk theme.

I reported the issue for Lollypop first, but developers said to raise an issue here for the theme.
https://github.com/gnumdk/lollypop/issues/1214

### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: gtk-3.22.16
- GNU/Linux distribution: openSUSE Tumbleweed 20170729

**Comment by ghost** [comment]
For the second issue, I guess it's a GTK issue... Happen to me sometimes...

**Comment by khurshid-alam** [comment]
@k-kirill Which icon theme do you use?

**Comment by bilelmoussaoui** [comment]
@khurshid-alam it seems to be Numix

**Comment by k-kirill** [comment]
About the first issue, the following selector is used for GtkImage - play_image:
>  *:disabled, *:disabled:disabled {
    color: mix(#ddd,#444,0.5); }

It seems to be a GTK issue as well because the button is sensitive on playing and only image is changed on pressing the enabled "pause" icon and the disabled "play" icon is shown instead.

**Comment by khurshid-alam** [comment]
It doesn't happen with other apps like totem. Beside it is reproducible with other themes.

**Comment by khurshid-alam** [comment]
@k-kirill  About radio album border : for me it doesn't show any album cover for any radio stations. Do you have any specific radio station for which it does ?

**Comment by k-kirill** [comment]
@khurshid-alam 
1) However, Adwaita does not define :disabled for GtkImage, that's why it works fine for it.
2) I use the following cover art for the radio:
![powerstationuk-logo500](https://user-images.githubusercontent.com/8539168/29740095-4e340f12-8a57-11e7-96d5-992ba31a9ec2.png)

**Comment by khurshid-alam** [comment]
@k-kirill 
If it's there, there are some use of it....I will test a bit...If I don't find any regression I will disable it either for lollypop or globally.

**Comment by k-kirill** [comment]
It seems that it makes sense to make the GtkImage sensitive on the sensitive GtkButton. Also, turns out the second issue affects Adwaita as well. So, I added a comment in the original defect:
https://github.com/gnumdk/lollypop/issues/1214#issuecomment-325114263

**Comment by ghost** [comment]
@k-kirill About radio album border, moving the paned view should fix the issue.

**Comment by k-kirill** [comment]
The glitches were fixed in the latest lollypop builds (0.9.300 and greater) in the aforementioned defect, so I reckon we can mark this issue as closed.
