### ISSUE TITLE
Any way to install theme locally?

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#685]
Hi,

I was curious if it's possible to download the numix theme folder from your github page and install it in my home folder in the local directory. I know you can install icon themes that way. I would rather install icon themes and gtk themes without root access, without a ppa, or .deb file. I am using Ubuntu linux and am using the Unity tweak tool to spice up my installation. How can I install it locally and how do I configure the Unity tweak tool to recognize the folders in my home folder? Ubuntu does not have the ~/.local/share/icons or ~/.local/share/icons folders by default, I had to add them myself.

Thanks!

**Comment by khurshid-alam** [comment]
Does this not work for you?

```sh
# Execute from repo root
scss --update --sourcemap=none src/gtk-3.20/scss:src/gtk-3.20/dist
glib-compile-resources --sourcedir=src/gtk-3.20 src/gtk-3.20/gtk.gresource.xml
./scripts/utils.sh install ~/.local/share/themes/Numix/
```
