### ISSUE TITLE
GTK 3.22 :: Darker background in Firefox and Thunderbird with 2.6.7

### ISSUE THREAD

**Issue by klemens** [numixproject/numix-gtk-theme#688]
After updating to version 2.6.7 I noticed that the background colors in Firefox and Thunderbird are much darker then before. A bisect revealed 9e4844a70bc3eaab792c4992176e063570da4f41 as the commit that introduced this change. It is not clear to me from the changelog if this was intentional.

Thunderbird 2.6.6:
![thunderbird-good](https://user-images.githubusercontent.com/813206/31557010-7bbf9742-b047-11e7-8be6-2e4a3de57688.png)
Thunderbird 2.6.7:
![thunderbird-bad](https://user-images.githubusercontent.com/813206/31557020-837062fa-b047-11e7-9a18-549087499d85.png)

Firefox 2.6.6:
![firefox-good](https://user-images.githubusercontent.com/813206/31556979-63d2deaa-b047-11e7-92a4-e8d736727db0.png)
Firefox 2.6.7:
![firefox-bad](https://user-images.githubusercontent.com/813206/31556993-6e093c52-b047-11e7-8ede-a38d08ba99e5.png)

**Comment by khurshid-alam** [comment]
It was intentional.
