### ISSUE TITLE
[Question, Ubuntu 17.10] Custom close,minimize,maximize icons

### ISSUE THREAD

**Issue by robertwhitebit** [numixproject/numix-gtk-theme#689]
Hey!

I was using custom close,min,max icons in Ubuntu 17.04 by replacing some icons in the src/unity folder. See image
![image](https://user-images.githubusercontent.com/11049034/32672903-2e7a9c68-c64d-11e7-9455-d247e601d5f5.png)

After upgrading to Ubuntu 17.10, these icons are not shown anymore :crying_cat_face: The default white Numix icons are shown. When hovering over an icon, the color changes to red.

Since Gnome utilizes the window bar differently, and these icons differ in size depending on the program (e.g. the Terminal uses small icons whereas GEdit or Files uses big ones) I won't be able to use my icons anymore :disappointed: However, it would be great to at least colorize the numix icons.

* red = close
* yellow = min
* green = un/max.

I'm not able to find the right files or code lines. Maybe someone can help me out here? :relaxed:

**Comment by khurshid-alam** [comment]
Ubuntu 17.10 uses gnome-shell. So you have to compile the theme with your custom icons.

**Comment by robertpainsi** [comment]
ah, thank you very much! :bow:
