### ISSUE TITLE
No window border style in MATE

### ISSUE THREAD

**Issue by aurecchia** [numixproject/numix-gtk-theme#69]
Hey,

Just wanted to point out that on MATE the window theme is not recognized by default.

The solution is simply to copy the _Numix/metacity-1/metacity-theme-2.xml_ to _Numix/metacity-1/metacity-theme-1.xml_.

After that the theme works without problems!

**Comment by satya164** [comment]
Hmm.. I think you should report a bug to MATE. The metacity format 2 should be recognized by MATE. I cannot just change the name since it uses features of Metacity 2, such as custom roundness for corners and constants.
