### ISSUE TITLE
Numix theme as shipped with Xubuntu 16.04 shows white text on some white buttons

### ISSUE THREAD

**Issue by clickworkorange** [numixproject/numix-gtk-theme#691]
The buttons in meeting requests in Evolution mail are unreadable: 

![screenshot_2017-11-29_15-23-10](https://user-images.githubusercontent.com/196348/33383059-3fa836ae-d51a-11e7-99bd-dfbca7c55ef8.png)

**Comment by khurshid-alam** [comment]
Which version is that? Please use the theme from PPA.
