### ISSUE TITLE
How to install  in OpenBox?

### ISSUE THREAD

**Issue by gayanW** [numixproject/numix-gtk-theme#692]
I see no instructions in the README.

**Comment by khurshid-alam** [comment]
Which distro?

**Comment by gayanW** [comment]
Debian

**Comment by gayanW** [comment]
Anyone? :)

**Comment by bilelmoussaoui** [comment]
https://github.com/numixproject/numix-gtk-theme#install-it

**Comment by gayanW** [comment]
I reinstall the `numix-gtk-theme` package, and now it shows up in Openbox configuration manager. Thanks.
