### ISSUE TITLE
Theme doesn't apper flat

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#695]
I have been using numix theme for few years. I recently installed numix-gtk-theme on archlinux and the theme has windows 2000 like box appearence instead of regular flat numix.
![numix_theme](https://user-images.githubusercontent.com/15420642/35075368-c9f6cd9e-fc1a-11e7-9985-79a1d63086b3.png)

**Comment by khurshid-alam** [comment]
For gtk2 styles you also need murrine theme engines.

**Comment by ghost** [comment]
@khurshid-alam Thank you so much, my issue is solved now.

Many thanks to numix community for beautiful themes and icons.
