### ISSUE TITLE
Ubuntu 17.10 filebar does not update to numix color theme

### ISSUE THREAD

**Issue by cosmicvarion** [numixproject/numix-gtk-theme#696]
When you drag a window to the filebar in Ubuntu 17.10 or make a window full screen, it becomes obvious the filebar is still Ambiance gray. The subsequent full screen highlight illustrating how the window will fill the screen after dragging the window to the top is Ambiance orange. The new "Show Applications" screen's icons are Ambiance gray and orange.

**Comment by khurshid-alam** [comment]
I don't understand. A screenshot may be ? This is only gtk theme. You may also need a numix gnome-shell theme.

@CosmicVarion ?
