### ISSUE TITLE
GTK2 - Spinbutton doesn't respect box limits

### ISSUE THREAD

**Issue by Harmaxx** [numixproject/numix-gtk-theme#698]
![numix1](https://user-images.githubusercontent.com/36097184/36201376-f3d9206a-1166-11e8-824b-27b81a67cb3a.png)

![numix2](https://user-images.githubusercontent.com/36097184/36201600-a293d92e-1167-11e8-91b8-f8cbb307800a.png)

It only happens with Numix, so I guess it's a bug in this theme.

Numix latest git
GTK+ 2.24.31
Murrine Engine 0.98

**Comment by khurshid-alam** [comment]
Which app are those? It seems some issue with murrine/gtk2. But I can't reproduce it.

@Harmaxx ?

**Comment by Harmaxx** [comment]
GIMP and Xsane, but all GTK2 apps with spin buttons show the same behaviour:

![murrine-numix](https://user-images.githubusercontent.com/36097184/36350003-42ad274a-146e-11e8-96ba-80693d7361e8.png)
These are Audacious, Gpicview and Volti.

I recompiled Cairo (I'm using the latest stable release, 1.14.12) without OpenGL support to avoid a possible issue with the gl backend and/or with Mesa, nothing changed. I tried a bunch of other themes and those that use Murrine show a similar issue:

![murrine-numix2](https://user-images.githubusercontent.com/36097184/36350016-8eed5846-146e-11e8-9071-0ddfc11b95fd.png)
This is not the expected behaviour, is it? Am I missing a dependency?

**Comment by khurshid-alam** [comment]
Not sure about dependency. Which distro? 

Here is Gimp from Ubuntu bionic
![numix-bug-698](https://user-images.githubusercontent.com/1333217/36695647-ef8ec78e-1b67-11e8-93ca-f8e38c9055d0.png)

**Comment by Harmaxx** [comment]
Those boxes with a level bar look ok here too. Try the text tool or the crop tool that use simpler boxes.

I'm using Gentoo.

**Comment by Harmaxx** [comment]
I spent some time on this and figured out that it has nothing to do with the GTK2 theme, it's something with Murrine and the XSETTINGS protocol.

Thank you for your time. Closed.
