### ISSUE TITLE
How can I change the active window title bar?

### ISSUE THREAD

**Issue by AHeinlein** [numixproject/numix-gtk-theme#699]
Hello,
I'd like to change the title bar of the active window to something more distinguishable, e.g. a colored background. What is the easiest way to do that?
I'd like to do the change in the source .scss files, not in the resulting .css. I guess the change goes somewhere in the _toolbar.scss, but I have little knowledge of scss.
I also read that there are differences between gtk-3.0 and gtk-3.20, is it possible to do the change for both?
Thanks a lot!

**Comment by khurshid-alam** [comment]
This is little complicated. titlebar color (bg/fg) is defined here : https://github.com/numixproject/numix-gtk-theme/blob/master/src/gtk-3.20/scss/_global.scss#L64

Active titlebar is defined here: https://github.com/numixproject/numix-gtk-theme/blob/master/src/gtk-3.20/scss/widgets/_toolbar.scss#L164

Inactive would be the backdrop section: https://github.com/numixproject/numix-gtk-theme/blob/master/src/gtk-3.20/scss/widgets/_toolbar.scss#L172

But ultimately it depends on the window manger as well.  Unity paints it's own color in` _unity..scss`. And same for metacity. And then there is `headerbar `, `titlebar(:not:headerbar) `cases. You need to use trial and error to find most suitable color for you.
