### ISSUE TITLE
Terminal doesn't need scrollbars when there isn't enough text in it to scroll through

### ISSUE THREAD

**Issue by me4oslav** [numixproject/numix-gtk-theme#7]
I do realise the scrollbars are sexy and everything, but really if possible we don't need them in gnome-terminal when there isn't enough text in the terminal window to scroll through.
![Screenshot from 2013-03-03 23:04:02](https://f.cloud.github.com/assets/1658870/214761/4ce2ccdc-8446-11e2-9ff4-bc4eef4f6ccb.png)

**Comment by satya164** [comment]
We cannot control when an app shows the scrollbar :(

**Comment by me4oslav** [comment]
Damn :(

**Comment by cldx** [comment]
Now you could bug gnome-terminal https://bugzilla.gnome.org/buglist.cgi?query_format=specific&order=relevance+desc&bug_status=__all__&product=gnome-terminal&content=scroll

but not sure if that's worth it :)

Also: https://bugzilla.gnome.org/show_bug.cgi?id=397062 Awesome Bug ain't it ;)
