### ISSUE TITLE
Ubuntu 17.10: Top bar is not themed correctly

### ISSUE THREAD

**Issue by jpaszek** [numixproject/numix-gtk-theme#700]
I just installed the numix theme on Ubuntu 17.10. There I noticed that the top bar theme has not changed and does not fit in the numix theme. Here is a picture of my desktop:

![screenshot from 2018-02-25 23-29-02](https://user-images.githubusercontent.com/18198067/36647302-d13a5b48-1a83-11e8-8b36-95006af2225b.png)

**Comment by khurshid-alam** [comment]
17.10 uses gnome-shell. Numix doesn't have a shell-theme atm. See #389
