### ISSUE TITLE
Scrollbars in Firefox barely visible

### ISSUE THREAD

**Issue by nioncode** [numixproject/numix-gtk-theme#701]
Is this how it's supposed to look like? I can barely see the 'progress' of the scroll bar in Firefox.
On scroll, the scrollbar also does not pop up like it does in other applications (like spacefm).

![2018-03-14-235436_1920x1080_scrot](https://user-images.githubusercontent.com/3159451/37435409-79be0f3c-27e3-11e8-8242-fead941f8fbb.png)

**Comment by khurshid-alam** [comment]
Please give Numix version, distro and other information.

**Comment by nioncode** [comment]
Sorry, I just found out that numixproject is not responsible for the numix-sx theme. Sorry for the noise.
