### ISSUE TITLE
Question: How to enable this theme for gtk3 applications?

### ISSUE THREAD

**Issue by holms** [numixproject/numix-gtk-theme#703]
I'm using DWM originally, but also I'm using `meld` application a lot which is using GTK+3, and I'd like to apply numix theme there. For gtk2 there's `gtk-chtheme` tool which is pretty good. Just installing this theme doesn't change default gtk3 theme.

Would be grateful for your help

**Comment by khurshid-alam** [comment]
We don't support dwm. Where is the doc for dwm theme?

**Comment by Harmaxx** [comment]
DWM, like any other WM, doesn't set the GTK+3 theme. You can do this manually editing the "gtk-theme-name" string in "~/.config/gtk-3.0/settings.ini".

**Comment by holms** [comment]
@khurshid-alam you don't need to support any WM out there, GTK+3 works on all WM's.
