### ISSUE TITLE
Blue version request

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [numixproject/numix-gtk-theme#705]
I am not a fan of the use of the #F0544C color, I think that #215D9C looks better
I adjusted this in the gtk-2.0/gtkrc file, but editing image files is not my thing, i assume the asset images are generated via script can someone please help my regenerate the files with the color change (assuming the maintainer does not want to add a blue version)

XFCE has so few theme choices now, but  i think this is the closet to what i want (since albatross is no longer maintained)

**Comment by GM-Script-Writer-62850** [comment]
I tried modifying all_assets.svg with inkscape and used the bucket tool and turned the red/orange images blueish but when i ran render-assets.sh the files are still red/orange...
[all-assets.svg.zip](https://github.com/numixproject/numix-gtk-theme/files/1910665/all-assets.svg.zip)

**Comment by GM-Script-Writer-62850** [comment]
just found out svg images are also text file, i got it now
If you are interested in maintaining it i can make a patch file
so far the only quirk i found is the blue marker in the calculator's menu is a little too dark relative to the background
![screenshot_2018-04-14_20-54-45](https://user-images.githubusercontent.com/564653/38773889-19deadd2-4026-11e8-8df9-5c25b1a71fce.png)
and yes i made my borders 3px thick

**Comment by khurshid-alam** [comment]
We don't use blue. But you can change the code and compile it yourself. For assets you have to edit it yourself.
