### ISSUE TITLE
Checked / Unchecked and Gtk Radio Menu should use unique symbol rather than different shade

### ISSUE THREAD

**Issue by slacka** [numixproject/numix-gtk-theme#707]
Steps to reproduce:
1. Launch gtk3-demo
2. open "Model Button" -> Flavors

Expected Results:
Empty checkbox or checked checkbox

Actual Results:
All have the same check mark symbol with the same grayscale intensity. Only if you look closely can you see that one is blue the other is gray. 

The "Menu" app also use the same symbol with only subtle shading differences. This makes gtk3 apps such as LibreOffice hard to use. 

For example this is how menus look in Fedora 27 when zoomed 2x:
https://bug-attachments.documentfoundation.org/attachment.cgi?id=140926

This is how Menus look in Antergos when zoomed 2x:
https://bug-attachments.documentfoundation.org/attachment.cgi?id=140925

Note how different symbols are used in Fedora's Adwaita theme.  By using the same symbols with the same shading, it makes UI's hard to read for normal people and impossible to use for color blind people.

**Comment by khurshid-alam** [comment]
Our assets are designed in that way. Since in Numix, menus and popovers are all dark, it is actually very noticeable.

![numix-gtk-theme-issue-707](https://user-images.githubusercontent.com/1333217/38943355-cff0aed8-434e-11e8-9cb5-2255c41f9794.png)

Antergos uses slighty different color than Numix.
