### ISSUE TITLE
Whisker Menu 2.1.6 brakes Arc-Dark-Solid theme

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#708]
I'm running Antergos, latest maintenance level.

While my whisker should look like this
![wo](https://user-images.githubusercontent.com/20510026/38879391-825ca230-4263-11e8-919d-dc523727251d.png)

it looks like this with Whisker Menu 2.1.6:
![wn](https://user-images.githubusercontent.com/20510026/38879485-c046ddfe-4263-11e8-8ab5-c1ec3d93f6d2.png)

Setting `gtk-application-prefer-dark-theme = true` in `~/.config/gtk-3.0/settings.ini` results in this:
![wn1](https://user-images.githubusercontent.com/20510026/38884331-9bbaf0c2-426f-11e8-858c-bf94e55ba86a.png)

Reverting to Whisker Menu 1.7.5 brings the old look back.

The used versions are: numix-gtk-theme 2.6.7 and numix-icon-theme-square 1:18.02.16.

**Comment by c0d3z3r0** [comment]
Same for me

**Comment by khurshid-alam** [comment]
See #666
