### ISSUE TITLE
Numix Dark - Nautilus & Nemo window is blank

### ISSUE THREAD

**Issue by cunoastere** [numixproject/numix-gtk-theme#71]
Hi Satya,

As discussed, here it is.

Nautilus window is blank when Numix Dark is selected as the GTK theme.
Same effect for Nemo 2.0 in Cinnamon 2.0.

Numix Dark - Gnome 3 Shell - GTK 3.10 & Cinnamon 2.0
Antergos ARCH based Linux OS

See the attached images.

![nautilus-numix-dark-gnome3](https://f.cloud.github.com/assets/5781423/1413605/65865302-3e41-11e3-98dc-061cdd24a5f3.png)
![nemo-numix-dark-cinnamon2](https://f.cloud.github.com/assets/5781423/1413606/6c3febc2-3e41-11e3-9383-a215dfa84644.png)
![numix-dark-gnome-tweak-gnome3](https://f.cloud.github.com/assets/5781423/1413609/725fcc48-3e41-11e3-99a8-dbe1be2cd9e3.png)

Cheers,

Razvan

**Comment by satya164** [comment]
Hmm... Nautilus and Nemo are working fine here. Are you sure it's not a problem specific to your setup? May be try creating a new user and test if the issues exist.

Here are nautilus and nemo in my system (Fedora 20, Cinnamon)

![screenshot from 2013-10-26 19 12 20](https://f.cloud.github.com/assets/1174278/1413646/d3105f46-3e44-11e3-9780-9909ecca82dd.png)
![screenshot from 2013-10-26 19 13 17](https://f.cloud.github.com/assets/1174278/1413647/d318e508-3e44-11e3-8305-bf220644516a.png)

**Comment by cunoastere** [comment]
Where did you have the theme installed?

I am using /usr/share/themes

I will try creating another user to see if this is happening again.

I also took a look at the theme folder permissions and everything is ok.

It maybe also an ARCH thing in the end with GTK 3.10; I can see that I have
installed Gnome Shell 3.10.1

**Comment by satya164** [comment]
I have it in ~/.local/share/themes with a symlink at ~/.themes

Do you have the same problem in Gnome Shell? Do you know any other person who has the same problem? Also try creating another user.

**Comment by satya164** [comment]
After all, Cinnamon doesn't work well with the new Gnome.

**Comment by cunoastere** [comment]
So - by installing the theme also in the home/user/.themes folder, I managed to have nautilus displayed properly but without a shadow :)
All the other applications look ok and have shadows..

I think we can close this one because it is just a weird bug coming from Gnome Shell & GTK 3.10.1

**Comment by cunoastere** [comment]
Cinnamon 2.0 is independent of Gnome 3.10 this was the major improvement of this release; so you can run Cinnamon 2.0 with Gtk 3.4, 3.6. 3.8, 3.10 and beyond :dancer:

**Comment by satya164** [comment]
@razvanenescu Thanks.

**Comment by satya164** [comment]
@razvanenescu Well, the Shell is independent. But the apps still use GTK.
