### ISSUE TITLE
Provide a dark variant officially

### ISSUE THREAD

**Issue by bianjp** [numixproject/numix-gtk-theme#710]
__Environment__: Arch Linux + Gnome 3.28
__Problem__: Gnome Tweaks has removed the `Global Dark Theme` switch since 3.25.91.  See more on https://jeremy.bicha.net/2017/08/29/gnome-tweaks-3-25-91/

There are two solutions that work for the moment:
1. Modify Gtk configuration file manually. Add the following lines to `~/.config/gtk-3.0/settings.ini`
   ```
   [Settings]
   gtk-application-prefer-dark-theme=1
   ```
   Not sure when will Gnome remove support for `Global Dark Theme` completely.
2. Use an unofficial dark version for Numix. For example, https://aur.archlinux.org/packages/numix-themes-darkblue/

It would be better if Numix officially provides a dark variant.

**Comment by Foggalong** [comment]
We did used to have a dark variant, will deal with this as part of #618 :)
