### ISSUE TITLE
Ubuntu 18.04 with xfce4 session: Numix theme is not applied to window borders

### ISSUE THREAD

**Issue by chudur-budur** [numixproject/numix-gtk-theme#711]
I have installed and applied numix-icon-theme and numix-gtk-theme on my Ubuntu 18.04 (xfce4 session, not Xubuntu). Everything works except the window borders do not change. How do I fix it?

![screenshot from 2018-05-30 00-28-43](https://user-images.githubusercontent.com/1117795/40699260-5a2b0d2e-63a1-11e8-8826-d2a15f965d6d.png)

**Comment by h3ct0r** [comment]
I'm having the same problem on a fresh install of Xubuntu 18.04 using the PPA: 
```
sudo add-apt-repository ppa:numix/ppa

sudo apt-get install numix-gtk-theme numix-icon-theme numix-icon-theme-circle
```
![screenshot_2018-06-11_13-24-58](https://user-images.githubusercontent.com/2656938/41244326-1a013d7a-6d7b-11e8-9dcf-455d0340813c.png)

**Comment by khurshid-alam** [comment]
Go to `xfce-settings-editor -> window-management` and choose Numix from the style tab.

![screenshot_2018-06-19_02-31-37](https://user-images.githubusercontent.com/1333217/41562137-6167809a-7369-11e8-96fd-25ac12141025.png)

**Comment by LUSUDEV** [comment]
excelente tema,
