### ISSUE TITLE
Install It: Distro Packages: Gentoo

### ISSUE THREAD

**Issue by hartwork** [numixproject/numix-gtk-theme#715]
Hi!

Just a quick note that numix can be installed out of the box on Gentoo by now:
```
sudo emerge -av x11-themes/numix-gtk-theme
```
If you want to use a Gentoo logo next to it, please check https://www.gentoo.org/inside-gentoo/artwork/gentoo-logo.html .

Best, Sebastian

**Comment by khurshid-alam** [comment]
I will add it to readme.
