### ISSUE TITLE
Missing window borders in Gnome 3.28

### ISSUE THREAD

**Issue by ThatLarsGuy** [numixproject/numix-gtk-theme#716]
I've noticed since upgrading to Ubuntu 18.04 that the 1px dark grey window borders appear to be missing.

This didn't seem to be the case in older versions of Ubuntu Gnome, and nor is it the case under XFCE on Ubuntu 18.04.

I've attached some screenshots so illustrate what I mean:
![window_bottoms](https://user-images.githubusercontent.com/5151207/43665588-0c513e24-97b4-11e8-8fa3-66583865de2e.png)
![window_headers](https://user-images.githubusercontent.com/5151207/43665590-0c90d052-97b4-11e8-9c0f-088806a87a05.png)

It doesn't affect usability - just Numix doesn't look as great - overlapping terminal windows can also seem to merge into one as there's no visible window boundary.

This issue seems to affect both the numix-gtk-theme package, but also when I check out from source.

**Comment by khurshid-alam** [comment]
XFCE has it's window manager. In gnome it was always like that for csd windows. Giving 1px border to headerbar (csd !ssd) windows creates all sorts of ugly effect.
