### ISSUE TITLE
Ugly fonts/colors after switching to Xubuntu 18.04

### ISSUE THREAD

**Issue by tawmoto** [numixproject/numix-gtk-theme#718]
I just updated from Xubuntu 16.04 to 18.04 and it seems that some items look a bit ugly now.

1.The panel font color "white" is not "white" anymore, is some kind of "grey".
2.The "System load monitor" has a white background, instead of black one, like in 16.04, now it looks really horrible.
3.The "start menu" was dark, now it's a light grey.
4.The text for a a selected tab is red, instead of old normal black.

![selection_033](https://user-images.githubusercontent.com/35702340/45149494-5c06d400-b1d2-11e8-8876-9811a14e0242.png)
![selection_032](https://user-images.githubusercontent.com/35702340/45149490-590be380-b1d2-11e8-964a-517ad6e1fc0c.png)

![selection_036](https://user-images.githubusercontent.com/35702340/45149498-5e692e00-b1d2-11e8-8e14-a3959f0a8fe9.png)
![selection_037](https://user-images.githubusercontent.com/35702340/45149501-5f9a5b00-b1d2-11e8-8cd1-741282955a9b.png)
![selection_038](https://user-images.githubusercontent.com/35702340/45149722-e8b19200-b1d2-11e8-9264-4404310c5438.png)

Thanks

**Comment by Foggalong** [comment]
I'm a Xubuntu user myself and haven't experienced any of these issues. Which version of the theme are you using? (preinstalled, PPA, or git).

On 2, does this same issue appear for any other GTK themes? Does it not happen for any GTK themes? Will help isolate the issue.

**Comment by tawmoto** [comment]
@Foggalong thanks for the reply, I just installed Xubuntu 18.04.1, I don't know how to get the theme version, sorry..Only the Numix has "problems". Please note that these are not horrible bugs, but it seems that someone mixed some colors. For example the System Load monitor looks really ugly on white background and it's a bit silly, look how nice was in 16.04 ...Also the start menu should be darker...
Numix is a back-blackground theme...

I created 2 small videos to show the problem.
https://drive.google.com/open?id=1NZH5ENK8GtmlMqQAj1UPDXQsJquwxZR4

**Comment by khurshid-alam** [comment]
Update the theme from PPA.

**Comment by tawmoto** [comment]
@khurshid-alam Is there any instructions on how to do this properly? I know i seems stupid but I don't want to break something :-)

**Comment by khurshid-alam** [comment]
```
sudo add-apt-repository ppa:numix/ppa
sudo apt-get update
sudo apt-get install numix-gtk-theme
```

Note, xfce in Ubuntu 18.10 has been ported (90%) to gtk3, there are lots things they broke and they don't give us a application level class to modify it ourselves. I already made several improvements for xfce, I am just waiting for gtk3 port to complete.

**Comment by tawmoto** [comment]
I see, but I was talking about Ubuntu 18.04.
Thanks

**Comment by tawmoto** [comment]
@khurshid-alam I updated like you said, absolutely nothing changed unfortunetaly, the grey start menu is very awkward, Numix being a dark theme.
Thanks for the help, though.

**Comment by tawmoto** [comment]
@khurshid-alam I just also wanted to note that from all the XFCE themes, Numix is the only one that shows the performance monitor with white margins, all the other themes shows it ok, like in 16.04. So I don't think it's a gtk3 problem. Perhaps this info helps.
See attached pics, the first one is Numix, the only one with white margins on the 2 meters. The theme is dark, so it should have dark margins, like the rest of the themes.
Thanks.:)

![image](https://user-images.githubusercontent.com/35702340/51698332-90105380-2012-11e9-8025-bd4495afa10e.png)
![image](https://user-images.githubusercontent.com/35702340/51698357-9acae880-2012-11e9-8fd4-f4a041f60b92.png)
![image](https://user-images.githubusercontent.com/35702340/51698368-a4ece700-2012-11e9-86d9-27a2ea3fe0ce.png)
![image](https://user-images.githubusercontent.com/35702340/51698376-ae764f00-2012-11e9-8103-d35da4fb97e7.png)
