### ISSUE TITLE
Numix Light - Nemo Breadcrumbs

### ISSUE THREAD

**Issue by cunoastere** [numixproject/numix-gtk-theme#72]
Hi Satya,

All the Numix themes are missing a style for the Nemo breadcrumbs.

Attached a screenshot with Nemo 2.0 and Numix Light, latest release, applied.

Same OS - Antergos based on ARCH and GTK 3.10, Cinnamon 2.0

![nemo-breadcrumbs-numix-light](https://f.cloud.github.com/assets/5781423/1413623/04f13d6c-3e42-11e3-845f-c162fb9122e7.png)

![numix-light-cinnamon2](https://f.cloud.github.com/assets/5781423/1413615/c68d547a-3e41-11e3-971b-6ef57425f358.png)

Cheers,

Razvan

**Comment by satya164** [comment]
I'll do them as soon as I have time.

**Comment by satya164** [comment]
Okay... Sorry. I don't get time to fix it. the issue won't be fixed.

**Comment by nimser** [comment]
@satya164 How can we help? Nemo is used on quite a lot of systems.

**Comment by satya164** [comment]
@fuzzytern You can send a pull request if you want. I'll try tonight to theme it though.

**Comment by satya164** [comment]
And feel free to throw some bucks at Numix if you like our work :D

**Comment by me4oslav** [comment]
We have donation form in our website, it is drop dead easy to use - http://numixproject.org/
