### ISSUE TITLE
Issue with the Blue variant with Python

### ISSUE THREAD

**Issue by FlorentLM** [numixproject/numix-gtk-theme#722]
Hi,
When I import the module Mayavi in any Python script, I get a bunch of errors if Numix Blue is my current theme. It does not happen with Numix Daily or any other theme I have.

Here are the example errors:
```
(python:19813): Gtk-WARNING **: 11:44:23.768: Theme parsing error: gtk.css:597:14: not a number
(python:19813): Gtk-WARNING **: 11:44:23.768: Theme parsing error: gtk.css:597:14: Expected a string.
```

Cheers

**Comment by khurshid-alam** [comment]
We don't support Numix-Blue. Please report at the respective issue tracker.
