### ISSUE TITLE
Changing the selected tab text color

### ISSUE THREAD

**Issue by tawmoto** [numixproject/numix-gtk-theme#729]
Hello,

I would like to change the selected tab text color from red to black (or bold black), I saw that this changed in 18.04, in 16.04 it was black. The current red is very intrusive for the eyes and it's present in almost all the Linux applications (meld, terminator, etc) when using Numix theme, it would be great if I could change it.

I attached some pics from different Linux apps.

How can I change it?
Thank you

![image](https://user-images.githubusercontent.com/35702340/50725278-f5ec7800-1103-11e9-9f49-e13ff14d9dbf.png)

![image](https://user-images.githubusercontent.com/35702340/50725289-0c92cf00-1104-11e9-8275-3ebdb4e75689.png)

**Comment by khurshid-alam** [comment]
The bottom border on active is being drawn from `tab.top tab:checked` style from [_notbeook.css](https://github.com/numixproject/numix-gtk-theme/blob/master/src/gtk-3.20/scss/widgets/_notebook.scss#L246). The color is `$selected_bg_color`. And you need to change for all tabs (tab.right, tab.bottom etc). Then compile.

I agree that color is bit eye-catchy for some, may we should revert back to old `selected_bg_color` or at least for the tabs.

**Comment by tawmoto** [comment]
Great, thanks. So is there a chance for an official change in the next versions? The red is a bit disturbing, indeed.

**Comment by khurshid-alam** [comment]
No. It will be red (by design/color-schemes) but darker.

**Comment by tawmoto** [comment]
Dark red is perfect. Thanks.
How should I subscribe in order to get a notification when this change is applied? Then I guess I have to update.
