### ISSUE TITLE
Nautilus background and icons labels change on adding/closing secondary tabs

### ISSUE THREAD

**Issue by SKUndef** [numixproject/numix-gtk-theme#73]
Whenever i open other tabs in Nautilus, the first one gets strange shadow on icon labels. When next i close all tabs leaving only one active, background changes to grey and shadow on icon labels remains.

The first image is in normal condition, the second is with more tabs and label shadow, the third combines grey background with shadow.

![normal](https://f.cloud.github.com/assets/5783302/1414320/9ba6a2ec-3e79-11e3-9dcb-8bccfa7b57ad.png)

![label_shadow](https://f.cloud.github.com/assets/5783302/1414323/cb19cb3a-3e79-11e3-85b3-6cca702fdf87.png)

![grey_bkg](https://f.cloud.github.com/assets/5783302/1414324/cebc48a8-3e79-11e3-9c0c-aa5ee2c14a1f.png)

**Comment by satya164** [comment]
Hi. This is a known issue with nautilus - https://bugzilla.gnome.org/show_bug.cgi?id=697606
Not a bug in Numix. Closing the issue.

**Comment by SKUndef** [comment]
Ah wow, hope they fix soon then, it's quite annoying! Thanks.
