### ISSUE TITLE
ArchLinux package has been removed from repositories

### ISSUE THREAD

**Issue by Ferdi265** [numixproject/numix-gtk-theme#737]
The ArchLinux package for numix has been removed from the repositories, and therefore the installation instructions in the README are wrong.

**Comment by khurshid-alam** [comment]
What !? Why it was removed ?

**Comment by Ferdi265** [comment]
I don't know either, I just noticed it was gone.

**Comment by Ferdi265** [comment]
The Arch Build System community repo still seems to contain the PKGBUILD for numix: [here](https://git.archlinux.org/svntogit/community.git/tree/repos/community-any/PKGBUILD?h=packages/numix-gtk-theme) with the latest stable release from 2017.

This package seems to have [disappeared from packages.archlinux.org](https://www.archlinux.org/packages/?sort=&q=numix&maintainer=&flagged=) and all mirrors currently up to date with it.

The AUR package [numix-gtk-theme-git](https://aur.archlinux.org/packages/numix-gtk-theme-git/) still exists though.

I have also not found any explanation on why this package disappeared from the package list.

**Comment by Ferdi265** [comment]
The AUR package [numix-gtk-theme-git](https://aur.archlinux.org/packages/numix-gtk-theme-git/) still exists though

**Comment by jonathonf** [comment]
I've pushed it back into the AUR: https://aur.archlinux.org/packages/numix-gtk-theme/
