### ISSUE TITLE
libreoffice 4.1+ lateral bar

### ISSUE THREAD

**Issue by rhoconlinux** [numixproject/numix-gtk-theme#74]
Hello, I have this problem on the new lateral bar, implemented in libreoffice versions greater than 4.1.0.
![captura de pantalla de 2013-10-22 18 28 24](https://f.cloud.github.com/assets/4784746/1417700/f8235108-3f98-11e3-973e-0504195372bb.png)

![captura de pantalla de 2013-10-28 07 23 31](https://f.cloud.github.com/assets/4784746/1417710/a93b8302-3f99-11e3-89cd-f69c69a108c9.png)

It seem to be an issue with the border. This is also not quite polished in other themes, including Adwaita. But in this case due to the blacki-ish border you can really notice that that border is not looking good. 

Thanks guys! : )

note: you can activate the bar in tools>options>advanced>check box on the bottom. Then, after restart LO it's in the view menu(Lateral Bar check).﻿

**Comment by fitojb** [comment]
Commit in LibreOffice master, try a daily build: http://cgit.freedesktop.org/libreoffice/core/commit/?id=4357dd89ca50deddd7cec7bfba87627a8515f62c

**Comment by rhoconlinux** [comment]
thanks :)

**Comment by megax** [comment]
@khurshid-alam Duplicate/new: https://github.com/numixproject/numix-gtk-theme/issues/199
