### ISSUE TITLE
Numix theme broken in Debian Buster 10.3 Xfce 4.12 & Xubuntu Xfce 4.14 Desktop

### ISSUE THREAD

**Issue by c1ph3rl1nux** [numixproject/numix-gtk-theme#742]
The Numix theme is not rendering correctly in Debian 10.3 Xfce 4.12 & Xubuntu Xfce 4.14 desktop.The side pane in thunar should be grey.
Any idea how this can be fixed?

![Screenshot from 2020-03-27 17-53-49](https://user-images.githubusercontent.com/62766456/77786689-234d7a80-7056-11ea-9473-095560d55962.png)

**Comment by c1ph3rl1nux** [comment]
Looks like it affects multiple users. See Ubuntu bug report here: [https://bugs.launchpad.net/ubuntu/+source/numix-gtk-theme/+bug/1875822](url)

**Comment by khurshid-alam** [comment]
Is it gtk2 or gtk3 ?

**Comment by khurshid-alam** [comment]
Thunar is gtk3 now and doesn't provide any node to overwrite the sidebar color from theme.

**Comment by c1ph3rl1nux** [comment]
But the the stock themes work just fine, greybird's side pane in thunar is light blue. It's only Numix that's broken. See screenshot below.
![Screenshot_2020-05-15_12-57-46](https://user-images.githubusercontent.com/62766456/82043318-b21c6200-96ab-11ea-90eb-198a0f90405a.png)
![Screenshot_2020-05-15_12-50-57](https://user-images.githubusercontent.com/62766456/82043192-71244d80-96ab-11ea-86c3-88ae79908ac3.png)

**Comment by darkshram** [comment]
@khurshid-alam I have examined different themes with the correct sidebar colors with styles for `scrolledwindow.sidebar`, `treeview.view` and `scrolledwindow.shortcuts-pane`. This is an example of how this issue _could_ be solved:

```
.thunar {

//
// Here goes miscellaneous unneeded(?) code for the rest of thunar layout:
//
// toolbar.horizontal button image { ... }
// scrolledwindow.standard-view { ... }
// toolbar { ... }
//

  scrolledwindow.sidebar treeview.view {
    background: $dark_sidebar_bg;
    color: $dark_sidebar_fg;
    
    &:selected, &:active {
      background: $selected_bg_color;
      color: $selected_fg_color;
    }
  }

  scrolledwindow.shortcuts-pane {
    border-top-width: 0;
  }
}
```
Just needs to replace $dark_sidebar_bg, $dark_sidebar_fg, $selected_bg_color and $selected_fg_color with the right values for Numix from _colors.scss and then add it to src/gtk-3.*/scss/apps/_xfce.scss.

$selected_bg_color --> $theme_selected_bg_color (?)
$selected_fg_color --> $theme_selected_fg_color (?)
$dark_sidebar_bg --> $bg_color (?)
$dark_sidebar_fg --> $fg_color (?)

**Comment by khurshid-alam** [comment]
Thanks. Can you open a pull requests ?

**Comment by darkshram** [comment]
@khurshid-alam I'm going to test it first. Please, I need to know which values to use instead of  $dark_sidebar_bg, $dark_sidebar_fg, $selected_bg_color and $selected_fg_color. Are the ones I tried to guess at the end of my post the right ones?

$selected_bg_color --> $theme_selected_bg_color (?)
$selected_fg_color --> $theme_selected_fg_color (?)
$dark_sidebar_bg --> $bg_color (?)
$dark_sidebar_fg --> $fg_color (?)

**Comment by darkshram** [comment]
@khurshid-alam
I have tested it. Seems to work, at least with gtk+-3.24.28. Seems fixed. I think this needs testing with gtk+-3.22/3.20 versions. Hope @c1ph3rl1nux may help testing.

![Captura de pantalla_2021-04-02_08-02-01](https://user-images.githubusercontent.com/10327500/113422342-c29ffe80-9389-11eb-936e-745987bc257c.png)

![Captura de pantalla_2021-04-02_07-22-33](https://user-images.githubusercontent.com/10327500/113419230-448d2900-9384-11eb-8d75-d08fec35a0c0.png)


So far, just created new file as `src/gtk-3.20/scss/apps/_thunar.scss` with this content:

```
@include exports("thunar") {
.thunar {
  scrolledwindow.sidebar treeview.view {
    background: $bg_color;
    color: $fg_color;
    
    &:selected, &:active {
      background: $selected_bg_color;
      color: $selected_fg_color;
    }
  }

  scrolledwindow.shortcuts-pane {
    border-top-width: 1;
  }
 }
}
```
And then added the following to `src/gtk-3.20/scss/_widgets.scss`, just before the line with `@import "apps/xfce";`:

`@import "apps/thunar";`

Repeated the same for gtk-3.0 folder and then executed `make && make install`.

Here is the preliminary patch:
[numix-gtk-theme-2.6.7-fix-thunar.tar.gz](https://github.com/numixproject/numix-gtk-theme/files/6249820/numix-gtk-theme-2.6.7-fix-thunar.tar.gz)

Will test more and see if something else is needed and **then will do a pull request**.

**Comment by c1ph3rl1nux** [comment]
@darkshram 
Thanks for the fix. Works like a charm!
