### ISSUE TITLE
Laptop Variant

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#746]
Could you make a laptop variant? UI elements are too big on a 1366x768p screen.
Thanks!

**Comment by Foggalong** [comment]
That sounds like a bug more than anything; I'm comfortably using Numix on three different laptops and HiDPIness. What's your setup? (Distro, screen, etc)

**Comment by Foggalong** [comment]
Also screenshots! 😅

**Comment by Foggalong** [comment]
Closed as missing information
