### ISSUE TITLE
2.6.7 is not tagged in master branch

### ISSUE THREAD

**Issue by jonathonf** [numixproject/numix-gtk-theme#747]
2.6.7 is tagged in the [latest-release](https://github.com/numixproject/numix-gtk-theme/tree/latest-release) branch but not in the [master](https://github.com/numixproject/numix-gtk-theme/tree/master) branch.

Please tag 2.6.7 in the master branch too.

**Comment by khurshid-alam** [comment]
We use that tag to pull from from latest release on our launchpad ppa (stable)build. Not sure if it will still pull if we stagging master branch as well. There is also an unstable ppa which pulls from master.
