### ISSUE TITLE
Numix Lightdm theme broken on Debian Buster 10.3 Xfce 4.12 & Xubuntu Xfce 4.14

### ISSUE THREAD

**Issue by c1ph3rl1nux** [numixproject/numix-gtk-theme#752]
The Numix Lightdm theme is not rendering correctly on Debian 10.3 Xfce 4.12 & Xubuntu Xfce 4.14 desktop.The login window should be dark and not white. Any idea how this can be fixed? See screenshot:
![screenshot](https://user-images.githubusercontent.com/62766456/119352598-2f58ba80-bca2-11eb-8d59-51362c80f6fc.jpg)

**Comment by khurshid-alam** [comment]
Please use the updated version from PPA.

**Comment by c1ph3rl1nux** [comment]
@khurshid-alam 
I'm sorry but I am a bit confused now. Isn't the GitHub source version the same as the one in the PPA? All fixes are merged into master, but also merged into develop and the release branch correct? Please correct me if I am wrong but if I compile from source, then I should have the most current version of the Numix theme. If not, where do I get the latest version source files?

**Comment by khurshid-alam** [comment]
There hasn't been a release for some time. We need to fix the build before another release. You can compile from source for now. Also note that gtk-3 xfce port is in progress. Numix doesn't have any style for that specific lightdm yet.

**Comment by c1ph3rl1nux** [comment]
@khurshid-alam 
Thank you, I compiled it from source and it's working fine now. I have been using the Numix theme since 2013 and I couldn't live without it.
