### ISSUE TITLE
Transparent background in GNOME 40 applications

### ISSUE THREAD

**Issue by piegamesde** [numixproject/numix-gtk-theme#755]
See https://gitlab.gnome.org/GNOME/vte/-/issues/284 https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/343 . This mainly affects GNOME terminal, but I suppose other applications will break too once they start using that CSS key.

**Comment by khurshid-alam** [comment]
In this commit https://gitlab.gnome.org/GNOME/vte/-/commit/ed887c2e3768083cfc59e93470eb74f2485812d4 text_view_bg is defined again. So It will be fixed in upcoming relese. Numix doesn't really define that color.

**Comment by piegamesde** [comment]
No. The devs explicitly stated that they only add that commit as a fix to existing releases. Newer versions won't include it anymore, because they ["don't like to cater to theme deficiencies"](https://gitlab.gnome.org/GNOME/vte/-/issues/284#note_917727) and ["Themes have had enough time to catch up by now"](https://gitlab.gnome.org/GNOME/vte/-/issues/284#note_1120751).

**Comment by khurshid-alam** [comment]
Ok. Understood. Fixed in ad4b345cb19edba96bec72d6dc97ed1b568755a8 .
