### ISSUE TITLE
Firefox TabBar should be a different color.

### ISSUE THREAD

**Issue by Redoubts** [numixproject/numix-gtk-theme#76]
With the Numix (Dark) theme in unity, inactive tabs and the tab-bar background are a dark grey. I don't think this works well with inactive tabs: the close button is obscured, and it's jarring compared with chrome. 

I think a good solution would be to make the tabs look more like the Greybird theme, with the tab-bar color being the same as the explorer bar directly below.

Current and Mock-Solution images:
![1](https://f.cloud.github.com/assets/2435101/1509878/8c20b0ce-4a68-11e3-8423-1122a34adf80.png)

![2](https://f.cloud.github.com/assets/2435101/1509880/94964912-4a68-11e3-912b-97891ce73f92.png)

a userChrome.css file containing

```
.tabbrowser-tabs {
    -moz-appearance:none !important;
    background-color: #E7E7E7 !important;
    color: #404040;
}
```

Seems close to ideal on my end, but there are a few things I couldn't make work - like the border under the tab-bar, but not the active tab.

**Comment by satya164** [comment]
Firefox isn't native GTK. So I don't think I can theme the tabs. May be @ochosi has any idea.

**Comment by ochosi** [comment]
yeah, the only thing you can do is provide a userchrome.css file. If you ship it with Numix, be aware that either
1) the user has to copy it to the respective directory to be able to use it or
2) you install it in the correct place, but _all_ gtk-themes will then use this userchrome.css

Problem 1) is mainly convenience, problem 2) causes regressions for all other themes.

**Comment by satya164** [comment]
Then I don't think it's possible. Sorry.

**Comment by Redoubts** [comment]
That's a shame. Thanks for the attention, though

**Comment by satya164** [comment]
Someone made a user style for firefox - http://userstyles.org/styles/95159/numix?r=1384602610
Check it out.

**Comment by Redoubts** [comment]
For posterity, the only change needed was altering line 3 in `Numix/gtk-2.0/gtkrc` so that gtk-color-scheme has `menubar_bg_color:#dedede\nmenubar_fg_color:#2d2d2d` in it instead.

**Comment by satya164** [comment]
@Redoubts but we cannot do it in the main theme, coz it's the design.
