### ISSUE TITLE
GTK2 vs GTK3 buttons (.button:active state)

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#78]
In the GTK+ 3 theme, .button:active defines that the background of a pressed button should be Numix red(ish). However, with the GTK+ 2 theme, the buttons gain a dashed border and the interior of the button is slightly shaded red, but still definitively grey.

**Comment by satya164** [comment]
Hmm... GTK3 active buttons aren't reddish.

About GTK2 theme, theming has several limitations and I'm unable to customize active state further. The Grey dotted line is focus line, which is hidden in GTK3.

**Comment by ghost** [comment]
Sorry for commenting on a closed issue, but isn't this already done with the Greybird theme?
