### ISSUE TITLE
Issue with Numix panel icons color

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#79]
Hello, I have a slight but annoying issue with the color of the Numix icons for the Unity panel: as much as I know the icons should be white, but they appear dark (http://goo.gl/PbYDtO) except when I open the dash (http://goo.gl/36TG8j).

**Comment by me4oslav** [comment]
Which numix icon theme do you use?

**Comment by ghost** [comment]
Hi, I'm using Numix-utouch.

**Comment by me4oslav** [comment]
I would suggest you using this:
http://me4oslav.deviantart.com/art/Numix-Circle-Linux-Desktop-Icon-Theme-414741466
You seems to use _extremely_ old version of uTouch, but even if you update to the newest one, we no longer maintain it.

**Comment by ghost** [comment]
Thanks for the response. I will give that new theme a go.

**Comment by me4oslav** [comment]
Happy to help! =)

**Comment by satya164** [comment]
The issue belongs to the icon themes.
