### ISSUE TITLE
Chromium pathbar is dark? 

### ISSUE THREAD

**Issue by me4oslav** [numixproject/numix-gtk-theme#8]
Are we sure Chromium "pathbar" to be dark when every other GTK 2 app in this spinoff uses light toolbar?
I thought the dark pathbar for Chromium was reserved for the a-la-Ambiance spinoff of the theme.
Having said that I like it dark ;p

**Comment by me4oslav** [comment]
On second thought - it makes a lot of sense with the toolbar being dark the pathbar (the bar right below it) to be dark.

**Comment by satya164** [comment]
yep, that's the logic.

**Comment by cldx** [comment]
It makes sense, it becomes hard to read the text in the unfocused tabs though (EDIT: on my Desktop, on my Laptop it looks much better, which is cofusing, maybe the resolution is somewhat messed up on my end)

EDIT: Playing around with my Monitor makes it look much better in "Office" Mode, whatever that means...

Edit, i don't know if it's possible but may we could make the Chrome Tabs look the same as GTK Tabs?

**Comment by me4oslav** [comment]
Nope, they are custom tabs.
