### ISSUE TITLE
Black bars in some applications

### ISSUE THREAD

**Issue by tkubicz** [numixproject/numix-gtk-theme#80]
OS: Ubuntu 13.04
numix-gtk-theme from official ppa: 2.1+221~201312030833~ubuntu13.04.1

Hello,

Recently I noticed, that some applications have black bars (or whole widgets) instead of gray.

For example, gedit:

When you open gedit, you'll see something like that:
![gedit_1](https://f.cloud.github.com/assets/1674937/1704818/f796fd3e-60d1-11e3-8b9c-f3498d6a3b54.png)

After creating a new tab, you should notice, that tab bar becomes black:
![gedit_2](https://f.cloud.github.com/assets/1674937/1704821/0d7cc8e0-60d2-11e3-9d76-f051d1525ade.png)

After closing all tabs:
![gedit_3](https://f.cloud.github.com/assets/1674937/1704822/144baf74-60d2-11e3-9828-2fa2831c2d6e.png)

How it behaves using Ambiance theme:
![gedit_4](https://f.cloud.github.com/assets/1674937/1704825/1c2bfe74-60d2-11e3-8836-c43f4675acab.png)

![gedit_5](https://f.cloud.github.com/assets/1674937/1704826/1f0cec2a-60d2-11e3-8463-e474fc243c8b.png)

You can see the same thing in default Ubuntu pdf application:
![pdf_wrong](https://f.cloud.github.com/assets/1674937/1704831/2eb80af6-60d2-11e3-870c-cd61bee5f81f.png)

I also noticed similar problem using Evolution.

**Comment by satya164** [comment]
It is recommended to disable overlay scrollbars. This issue occurs due to overlay scrollbars, but I cannot fix it since the fix leads to other bugs.

**Comment by khurshid-alam** [comment]
This doesn't happen because of overlay scrollbars even though disabling scollbar may appear to be the fix. I am using shimmer-themes(which is couple of commits behind git) from repo in trusty with overlay scrollbar. It works without a problem. I suspect some changes in the code causing this.

Screenshot: ![screenshot](http://i.imgur.com/WVvDPzx.png)

Also it doesn't happen with other shimmer themes (like greybird).

**Comment by satya164** [comment]
@khurshid-alam The Shimmer themes package has a patch to fix this issue. However the patch is a hack and messes up things in other distros. Hence it cannot be merged.

**Comment by spartako** [comment]
This issue is still happening. Is there anything planned to fix it?

**Comment by satya164** [comment]
@spartako this is an issue with overlay scrollbars. Disable them

**Comment by spartako** [comment]
I swear it didn't work when I tried that before... Thanks!
