### ISSUE TITLE
black background in evolution mail viewer

### ISSUE THREAD

**Issue by patriziobruno** [numixproject/numix-gtk-theme#81]
![schermata da 2013-12-18 10 42 40](https://f.cloud.github.com/assets/2834179/1773026/899c65b2-67de-11e3-96fe-aef81301d10c.png)

**Comment by me4oslav** [comment]
Dublicate of #80 .
The last line in #80 states : "I also noticed similar problem using Evolution.".

**Comment by 89iuv** [comment]
I have the same problem with evolution and i do use it as my default mail app.

**Comment by satya164** [comment]
Should be fixed with a4624f2
