### ISSUE TITLE
Separator color in Midori

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#82]
With the latest updates to the icon themes and GTK+ themes, the light separator looks rather out of place.

![2013-12-21-094341_1920x1080_scrot](https://f.cloud.github.com/assets/6130178/1796049/8837a2d6-6a4f-11e3-961f-a15172379f65.png)

**Comment by satya164** [comment]
Can you share your GTK version and Midori version?

**Comment by ghost** [comment]
GTK+ 3.10.6, midori-gtk3 0.5.6.

**Comment by satya164** [comment]
Thanks. Also, are you on Ubuntu or some other distro? Also if you are on Ubuntu, also mention if you use any PPA.

**Comment by ghost** [comment]
I am using the official versions in the Arch Linux repositories.
