### ISSUE TITLE
Back, forward, and refresh icons in Chromium are rather faded [x-report]

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#83]
In Chrome/ium, the back, forward, and refresh icons (with the latest updates to the icon theme) are quite faded. There are probably two reasonable solutions:
1. Darken the icons in the numixproject/numix-icon-theme repository
2. Darken the background in the GTK+ theme

![2013-12-21-094348_1920x1080_scrot](https://f.cloud.github.com/assets/6130178/1796052/b071b48a-6a4f-11e3-964d-5e09afa6c021.png)

**Comment by satya164** [comment]
https://github.com/numixproject/numix-icon-theme/issues/28
