### ISSUE TITLE
Buttons don't show correctly on rhythmbox

### ISSUE THREAD

**Issue by gjm** [numixproject/numix-gtk-theme#84]
The action buttons above the music browser only show when the mouse hovers them.

Without the mouse:
![rhythmbox1](https://f.cloud.github.com/assets/77360/1797023/2ccd4616-6aa0-11e3-83fe-7a91c8159362.png)

On mouse hover:
![rhythmbox2](https://f.cloud.github.com/assets/77360/1797024/2cd34214-6aa0-11e3-83e7-5b181dc29599.png)

**Comment by satya164** [comment]
Rhythmbox doesn't seem to apply correct colors to toolbar buttons. And strange that I don't have the black line at left that you seem to have!

**Comment by gjm** [comment]
:( is there a workaround or something you can do? At least to make the buttons visible somehow?

**Comment by satya164** [comment]
@gjm I'm trying to fix it. But I cannot gurrantee when I'll be able to :(

**Comment by 89iuv** [comment]
This same issue is bugging me.

**Comment by satya164** [comment]
@89iuv I'll work it. But I have exams right now. So I need some time.
