### ISSUE TITLE
Dark toolbars in Geary

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#85]
In Geary's compose message mode, the toolbar buttons and toolbar are dark. I know this is an intended effect, but I'm not sure if it's wise to also have it apply to elements located in the middle of a window, aesthetically speaking. (If it is, feel free to close this immediately.)

Using Geary 0.5.0 with GTK+ 3.10.6 on Arch Linux.

![2013-12-23-153200_1920x1080_scrot](https://f.cloud.github.com/assets/6130178/1803310/28f51954-6c19-11e3-9d08-d8eddcaa5f80.png)

**Comment by satya164** [comment]
Unfortunately, every widget having the class .toolbar will be dark. We cannot do anything about it :(
