### ISSUE TITLE
Nautilus spaces headerbar/toolbar from Trash header

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#86]
See the following screenshot. GTK 3.10.6, Nautilus 3.10.1, latest version of all the Numix Project stuff. 

Also, merry Christmas! Hope y'all over at there get some rest.

![2013-12-24-112351_1920x1080_scrot](https://f.cloud.github.com/assets/6130178/1806701/15c5e92c-6cb8-11e3-9276-143c3f0929e0.png)

**Comment by satya164** [comment]
Not a Numix specific issue. Also happens in Adwaita.

Also, merry Christmas to you too. I'm having exams from 26th, so no rest for me :(
