### ISSUE TITLE
gld gripitem too big

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#87]
Hi,

I'm using Numix theme. I think the theme is great.

I think the grab element in gdl is just to large with the theme.
Gdl is the library used in Anjuta(ide) and other large applications for docking windows.
Adding following to the css fixes this:

<pre>
/*************
 * gdl       *
 *************/

GdlDockItemGrip .button {
    padding:0;
}
</pre>

Here's the before and after.
BEFORE:
![before](https://f.cloud.github.com/assets/6022889/1827085/9f5e11b8-7222-11e3-8905-df404a8929c9.png)

AFTER:
![after](https://f.cloud.github.com/assets/6022889/1827086/a846bf6e-7222-11e3-99f2-ea291f91a4ac.png)

Hope to see this in your next release. ;)

**Comment by satya164** [comment]
Big is always relative. For me, the current size is ok.

However, if you want smaller size, you can put the CSS code you mentioned to a file ~/.config/gtk-3.0/gtk.css and your settings won't be affected by Numix updates.
