### ISSUE TITLE
LightDM GTK+ greeter support

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-gtk-theme#88]
Hey, I'd absolutely _love_ to see support for the LightDM GTK+ greeter in the theme - see [this](http://www.smdavis.us/2013/06/03/lightdm-gtk-greeter-1-6-0-released/) for widget names and the Greybird repo for examples.

Thanks in advance!

**Comment by satya164** [comment]
Thanks. LightDM support will be added soon.

**Comment by satya164** [comment]
LightDM support was added in fd5b36e

But some upstream tweaks are needed to get proper border radius. I've reported the bug here https://bugs.launchpad.net/lightdm-gtk-greeter/+bug/1265848

**Comment by rickpalmeira** [comment]
whoa, you guys deserve a medal (and more donations to numix)

**Comment by me4oslav** [comment]
Totally pointless, but funny comment - we can buy medals with the money. :D

**Comment by ghost** [comment]
I wish I could donate but I has no credit card. :c
