### ISSUE TITLE
Issue on Gedit

### ISSUE THREAD

**Issue by SKUndef** [numixproject/numix-gtk-theme#89]
Hi,

is Gedit supposed to have the following dark background?

![schermata del 2014-01-18 09 53 31](https://f.cloud.github.com/assets/5783302/1946734/904673e6-801e-11e3-8ada-95e5f44a3103.png)

Thanks!

**Comment by me4oslav** [comment]
Are you using the overlay scrollbars by any chance?

**Comment by satya164** [comment]
Disable overlay scrollbars and you'll be fine.

**Comment by SKUndef** [comment]
Ahhh nice, thanks!
