### ISSUE TITLE
Dark toolbar messes up with the icon theme

### ISSUE THREAD

**Issue by me4oslav** [numixproject/numix-gtk-theme#9]
For the time being our icon theme: https://github.com/cldx/numix only has dark toolbar icons and with a dark toolbar in the GTK theme one gets dark on dark and that ain't cool.

**Comment by satya164** [comment]
I would propose not to have a variant with dark toolbar since it's tricky to get a trouble free dark toolbar in GTK2 (at least for me) and the Ambiance GTK2 still has a light toolbar!

**Comment by me4oslav** [comment]
We will cross that bridge when it comes to :)

**Comment by satya164** [comment]
What should I do now? Since we want to have a dark toolbar, I need to have it enabled!

**Comment by me4oslav** [comment]
Cookies! Do cookies! ;>
But really, we still don't know if we'll do dark toolbar theme, so for the time being do this theme (this is our main spinoff):
dark titlebar, dark menubar, dark menus
everything else - light

**Comment by satya164** [comment]
Done. Also, I think the GTK2 theme is done too. I'm a noob in GTK2 theming though. So...
