### ISSUE TITLE
Numix make a display bug in EOG

### ISSUE THREAD

**Issue by Deevad** [numixproject/numix-gtk-theme#90]
- To reproduce : 
  1) Change your theme to Numix GTK 
  2) Download this picture : http://paulstevensdesign.files.wordpress.com/2011/10/moire-pattern4.jpg
  3) open the image with EOG
- Result : 
  EOG display the image , pretending it's 100% . If you resize up the windows ; you'll see the image was 99% displayed ( and it trigger a resizing algorythm, certainly a blury cubic ). This is annoying if you have a folder with pixel art, or work with precise images. Is a EOG bug ? Difficult to know as 4 other GTK theme I tested doesn't make this behavior. That's why I report it here. It does sounds like EOG need a margin or a padding somewhere. 
- My profile : 
  Numix from Git , ArchLinux 64bit , Gnome 3.10.2 
- Picture demo : 
  with http://paulstevensdesign.files.wordpress.com/2011/10/moire-pattern4.jpg
  ![numix-report](https://f.cloud.github.com/assets/4021867/1957399/1d471aee-8208-11e3-8389-dbd6dcb206cb.png)

**Comment by satya164** [comment]
@ochosi @me4oslav can you test it?

**Comment by satya164** [comment]
Any news?
