### ISSUE TITLE
Install instruction for Git

### ISSUE THREAD

**Issue by blueyed** [numixproject/numix-gtk-theme#93]
I am using Ubuntu 13.10 and have cloned the Git repository into ~/.themes/Numix.

While "Numix" can be selected in gnome-tweak-tools' `Gtk+ Theme` dropdown, it does not show up in the `Current theme` dropdown.

If I install Ubuntu's `shimmer-themes` package (which contains Numix), it does show up however.

What am I missing?
It would be nice, if the README could be extended accordingly.

**Comment by satya164** [comment]
From Gnome 3.10 on wards, Gnome uses ~/.local/share/themes for the themes. So you need to install Numix to ~/.local/share/themes. Note that this way the GTK2 theme won't work. For all themes to work, you need to install it in /usr/share/themes. It's written in the README.
