### ISSUE TITLE
Ubuntu 13.10 installing flat theme is also installing gnome-tweak-tool

### ISSUE THREAD

**Issue by dgeorgiev** [numixproject/numix-gtk-theme#95]
Hi,
I have purchased Numix Flat Theme, but when I install it gnome-tweak-tool is installed also.
I use unity, and have already unity-tweak-tool so the gnome-tweak-tool is not needed, can the dependency be disabled maybe?

PS: I love to have a minimum setup of programs only that I use, and this is strange dependency in my opinion.

**Comment by me4oslav** [comment]
Awkward, we shall look at it ASAP.
P.S. To brag a bit - I am the guy that designed 90% of Unity Tweak Tool. ;p

**Comment by dgeorgiev** [comment]
I know.
Probably that's why it is installed and not gnome-tweak or ubuntu-tweak :D

**Comment by me4oslav** [comment]
Hah, my famous reputation of being well know to not sod the design up. ;D

**Comment by ericoporto** [comment]
This is not solved on Ubuntu 14.04, just bought the theme from Ubuntu Software Center.
