### ISSUE TITLE
Bluetooth: when connected switch is not correctly themed

### ISSUE THREAD

**Issue by Vistaus** [numixproject/numix-gtk-theme#98]
When you connect to a bluetooth device you've set up earlier, flipping the switch at Connection from Off to On doesn't theme it correctly, even after re-opening gnome-control-center. The switch stays black when switched to On while it should switch to orange, like the rest of the switches. I attached a screenshot.

(I'm using GNOME 3.10 btw)
![screenshot from 2014-02-17 11 35 56](https://f.cloud.github.com/assets/1716229/2184436/d5da98de-97bf-11e3-9ac4-3c20c7f9af20.png)

**Comment by rickpalmeira** [comment]
Do this happen only on numix or on other icon themes too?

**Comment by Vistaus** [comment]
Happens only on Numix GTK theme.

**Comment by satya164** [comment]
How can this happen in a theme? Can you attach some screenshots with Adwaita?
