### ISSUE TITLE
Xfwm4: stick icon does not reflect the window state

### ISSUE THREAD

**Issue by achadwick** [numixproject/numix-gtk-theme#99]
The new Stick icon,

![stick1](https://f.cloud.github.com/assets/61299/2217132/ff6950d8-9a16-11e3-8447-4e73033d1f5b.png)

does not reflect the Stick state when it's clicked. The user is left with no hint about whether the window is pinned unless they attempt to switch workspace.

I'm not sure about making it look like a cog either, though to be honest a circle doesn't really express "window stickiness" either. Not sure what to suggest here.

**Comment by satya164** [comment]
Well, I have no idea what else we can use. So just using something similar to the default style.
